### ISSUE TITLE
在其他手机助手运行的同时运行adb指令可能导致的编码异常问题

### ISSUE THREAD

**Issue by yimelia** [AirtestProject/Airtest#10]
当pc上运行了其他手机助手时，可能会因为端口占用的问题，导致没法运行自己的adb指令：

```
List of devices attached
adb server version (31) doesn't match this client (39); killing...
error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037:
通常每个套接字地址(协议/网络地址/端口)只允许使用一次。 (10048)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon
```

里面的中文报错信息编码被adb处理成了utf-8编码，在airtest中运行adb指令时因为decode的编码是gbk，导致抛出异常：

```
Traceback (most recent call last):
  File "app\plugins\device\device_panel\util.py", line 25, in adbDevices
  File "airtest\core\android\adb.py", line 192, in devices
  File "airtest\core\android\adb.py", line 168, in cmd
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 106-107: illegal
multibyte sequence
```

相关代码：

[adb1](https://github.com/aosp-mirror/platform_system_core/blob/c1314c8b13ef718b24372b6749725bdf7e76d46d/adb/sysdeps_win32.cpp#L895)

[adb2](https://github.com/aosp-mirror/platform_system_core/blob/ad81a1d94a18097d32a80040ebac5940f073c8b6/base/errors_windows.cpp#L36)

**Comment by adolli** [comment]
这个应该已经修了吧
