### ISSUE TITLE
ios 点击系统弹窗报错，如图

### ISSUE THREAD

**Issue by Pactortester** [AirtestProject/Airtest#1024]
# iOS弹窗
![image](https://user-images.githubusercontent.com/29191106/153715478-3455c12a-506d-4b49-a597-9c7d6b9f39cb.png)

# 脚本
![image](https://user-images.githubusercontent.com/29191106/153715534-f3a763c7-2989-4727-a444-5add059bca48.png)

# 报错
`----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest/cli/runner.py", line 73, in runTest
  File "site-packages/six.py", line 703, in reraise
  File "airtest/cli/runner.py", line 70, in runTest
  File "/Users/lijiawei/Desktop/ppup.air/ppup.py", line 10, in <module>
    touch(pos)
  File "airtest/utils/logwraper.py", line 90, in wrapper
  File "airtest/core/api.py", line 357, in touch
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 34, in wrapper
    return func(self, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 328, in touch
    self.driver.click(x, y, duration)
  File "site-packages/wda/__init__.py", line 912, in click
  File "site-packages/wda/__init__.py", line 931, in tap_hold
  File "site-packages/wda/utils.py", line 47, in _inner
  File "site-packages/wda/__init__.py", line 454, in _fetch
  File "site-packages/wda/__init__.py", line 124, in httpdo
  File "site-packages/wda/__init__.py", line 180, in _unsafe_httpdo
wda.exceptions.WDAUnknownError: WDARequestError(status=110, value={'error': 'unknown error', 'message': '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'})

----------------------------------------------------------------------
Ran 1 test in 4.519s`

**Comment by J4Yaaa** [comment]
请问这个问题解决了吗 我这边也遇到相同的问题

**Comment by CJ-Irving-11** [comment]
我在使用facebook-wda中点击系统弹窗时也出现了这个问题
