### ISSUE TITLE
依赖问题导致运行失败，原因是最新版本的jinja2接口废弃

### ISSUE THREAD

**Issue by felixruan** [AirtestProject/Airtest#1033]
下载airtest1.2.4
pip install -r requirements.txt
```
Jinja2>=2.8
Pillow>=3.4.0
requests>=2.11.1
six
mss==6.1.0
numpy<=1.19.3
opencv-contrib-python
facebook-wda>=1.3.3
pywinauto==0.6.3
```
其中
Jinja2>=2.8

运行Airtest\playground\blackjack_example报错
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  ....
  File "D:\python\lib\site-packages\airtest\report\report.py", line 15, in <module>
    from jinja2 import evalcontextfilter, Markup, escape
ImportError: cannot import name 'evalcontextfilter' from 'jinja2' (D:\python\lib\site-packages\jinja2\__init__.py)
```

Jinja2>=3.1.0 版本已经废弃这些接口（ evalcontextfilter, Markup, escape）

请更新Airtest代码或修订依赖最高版本

**Comment by felixruan** [comment]
当前规避解决方式，降低Jinja2版本
pip install --upgrade Jinja2==3.0.3

**Comment by yimelia** [comment]
收到，已知问题，即将更新的1.2.5版本会修复这个问题
