### ISSUE TITLE
使用Recorder录制视频，honor 8x抛出异常

### ISSUE THREAD

**Issue by qwerdome** [AirtestProject/Airtest#1079]
:bulb:**相关项目:** Airtest

**标题:** [BUG提交]使用Recorder录制视频，honor 8x抛出异常

**AirtestIDE版本:** 无

- [x] **使用了本地Pyhton环境运行脚本**
- Python版本: 3.7.6
- Airtest版本: v1.2.6

**报错描述:**
&nbsp;&nbsp;&nbsp;&nbsp;from airtest.core.android.recorder import Recorder
结束录屏抛出异常

**相关截图:**
![](https://hfc20-issue-helper.s3.nie.netease.com/media/2022/08/29/344/image.png)

**报错Log:**
```
Traceback (most recent call last):
  File "D:/tx/farm/pytest_airtest_allure/test.py", line 10, in <module>
    recorder.stop_recording(output="test2.mp4")
  File "D:\tx\python\lib\site-packages\airtest\utils\snippet.py", line 125, in ready_func
    return func(inst, *args, **kwargs)
  File "D:\tx\python\lib\site-packages\airtest\core\android\recorder.py", line 108, in stop_recording
    raise AirtestError("start_recording first")
airtest.core.error.AirtestError: 'start_recording first'
```

**连接设备信息:**
设备类型 | 设备型号 | 系统版本号 | apk名称/下载链接
------------ | ------------- | ------------- | -------------
Android | honor 8x | 鸿蒙2.0 Android 10 | 无

**提供最小可复现此BUG的代码:**
```
from airtest.core.android.adb import ADB
from airtest.core.android.recorder import Recorder
import time
adb=ADB("SJQ4C19123001156")
recorder = Recorder(adb)
recorder.start_recording()
print("开始等待")
time.sleep(5)
print("结束等待")
recorder.stop_recording(output="test2.mp4")
```

**Comment by yangyang066** [comment]
解决了嘛

**Comment by 15876379684aa** [comment]
解决了吗？
