### ISSUE TITLE
windows单屏幕，exists可以识别，touch报错

### ISSUE THREAD

**Issue by lanayalouisforever** [AirtestProject/Airtest#1096]
**图像识别**

**描述问题bug**
使用，AirtestIDE-win-1.2.14的Airtest辅助窗口中的【exists】识别图片，然后再使用【touch】。
```
if exists(Template(r"tpl1673601243843.png", record_pos=(-0.338, 0.495), resolution=(377, 637))):
        touch(Template(r"tpl1673601243843.png", record_pos=(-0.344, 0.495), resolution=(377, 637)))
```
ide生成的报告中，touch步骤对应的报告，目标识别图片显示别被识别，但是程序报错

错误信息：
```
Traceback (most recent call last):
  File "airtest\utils\logwraper.py", line 90, in wrapper
  File "airtest\core\api.py", line 358, in touch
  File "C:\AirtestIDE-win-1.2.14\AirtestIDE\airtest\core\win\win.py", line 263, in touch
    self.mouse.move(coords=(end_x, end_y))
  File "site-packages\pywinauto\mouse.py", line 232, in move
  File "site-packages\pywinauto\mouse.py", line 125, in _perform_click_input
pywintypes.error: (0, 'SetCursorPos', 'No error message is available')
```

**复现步骤**
1. ide 点击运行

**预期效果**
正确的位置进行touch操作

**python 版本:** `python3.8`

**airtest 版本:** `1.2.14`

**设备:**
windows10专业版，显示器24寸

**其他相关环境信息**
未尝试

**Comment by lanayalouisforever** [comment]
已解决。重启电脑就好了。
