### ISSUE TITLE
自动选择cap方式在某些设备上失效

### ISSUE THREAD

**Issue by cauchy733** [AirtestProject/Airtest#1100]
**描述问题bug**
在设备无法使用minicap时，不会自动切换到javacap，而是会runtime error
```
[12:53:13][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 get-state
[12:53:13][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 wait-for-device
[12:53:14][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell getprop ro.build.version.sdk
[12:53:14][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell ls /data/local/tmp/minicap
[12:53:14][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell ls /data/local/tmp/minicap.so
[12:53:14][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[12:53:14][DEBUG]<airtest.core.android.cap_methods.minicap> version:5
[12:53:14][DEBUG]<airtest.core.android.cap_methods.minicap> skip install minicap
[12:53:14][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell ls -l /data/local/tmp/rotationwatcher.jar
[12:53:14][DEBUG]<airtest.core.android.rotation> install_rotationwatcher skipped
[12:53:14][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell app_process -Djava.class.path=/data/local/tmp/rotationwatcher.jar /data/local/tmp com.example.rotationwatcher.Main
[12:53:14][DEBUG]<airtest.utils.nbsp> [rotation_server]b'0'
[12:53:15][INFO]<airtest.core.android.rotation> update orientation None->0
[12:53:15][DEBUG]<airtest.core.android.cap_methods.minicap> update_rotation: 0
[12:53:15][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell wm size
[12:53:15][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell getprop ro.sf.lcd_density
[12:53:15][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell dumpsys SurfaceFlinger
[12:53:15][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell dumpsys input
[12:53:15][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell getevent -p
[12:53:15][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'airtest_minicap' -P 1080x2340@1080x2340/0 -s
[12:53:15][DEBUG]<airtest.core.android.cap_methods.minicap> do update rotation
[12:53:15][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 forward --no-rebind tcp:12713 localabstract:minicap_12713
[12:53:15][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_12713' -P 1080x2340@1080x2340/0 -l 2>&1
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 21054'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1080x2340@1080x2340/0'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_30.cpp:243) Creating SurfaceComposerClient'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_30.cpp:246) Performing SurfaceComposerClient init check'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_30.cpp:257) Creating virtual display'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_30.cpp:263) Creating buffer queue'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_30.cpp:266) Setting buffer options'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_30.cpp:270) Creating CPU consumer'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_30.cpp:274) Creating frame waiter'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_30.cpp:278) Publishing virtual display'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'Vector<> have different types (this=0x7fc7600f30, rhs=0x7fc7601080)'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b'Aborted'
[12:53:16][DEBUG]<airtest.utils.nbsp> [minicap_server]b''
Traceback (most recent call last):
  File "C:\Users\keyingkai\PycharmProjects\airtest\main.py", line 6, in <module>
    print(G.DEVICE.snapshot())
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\android.py", line 407, in snapshot
    screen = self.screen_proxy.snapshot(ensure_orientation=ensure_orientation)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\cap_methods\minicap.py", line 369, in snapshot
    return super(Minicap, self).snapshot()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\cap_methods\base_cap.py", line 42, in snapshot
    screen = self.get_frame_from_stream()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\cap_methods\minicap.py", line 27, in wrapper
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\cap_methods\minicap.py", line 345, in get_frame_from_stream
    self.frame_gen = self.get_stream()
                     ^^^^^^^^^^^^^^^^^
  File "C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\utils\snippet.py", line 125, in ready_func
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\cap_methods\minicap.py", line 223, in get_stream
    stopped = next(gen)
              ^^^^^^^^^
  File "C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\utils\threadsafe.py", line 23, in __next__
    return self._next()
           ^^^^^^^^^^^^
  File "C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\cap_methods\minicap.py", line 238, in _get_stream
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\cap_methods\minicap.py", line 318, in _setup_stream_server
    raise RuntimeError("minicap server setup timeout")
RuntimeError: minicap server setup timeout
[12:53:21][DEBUG]<airtest.core.android.adb> C:\Users\keyingkai\PycharmProjects\airtest\venv\Lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 10.30.20.80:20841 forward --remove tcp:12713
[12:53:21][DEBUG]<airtest.utils.nbsp> [rotation_server]b''
```
**相关截图**
初步判断是进行get_frame时没有进行报错判断
![企业微信截图_1675054257950](https://user-images.githubusercontent.com/62271329/215391148-69f9347a-657b-4308-a8f0-81e9095c2f14.png)
![企业微信截图_16750542064388](https://user-images.githubusercontent.com/62271329/215391157-73a4be75-755e-445a-acfd-1ad563b1f34d.png)

**复现步骤**
经常出现 但是非必现
连接小米9 并使用如下代码
```
from airtest.core.api import *
from airtest.core.android.android import Android

auto_setup(__file__, devices=["Android://127.0.0.1:5037/10.30.20.80:20841"])

print(G.DEVICE.snapshot())
```
**预期效果**
minicap失效后，转换为javacap

**python 版本:** `python3.7`

**airtest 版本:** `1.2.7`

**设备:**
 - 型号: MI9
 - 系统: 安卓11

**其他相关环境信息**

**Comment by cauchy733** [comment]
已经合入master
