### ISSUE TITLE
Airtest脚本打包APK放手机里运行报错

### ISSUE THREAD

**Issue by Tnxent** [AirtestProject/Airtest#1116]
Airtest+PocoUI写的自动化脚本在AirtestIDE上能正常运行，打包成APK放手机里运行stop_app()函数直接报错是什么原因？

Error in launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest):
junit.framework.AssertionFailedError:
=================script error start================
Traceback (most recent call last):
  File "copy_app\main.py", line 80, in test
  File "/data/user/0/com.netease.open.airbase/files/app/MB_v2.air/MB_v2.py", line 226, in <module>    non_stop()
  File "/data/user/0/com.netease.open.airbase/files/app/MB_v2.air/MB_v2.py", line 190, in non_stop    restart_app()
  File "/data/user/0/com.netease.open.airbase/files/app/MB_v2.air/MB_v2.py", line 31, in restart_app
    stop_app('com.keyboard.mb')
  File "copy_app/airtest\utils\logwraper.py", line 72, in wrapper
  File "copy_app/airtest\core\api.py", line 158, in stop_app
  File "kivy.py", line 67, in stop_app
  File "copy_app\airtest\core\kivy\controler.py", line 43, in stop_app
AttributeError: 'org.kivy.android.Controler' object has no attribute 'finishApp'
=================script error end================

        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at org.kivy.android.ExampleInstrumentedTest.launchAirtestAndPoco(ExampleInstrumentedTest.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2261)

**python 版本:** `python3.8`

**airtest 版本:** `1.2.9.1`

**设备:**
 - 型号: 三星N10
 - 系统: 安卓12（没root）

**Comment by gxp19971014** [comment]
请问是airtestIDE 集成的firebase打包的吗？  我打包一个打开APP的DEMO例子的APK在手机上都执行不起来
