### ISSUE TITLE
AirtestIDE中Selenium_Window初始化打开浏览器后，捕捉元素按钮和其他常用api(例如start_web)不能使用，控制台监控有报错

### ISSUE THREAD

**Issue by guangxun123** [AirtestProject/Airtest#1137]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**

AirtestIDE中Selenium_Window初始化打开浏览器后，捕捉元素按钮和其他常用api（例如start_web）不能使用，命令行监控有报错
```

[14:43:27][DEBUG]<airtest.core.android.adb> C:\tools\airtest\AirtestIDE-win-1.2.8\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices
['chrome.exe', '--remote-debugging-port=9222', '--user-data-dir=C:\\Users\\Lenovo\\AppData\\Local\\Temp\\AirtestIDE\\selenium_user_data']
queue size is: 10
Traceback (most recent call last):
  File "plugins/selenium_plugin\selenium_wnd.py", line 217, in startWebSlot
  File "plugins/selenium_plugin\selenium_assistant.py", line 68, in get_web_addr
  File "site-packages\pychrome\tab.py", line 206, in start
  File "site-packages\websocket\_core.py", line 494, in create_connection
  File "site-packages\websocket\_core.py", line 220, in connect
  File "site-packages\websocket\_handshake.py", line 69, in handshake
  File "site-packages\websocket\_handshake.py", line 135, in _get_resp_headers
Sentry responded with an error: HTTP Error 503: Service Unavailable (url: http://web-server-airtestide-airtestide.tantive4-sentry.cube-dg.nie.netease.com:9009/api/3/store/)
{'culprit': 'websocket._handshake in _get_resp_headers',
 'event_id': 'd8916e9416964a1c8f7183e39a9be986',
 'exception': {'values': [{'module': 'websocket._exceptions',
                           'stacktrace': {'frames': [{'abs_path': 'plugins/selenium_plugin\\selenium_wnd.py',
                                                      'filename': 'plugins/selenium_plugin\\selenium_wnd.py',
                                                      'function': 'startWebSlot',
                                                      'lineno': 217,
                                                      'module': 'selenium_plugin.selenium_wnd',
                                                      'vars': {'default_addr': "'Write "
                                                                               'your '
                                                                               'test '
                                                                               'web '
                                                                               "address!'",
                                                               'self': '<selenium_plugin.selenium_wnd.SeleniumWindow '
                                                                       'object '
                                                                       'at '
                                                                       '0x00000173886C5048>'}},
                                                     {'abs_path': 'plugins/selenium_plugin\\selenium_assistant.py',
                                                      'filename': 'plugins/selenium_plugin\\selenium_assistant.py',
                                                      'function': 'get_web_addr',
                                                      'lineno': 68,
                                                      'module': 'selenium_plugin.selenium_assistant',
                                                      'vars': {'self': '<selenium_plugin.selenium_assistant.SeleniumAssistant '
                                                                       'object '
                                                                       'at '
                                                                       '0x00000173886C5CA8>'}},
                                                     {'abs_path': 'site-packages\\pychrome\\tab.py',
                                                      'filename': 'site-packages\\pychrome\\tab.py',
                                                      'function': 'start',
                                                      'lineno': 206,
                                                      'module': 'pychrome.tab',
                                                      'vars': {'self': '<Tab '
                                                                       '[F79552413B5B7D5E3A33F81330175EB2]>'}},
                                                     {'abs_path': 'site-packages\\websocket\\_core.py',
                                                      'filename': 'site-packages\\websocket\\_core.py',
                                                      'function': 'create_connection',
                                                      'lineno': 494,
                                                      'module': 'websocket._core',
                                                      'vars': {'class_': '<class '
                                                                         "'websocket._core.WebSocket'>",
                                                               'enable_multithread': True,
                                                               'fire_cont_frame': False,
                                                               'options': {},
                                                               'skip_utf8_validation': False,
                                                               'sockopt': [],
                                                               'sslopt': {},
                                                               'timeout': None,
                                                               'url': "'ws://127.0.0.1:9222/devtools/page/F79552413B5B7D5E3A33F81330175EB2'",
                                                               'websock': '<websocket._core.WebSocket '
                                                                          'object '
                                                                          'at '
                                                                          '0x000001738E6C8978>'}},
                                                     {'abs_path': 'site-packages\\websocket\\_core.py',
                                                      'filename': 'site-packages\\websocket\\_core.py',
                                                      'function': 'connect',
                                                      'lineno': 220,
                                                      'module': 'websocket._core',
                                                      'vars': {'addrs': ["'127.0.0.1'",
                                                                         9222,
                                                                         "'/devtools/page/F79552413B5B7D5E3A33F81330175EB2'"],
                                                               'options': {},
                                                               'self': '<websocket._core.WebSocket '
                                                                       'object '
                                                                       'at '
                                                                       '0x000001738E6C8978>',
                                                               'url': "'ws://127.0.0.1:9222/devtools/page/F79552413B5B7D5E3A33F81330175EB2'"}},
                                                     {'abs_path': 'site-packages\\websocket\\_handshake.py',
                                                      'filename': 'site-packages\\websocket\\_handshake.py',
                                                      'function': 'handshake',
                                                      'lineno': 69,
                                                      'module': 'websocket._handshake',
                                                      'vars': {'header_str': "'GET "
                                                                             '/devtools/page/F79552413B5B7D5E3A33F81330175EB2 '
                                                                             'HTTP/1.1\r\n'
                                                                             'Upgrade: '
                                                                             'websocket\r\n'
                                                                             'Connection: '
                                                                             'Upgrade\r\n'
                                                                             'Host: '
                                                                             '127.0.0.1:9222\r\n'
                                                                             'Origin: '
                                                                             'http://127.0.0.1:9222\r\n'
                                                                             'Sec-WebSocket-Key: '
                                                                             'H3WCI9xGzAmbbbHJwR2dPA==\r\n'
                                                                             'Sec-WebSocket-Version: '
                                                                             '13\r\n'
                                                                             '\r\n'
                                                                             "'",
                                                               'headers': ["'GET "
                                                                           '/devtools/page/F79552413B5B7D5E3A33F81330175EB2 '
                                                                           "HTTP/1.1'",
                                                                           "'Upgrade: "
                                                                           "websocket'",
                                                                           "'Connection: "
                                                                           "Upgrade'",
                                                                           "'Host: "
                                                                           "127.0.0.1:9222'",
                                                                           "'Origin: "
                                                                           "http://127.0.0.1:9222'",
                                                                           "'Sec-WebSocket-Key: "
                                                                           "H3WCI9xGzAmbbbHJwR2dPA=='",
                                                                           "'Sec-WebSocket-Version: "
                                                                           "13'",
                                                                           "''",
                                                                           "''"],
                                                               'hostname': "'127.0.0.1'",
                                                               'key': "'H3WCI9xGzAmbbbHJwR2dPA=='",
                                                               'options': {},
                                                               'port': 9222,
                                                               'resource': "'/devtools/page/F79552413B5B7D5E3A33F81330175EB2'",
                                                               'sock': '<socket.socket '
                                                                       '[closed] '
                                                                       'fd=-1, '
                                                                       'family=AddressFamily.AF_INET, '
                                                                       'type=0, '
                                                                       'proto=6>'}},
                                                     {'abs_path': 'site-packages\\websocket\\_handshake.py',
                                                      'filename': 'site-packages\\websocket\\_handshake.py',
                                                      'function': '_get_resp_headers',
                                                      'lineno': 135,
                                                      'module': 'websocket._handshake',
                                                      'vars': {'resp_headers': {"'content-length'": "'239'",
                                                                                "'content-type'": "'text/html'"},
                                                               'sock': '<socket.socket '
                                                                       '[closed] '
                                                                       'fd=-1, '
                                                                       'family=AddressFamily.AF_INET, '
                                                                       'type=0, '
                                                                       'proto=6>',
                                                               'status': 403,
                                                               'status_message': "'Forbidden'",
                                                               'success_status': 101}}]},
                           'type': 'WebSocketBadStatusException',
                           'value': 'Handshake status 403 Forbidden'}]},
 'extra': {'sys.argv': ["'C:\\tools\\airtest\\AirtestIDE-win-1.2.8\\AirtestIDE\\AirtestIDE.exe'"]},
 'level': 40,
 'message': 'WebSocketBadStatusException: Handshake status 403 Forbidden',
 'modules': {'python': '3.6.8'},
 'platform': 'python',
 'project': '3',
 'release': '1.2.8',
 'server_name': 'AirtestIDE',
 'tags': {'bit': '64bit', 'debug': 'RELEASE', 'platform': 'Windows'},
 'time_spent': None,
 'timestamp': '2023-05-25T06:45:05Z'}
['WebSocketBadStatusException: Handshake status 403 Forbidden', '  File "plugins/selenium_plugin\\selenium_wnd.py", line 217, in startWebSlot', '  File "plugins/selenium_plugin\\selenium_assistant.py", line 68, in get_web_addr', '  File "site-packages\\pychrome\\tab.py", line 206, in start', '  File "site-packages\\websocket\\_core.py", line 494, in create_connection', '  File "site-packages\\websocket\\_core.py", line 220, in connect', '  File "site-packages\\websocket\\_handshake.py", line 69, in handshake', '  File "site-packages\\websocket\\_handshake.py", line 135, in _get_resp_headers']
websocket._exceptions.WebSocketBadStatusException: Handshake status 403 Forbidden
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

![image](https://github.com/AirtestProject/Airtest/assets/49149787/f461ea1e-dacf-4526-a2b8-b9d6b9cf88cd)

**airtest 版本:** `v1.2.8`
**尝试更换v1.2.8以上的版本，问题依然存在**

**设备:**
 - 系统: 
 
![image](https://github.com/AirtestProject/Airtest/assets/49149787/e88a722c-159b-4d20-846e-9109201a943f)

**Comment by guangxun123** [comment]
我已经找到解决方案，原因是浏览器版本太高，看来是工具没有兼容。详见：https://github.com/AirtestProject/AirtestIDE/issues/1093

希望官方同学能尽快支持
