### ISSUE TITLE
device().list_app("all")报错

### ISSUE THREAD

**Issue by songzhenhua** [AirtestProject/Airtest#1153]
:bulb:**相关项目:** Airtest

**标题:** [BUG提交]device().list_app("all")报错

**AirtestIDE版本:** 无

- [x] **使用了本地Pyhton环境运行脚本**
- Python版本: 3.8
- Airtest版本: v1.3.0

**报错描述:**
&nbsp;&nbsp;&nbsp;&nbsp;airtest1.3.0.1，device().list_app("all")报错
/site-packages/airtest/core/ios/ios.py中第850行，写的是TIDevice.list_app(self.udid, type=type)，但110行却是def list_app(udid, app_type="user")，参数名定义的不一致，一个是app_type，一个是type

**相关截图:**
![](https://hfc20-issue-helper.s3.nie.netease.com/media/2023/08/07/512/1.png)
![](https://hfc20-issue-helper.s3.nie.netease.com/media/2023/08/07/512/2.png)

**报错Log:**
```
Traceback (most recent call last):
  File "/Users/szh/opt/miniconda3/envs/test/lib/python3.8/site-packages/airtest/cli/runner.py", line 75, in runTest
    six.reraise(*sys.exc_info())
  File "/Users/szh/opt/miniconda3/envs/test/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/Users/szh/opt/miniconda3/envs/test/lib/python3.8/site-packages/airtest/cli/runner.py", line 72, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/szh/auto_test/hop/testsuite/suite_newroom_skin/suite_newroom_skin.py", line 26, in <module>
    all_app = dev.list_app()
  File "/Users/szh/opt/miniconda3/envs/test/lib/python3.8/site-packages/airtest/core/ios/ios.py", line 47, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/szh/opt/miniconda3/envs/test/lib/python3.8/site-packages/airtest/core/ios/ios.py", line 850, in list_app
    return TIDevice.list_app(self.udid, type=type)
  File "/Users/szh/opt/miniconda3/envs/test/lib/python3.8/site-packages/airtest/core/ios/ios.py", line 67, in wrapper
    return func(*args, **kwargs)
TypeError: list_app() got an unexpected keyword argument 'type'

```

**连接设备信息:**
设备类型 | 设备型号 | 系统版本号 | apk名称/下载链接 | 使用的wda版本 | wda更新到最新
------------ | ------------- | ------------- | ------------- | -------------  | -------------
iOS |  |  |  | Appium/WebDriverAgent | 否

**提供最小可复现此BUG的代码:**
```
无
```

**Comment by yimelia** [comment]
感谢提出，最新版已修复此问题
