### ISSUE TITLE
进程运行用例执行失败报错orientationWatcher has ended后卡死

### ISSUE THREAD

**Issue by Louis-me** [AirtestProject/Airtest#1160]
**环境信息**
- win10 python3.7.9 
- pocoui==1.0.80 和1.0.89
- airtest==1.1.7 和1.3.0.1
- vivo 真机和雷电模拟器
- pycham
**描述问题bug**

- 采用进程批量运行用例报错orientationWatcher has ended，后续操作直接卡死无法操作
- 下面时核心代码
```
# 启动器
from multiprocessing import Pool
tm_cases=[{},{}]
pool = Pool()
 pool.map(self.run_case1, tm_cases)
for i in testcase:
  args = Namespace(device=air_device, log=log, compress=None, recording=recording, script=script, no_image=None)
  run_script(args, AirtestCase)

# 测试用例  test.air
auto_setup(__file__)
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)
 try:
        poco(text="取消").click() if poco(text="取消").exists() else print("")
        # 点击我的
        poco("com.jianshu.haruki:id/tv_more_menu").wait(5).click()
        # 点击我的文章
        poco(text="我的文章1").wait(5).click()
        # 向上滑动
        # poco("com.jianshu.haruki:id/refresh_view").focus([0.5, 0.5]).swipe([0.5, -0.5])
    except Exception as e:
        snapshot(msg="报错后截图")
        raise e
 
```
**报错**
```
D:\app\Python37\python.exe E:/proj/airtestAutoTest/runner.py
[05:37:13][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 wait-for-device
[05:37:13][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk
[05:37:13][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys activity top
[05:37:13][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.netease.nie.yosemite
[05:37:13][INFO]<airtest.core.android.yosemite> local version code is 303, installed version code is 421
[05:37:13][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell settings get secure default_input_method
[05:37:13][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ime list -a
[05:37:14][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.netease.open.pocoservice
installed version is 41, installer version is 41. force_reinstall=False
[05:37:14][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[05:37:14][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:17919 tcp:10080
[05:37:14][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:11720 tcp:10081
[05:37:14][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ps -A |echo $(grep -E com.github.uiautomator)
[05:37:14][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell am force-stop com.netease.open.pocoservice
[05:37:14][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell am start -n com.netease.open.pocoservice/.TestActivity
[05:37:14][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner

[05:37:21][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell monkey -p com.jianshu.haruki -c android.intent.category.LAUNCHER 1
D:\app\Python37\Lib\site-packages\airtest\report\log\2023-09-14-17-37-12\他的\我的_001_打开我的关注 创建日志文件成功
save log in 'D:\app\Python37\Lib\site-packages\airtest\report\log\2023-09-14-17-37-12\他的\我的_001_打开我的关注'
[05:37:21][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 wait-for-device
[05:37:21][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk
[05:37:21][WARNING]<airtest.core.api> Device:emulator-5554 updated <airtest.core.android.android.Android object at 0x00000246EA62CC48> -> <airtest.core.android.android.Android object at 0x00000246EA660208>
[05:37:21][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys activity top
[05:37:22][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.netease.nie.yosemite
[05:37:22][INFO]<airtest.core.android.yosemite> local version code is 303, installed version code is 421
[05:37:22][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell settings get secure default_input_method
[05:37:22][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ime list -a
[05:37:22][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.netease.open.pocoservice
installed version is 41, installer version is 41. force_reinstall=False
[05:37:22][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[05:37:22][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:16363 tcp:10080
[05:37:22][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:14715 tcp:10081
[05:37:22][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ps -A |echo $(grep -E com.github.uiautomator)

[05:37:23][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell pm path jp.co.cyberagent.stf.rotationwatcher
[05:37:23][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-63dJAEM_z3bx2OF051gToA==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ls /data/local/tmp/minicap
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ls /data/local/tmp/minicap.so
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[05:37:24][DEBUG]<airtest.core.android.minicap> version:5
[05:37:24][DEBUG]<airtest.core.android.minicap> upgrade minicap to lastest version: 5->6
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell rm -r /data/local/tmp/minicap*
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.cpu.abi
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.preview_sdk
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.release
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 push D:\app\Python37\lib\site-packages\airtest\core\android\static\stf_libs\x86_64\minicap /data/local/tmp/minicap
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 push D:\app\Python37\lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-28/x86_64/minicap.so /data/local/tmp/minicap.so
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap.so
[05:37:24][INFO]<airtest.core.android.minicap> minicap installation finished
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[05:37:24][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys window displays
[05:37:25][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.product.cpu.abi
[05:37:25][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk
[05:37:25][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell ls -l /data/local/tmp/minitouch
[05:37:25][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 push D:\\app\\Python37\\lib\\site-packages\\airtest\\core\\android\\static\\stf_libs\\x86_64\\minitouch /data/local/tmp/minitouch
[05:37:25][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minitouch
[05:37:25][INFO]<airtest.core.android.touch_methods.minitouch> install_minitouch finished
[05:37:25][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[05:37:25][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys window displays
[05:37:25][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:17492 localabstract:minitouch_17492
[05:37:25][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell /data/local/tmp/minitouch -n 'minitouch_17492' 2>&1
[05:37:25][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mouse0 is not supported by libevdev'
[05:37:25][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mice is not supported by libevdev'
[05:37:25][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Type B touch device input (1919x1079 with 16 contacts) detected on /dev/input/event2 (score 22453)'
[05:37:25][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: hard-limiting maximum number of contacts to 10'
[05:37:25][DEBUG]<airtest.core.android.touch_methods.minitouch> minitouch header:b'v 1\n^ 10 1919 1079 2\n$ 16556\n'
[05:37:25][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Connection established'
[05:37:40][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --no-rebind tcp:12294 localabstract:minicap_12294
[05:37:40][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[05:37:40][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell dumpsys window displays
[05:37:41][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_12294' -P 1080x1920@1080x1920/0 -l 2>&1
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 16600'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1080x1920@1080x1920/0'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 6268932 bytes for JPG encoder'
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:489) Server start'
[05:37:41][DEBUG]<airtest.core.android.minicap> (1, 24, 16600, 1080, 1920, 1080, 1920, 0, 2)
[05:37:41][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:492) New client connection'
[05:37:41][ERROR]<airtest.core.api> Traceback (most recent call last):
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 26, in wrapped
    proxy.wait_for_appearance(timeout=proxy.poco._pre_action_wait_for_appearance)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 681, in wait_for_appearance
    raise PocoTargetTimeout('appearance', self)
poco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of "UIObjectProxy of "text=我的文章1""

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\app\Python37\lib\site-packages\airtest\cli\runner.py", line 70, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "E:\proj\airtestAutoTest\air_case\android\他的\我的_001_打开我的关注.air\我的_001_打开我的关注.py", line 40, in <module>
    operate()
  File "E:\proj\airtestAutoTest\air_case\android\他的\我的_001_打开我的关注.air\我的_001_打开我的关注.py", line 37, in operate
    raise e
  File "E:\proj\airtestAutoTest\air_case\android\他的\我的_001_打开我的关注.air\我的_001_打开我的关注.py", line 32, in operate
    poco(text="我的文章1").wait(5).click()
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 29, in wrapped
    raise e
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 874, in _do_query
    raise PocoNoSuchNodeException(self)
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "text=我的文章1"

======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 26, in wrapped
    proxy.wait_for_appearance(timeout=proxy.poco._pre_action_wait_for_appearance)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 681, in wait_for_appearance
    raise PocoTargetTimeout('appearance', self)
poco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of "UIObjectProxy of "text=我的文章1""

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\app\Python37\lib\site-packages\airtest\cli\runner.py", line 73, in runTest
    six.reraise(*sys.exc_info())
  File "D:\app\Python37\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\app\Python37\lib\site-packages\airtest\cli\runner.py", line 70, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "E:\proj\airtestAutoTest\air_case\android\他的\我的_001_打开我的关注.air\我的_001_打开我的关注.py", line 40, in <module>
    operate()
  File "E:\proj\airtestAutoTest\air_case\android\他的\我的_001_打开我的关注.air\我的_001_打开我的关注.py", line 37, in operate
    raise e
  File "E:\proj\airtestAutoTest\air_case\android\他的\我的_001_打开我的关注.air\我的_001_打开我的关注.py", line 32, in operate
    poco(text="我的文章1").wait(5).click()
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 29, in wrapped
    raise e
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "D:\app\Python37\lib\site-packages\poco\proxy.py", line 874, in _do_query
    raise PocoNoSuchNodeException(self)
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "text=我的文章1"

----------------------------------------------------------------------
Ran 1 test in 19.571s

FAILED (errors=1)
[05:37:41][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:17919
[05:37:41][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:11720
[05:37:41][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:16363
[05:37:41][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:14715
[05:37:41][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:17492
[05:37:41][DEBUG]<airtest.core.android.adb> D:\app\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s emulator-5554 forward --remove tcp:12294
[05:37:41][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended

```
**截图**
![image](https://github.com/AirtestProject/Airtest/assets/3804513/29fbbf35-9d46-44d2-b2f0-905836a020c7)

**期望结果**
- 执行用例失败后，不影响到其他后续操作

**其他**
- 不使用进程的方式运行批量用例没有问题
- 中途没有调用adb做其他操作

**Comment by yimelia** [comment]
'orientationWatcher has ended' 这只是一条debug log，不是报错，真正的报错是这个：

poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "text=我的文章1"

检查你的界面上是否存在这个元素。
