### ISSUE TITLE
使用Airtest框架编写的PC端python自动化测试脚本无法在Linux系统下执行

### ISSUE THREAD

**Issue by 957Natural** [AirtestProject/Airtest#1178]
Remove any following parts if does not have details about

**Describe the bug**
无法在Linux系统下执行,报错提示
root@root:/home/xie/test# airtest run test.py  --device "Windows:///?title_re=Skype" --log /
save log in '/'
======================================================================
ERROR: setUpClass (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airtest/cli/runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "/usr/local/lib/python3.9/site-packages/airtest/cli/runner.py", line 149, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root, compress)
  File "/usr/local/lib/python3.9/site-packages/airtest/core/api.py", line 141, in auto_setup
    connect_device(dev)
  File "/usr/local/lib/python3.9/site-packages/airtest/utils/logwraper.py", line 131, in wrapper
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/airtest/core/api.py", line 74, in connect_device
    dev = init_device(platform, uuid, **params)
  File "/usr/local/lib/python3.9/site-packages/airtest/core/api.py", line 41, in init_device
    cls = import_device_cls(platform)
  File "/usr/local/lib/python3.9/site-packages/airtest/core/helper.py", line 249, in import_device_cls
    from airtest.core.win.win import Windows as cls
  File "/usr/local/lib/python3.9/site-packages/airtest/core/win/__init__.py", line 4, in <module>
    from .win import Windows
  File "/usr/local/lib/python3.9/site-packages/airtest/core/win/win.py", line 10, in <module>
    import win32api
ModuleNotFoundError: No module named 'win32api'

```
paste traceback here
```

**To Reproduce**

**Expected behavior**
希望让airtest编写的PC端自动化测试脚本可以在Linux系统下执行

**Screenshots**

**python version:** `python3.9`

**airtest version:** `1.3.1`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Ubunto16.04
 - more information if have

**Additional context**

**Comment by yimelia** [comment]
`pip install win32api`
