### ISSUE TITLE
安装完最新的appium的wda，airtest无法连接IOS

### ISSUE THREAD

**Issue by zhangruejun** [AirtestProject/Airtest#1200]
:bulb:**相关项目:** Airtest

**标题:** [BUG提交]安装完最新的appium的wda，airtest无法连接IOS

**AirtestIDE版本:** 1.2.17

**未使用本地Pyhton环境运行脚本**

**报错描述:**
&nbsp;&nbsp;&nbsp;&nbsp;wda安装成功，服务也已经启动了，浏览器ios信息也能输出。airtest就是连接不上，每次都报这个。只有16.2系统那台设备能正常连接。IOS14.3、13.3设备都不行。

**相关截图:**
无

**报错Log:**
```

[17:10:23][DEBUG]<airtest.core.android.adb> C:\Users\zhangzhanwei\Desktop\AirtestIDE-win-1.2.15\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices
[I 240305 17:10:23 _device:984] BundleID: com.facebook.WebDriverAgentRunnerZZwaa.xctrunner
[I 240305 17:10:23 _device:1000] ProductVersion: 13.6
[I 240305 17:10:23 _device:1001] DeviceIdentifier: 00008030-000E656C1403802E
[I 240305 17:10:24 _device:1122] xctrunner quited
[17:10:28][ERROR]<airtest> Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 380, in _make_request
  File "http\client.py", line 1331, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 266, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 638, in urlopen
  File "site-packages\urllib3\util\retry.py", line 367, in increment
  File "site-packages\urllib3\packages\six.py", line 685, in reraise
  File "site-packages\urllib3\connectionpool.py", line 600, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages\urllib3\connectionpool.py", line 380, in _make_request
  File "http\client.py", line 1331, in getresponse
  File "http\client.py", line 297, in begin
  File "http\client.py", line 266, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\plugins\devicepool\abstract\device.py", line 84, in run
  File "app\plugins\devicepool\ios\device.py", line 157, in connect
  File "C:\Users\zhangzhanwei\Desktop\AirtestIDE-win-1.2.15\AirtestIDE\airtest\core\ios\ios.py", line 536, in display_info
    self._display_info()
  File "C:\Users\zhangzhanwei\Desktop\AirtestIDE-win-1.2.15\AirtestIDE\airtest\core\ios\ios.py", line 545, in _display_info
    snapshot = self.snapshot()
  File "C:\Users\zhangzhanwei\Desktop\AirtestIDE-win-1.2.15\AirtestIDE\airtest\core\ios\ios.py", line 47, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\zhangzhanwei\Desktop\AirtestIDE-win-1.2.15\AirtestIDE\airtest\core\ios\ios.py", line 633, in snapshot
    data = self._neo_wda_screenshot()
  File "C:\Users\zhangzhanwei\Desktop\AirtestIDE-win-1.2.15\AirtestIDE\airtest\core\ios\ios.py", line 618, in _neo_wda_screenshot
    value = self.driver.http.get('screenshot').value
  File "site-packages\wda\utils.py", line 47, in _inner
  File "site-packages\wda\__init__.py", line 454, in _fetch
  File "site-packages\wda\__init__.py", line 124, in httpdo
  File "site-packages\wda\__init__.py", line 154, in _unsafe_httpdo
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**连接设备信息:**
设备类型 | 设备型号 | 系统版本号 | apk名称/下载链接 | 使用的wda版本 | wda更新到最新
------------ | ------------- | ------------- | ------------- | -------------  | -------------
iOS | iPhone 12 | IOS 14.2 |  | Appium/WebDriverAgent | 是

**提供最小可复现此BUG的代码:**
```
无
```

**Comment by csushiye** [comment]
也遇到类似的问题，手机iphone12，ios14
