### ISSUE TITLE
支持iOS 17

### ISSUE THREAD

**Issue by mewehk** [AirtestProject/Airtest#1223]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**描述问题bug**
连接不上iOS 17的设备
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tidevice/_device.py", line 501, in start_service
    return self._unsafe_start_service(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tidevice/_device.py", line 520, in _unsafe_start_service
    raise MuxServiceError(error)
tidevice.exceptions.MuxServiceError: InvalidService

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1535, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/m/Dev/pos_automation_test/ui_automation/tests/place_takeout_order/place_takeout_order.py", line 36, in <module>
    main()
  File "/Users/m/Dev/pos_automation_test/ui_automation/helper/report.py", line 9, in wrapper
    test_func(*args, **kwargs)
  File "/Users/m/Dev/pos_automation_test/ui_automation/tests/place_takeout_order/place_takeout_order.py", line 20, in main
    launch_app()
  File "/Users/m/Dev/pos_automation_test/ui_automation/setup.py", line 28, in launch_app
    start_app(config.APP_BUNDLE_ID)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airtest/utils/logwraper.py", line 131, in wrapper
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airtest/core/api.py", line 189, in start_app
    G.DEVICE.start_app(package, activity)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airtest/core/ios/ios.py", line 51, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airtest/core/ios/ios.py", line 865, in start_app
    return TIDevice.start_app(self.udid, bundle_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airtest/core/ios/ios.py", line 71, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/airtest/core/ios/ios.py", line 215, in start_app
    BaseDevice(udid, Usbmux()).app_start(bundle_id=bundle_id)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tidevice/_device.py", line 720, in app_start
    with self.connect_instruments() as ts:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
           ^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tidevice/_device.py", line 814, in connect_instruments
    conn = self.start_service(
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tidevice/_device.py", line 503, in start_service
    self.mount_developer_image()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tidevice/_device.py", line 674, in mount_developer_image
    raise ServiceError("DeveloperImage not found")

```

**复现步骤**
直接运行

**预期效果**
连接上设备

**python 版本:** `python3.12.4`

**airtest 版本:** `1.3.3`

**设备:**
 - 型号: [iPad]
 - 系统: [iOS 17.5]
 - (别的信息)

**其他相关环境信息**
Mac

**Comment by Zebratestuser** [comment]
how did you solve this problem?

**Comment by brucehank** [comment]
I have the same issue, unable to test iOS 17+. Does anyone know if Airtest will address this problem in the future?

**Comment by loading0** [comment]
连一个官方回复都没有的，这是让大家放弃airtest吗？
