### ISSUE TITLE
Unable to connect_device()

### ISSUE THREAD

**Issue by ahsenqamar** [AirtestProject/Airtest#125]
Hi,
I am trying a very simple procedure to make sure that my phone gets connected. Here is the code:
```
from airtest.core.api import *

# connect to android phone with adb
connect_device("android:///")
```
I am seeing the error:
```
Connected to pydev debugger (build 181.5087.37)
[09:49:57][DEBUG]<airtest.core.android.adb> /home/local/user/.env/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb devices
Traceback (most recent call last):
  File "/home/local/user/Applications/pycharm-2018.1.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/local/user/Applications/pycharm-2018.1.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/local/user/Applications/pycharm-2018.1.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/local/user/connqa_tests/tests/app_tests/test_cases.py", line 4, in <module>
    connect_device("android:///")
  File "/home/local/user/.env/local/lib/python2.7/site-packages/airtest/core/api.py", line 62, in connect_device
    dev = init_device(platform, uuid, **params)
  File "/home/local/user/.env/local/lib/python2.7/site-packages/airtest/core/api.py", line 32, in init_device
    dev = cls(uuid, **kwargs)
  File "/home/local/user/.env/local/lib/python2.7/site-packages/airtest/core/android/android.py", line 32, in __init__
    if not ADB().devices(state="device"):
  File "/home/local/user/.env/local/lib/python2.7/site-packages/airtest/core/android/adb.py", line 215, in devices
    output = self.cmd("devices", device=False)
  File "/home/local/user/.env/local/lib/python2.7/site-packages/airtest/core/android/adb.py", line 172, in cmd
    proc = self.start_cmd(cmds, device)
  File "/home/local/user/.env/local/lib/python2.7/site-packages/airtest/core/android/adb.py", line 151, in start_cmd
    stderr=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```
It seems to be an issue with getting the device list using ADB. I noticed that it is trying to use the version of ADB that comes as part of the pip install and that should work. I am running this on Linux and a Galaxy S7 (Android N). Any help would be appreciated.

**Comment by Meteorix** [comment]
Please locate the adb executable in `/home/local/user/.env/local/lib/python2.7/site-packages/airtest/core/android/`, and `chmod +x adb` to grant execute permission.

**Comment by ahsenqamar** [comment]
Thanks that worked.
