### ISSUE TITLE
最新版1.3.4安装，numpy报异常

### ISSUE THREAD

**Issue by felixruan** [AirtestProject/Airtest#1251]
* 图像识别、设备控制相关问题

**描述问题bug**
pip install airtest，对应的numpy版本是2.0.2。然后测试代码中引入：
from airtest.core.android.adb import ADB
报错如下异常：

```
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000
Traceback (most recent call last):
  File "D:\python\test\testcompat.py", line 22, in setup_test_compat
    from airtest.core.android.adb import ADB
  File "D:\python\test\venv\lib\site-packages\airtest\core\android\__init__.py", line 4, in <module>
    from airtest.core.android.android import Android
  File "D:\python\test\venv\lib\site-packages\airtest\core\android\android.py", line 8, in <module>
    from airtest import aircv
  File "D:\python\test\venv\lib\site-packages\airtest\aircv\__init__.py", line 1, in <module>
    from .aircv import *  # noqa
  File "D:\python\test\venv\lib\site-packages\airtest\aircv\aircv.py", line 5, in <module>
    import cv2
  File "D:\python\test\venv\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "D:\python\test\venv\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib\__init__.py", line 127, in import_module
    applySysPathWorkaround = True
ImportError: numpy.core.multiarray failed to import
```

**python 版本:** `python3.9.12`

**airtest 版本:** `1.3.4`

**Comment by felixruan** [comment]
需要手动降低numpy的版本至
pip install numpy==1.26.4
