### ISSUE TITLE
airtest.aircv.error.FileNotExistError

### ISSUE THREAD

**Issue by Seeincup-Ming** [AirtestProject/Airtest#137]
饪?  AirTest airtest report run.air
run.air/tpl1534489236607.png
Traceback (most recent call last):
  File "/usr/local/bin/airtest", line 9, in <module>
    load_entry_point('airtest==1.0.22', 'console_scripts', 'airtest')()
  File "/Library/Python/2.7/site-packages/airtest/cli/__main__.py", line 13, in main
    report_main(args)
  File "/Library/Python/2.7/site-packages/airtest/report/report.py", line 385, in main
    rpt.report(HTML_TPL, output_file=args.outfile, record_list=record_list)
  File "/Library/Python/2.7/site-packages/airtest/report/report.py", line 324, in report
    steps = self._analyse()
  File "/Library/Python/2.7/site-packages/airtest/report/report.py", line 83, in _analyse
    translated_steps = [self._translate_step(s) for s in steps]
  File "/Library/Python/2.7/site-packages/airtest/report/report.py", line 90, in _translate_step
    code = self._translate_code(step)
  File "/Library/Python/2.7/site-packages/airtest/report/report.py", line 198, in _translate_code
    crop_img = imread(os.path.join(self.script_root, str(value['filename'])))
  File "/Library/Python/2.7/site-packages/airtest/aircv/aircv.py", line 15, in imread
    raise FileNotExistError("File not exist: %s" % filename)
airtest.aircv.error.FileNotExistError

**Comment by Seeincup-Ming** [comment]
生成报告的时候，保留这个错。发现run.air/tpl1534489236607.png这个文件并没有生成。

**Comment by Seeincup-Ming** [comment]
raceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.22-py3.6.egg/airtest/__main__.py", line 6, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.22-py3.6.egg/airtest/cli/__main__.py", line 13, in main
    report_main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.22-py3.6.egg/airtest/report/report.py", line 385, in main
    rpt.report(HTML_TPL, output_file=args.outfile, record_list=record_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.22-py3.6.egg/airtest/report/report.py", line 324, in report
    steps = self._analyse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.22-py3.6.egg/airtest/report/report.py", line 83, in _analyse
    translated_steps = [self._translate_step(s) for s in steps]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.22-py3.6.egg/airtest/report/report.py", line 83, in <listcomp>
    translated_steps = [self._translate_step(s) for s in steps]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.22-py3.6.egg/airtest/report/report.py", line 90, in _translate_step
    code = self._translate_code(step)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.22-py3.6.egg/airtest/report/report.py", line 198, in _translate_code
    crop_img = imread(os.path.join(self.script_root, str(value['filename'])))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest-1.0.22-py3.6.egg/airtest/aircv/aircv.py", line 14, in imread
    raise FileNotExistError("File not exist: %s" % filename)
airtest.aircv.error.FileNotExistError: File not exist: run.air/tpl1534489236607.png

我怀疑是 python 的版本不对，所以升级了版本之后，依然是这个错误

**Comment by Seeincup-Ming** [comment]
python3 -m airtest run run.air --log
python3 -m airtest report run.air/

**Comment by yimelia** [comment]
@Seeincup-Ming `run.air/tpl1534489236607.png`是生成脚本时的脚本内图片，可以确认一下生成脚本时是否生成了这张图，可以用AirtestIDE重新截取一次，保存后再尝试运行

**Comment by yimelia** [comment]
如果还有问题，可以re-open这个issue
