### ISSUE TITLE
手机连接IDE，操作IDE画面报错

### ISSUE THREAD

**Issue by 15968822059** [AirtestProject/Airtest#138]
机型：Redmi Note 5A  
Android版本:7.1.2

RuntimeError: minitouch setup timeout
Traceback (most recent call last):
  File "app\plugins\device\android\util.py", line 185, in run
  File "airtest\utils\snippet.py", line 104, in ready_func
  File "airtest\utils\snippet.py", line 115, in wrapper
  File "airtest\core\android\minitouch.py", line 51, in install_and_setup
  File "airtest\core\android\minitouch.py", line 143, in setup_server
RuntimeError: minitouch setup timeout

**Comment by yimelia** [comment]
@15968822059 
小米设备请参考 [FAQ](http://airtest.netease.com/docs/docs_AirtestIDE-zh_CN/8_faq/2_android_faq.html#id8)，打开开发者选项中的多个设置之后再尝试重新连接~
