### ISSUE TITLE
airtest report 无法找到图片,生成report

### ISSUE THREAD

**Issue by zijunt** [AirtestProject/Airtest#160]
如果直接使用 airtestIDE, 可以生成report, log.html
```
/Applications/AirtestIDE.app/Contents/MacOS/AirtestIDE reporter /Users/roy.tang/dev/UI_airTest/UITest/AccountSettings/Paywall.air --log_root /var/folders/hz/gqxjrlvd43l4py8bmc0yp1_40000gp/T/AirtestIDE/scripts/2c9bff7d48db93fc7a840dcb13771084 --outfile /var/folders/hz/gqxjrlvd43l4py8bmc0yp1_40000gp/T/AirtestIDE/scripts/2c9bff7d48db93fc7a840dcb13771084/log.html --static_root /Applications/AirtestIDE.app/Contents/MacOS/airtest/report --lang en
```

相同路径下, airtest report 报错
```
airtest report /Users/roy.tang/dev/UI_airTest/UITest/AccountSettings/Paywall.air --log_root /var/folders/hz/gqxjrlvd43l4py8bmc0yp1_40000gp/T/AirtestIDE/scripts/2c9bff7d48db93fc7a840dcb13771084 --outfile /var/folders/hz/gqxjrlvd43l4py8bmc0yp1_40000gp/T/AirtestIDE/scripts/2c9bff7d48db93fc7a840dcb13771084/log.html --static_root /Applications/AirtestIDE.app/Contents/MacOS/airtest/report --lang en

错误信息：
Traceback (most recent call last):
  File "/Users/roy.tang/airtest/bin/airtest", line 11, in <module>
    sys.exit(main())
  File "/Users/roy.tang/airtest/lib/python3.6/site-packages/airtest/cli/__main__.py", line 13, in main
    report_main(args)
  File "/Users/roy.tang/airtest/lib/python3.6/site-packages/airtest/report/report.py", line 385, in main
    rpt.report(HTML_TPL, output_file=args.outfile, record_list=record_list)
  File "/Users/roy.tang/airtest/lib/python3.6/site-packages/airtest/report/report.py", line 324, in report
    steps = self._analyse()
  File "/Users/roy.tang/airtest/lib/python3.6/site-packages/airtest/report/report.py", line 83, in _analyse
    translated_steps = [self._translate_step(s) for s in steps]
  File "/Users/roy.tang/airtest/lib/python3.6/site-packages/airtest/report/report.py", line 83, in <listcomp>
    translated_steps = [self._translate_step(s) for s in steps]
  File "/Users/roy.tang/airtest/lib/python3.6/site-packages/airtest/report/report.py", line 90, in _translate_step
    code = self._translate_code(step)
  File "/Users/roy.tang/airtest/lib/python3.6/site-packages/airtest/report/report.py", line 198, in _translate_code
    crop_img = imread(os.path.join(self.script_root, str(value['filename'])))
  File "/Users/roy.tang/airtest/lib/python3.6/site-packages/airtest/aircv/aircv.py", line 14, in imread
    raise FileNotExistError("File not exist: %s" % filename)
airtest.aircv.error.FileNotExistError: File not exist: /Users/roy.tang/dev/UI_airTest/UITest/AccountSettings/Paywall.air/tpl1529621845911.png
```
在Payway.air测试中由于调用了了另一个测试，airtest report 无法找到另一个测试的图片

**Comment by yimelia** [comment]
@zijunt 你好，请提供一下使用的airtest版本号？

**Comment by zijunt** [comment]
airtest 1.0.22 . airtestIDE 是v1.0.0rc

**Comment by yimelia** [comment]
@zijunt Hi，更新到当前最新版本airtest，这个问题修复啦，如果还有疑问的话可以reopen一下这个Issue
