### ISSUE TITLE
airtest脚本打包成apk后，运行报错

### ISSUE THREAD

**Issue by lycfr** [AirtestProject/Airtest#199]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

```
（在这里粘贴traceback或其他报错信息）
```

**相关截图**
airtest脚本很简单：
![image](https://user-images.githubusercontent.com/29672247/48048800-993e1100-e1d7-11e8-8f4c-639f0b303708.png)

`C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\apk>adb shell am instrument
 -w com.netease.open.airbase/android.support.test.runner.AndroidJUnitRunner

org.kivy.android.ExampleInstrumentedTest:
Error in launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest):
junit.framework.AssertionFailedError:
=================script error start================
Traceback (most recent call last):
  File "copy_app\main.py", line 81, in test
  File "/data/data/com.netease.open.airbase/files/app/meipaidemo.air/meipaidemo.
py", line 8, in <module>
    touch(Template(r"tpl1541486716314.png", record_pos=(0.001, 0.801), resolutio
n=(1080, 1920)))
  File "copy_app/airtest\utils\logwraper.py", line 72, in wrapper
  File "copy_app/airtest\core\api.py", line 256, in touch
  File "copy_app/airtest\utils\logwraper.py", line 72, in wrapper
  File "copy_app/airtest\core\cv.py", line 60, in loop_find
TargetNotFoundError: 'Picture Template(tpl1541486716314.png) not found in screen
'
=================script error end================

        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at org.kivy.android.ExampleInstrumentedTest.launchAirtestAndPoco(Example
InstrumentedTest.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
Method.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
lable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
thod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
hod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate
(ActivityTestRule.java:433)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecuto
r.java:58)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRu
nner.java:375)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation
.java:1939)

Time: 33.455
There was 1 failure:
1) launchAirtestAndPoco[0](org.kivy.android.ExampleInstrumentedTest)
junit.framework.AssertionFailedError:
=================script error start================
Traceback (most recent call last):
  File "copy_app\main.py", line 81, in test
  File "/data/data/com.netease.open.airbase/files/app/meipaidemo.air/meipaidemo.
py", line 8, in <module>
    touch(Template(r"tpl1541486716314.png", record_pos=(0.001, 0.801), resolutio
n=(1080, 1920)))
  File "copy_app/airtest\utils\logwraper.py", line 72, in wrapper
  File "copy_app/airtest\core\api.py", line 256, in touch
  File "copy_app/airtest\utils\logwraper.py", line 72, in wrapper
  File "copy_app/airtest\core\cv.py", line 60, in loop_find
TargetNotFoundError: 'Picture Template(tpl1541486716314.png) not found in screen
'
=================script error end================

        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at org.kivy.android.ExampleInstrumentedTest.launchAirtestAndPoco(Example
InstrumentedTest.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
Method.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
lable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
thod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
hod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate
(ActivityTestRule.java:433)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecuto
r.java:58)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRu
nner.java:375)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation
.java:1939)

FAILURES!!!
Tests run: 1,  Failures: 1`

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号:红米5plus
 - 系统: [android 7.1.2
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
报错内容是 `TargetNotFoundError: 'Picture Template(tpl1541486716314.png) not found in screen` ，在当前屏幕上没找到目标图片，可以尝试在IDE上连手机，多调试运行直到成功率较高后再进行打包
