### ISSUE TITLE
通过pid获取windows窗口的情况下，报没有取整的错误

### ISSUE THREAD

**Issue by startnothings** [AirtestProject/Airtest#206]
**问题分类**
* 设备控制

**Demo**
```python
from airtest.core import api
device = api.connect_device('windows:///?process=6666')
```
**描述问题bug**
应该先对pid进行取整

报错信息
```python
Traceback (most recent call last):
  File "E:/ftest/airtest_test.py", line 4, in <module>
    device = api.connect_device('windows:///?process=4')
  File "C:\Python27\lib\site-packages\airtest\core\api.py", line 62, in connect_device
    dev = init_device(platform, uuid, **params)
  File "C:\Python27\lib\site-packages\airtest\core\api.py", line 32, in init_device
    dev = cls(uuid, **kwargs)
  File "C:\Python27\lib\site-packages\airtest\core\win\win.py", line 40, in __init__
    self._init_connect(handle, kwargs)
  File "C:\Python27\lib\site-packages\airtest\core\win\win.py", line 50, in _init_connect
    self.connect(**kwargs)
  File "C:\Python27\lib\site-packages\airtest\core\win\win.py", line 68, in connect
    self.app = self._app.connect(**kwargs)
  File "C:\Python27\lib\site-packages\pywinauto\application.py", line 917, in connect
    assert_valid_process(self.process)
  File "C:\Python27\lib\site-packages\pywinauto\application.py", line 1293, in assert_valid_process
    process_handle = win32api.OpenProcess(win32con.MAXIMUM_ALLOWED, 0, process_id)
TypeError: an integer is required
```

**Comment by yimelia** [comment]
参数错误，是handle=6666，而不是process

**Comment by yimelia** [comment]
感谢反馈，该问题将在下次更新时修复

**Comment by startnothings** [comment]
我不确定这里是否应该使用handle，但是如果填入handle参数，在对Windows类实例化时，会传入多个handle参数，导致报错。
```python
Traceback (most recent call last):
  File "E:/ftest/airtest_test.py", line 4, in <module>
    device = api.connect_device('windows:///?handle=6666')
  File "C:\Python27\lib\site-packages\airtest\core\api.py", line 62, in connect_device
    dev = init_device(platform, uuid, **params)
  File "C:\Python27\lib\site-packages\airtest\core\api.py", line 32, in init_device
    dev = cls(uuid, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'handle'
```

**Comment by yimelia** [comment]
@startnothings 之前的回复有误，这里的确是有问题的，下个版本会修复。
当前支持的连接语句可以这样写： `windows:///666666`，这里的6666是handle，等这里bug修复后可以支持 `windows:///?process=66666` 这样的参数
