### ISSUE TITLE
Mac上AirtestIDE无法抓取UI

### ISSUE THREAD

**Issue by geonsme** [AirtestProject/Airtest#214]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
AirtestIDE for Mac，选中Unity模式，UI显示框显示不出游戏中的UI结构。脚本运行是正常的，桌面同步也是正常的，但是不能通过IDE抓UI名字了，在Screen上没有描绘出UI结构

```
无报错代码
```

**相关截图**
![image](https://user-images.githubusercontent.com/15323302/49359973-bf8d9880-f712-11e8-921b-18e50d1e23d6.png)

**复现步骤**
1. 在Mac上使用AirtestIDE连接
2. Go to Poco Assistant的Unity模式
4. UI Inspector没有刷新出UI数据

**预期效果**
poco inspector能显示ui数据
对应的screen上显示UI结构，并可以直接选中

**python 版本:** `python3.5`

**airtest 版本:** `1.1.0`

**设备:**
 - 系统：ios 12.1.1

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by brantxiong** [comment]
可以修改下UnityPoco连接代码试试：
```python
from airtest.core.api import device as current_device
print(current_device().get_ip_address())

# pass the device object to initialize poco instance
poco = UnityPoco(device=current_device())
```
可以贴下输出看看

**Comment by geonsme** [comment]
> 可以修改下UnityPoco连接代码试试：
> 
> ```python
> from airtest.core.api import device as current_device
> print(current_device().get_ip_address())
> 
> # pass the device object to initialize poco instance
> poco = UnityPoco(device=current_device())
> ```
> 
> 可以贴下输出看看

已经查到了解决方案，需要通过terminal，执行bash ````./AirtestIDE```启动IDE，如果直接双击IDE不会加载其他插件

**Comment by sucl266** [comment]
您好，我也遇到了类似的问题，按您的代码输出如下，希望能帮忙看看
[Start running..]
save log in '/var/folders/rz/_g25p3h96vd18by1rcxr275r0000gn/T/AirtestIDE/scripts/2c18c10e1cdf82bed5cf2411531ab90a'
192.168.33.69
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 65, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 61, in runTest
  File "/Users/liuxx/sucl/ios总结文档/2、JJGameSDK相关/AirtestIDE.app/Contents/MacOS/11.air/11.py", line 12, in <module>
    poco = UnityPoco(device=current_device())
NameError: name 'UnityPoco' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.716s

FAILED (errors=1)
[Finished]

**Comment by sucl266** [comment]
> 可以修改下UnityPoco连接代码试试：
> 
> ```python
> from airtest.core.api import device as current_device
> print(current_device().get_ip_address())
> 
> # pass the device object to initialize poco instance
> poco = UnityPoco(device=current_device())
> ```
> 
> 可以贴下输出看看

[Start running..]
save log in '/var/folders/rz/_g25p3h96vd18by1rcxr275r0000gn/T/AirtestIDE/scripts/2c18c10e1cdf82bed5cf2411531ab90a'
192.168.33.69
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 65, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 61, in runTest
  File "/Users/liuxx/sucl/ios总结文档/2、JJGameSDK相关/AirtestIDE.app/Contents/MacOS/11.air/11.py", line 12, in <module>
    poco = UnityPoco(device=current_device())
NameError: name 'UnityPoco' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.716s

FAILED (errors=1)
[Finished]

**Comment by sucl266** [comment]
> > 可以修改下UnityPoco连接代码试试：
> > ```python
> > from airtest.core.api import device as current_device
> > print(current_device().get_ip_address())
> > 
> > # pass the device object to initialize poco instance
> > poco = UnityPoco(device=current_device())
> > ```
> > 
> > 
> > 可以贴下输出看看
> 
> 已经查到了解决方案，需要通过terminal，执行bash ````./AirtestIDE```启动IDE，如果直接双击IDE不会加载其他插件

您好，我也遇到类似问题，显示name 'UnityPoco' is not defined，请问该怎么解决啊

  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 65, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 61, in runTest
  File "/Users/liuxx/sucl/ios总结文档/2、JJGameSDK相关/AirtestIDE.app/Contents/MacOS/11.air/11.py", line 12, in <module>
    poco = UnityPoco(device=current_device())
NameError: name 'UnityPoco' is not defined

**Comment by yimelia** [comment]
@sucl266 选中Unity模式后，IDE会提示你插入初始化语句，要点确定

**Comment by sucl266** [comment]
您好，按照您说的，加入初始化后，运行结果如下，还是有问题，希望能帮忙解决一下









| |
苏晨璐
|
|
su_chenlu@163.com
|
签名由网易邮箱大师定制


在2019年07月17日 10:43，yimelia<notifications@github.com> 写道：

@sucl266 选中Unity模式后，IDE会提示你插入初始化语句，要点确定

**Comment by yimelia** [comment]
@sucl266 
看不到内容，如果是报错log的话，请复制文字发出来看看

**Comment by yimelia** [comment]
@sucl266 以及如果问题不完全相同的话，最好是新开一个issue，贴清楚你的环境信息和脚本内容，具体的poco类型等各种信息
