### ISSUE TITLE
minicap获取模拟器的device_info时，报json加载的错

### ISSUE THREAD

**Issue by powerkx** [AirtestProject/Airtest#216]
airtest/core/android/minicap.py

def get_display_info(self):
        """
        Get display info by minicap
        Warnings:
            It might segfault, the preferred way is to get the information from adb commands
        Returns:
            display information
        """
        display_info = self.adb.shell("%s -i" % self.CMD)
        **display_info = json.loads(display_info)**
        display_info["orientation"] = display_info["rotation"] / 90
return display_info

在使用安卓模拟器（MuMu 2.0.25（20181108））时，用minicap获取android device info的时候，上述方法中执行adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i后，display_info得到的字符串包含warning：
C:\Users\xxxxxxx>C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---

**WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.**
{
    "id": 0,
    "width": 1080,
    "height": 1920,
    "xdpi": 160.00,
    "ydpi": 160.00,
    "size": 13.77,
    "density": 2.00,
    "fps": 60.00,
    "secure": true,
    "rotation": 0
}
---0---

从而导致json.loads报错如下：
[04:20:18][INFO]<airtest.core.api> Try finding:
Template(hyg_tab.png)
[04:20:19][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys package com.netease.nie.yosemite ; echo ---$?---
[04:20:19][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[04:20:19][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 forward --no-rebind tcp:19436 localabstract:javacap_19436
[04:20:19][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell pm path com.netease.nie.yosemite ; echo ---$?---
[04:20:20][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell CLASSPATH=/data/app/com.netease.nie.yosemite-1/base.apk exec app_process /system/bin com.netease.nie.yosemite.Capture --scale 100 --socket javacap_19436 -lazy 2>&1
[04:20:21][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'Capture server listening on @javacap_19436'
[04:20:22][DEBUG]<airtest.core.android.javacap> (1, 3, 0, 1080, 1920, 0, 0, 0, 1)
111111111111111111
[04:20:23][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell ls /data/local/tmp/minicap ; echo ---$?---
use minicap get display info...
[04:20:23][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell ls /data/local/tmp/minicap.so ; echo ---$?---
[04:20:23][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1

version:5
[04:20:23][DEBUG]<airtest.core.android.minicap> upgrade minicap to lastest version: -1->5
[04:20:23][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell rm /data/local/tmp/minicap*
[04:20:23][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.product.cpu.abi
[04:20:23][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.preview_sdk
[04:20:23][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.release
[04:20:24][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 push C:\Python36-32\lib\site-packages\airtest\core\android\static\stf_libs\x86\minicap /data/local/tmp/minicap
[04:20:25][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell chmod 755 /data/local/tmp/minicap ; echo ---$?---
[04:20:25][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 push C:\Python36-32\lib\site-packages\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-23/x86/minicap.so /data/local/tmp/minicap.so
[04:20:25][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell chmod 755 /data/local/tmp/minicap.so ; echo ---$?---
[04:20:25][INFO]<airtest.core.android.minicap> minicap installation finished
[04:20:25][DEBUG]<airtest.core.android.adb> C:\Python36-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
5555555555555
LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap
6666666666666
testDown.
E
======================================================================
ERROR: testA (__main__.AndroidTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/pycharm_workspace/utils_job/test_airtest.py", line 97, in testA
    if exists(Template("hyg_tab.png")):
  File "C:\Python36-32\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "C:\Python36-32\lib\site-packages\airtest\core\api.py", line 408, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "C:\Python36-32\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "C:\Python36-32\lib\site-packages\airtest\core\cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "C:\Python36-32\lib\site-packages\airtest\core\android\android.py", line 233, in snapshot
    if ensure_orientation and self.display_info["orientation"]:
  File "C:\Python36-32\lib\site-packages\airtest\core\android\android.py", line 518, in display_info
    self._display_info = self.get_display_info()
  File "C:\Python36-32\lib\site-packages\airtest\core\android\android.py", line 540, in get_display_info
    display_info = self.minicap.get_display_info()
  File "C:\Python36-32\lib\site-packages\airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "C:\Python36-32\lib\site-packages\airtest\core\android\minicap.py", line 139, in get_display_info
    display_info = json.loads(display_info)
  File "C:\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**python 版本:** `python3.6`

**airtest 版本:** `1.0.24`

**设备:**
 - 型号: android模拟器MuMu 2.0.25（20181108）
 - 系统: [e.g. Android 6.0.1]

**Comment by yimelia** [comment]
在device的连接字符串后面加上 `&&ori_method=ADBORI`即可，完整示例如下：
```
Android://127.0.0.1:5037/79d03fa?cap_method=JAVACAP&&ori_method=ADBORI
```

**Comment by powerkx** [comment]
谢谢yimelia提供的方法，改成connect_device("android://localhost:5037/%s?cap_method=JAVACAP&&ori_method=ADBORI" % desired_caps['udid'])之后不报错了

**Comment by huage2580** [comment]
依旧会报错，当我在IDE点运行就没问题。
我自己用cmd运行就会报错。
"F:\AirtestIDE_2018-11-06_py3_win64\AirtestIDE" runner "F:\yScript.air"  --device Android://127.0.0.1:5037/127.0.0.1:7555?cap_method=JAVACAP&&ori_method=ADBORI --log "C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\scripts\d3464acd3af72522df513e8c63a138cb"

**Comment by yimelia** [comment]
@huage2580 可能是因为在使用cmd运行时，部分命令行终端里需要进行转义，具体可以查看 [文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id9)
