### ISSUE TITLE
Text 停止

### ISSUE THREAD

**Issue by Topi9999** [AirtestProject/Airtest#226]
**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
半年前还可以用的text等api，奇奇怪怪问题多就放弃了，现在再试试都不能用了。。都不懂你们更新了啥。。。按键设置了 你们的tosemite输入法了，有输入进去，但是脚本报错终止了。
```

[05:08:16][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices
[05:08:16][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe devices
[05:08:16][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 1e5260bd wait-for-device
[05:08:16][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 1e5260bd shell getprop ro.build.version.sdk
[05:08:17][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 1e5260bd shell dumpsys package com.netease.nie.yosemite
[05:08:17][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[05:08:17][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 1e5260bd shell settings get secure default_input_method
[05:08:17][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 1e5260bd shell ime list -a
[05:08:18][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 1e5260bd shell am broadcast -a ADB_INPUT_TEXT --es msg '123'
[05:08:19][DEBUG]<airtest.core.android.adb> D:\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -s 1e5260bd shell input keyevent ENTER
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\core\android\adb.py", line 368, in shell
  File "airtest\core\android\adb.py", line 326, in raw_shell
  File "airtest\core\android\adb.py", line 187, in cmd
airtest.core.error.AdbError: stdout[b''] stderr[b'']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "E:\AirTest\test1.air\test1.py", line 29, in <module>
    text("123")
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 364, in text
  File "airtest\core\android\android.py", line 314, in text
  File "airtest\core\android\adb.py", line 370, in shell
airtest.core.error.AdbShellError: stdout[b''] stderr[b'']

（在这里粘贴traceback或其他报错信息）
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)
![image](https://user-images.githubusercontent.com/38421083/49722135-f299d400-fc9e-11e8-9c3a-a775fd1a7958.png)

![image](https://user-images.githubusercontent.com/38421083/49722289-6805a480-fc9f-11e8-9422-e3dabf099e06.png)

**复现步骤**
1. 插入设备，text(123)
2.错误中断

**预期效果**
(预期想要得到什么、见到什么)
正常输入，执行下一步呀

**python 版本:** `python3.7`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2] ViVO X9 Plus
 - 系统: [e.g. Android 8.1] 7.1.2
 - (别的信息)

**Comment by Topi9999** [comment]
没有人回答吗。。

**Comment by rockywhisper** [comment]
@Topi9999  Hi，你好。

有2种可能：

1、在设置中配置了本地运行环境？
![image](https://user-images.githubusercontent.com/8188879/49777822-0ac03080-fd3d-11e8-8a5a-3666982b8233.png)
配置本地环境后，可能会因为本地airtest环境的老旧导致adb输出异常。

2、设备的输出异常问题，我们下午会安排同学验证下这台设备。    :-)

**Comment by rockywhisper** [comment]
@Topi9999 

我们验证了一下，发现是正常的。

请确认开发者选项里面的“模拟位置点击”开关是打开的：
![image](https://user-images.githubusercontent.com/8188879/49779091-23334980-fd43-11e8-8ef2-35b278c597c9.png)

**Comment by Topi9999** [comment]
OK 可以了 麻烦结贴

**Comment by rockywhisper** [comment]
@Topi9999  

如果后续有其他奇怪的问题，可以随时提出issues，或者在QQ交流群中沟通哈。

**Comment by Topi9999** [comment]
恩，马上提=。 =
