### ISSUE TITLE
OSError: 36041 requested and 0 written

### ISSUE THREAD

**Issue by houxiaoxuan** [AirtestProject/Airtest#227]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别相关问题 -> https://github.com/AirtestProject/Airtest/issues
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> 此仓库

**描述问题bug**

```
问过客服大哥，说是不是磁盘满了，查看了一下，airtest所在的盘果然是满了，清理后再遇到了再说。


Traceback (most recent call last):
  File "C:\Users\imeu170228\Desktop\P82C-MTBF测试全脚本.air\201812101138\MTBF_1280_NoStop.air\MTBF_1280_NoStop.py", line 186, in MTBF_003
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 254, in touch
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\cv.py", line 60, in loop_find
airtest.core.error.TargetNotFoundError: 'Picture Template(file:///C:/Users/imeu170228/Desktop/P82C-MTBF测试全脚本.air/201812101138/MTBF_1280_NoStop.air/tpl1543801730079.png) not found in screen'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\Users\imeu170228\Desktop\P82C-MTBF测试全脚本.air\201812101138\MTBF_1280_NoStop.air\MTBF_1280_NoStop.py", line 1221, in <module>
  File "C:\Users\imeu170228\Desktop\P82C-MTBF测试全脚本.air\201812101138\MTBF_1280_NoStop.air\MTBF_1280_NoStop.py", line 1203, in main
  File "C:\Users\imeu170228\Desktop\P82C-MTBF测试全脚本.air\201812101138\MTBF_1280_NoStop.air\MTBF_1280_NoStop.py", line 249, in MTBF_003
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 215, in snapshot
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\cv.py", line 83, in try_log_screen
  File "airtest\aircv\aircv.py", line 26, in imwrite
OSError: 36041 requested and 0 written


```

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
![122](https://user-images.githubusercontent.com/39590235/49714527-21588000-fc88-11e8-9113-72672771b9ce.png)

**python 版本:** `python2.7`

**poco 版本:** `1.0.69`
> poco版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)
AirtestIDE windows(64bit)versionV1.1.0

**Comment by adolli** [comment]
暂时先close了。如果不是磁盘满或还有其他问题，请reopen这个issue
