### ISSUE TITLE
android，无法在start_app

### ISSUE THREAD

**Issue by tester20183450** [AirtestProject/Airtest#245]
[Start running..]
save log in 'C:\Users\周晓鸣\AppData\Local\Temp\AirtestIDE\scripts\abf56267304aaf4bc0948e83c04e6edf'
installed version is 39, installer version is 39. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
[pocoservice.apk] background daemon started.
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\Users\周晓鸣\Desktop\action.air\action.py", line 86, in <module>
    action=Action()
  File "C:\Users\周晓鸣\Desktop\action.air\action.py", line 21, in __init__
    self.qsddy=poco("android.widget.GridView").child("android.widget.LinearLayout")[4].child("com.yunda.ydqiantong:id/iv_item_apps")
  File "poco\proxy.py", line 184, in __getitem__
  File "poco\proxy.py", line 821, in _do_query
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "android.widget.GridView/android.widget.LinearLayout"

**Comment by tester20183450** [comment]
修改

**Comment by yimelia** [comment]
在AirtestIDE里选了Android是否能看到UI控件树的内容？

**Comment by yimelia** [comment]
报错内容是说找不到对应控件，可以考虑在start_app后sleep一下等待一段时间看看会不会改善。也可以把代码和截图（控件选取时的）贴出来看看
