### ISSUE TITLE
Mac命令行执行脚本问题

### ISSUE THREAD

**Issue by stevesony** [AirtestProject/Airtest#247]
Mac下使用命令行执行脚本如果脚本里只是ADB命令是没问题的，如果脚本里有图像识别元素运行就会报错！在AirtestIDE下执行脚本是没问题的，唯独命令行执行会出问题！
复制AirtestIDE执行时log里面的运行命令到终端运行也会报错！
sonydeMacBook-Pro:desktop sony$ adb devices
List of devices attached
emulator-5554	device

sonydeMacBook-Pro:desktop sony$ airtest run test01.air --device Android://127.0.0.1:5037/emulator-5554?cap_method=JAVACAP&&ori_method=ADBORI&&touch_method=ADBTOUCH
do not save log
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 wait-for-device
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.sdk
[12:25:51][INFO]<airtest.core.api> Try finding:
Template(file:///Users/sony/Desktop/test01.air/1.png)
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell dumpsys package com.netease.nie.yosemite ; echo ---$?---
[12:25:51][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 forward --no-rebind tcp:11712 localabstract:javacap_11712
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell pm path com.netease.nie.yosemite ; echo ---$?---
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell CLASSPATH=/data/app/com.netease.nie.yosemite-1/base.apk exec app_process /system/bin com.netease.nie.yosemite.Capture --scale 100 --socket javacap_11712 -lazy 2>&1
[12:25:51][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'Capture server listening on @javacap_11712'
[12:25:51][DEBUG]<airtest.core.android.javacap> (1, 3, 0, 1280, 720, 0, 0, 0, 1)
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell ls /data/local/tmp/minicap ; echo ---$?---
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell ls /data/local/tmp/minicap.so ; echo ---$?---
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[12:25:51][DEBUG]<airtest.core.android.minicap> WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.
version:5
[12:25:51][DEBUG]<airtest.core.android.minicap> upgrade minicap to lastest version: -1->5
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell rm /data/local/tmp/minicap*
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell getprop ro.product.cpu.abi
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.preview_sdk
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell getprop ro.build.version.release
[12:25:51][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 push /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/stf_libs/x86/minicap /data/local/tmp/minicap
[12:25:52][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap ; echo ---$?---
[12:25:52][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 push /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/stf_libs/minicap-shared/aosp/libs/android-23/x86/minicap.so /data/local/tmp/minicap.so
[12:25:52][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell chmod 755 /data/local/tmp/minicap.so ; echo ---$?---
[12:25:52][INFO]<airtest.core.android.minicap> minicap installation finished
[12:25:52][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/cli/runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "/Users/sony/Library/Python/3.7/lib/python/site-packages/six.py", line 693, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/cli/runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/sony/Desktop/test01.air/test01.py", line 6, in <module>
    touch(Template(r'file:///Users/sony/Desktop/test01.air/1.png', record_pos=(0.349, -0.204), resolution=(1280, 720)))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/api.py", line 254, in touch
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/android.py", line 233, in snapshot
    if ensure_orientation and self.display_info["orientation"]:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/android.py", line 517, in display_info
    self._display_info = self.get_display_info()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/android.py", line 536, in get_display_info
    display_info = self.minicap.get_display_info()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/utils/snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 136, in get_display_info
    display_info = json.loads(display_info)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 1 test in 1.024s

FAILED (errors=1)
[12:25:52][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 forward --remove tcp:11712
sonydeMacBook-Pro:desktop sony$

**Comment by yimelia** [comment]
模拟器连接前，需要[勾选use javacap选项](http://airtest.netease.com/docs/cn/2_device_connection/3_emulator_connection.html#id6)
因此，在用命令行运行时，也需要添加对应的参数才可以成功截图，请参考这个[文档](http://airtest.netease.com/docs/cn/4_run_script/run_script.html#id10)
