### ISSUE TITLE
数组越界报错

### ISSUE THREAD

**Issue by wangda001** [AirtestProject/Airtest#254]
###深度遍历后操作总会报数组越界错误，不知道咋回事 
```python
Traceback (most recent call last):
  File "C:\Users\wang\PycharmProjects\dhhsd_automation\venv\lib\site-packages\poco\sdk\Selector.py", line 136, in selectImpl
    result = [self.selectImpl(cond, multiple, root, maxDepth, onlyVisibleNode, includeRoot)[i]]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

 File "C:\Users\wang\PycharmProjects\dhhsd_automation\venv\lib\site-packages\poco\sdk\Selector.py", line 139, in selectImpl
    u'Query results index out of range. Index={} condition "{}" from root "{}".'.format(i, cond, root))
poco.sdk.exceptions.NoSuchTargetException: Query results index out of range. Index=6 condition "('>', (('and', (('attr=', ('name', 'BattleMove')),)), ('and', (('attr=', ('name', 'Monster')),))))" from root "<poco.freezeui.hie
```

**Comment by Meteorix** [comment]
请按照issue template重新提一个issue吧，这样没法帮到你
