### ISSUE TITLE
运行脚本时报minitouch setup timeout错误

### ISSUE THREAD

**Issue by az2319808145** [AirtestProject/Airtest#255]
设备：小米手机  root了

执行脚本时报这个错误：minitouch setup timeout
poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)判断元素是否存在
这段语句是poco辅助窗选择android自动生成的语句
我将括号里的这段代码删除之后就好了。想问下这是什么原因？

**Comment by wujie59888** [comment]
> 个是什么问题，直接用IDE运行touch指令，能

IDE 怎么运行touch指令？

**Comment by yimelia** [comment]
1. 直接运行 `touch((x, y))` 注意括号是2层， 传入一个比较便于观察的x,y坐标位置看看是否能运行
2. 运行 `shell('input tap x y')` 同样传入一个便于观察的xy坐标看能否运行

**Comment by wujie59888** [comment]
YIMELIA
测试了，IDE 里面按照你的方式，可以用

**Comment by wujie59888** [comment]
`shell('input swipe x0 y0 x1 y1 100')` 可以滑动，`shell('input tap x y')`   这个是可以的

**Comment by wujie59888** [comment]
单独启动minitouch，找不到设备节点
Note: device /dev/input/mice is not supported by libevdev
Unable to find a suitable touch device


Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\Users\victor\Desktop\airtest环境搭建\AirtestIDE_2019-01-15_py3_win64\script\test.air\test.py", line 12, in <module>
    touch(Template(r"tpl1550835749738.png", record_pos=(-0.291, -0.015), resolution=(1280, 720)))
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 259, in touch
  File "airtest\core\android\android.py", line 337, in touch
  File "airtest\utils\snippet.py", line 104, in ready_func
  File "airtest\utils\snippet.py", line 115, in wrapper
  File "airtest\core\android\minitouch.py", line 51, in install_and_setup
  File "airtest\core\android\minitouch.py", line 143, in setup_server
RuntimeError: minitouch setup timeout

**Comment by wujie59888** [comment]
minitouch识别设备节点的目的是什么？能否跳过找个识别TP 设备节点的步骤直接启动？

**Comment by yimelia** [comment]
1. 当前的IDE版本有点问题，勾选了adb touch后依然会使用Minitouch去进行点击和滑动操作
2. Minitouch适配性比较低，可能非手机设备不一定能够完美适配，具体细节请查阅minitouch的官网代码
3. 我们需要一点时间去尝试修复IDE中不支持adb touch的问题

**Comment by yimelia** [comment]
以及，如果是录制指定apk的脚本，是能够在你们的开发板上用adbtouch进行回放的，目前受到影响的只有IDE下无法操作

**Comment by wujie59888** [comment]
好的，非常感谢，
你们以前的老版本，有哪个IDE版本的adb touch是可以工作的？
minitouch的官网，就是stf那个？

**Comment by yimelia** [comment]
你们以前的老版本，有哪个IDE版本的adb touch是可以工作的？
没有，在IDE的屏幕操作中一直都不支持这个功能，但是脚本运行是没问题的。

minitouch的官网，就是stf那个？
是的

**Comment by wujie59888** [comment]
您估计什么时候能够正式更新这个版本呢？支持adb touch的

**Comment by wujie59888** [comment]
在线等啊 ，谢谢美女先

**Comment by yimelia** [comment]
这个需求已加入排期，下一次更新时会尽可能发布
