### ISSUE TITLE
assert_exists 提示 'str' object has no attribute 'threshold'

### ISSUE THREAD

**Issue by BugaoxingXXX** [AirtestProject/Airtest#261]
**描述问题bug**
在使用assert_exists方法匹配图片的时候，报错

（在这里粘贴traceback或其他报错信息）
`[10:37:56][INFO]<airtest.core.api> Try finding:
t.jpg
Traceback (most recent call last):
  File ".\Untitled-1.py", line 50, in <module>
    assert_exists('t.jpg')
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\api.py", line 445, in assert_exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT, threshold=ST.THRESHOLD_STRICT)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\cv.py", line 48, in loop_find
    query.threshold = threshold
AttributeError: 'str' object has no attribute 'threshold'`

**复现步骤**
1. 启动手机之后，使用assert_exists判断图标是否存在

**预期效果**
期望结果是可以提示图片存在与否

**python 版本:** `Python 3.7.1`

**airtest 版本:** 
`airtest==1.0.25`

**设备:**
VIVO X9 Android 7.1

**Comment by yimelia** [comment]
不能直接传一个字符串作为图片名，图片是一个Template("xxx.png")的类，里面有一些参数的，具体可以用IDE截一张图，然后编辑器里右键切换到代码模式（1.2.0版本的功能），可以看到一张图具体是由哪些参数构成的
如果一定要传一张单独的图片路径作为参数，需要类似这样： `touch(Template("xxx.png"))`
