### ISSUE TITLE
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)

### ISSUE THREAD

**Issue by Don-Charles** [AirtestProject/Airtest#269]
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\Users\Desktop\untitled.air\untitled.py", line 6, in <module>
    touch(Template(r"tpl1550065097047.png", record_pos=(0.292, -0.14), resolution=(900, 650)))
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 259, in touch
  File "D:\AirtestIDE_2019-01-15_py3_win64\airtest\core\win\win.py", line 172, in touch
    self.mouse.press(button=button, coords=coords)
  File "site-packages\pywinauto\mouse.py", line 237, in press
  File "site-packages\pywinauto\mouse.py", line 125, in _perform_click_input
pywintypes.error: (0, 'SetCursorPos', 'No error message is available')

**相关截图**

**预期效果**
预期应该是鼠标点击某个按钮，但结果鼠标没动也没点击，只是将应用窗口置顶了（该应用不能被嵌入）

该应用链接  https://pan.baidu.com/s/18EyAqgoyQRHQx_LpzLeEKQ

**python 版本:** `python3.6`

**airtest 版本:** `1.0.25`

**设备:**
 - 型号: windows 10家庭版
 - 系统:  windows

**Comment by Meteorix** [comment]
请提供更多信息，按照issue template填写，不然没法定位问题

**Comment by yimelia** [comment]
试一下用管理员模式启动IDE，然后重新操作一遍看看？可能是没有权限导致的

**Comment by Don-Charles** [comment]
用管理员模式试了一下，可以了，万分感谢。
