### ISSUE TITLE
多线程 多设备问题

### ISSUE THREAD

**Issue by JustinToken** [AirtestProject/Airtest#275]
Remove any following parts if does not have details about

**Describe the bug**
你们好，
多线程下使用touch命令出现 ValueError: generator already executing 错误。实际上我在测试如何用多线程控制多设备，但是目前看起来困难重重。官方能有个同时控制多设备的demo吗？或者帮助看下以下代码有什么问题

```
paste traceback here
```
![image](https://user-images.githubusercontent.com/47622050/52926775-316c9a00-3372-11e9-9204-3867671858f2.png)

Code:
# -*- encoding=utf8 -*-
import threading
from multiprocessing import Pool

__author__ = "admin"

from airtest.core.api import *
from airtest.core.api import auto_setup
from airtest.core.android import Android
from poco.drivers.android.uiautomation import AndroidUiautomationPoco

path = "C:\\"

devices = {

    "192.168.20.228",
    "192.168.20.232",
    "192.168.20.114",
    "192.168.20.140",
    "192.168.20.152",
    "192.168.20.243"
}

def keppRun(devicesName):
    # dev = connect_device("Android:///" + devicesName)
    dev = Android(devicesName + ":5555")
    dev.wake()

    # dev.clear_app("com.sina.weibo")
    dev.start_app("com.sina.weibo")
    sleep(4.0)
    poco = AndroidUiautomationPoco(dev, use_airtest_input=True, screenshot_each_action=False)
    sleep(4.0)

    touch(Template(path + "tpl1550124121823.jpg", record_pos=(-0.42, -0.758), resolution=(1080, 1920)))
    sleep(1.0)

    poco("com.sina.weibo:id/tv_for_psw_login").click()
    sleep(1.0)

    poco("com.sina.weibo:id/et_pws_username").set_text('15858178134')

    poco("com.sina.weibo:id/et_pwd").set_text('12345678901')

    poco("com.sina.weibo:id/bn_pws_Login").click()

    dev.touch(Template(path + r"point.jpg", record_pos=(0.287, 0.556), resolution=(1080, 2340)))

if __name__ == "__main__":
    threads = []
    auto_setup(__file__)
    for item in devices:
        time.sleep(1)
        t = threading.Thread(target=keppRun, args=(item,), name=item)
        t.setDaemon(True)
        t.start()
        threads.append(t)
    # 等待所有线程完成
    for t in threads:
        t.join()

**Expected behavior**
一台机器控制50台设备。

**Screenshots**

**python version:** `python3.6`

**airtest version:** `1.0.25`

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: Android 8.1
 - more information if have

**Additional context**

**Comment by Meteorix** [comment]
airtest使用了一些全局变量，所以建议一个脚本只控制一个设备，然后写一个总控脚本用subprocess来调用多个脚本

**Comment by Meteorix** [comment]
另外，你也可以尝试使用multiprocess替代threading

**Comment by JustinToken** [comment]
非常感谢您的及时回复，我现在已经可以通过multiprocess控制多设备。但是并发情况下有的机器偶尔会发生cannot unpack non-iterable Template object错误。
发生错误的Code:
![image](https://user-images.githubusercontent.com/47622050/52931085-fecc9c80-3385-11e9-960a-b87ea422604c.png)

**Comment by Meteorix** [comment]
这应该还是multiprocess的问题，可以贴一下完整的traceback吗

**Comment by JustinToken** [comment]
这次没有复现，但是出现了Process crashed。这个问题一直也比较常见。请问airlab也是使用airtest控制的吗，是怎样的架构。

------------------------------
[02:17:44][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Connection established'
[02:17:44][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mice is not supported by libevdev'
[02:17:44][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.243 shell ls /data/local/tmp/minitouch
[02:17:44][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Type A touch device huawei,ts_kit (1080x2340 with 16 contacts) detected on /dev/input/event4 (score 21589)'
[02:17:44][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: hard-limiting maximum number of contacts to 10'
[02:17:45][DEBUG]<airtest.core.android.minitouch> minitouch header:b'v 1\n^ 10 1080 2340 255\n$ 21834\n'
[02:17:45][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Connection established'
[02:17:45][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.243 shell ls -l /data/local/tmp/minitouch
[02:17:45][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.243 shell rm /data/local/tmp/minitouch*
[02:17:45][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.243 push C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\airtest\\core\\android\\static\\stf_libs\\arm64-v8a\\minitouch /data/local/tmp/minitouch
[02:17:45][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.243 shell chmod 755 /data/local/tmp/minitouch
[02:17:46][INFO]<airtest.core.android.minitouch> install_minitouch finished
[02:17:46][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.243 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[02:17:46][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.243 forward --no-rebind tcp:12914 localabstract:minitouch_12914
[02:17:46][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.243 shell /data/local/tmp/minitouch -n 'minitouch_12914' 2>&1
[02:17:46][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mouse0 is not supported by libevdev'
[02:17:46][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mice is not supported by libevdev'
[02:17:46][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Type A touch device huawei,ts_kit (1080x2340 with 16 contacts) detected on /dev/input/event4 (score 21589)'
[02:17:46][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: hard-limiting maximum number of contacts to 10'
[02:17:46][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Connection established'
[02:17:46][DEBUG]<airtest.core.android.minitouch> minitouch header:b'v 1\n^ 10 1080 2340 255\n$ 31286\n'
[02:17:46][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell am force-stop com.netease.open.pocoservice
[02:17:46][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell am start -n com.netease.open.pocoservice/.TestActivity
[02:17:47][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[pocoservice.apk] background daemon started.
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
出錯<traceback object at 0x0EB0FD28>
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[02:17:53][INFO]<airtest.core.api> Try finding:
Template(C:\usr\pythonProject\weibo\keep\testCase\tpl1550124121823.jpg)
[02:17:53][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell pm path jp.co.cyberagent.stf.rotationwatcher
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[02:17:53][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-MrPx2oLbONg4ZfZam_FpDQ==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[02:17:54][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell ls /data/local/tmp/minicap
[02:17:54][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell ls /data/local/tmp/minicap.so
[02:17:54][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[02:17:54][DEBUG]<airtest.core.android.minicap> version:5
[02:17:54][DEBUG]<airtest.core.android.minicap> skip install minicap
[02:17:54][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 forward --no-rebind tcp:15762 localabstract:minicap_15762
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[02:17:54][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[02:17:54][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_15762' -P 1080x2340@1080x2340/0 -l 2>&1
[02:17:54][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 15336'
[02:17:54][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1080x2340@1080x2340/0'
[02:17:54][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_27.cpp:241) Creating SurfaceComposerClient'
[02:17:54][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_27.cpp:244) Performing SurfaceComposerClient init check'
[02:17:54][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_27.cpp:255) Creating virtual display'
[02:17:54][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_27.cpp:261) Creating buffer queue'
[02:17:54][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_27.cpp:264) Setting buffer options'
[02:17:54][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_27.cpp:268) Creating CPU consumer'
[02:17:54][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_27.cpp:272) Creating frame waiter'
[02:17:54][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_27.cpp:276) Publishing virtual display'
[02:17:55][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 7678980 bytes for JPG encoder'
[02:17:55][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:473) Server start'
[02:17:55][DEBUG]<airtest.core.android.minicap> (1, 24, 15336, 1080, 2340, 1080, 2340, 0, 2)
[02:17:55][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:475) New client connection'
[02:17:55][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[02:17:55][DEBUG]<airtest.core.api> resize: (118, 84)->(118, 84), resolution: (1080, 1920)=>(1080, 2340)
[02:17:55][DEBUG]<airtest.core.api> try match with _find_template
[02:17:55][DEBUG]<airtest.aircv.template> threshold=0.7, result={'result': (86, 159), 'rectangle': ((27, 117), (27, 201), (145, 201), (145, 117)), 'confidence': 0.8446519374847412}
[02:17:55][DEBUG]<airtest.core.api> match result: {'result': (86, 159), 'rectangle': ((27, 117), (27, 201), (145, 201), (145, 117)), 'confidence': 0.8446519374847412}
[02:17:55][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell getprop ro.product.cpu.abi
[02:17:55][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell getprop ro.build.version.sdk
[02:17:55][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell ls /data/local/tmp/minitouch
[02:17:55][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell ls -l /data/local/tmp/minitouch
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[02:17:55][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell rm /data/local/tmp/minitouch*
[02:17:55][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 push C:\\Users\\admin\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\airtest\\core\\android\\static\\stf_libs\\arm64-v8a\\minitouch /data/local/tmp/minitouch
[02:17:56][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell chmod 755 /data/local/tmp/minitouch
[02:17:56][INFO]<airtest.core.android.minitouch> install_minitouch finished
[02:17:56][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[02:17:56][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 forward --no-rebind tcp:13696 localabstract:minitouch_13696
[02:17:56][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell /data/local/tmp/minitouch -n 'minitouch_13696' 2>&1
[02:17:56][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mouse0 is not supported by libevdev'
[02:17:56][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mice is not supported by libevdev'
[02:17:56][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Type A touch device huawei,ts_kit (1080x2340 with 16 contacts) detected on /dev/input/event4 (score 21589)'
[02:17:56][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: hard-limiting maximum number of contacts to 10'
[02:17:56][DEBUG]<airtest.core.android.minitouch> minitouch header:b'v 1\n^ 10 1080 2340 255\n$ 15367\n'
[02:17:56][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Connection established'
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
出錯<traceback object at 0x0ECDECB0>
[02:18:14][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell am force-stop com.netease.open.pocoservice
Exception ignored in: <function RpcObjectProxy.__del__ at 0x0EB80270>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
    self._client__.evaluate(RpcObjectProxy(self._uri__, self._client__, action), wait_for_response=False)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hrpc\client.py", line 63, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hrpc\transport\http.py", line 26, in send
    raise TransportDisconnected(e)
hrpc.exceptions.TransportDisconnected: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[02:18:14][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell am start -n com.netease.open.pocoservice/.TestActivity
[02:18:14][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:INSTRUMENTATION_RESULT: shortMsg=Process crashed.\r\nINSTRUMENTATION_CODE: 0\r\n'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[02:18:43][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell am force-stop com.netease.open.pocoservice
[02:18:43][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.20.114 shell am start -n com.netease.open.pocoservice/.TestActivity

**Comment by Meteorix** [comment]
推荐用subprocess，进程间隔离比较好

**Comment by Meteorix** [comment]
稍晚点我写个例子，你可以先自己试试，比较简单

**Comment by JustinToken** [comment]
还是偶尔会出现异常。
Code:
![image](https://user-images.githubusercontent.com/47622050/52943097-516a8080-33a7-11e9-8c5c-6029e3f42e04.png)

Error:
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

![image](https://user-images.githubusercontent.com/47622050/52940295-254c0100-33a1-11e9-87d6-312399302573.png)

**Comment by chengxiao** [comment]
@Meteorix 遇到相同的问题了,想请教下多设备的演示

**Comment by chengxiao** [comment]
测试了不管在多线程还是在多进程的情况下 只要使用到 airtest 模块中的一些操作方法(snapshot(),text(),swipe())似乎脚本都无法进行下去.求助呀 真的没有办法在多设备上运行么?

**Comment by StevenXUzw** [comment]
设备管理要改一下

**Comment by Meteorix** [comment]
用subprocess基本跟单机执行airtest一样了，大概的代码如下：

```python

# 脚本名字
air = "your_case.air"

# 多台设备的序列号
devs = ["serialno1", "serialno2", "serialno3", "serialno4", "serialno5",]

# 各台设备通过subprocess调用，环境完全独立
for dev in devs:
    log_dir = "log_%s" % dev
    cmd = [
        "airtest",
        "run",
        air,
        "--device",
        "Android:///" + dev,
        "--log",
        log_dir
    ]

    print(" ".join(cmd))
    ret = subprocess.call(cmd, shell=True, cwd=os.path.dirname(air))

    # 生成html report
    # ...


```

**Comment by Meteorix** [comment]
完整的示例在这里，还包含了一个汇总报告，可以作为参考 

https://github.com/AirtestProject/multi-device-runner

**Comment by JustinToken** [comment]
非常感谢

**Comment by Skisperd** [comment]
C:\Users\tf.dias\AppData\Local\Programs\Python\Python37\python.exe "C:/Program Files/AirtestIDE/airtest/multi-device-runner-master/run.py"
Traceback (most recent call last):
  File "C:/Program Files/AirtestIDE/airtest/multi-device-runner-master/run.py", line 10, in <module>
    from airtest.core.android.adb import*
ModuleNotFoundError: No module named 'airtest'

**Comment by EraChen233** [comment]
![image](https://user-images.githubusercontent.com/5961185/54247139-c2e6ba80-4572-11e9-86cc-51e87ea94945.png)

**Comment by EraChen233** [comment]
你的电脑系统里默认的python环境是python3.7吗？必须是运行环境下的python安装了airtest。可以在这个文件夹的 `Python37\Lib\site-packages` 是否存在文件夹airtest
![image](https://user-images.githubusercontent.com/5961185/54280965-b9da0580-45d3-11e9-971c-441c50a2500d.png)

或者切换电脑默认python版本为python 3，重新安装airtest

**Comment by 2454760302hui** [comment]
@Meteorix 目前就是脚本和设备都是独立的，能出个demo 来模拟总控，调用其他脚本的实例吗？

**Comment by EraChen233** [comment]
可以参考这个自行实现
https://github.com/AirtestProject/multi-device-runner

**Comment by 2454760302hui** [comment]
ok，try again
