### ISSUE TITLE
从开始连接，就报错，鼠标一直不可以操作。用total control控制没问题

### ISSUE THREAD

**Issue by giveme555** [AirtestProject/Airtest#282]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
点击开始connect就一直报错
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF wait-for-device
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getprop ro.build.version.sdk
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell dumpsys display
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell dumpsys SurfaceFlinger ; echo ---$?---
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getevent -p ; echo ---$?---
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-1.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell ls /data/local/tmp/minicap ; echo ---$?---
Minitouch init failedC:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF wait-for-device, please select 'Use ADB touch' and try again
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getprop ro.build.version.sdk
Device:0123456789ABCDEF updated <airtest.core.android.android.Android object at 0x00000187055E94A8> -> <airtest.core.android.android.Android object at 0x0000018708674A20>
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell dumpsys display
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell dumpsys SurfaceFlinger ; echo ---$?---
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getevent -p ; echo ---$?---
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-1.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell ls /data/local/tmp/minicap ; echo ---$?---
Minitouch init failed, please select 'Use ADB touch' and try againC:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF wait-for-device
C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe devices
Traceback (most recent call last):

对应的logcat日志如下：
-P 5037 -s 0123456789ABCDEF shell getprop ro.product.cpu.abi
[06:34:21][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getprop ro.build.version.sdk
[06:34:21][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell ls /data/local/tmp/minitouch ; echo ---$?---
[06:34:21][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell ls -l /data/local/tmp/minitouch ; echo ---$?---
[06:34:21][DEBUG]<airtest.core.android.minitouch> install_minitouch skipped
[06:34:21][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell dumpsys display
[06:34:21][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell dumpsys SurfaceFlinger ; echo ---$?---
[06:34:22][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getevent -p ; echo ---$?---
[06:34:22][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF forward --no-rebind tcp:18071 localabstract:minitouch_18071
[06:34:22][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell /data/local/tmp/minitouch -n 'minitouch_18071' 2>&1
[06:34:22][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mice is not supported by libevdev'
[06:34:22][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to find a suitable touch device'
Traceback (most recent call last):
  File "app\plugins\device\android\util.py", line 187, in run
  File "airtest\utils\snippet.py", line 104, in ready_func
  File "airtest\utils\snippet.py", line 115, in wrapper
  File "airtest\core\android\minitouch.py", line 51, in install_and_setup
  File "airtest\core\android\minitouch.py", line 143, in setup_server
RuntimeError: minitouch setup timeout
[06:34:27][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getprop ro.product.cpu.abi
[06:34:27][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getprop ro.build.version.sdk
[06:34:27][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell ls /data/local/tmp/minitouch ; echo ---$?---
[06:34:27][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell ls -l /data/local/tmp/minitouch ; echo ---$?---
[06:34:28][DEBUG]<airtest.core.android.minitouch> install_minitouch skipped
[06:34:28][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell dumpsys display
[06:34:28][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell dumpsys SurfaceFlinger ; echo ---$?---
[06:34:28][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getevent -p ; echo ---$?---
[06:34:28][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF forward --no-rebind tcp:13259 localabstract:minitouch_13259
[06:34:28][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell /data/local/tmp/minitouch -n 'minitouch_13259' 2>&1
[06:34:28][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mice is not supported by libevdev'
[06:34:28][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to find a suitable touch device'
Traceback (most recent call last):
  File "app\plugins\device\android\util.py", line 187, in run
  File "airtest\utils\snippet.py", line 104, in ready_func
  File "airtest\utils\snippet.py", line 115, in wrapper
  File "airtest\core\android\minitouch.py", line 51, in install_and_setup
  File "airtest\core\android\minitouch.py", line 143, in setup_server
RuntimeError: minitouch setup timeout
[06:34:33][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getprop ro.product.cpu.abi
[06:34:33][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getprop ro.build.version.sdk
[06:34:34][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell ls /data/local/tmp/minitouch ; echo ---$?---
[06:34:34][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell ls -l /data/local/tmp/minitouch ; echo ---$?---
[06:34:34][DEBUG]<airtest.core.android.minitouch> install_minitouch skipped
[06:34:34][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell dumpsys display
[06:34:34][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell dumpsys SurfaceFlinger ; echo ---$?---
[06:34:34][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell getevent -p ; echo ---$?---
[06:34:34][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF forward --no-rebind tcp:14346 localabstract:minitouch_14346
[06:34:34][DEBUG]<airtest.core.android.adb> C:\Users\hp\Desktop\AirtestIDE_2018-11-06_py3_win64\AirtestIDE_2018-11-06_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 0123456789ABCDEF shell /data/local/tmp/minitouch -n 'minitouch_14346' 2>&1
[06:34:35][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: device /dev/input/mice is not supported by libevdev'
[06:34:35][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to find a suitable touch device'
Traceback (most recent call last):
  File "app\plugins\device\android\util.py", line 187, in run
  File "airtest\utils\snippet.py", line 104, in ready_func
  File "airtest\utils\snippet.py", line 115, in wrapper
  File "airtest\core\android\minitouch.py", line 51, in install_and_setup
  File "airtest\core\android\minitouch.py", line 143, in setup_server
RuntimeError: minitouch setup timeout
```
（在这里粘贴traceback或其他报错信息）
```

**预期效果**
(预期想要得到什么、见到什么)

可以正常连接，并且可以控制
**python 版本:** `python3`

**airtest 版本:** `1.1.0`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: []
 - 系统: [android 4.4]
 - (别的信息)

**Comment by yimelia** [comment]
请问是什么设备？
部分手机需要在开发者选项中开启允许模拟点击才能使用minitouch点击

**Comment by giveme555** [comment]
android4.4的开发板子

**Comment by yimelia** [comment]
请在连接前，勾选`use ADB touch`选项后再点connect按钮尝试。

**Comment by giveme555** [comment]
use ADB touch都已经打开也不能用

**Comment by yimelia** [comment]
adb touch的原理是，运行了 `adb shell input tap x y` 这条指令，可以在你们的机器连上开发板后， 用ADB试着运行这个指令看看是什么效果。
以及你们的开发板是否支持触屏交互？

**Comment by wujie59888** [comment]
命令模式可以的，但就是minitouch 初始化失败

**Comment by giveme555** [comment]
adb 命令交互没有问题，minitouch初始化失败
