### ISSUE TITLE
genymotion模拟器无法使用图像识别功能

### ISSUE THREAD

**Issue by qjgods** [AirtestProject/Airtest#302]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
我在使用airtestIDE的时候是可以正常运行的，但是直接用airtest运行就报错:

```
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/home/qj/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/qj/super_learning/answer.air/answer.py", line 69, in <module>
    refresh()
  File "/home/qj/super_learning/answer.air/answer.py", line 15, in refresh
    pos=exists(Template(r"tpl1551871375678.png", record_pos=(-0.421, 0.167), resolution=(240, 320)))
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/api.py", line 409, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 233, in snapshot
    if ensure_orientation and self.display_info["orientation"]:
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 524, in display_info
    self._display_info = self.get_display_info()
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 543, in get_display_info
    display_info = self.minicap.get_display_info()
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/minicap.py", line 149, in get_display_info
    display_info = json.loads(display_info)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

我还试过换成javacap，报的错是：
```
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/home/qj/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/qj/super_learning/answer.air/answer.py", line 69, in <module>
    refresh()
  File "/home/qj/super_learning/answer.air/answer.py", line 15, in refresh
    pos=exists(Template(r"tpl1551871375678.png", record_pos=(-0.421, 0.167), resolution=(240, 320)))
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/api.py", line 409, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 233, in snapshot
    if ensure_orientation and self.display_info["orientation"]:
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 524, in display_info
    self._display_info = self.get_display_info()
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 543, in get_display_info
    display_info = self.minicap.get_display_info()
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/minicap.py", line 149, in get_display_info
    display_info = json.loads(display_info)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
我还试过两个参数都加上：cap_method=JAVACAP&&ori_method=ADBORI。还是报错：

```
Traceback (most recent call last):
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/home/qj/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/qj/super_learning/answer.air/answer.py", line 69, in <module>
    refresh()
  File "/home/qj/super_learning/answer.air/answer.py", line 15, in refresh
    pos=exists(Template(r"tpl1551871375678.png", record_pos=(-0.421, 0.167), resolution=(240, 320)))
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/api.py", line 409, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 233, in snapshot
    if ensure_orientation and self.display_info["orientation"]:
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 524, in display_info
    self._display_info = self.get_display_info()
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 543, in get_display_info
    display_info = self.minicap.get_display_info()
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/minicap.py", line 149, in get_display_info
    display_info = json.loads(display_info)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


```

**python 版本:** `python3.6.7`

**airtest 版本:** `1.0.26`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: genymotion 2.8 
 - 系统: [Android 6]

**其他相关环境信息**
ubuntu18.04

**Comment by Meteorix** [comment]
推荐使用夜神（nox）模拟器

**Comment by qjgods** [comment]
> 推荐使用夜神（nox）模拟器

夜神模拟器没有Linux版呢。

**Comment by Meteorix** [comment]
I see...这看起来是个bug

**Comment by Meteorix** [comment]
使用 ```cap_method=JAVACAP&&ori_method=ADBORI``` 应该是对的，看报错对不上，请问你是如何使用这个参数的？

**Comment by qjgods** [comment]
> 使用 `cap_method=JAVACAP&&ori_method=ADBORI` 应该是对的，看报错对不上，请问你是如何使用这个参数的？

airtest run answer.air --device Android:///192.168.57.101:5555?cap_method=JAVACAP&&ori_method=ADBORI

**Comment by qjgods** [comment]
> 使用 `cap_method=JAVACAP&&ori_method=ADBORI` 应该是对的，看报错对不上，请问你是如何使用这个参数的？

我是开了两个模拟器的，我发现只要有一个模拟器最小化的时候运行这个命令才会报这个错。我现在把他们都显示出来，再运行一下，报的是另外的一个错：

```
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/home/qj/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/qj/super_learning/answer.air/answer.py", line 69, in <module>
    refresh()
  File "/home/qj/super_learning/answer.air/answer.py", line 15, in refresh
    pos=exists(Template(r"tpl1551871375678.png", record_pos=(-0.421, 0.167), resolution=(240, 320)))
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/api.py", line 409, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 220, in snapshot
    screen = self.javacap.get_frame_from_stream()
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/javacap.py", line 101, in get_frame_from_stream
    return self.frame_gen.send(None)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/javacap.py", line 64, in get_frames
    t = s.recv(24)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/safesocket.py", line 32, in recv
    raise socket.error("socket connection broken")
OSError: socket connection broken


```

**Comment by Meteorix** [comment]
单个模拟器没有最小化的时候，运行正常吗？

**Comment by qjgods** [comment]
> 单个模拟器没有最小化的时候，运行正常吗？

也不行呢，还是报错，很奇怪的是，一会是json错误，一会又是socket connection broken...，这个是sockey错误的信息：

```
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/home/qj/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/qj/super_learning/answer.air/answer.py", line 69, in <module>
    refresh()
  File "/home/qj/super_learning/answer.air/answer.py", line 15, in refresh
    pos=exists(Template(r"tpl1551871375678.png", record_pos=(-0.421, 0.167), resolution=(240, 320)))
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/api.py", line 409, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/android.py", line 220, in snapshot
    screen = self.javacap.get_frame_from_stream()
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/javacap.py", line 101, in get_frame_from_stream
    return self.frame_gen.send(None)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/core/android/javacap.py", line 64, in get_frames
    t = s.recv(24)
  File "/home/qj/.local/lib/python3.6/site-packages/airtest/utils/safesocket.py", line 32, in recv
    raise socket.error("socket connection broken")
OSError: socket connection broken
```

**Comment by Meteorix** [comment]
这个问题我们验证一下，多谢反馈

**Comment by zhugehui9527** [comment]
我用的mumu模拟器，也报这个json错误，用真机没有问题，
信息：mumu模拟器，系统：6.0.1；MAC airtestide:1.2
报错信息：/data/local/tmp/minicap.so ; echo ---$?---
minicap installation finished
/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s emulator-5554 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/device/android/android_client.py", line 162, in loadConnectedPhones
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/device/android/android_phone.py", line 83, in __init__
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/device/android/android_phone.py", line 111, in _initDev
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/android.py", line 524, in display_info
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/android.py", line 543, in get_display_info
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/snippet.py", line 106, in ready_func
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/minicap.py", line 149, in get_display_info
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
奇怪的是，我没有这个路径：/Users/wjjn3033/dev/idestable/airtest/airtest， 这个是代码写死的？

**Comment by Meteorix** [comment]
@zhugehui9527 还是推荐用夜神模拟器，模拟器都需要指定参数 ``cap_method=JAVACAP&&ori_method=ADBORI``

另外路径跟这个无关，只是编译时的路径
