### ISSUE TITLE
生成测试报告报错：json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 190 (char 1 89)

### ISSUE THREAD

**Issue by RonChu-01** [AirtestProject/Airtest#325]
1、IDE中可以查看测试报告；
2、本机环境中执行生成报告指令报错：
airtest report muti.air --log_root d:/log/ --outfile log/log.html --lang zh 
报错信息：
(venv) D:\myproject\venv\Scripts>airtest report muti.air --log_root d:/log/ --ou
tfile log/log.html --lang zh
Traceback (most recent call last):
  File "d:\python\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\myproject\venv\Scripts\airtest.exe\__main__.py", line 9, in <module>
  File "d:\myproject\venv\lib\site-packages\airtest\cli\__main__.py", line 13, i
n main
    report_main(args)
  File "d:\myproject\venv\lib\site-packages\airtest\report\report.py", line 406,
 in main
    rpt.report(HTML_TPL, output_file=args.outfile, record_list=record_list)
  File "d:\myproject\venv\lib\site-packages\airtest\report\report.py", line 336,
 in report
    self._load()
  File "d:\myproject\venv\lib\site-packages\airtest\report\report.py", line 70,
in _load
    self.log.append(json.loads(line, strict=False))
  File "d:\python\Lib\json\__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "d:\python\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "d:\python\Lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 190 (char 1
89)

**Comment by RonChu-01** [comment]
[log.txt](https://github.com/AirtestProject/Airtest/files/2970869/log.txt)

**Comment by EraChen233** [comment]
这个log.txt是否被修改过？
![image](https://user-images.githubusercontent.com/5961185/54502490-dd9ba380-4965-11e9-95ec-3f4693a7d3c6.png)

**Comment by RonChu-01** [comment]
> 这个log.txt是否被修改过？
> ![image](https://user-images.githubusercontent.com/5961185/54502490-dd9ba380-4965-11e9-95ec-3f4693a7d3c6.png)

谢谢回答
这边发现，可能是这边多机执行然后把多机器执行的log写进了同一个log.txt文件的原因
1、没有修改过；
2、这边单机执行是可以生成测试报告的；
3、多机器执行时，生成测试报告报错；

**Comment by RonChu-01** [comment]
暂时关闭这个issue了

**Comment by EraChen233** [comment]
注意把一个测试脚本的log写在一个 log.txt 就不会出现这种问题了

**Comment by RonChu-01** [comment]
> 注意把一个测试脚本的log写在一个 log.txt 就不会出现这种问题了

嗯 谢谢
这边看看聚合报告的生成

**Comment by EraChen233** [comment]
聚合报告可以参考一下这个例子 https://github.com/AirtestProject/multi-device-runner

**Comment by RonChu-01** [comment]
> 聚合报告可以参考一下这个例子 https://github.com/AirtestProject/multi-device-runner

嗯 收到 再次感谢（已经在看了 嘿嘿 ）
