### ISSUE TITLE
本机真实python版本与虚拟环境python版本相同，虚拟环境运行airtest正常，本地环境安装airtest，运行airtest报错：pkg_resources.DistributionNotFound: The 'opencv-contrib-python==3.4.2.17' distri bution was not found and is required by airtest

### ISSUE THREAD

**Issue by RonChu-01** [AirtestProject/Airtest#326]
1、本地python版本：3.6.8
2、安装airtest，运行代码时，在cv2模块报 ImportError: DLL load failed: 找不到指定模块 的错
按照官网卸载重装，pip install opencv-contrib-python==3.2.0.7后报错
3、本机创建虚拟环境进行安装，可以正常启动；虚拟环境python版本，3.6.8

Traceback (most recent call last):
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 581, in _bu
ild_master
    ws.require(__requires__)
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 898, in req
uire
    needed = self.resolve(parse_requirements(requirements))
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 789, in res
olve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (opencv-contrib-python 3.2.0.7 (d:\pyth
on\lib\site-packages), Requirement.parse('opencv-contrib-python==3.4.2.17'), {'a
irtest'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Scripts\airtest-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 3126, in <m
odule>
    @_call_aside
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 3110, in _c
all_aside
    f(*args, **kwargs)
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 3139, in _i
nitialize_master_working_set
    working_set = WorkingSet._build_master()
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 583, in _bu
ild_master
    return cls._build_from_requirements(__requires__)
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 596, in _bu
ild_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "d:\python\lib\site-packages\pkg_resources\__init__.py", line 784, in res
olve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'opencv-contrib-python==3.4.2.17' distri
bution was not found and is required by airtest

**Comment by Meteorix** [comment]
分别看看
``pip version``
``python version``

**Comment by RonChu-01** [comment]
> 分别看看
> `pip version`
> `python version`

谢谢，问题已经解决
本机环境问题，没有更新pip至最新版本（之前是安装后才更新了pip......），更新pip版本后，重新卸载安装airtest正常运行

**Comment by niuniuprice** [comment]
你好，airtest在虚拟机环境里运行，点击和输入按键之类的操作，会不会有操作失效的情况？
