### ISSUE TITLE
用airtest点击win10自带的计算器就好使，点击我们的应用程序touch无作用。会报下边的错

### ISSUE THREAD

**Issue by stimwhx** [AirtestProject/Airtest#350]
"C:\Users\stimwhx\Downloads\AirtestIDE_2019-01-15_py3_win64\AirtestIDE" runner "C:\Users\stimwhx\Desktop\untitled.air"  --device Windows:///1445348 --log "C:\Users\stimwhx\AppData\Local\Temp\AirtestIDE\scripts\40ab1620d1bbe32b72c3f21f785c6a39"
============================================================

[Start running..]
save log in 'C:\Users\stimwhx\AppData\Local\Temp\AirtestIDE\scripts\40ab1620d1bbe32b72c3f21f785c6a39'
C:\Users\stimwhx\Downloads\AirtestIDE_2019-01-15_py3_win64\pywinauto\application.py:1032: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
[07:31:05][INFO]<airtest.core.api> Try finding:
Template(C:\Users\stimwhx\Desktop\untitled.air\tpl1554809272709.png)
[07:31:05][DEBUG]<airtest.core.api> resize: (248, 58)->(755, 176), resolution: (320, 532)=>(1046, 650)
[07:31:05][DEBUG]<airtest.core.api> try match with _find_template
[07:31:05][DEBUG]<airtest.aircv.template> threshold=0.7, result={'result': (501, 140), 'rectangle': ((124, 52), (124, 228), (879, 228), (879, 52)), 'confidence': 0.26599955558776855}
[07:31:05][DEBUG]<airtest.core.api> try match with _find_sift_in_predict_area
[07:31:05][DEBUG]<airtest.core.api> try match with _find_sift
[aircv][sift] threshold=0.7, result={'result': [767, 285], 'rectangle': [(649, 255), (649, 314), (884, 314), (884, 255)], 'confidence': 0.8295043706893921}
[07:31:06][DEBUG]<airtest.core.api> match result: {'result': [767, 285], 'rectangle': [(649, 255), (649, 314), (884, 314), (884, 255)], 'confidence': 0.8295043706893921}
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "C:\Users\stimwhx\Desktop\untitled.air\untitled.py", line 6, in <module>
    touch(Template(r"tpl1554809272709.png", record_pos=(3.297, 0.144), resolution=(320, 532)))
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 259, in touch
  File "C:\Users\stimwhx\Downloads\AirtestIDE_2019-01-15_py3_win64\airtest\core\win\win.py", line 172, in touch
    self.mouse.press(button=button, coords=coords)
  File "site-packages\pywinauto\mouse.py", line 237, in press
  File "site-packages\pywinauto\mouse.py", line 125, in _perform_click_input
pywintypes.error: (0, 'SetCursorPos', 'No error message is available')

----------------------------------------------------------------------
Ran 1 test in 6.463s

FAILED (errors=1)
[Finished]

============================================================

**Comment by yimelia** [comment]
试一下启动IDE时，用管理员模式启动

**Comment by stimwhx** [comment]
你好，还是不行。会提示找不到这个图片。
我想问一下，他提示说我用的是64位的python,说这个是32位的。我要换一个32位的python么？
C:\Users\stimwhx\Downloads\AirtestIDE_2019-01-15_py3_win64\pywinauto\application.py:1032: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
我去找了C:\Users\stimwhx\Downloads\AirtestIDE_2019-01-15_py3_win64\pywinauto这个目录，没有
还有这个提示；ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)

**Comment by stimwhx** [comment]
我不用我们的应用，用网易云音乐都识别不了。

**Comment by yimelia** [comment]
重启一下IDE，然后不连窗口，选桌面模式：
![image](https://user-images.githubusercontent.com/6896468/55847816-709eb680-5b7d-11e9-9679-fe0ffe3e1a58.png)

这样是将整个桌面作为被测应用来运行脚本的，试一下看看直接这样能不能识别到

**Comment by stimwhx** [comment]
6666    可以了，谢谢
