### ISSUE TITLE
Connection reset error up on clearing data/Forcing closing the app and relaunch and the poco/airtest code fails to work 

### ISSUE THREAD

**Issue by anandplay17** [AirtestProject/Airtest#351]
Remove any following parts if does not have details about

Android - Connection reset error up on clearing data/Forcing closing the app and relaunch and the poco/airtest code fails to work 

```
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 66, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 62, in runTest
  File "/Users/playsimplegames/qa_automation/wordwars1/ww_objects.air/ww_objects.py", line 400, in <module>
    new_guest()
  File "/Users/playsimplegames/qa_automation/wordwars1/ww_objects.air/ww_objects.py", line 393, in new_guest
    login_screen.wait_for_appearance()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 628, in wait_for_appearance
    while not self.exists():
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 723, in exists
    return self.attr('visible')
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 684, in attr
    nodes = self._do_query(multiple=False)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 819, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/freezeui/hierarchy.py", line 89, in select
    return self.selector.select(query, multiple)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/sdk/Selector.py", line 77, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/sdk/Selector.py", line 70, in getRoot
    return self.dumper.getRoot()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/freezeui/hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=30)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/simplerpc.py", line 74, in wait
    self.agent.update()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/rpcclient.py", line 64, in update
    data = self.conn.recv()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/transport/tcp/main.py", line 36, in recv
    msg_bytes = self.c.recv()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/utils/simplerpc/transport/tcp/safetcp.py", line 39, in recv
    trunk = self.sock.recv(size)
ConnectionResetError: [Errno 54] Connection reset by peer

```

1. Force close the app and relaunch through adb from airtest IDE 
2.the second line of code should be a poco code for UI hierarchy 
3. Observe 

**Expected behavior**
The code should run because the UI hierarchy code works perfectly in the same session 

**Screenshots**

**python version:** `python3.5`

**airtest version:** `1.0.22`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
 - Device: [e.g. google pixel 2]
 - OS: [e.g. Android 8.1]
 - more information if have

**Additional context**

**Comment by yimelia** [comment]
hi @anandplay17 
The connection is broken and the poco variable needs to be reinitialized
so after relaunching the app, redefine the `poco` and try again

**Comment by anandplay17** [comment]
@yimelia  I tried it and it din work couple of days back, however the mistake was my ADB functions where in different .air file and "auto_setup(__file__)" was missing in that file. I added that plus i redefined poco after force close relaunch. Not sure if this could be improved
