### ISSUE TITLE
期望能够提供手势密码那种可以拐弯的连续swipe的支持

### ISSUE THREAD

**Issue by ElesG** [AirtestProject/Airtest#36]
类似这里提到的的方法：https://github.com/alibaba/macaca/issues/366
可以连续地连上不在同一直线上的三个点

**Comment by Meteorix** [comment]
@ElesG 你看这里的motionevent够用吗：
https://github.com/AirtestProject/Airtest/blob/master/playground/android_motionevents.py

**Comment by ElesG** [comment]
@Meteorix 很感谢你的回答，看了那份sample，不是很明白DownEvent、UpEvent、MoveEvent的定义，因为他好像只有一个起始坐标却没有步长之类的参数，我怎么知道要移动多少呢？
另外我在AirTestIDE执行如下代码时他总提示我“name 'DownEvent' is not defined”，希望得到你的指引。
```
from airtest.core.android.minitouch import *

figure1_events = [
    # MoveEvent((537.5,945.5),0),
    # MoveEvent((537.5,1538),1),
    # MoveEvent((830,1538),2)
    DownEvent((100, 100), 0),
	DownEvent((200, 200), 1),
	SleepEvent(1),
	UpEvent(0), UpEvent(1)
    
]
device.minitouch.perform(figure1_events)
```

**Comment by Meteorix** [comment]
@ElesG IDE下周版本才会包含这个最新的代码

文档还没更新，先看看这里的代码吧，应该很好理解
https://github.com/AirtestProject/Airtest/blob/edf903941afee29d74a957318e26058eae330732/airtest/core/android/minitouch.py#L456

**Comment by ElesG** [comment]
@Meteorix 大致理解了，我决定直接运行https://github.com/AirtestProject/Airtest/blob/master/playground/android_motionevents.py试一下 验证下我的理解，可是运行过程中总提示以下报错，请问你有遇到过这种情况吗？
系统参数：
python 2.7.10 （电脑自带的）
macOS 10.13.4
已通过pip安装好了airtest
```
[03:24:13][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb devices
Traceback (most recent call last):
  File "tryMove.py", line 5, in <module>
    connect_device("Android:///")
  File "/Library/Python/2.7/site-packages/airtest/core/api.py", line 46, in connect_device
    dev = cls(uuid, **params)
  File "/Library/Python/2.7/site-packages/airtest/core/android/android.py", line 29, in __init__
    self.serialno = serialno or ADB().devices(state="device")[0][0]
  File "/Library/Python/2.7/site-packages/airtest/core/android/adb.py", line 196, in devices
    output = self.cmd("devices", device=False)
  File "/Library/Python/2.7/site-packages/airtest/core/android/adb.py", line 167, in cmd
    proc = self.start_cmd(cmds, device)
  File "/Library/Python/2.7/site-packages/airtest/core/android/adb.py", line 146, in start_cmd
    stderr=subprocess.PIPE
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
exiting.......
```

**Comment by adolli** [comment]
这是因为你mac上已经装了adb但是版本不匹配，可以升级adb到1.0.39或者卸载掉。

**Comment by adolli** [comment]
试试下面的命令，看下输出是否正常

**Comment by Meteorix** [comment]
@ElesG 这是因为你安装的airtest位置没有adb的执行权限

**Comment by Meteorix** [comment]
你可以找到airtest的安装目录，下面的adb路径，然后sudo改变权限

**Comment by ElesG** [comment]
@Meteorix 我将`airtest/core/android/adb.py`、`airtest/core/android/android.py`都授予了运行的权限了，可是还是提示同样的错误。
我以为是因为`subprocess.py`也没有执行权限所以才导致报错，可是我没法给`  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py`授予执行权限。请问是我操作失误导致环境出现问题了吗？
