### ISSUE TITLE
持续集成

### ISSUE THREAD

**Issue by sunyunxian** [AirtestProject/Airtest#368]
Airtest 编写脚本在本地能用命令行运行，集成到 jinkens 上报错；

```
Traceback (most recent call last):
  File "D:\develop\python3.6.8\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\develop\python3.6.8\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\develop\python3.6.8\lib\site-packages\airtest\__main__.py", line 2, in <module>
    from airtest.cli.__main__ import main
  File "D:\develop\python3.6.8\lib\site-packages\airtest\cli\__main__.py", line 2, in <module>
    from airtest.cli.parser import get_parser
  File "D:\develop\python3.6.8\lib\site-packages\airtest\cli\parser.py", line 4, in <module>
    from airtest.report.report import get_parger as report_parser
  File "D:\develop\python3.6.8\lib\site-packages\airtest\report\report.py", line 7, in <module>
    import six
ModuleNotFoundError: No module named 'six'
Finished: SUCCESS
```

**本地命令行执行命令**
`python -m airtest run D:\develop\Smoke_test\smoke_test_1.air --device Android://127.0.0.1:5037//3HX5T16C17045062 --log D:\develop\Smoke_test\log --recording`

**python 版本:** `python3.6.8`

**airtest 版本:** `1.2.0`

** 本机:**`Win7`
**jinkens版本:**`2.164.2`

**Comment by yimelia** [comment]
检查Jenkins服务器上的环境
