### ISSUE TITLE
无法正常识别Cocos-lua打出来的windows程序中的图片

### ISSUE THREAD

**Issue by Macile** [AirtestProject/Airtest#369]
无法正常找到图片识别，总是提示找不到图片，重启一下或者过一会又能跑几步双击查看原图过一会就运行时截图全是同一张，

（在这里粘贴traceback或其他报错信息）
```Traceback (most recent call last):
  File "airtest\cli\runner.py", line 65, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 61, in runTest
  File "D:\AirtestProject\TestSmp.air\TestSmp.py", line 10, in <module>
    touch(Template(r"tpl1555933208343.png", rgb=True, record_pos=(1.692, 0.377), resolution=(726, 604)))
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 256, in touch
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\cv.py", line 77, in loop_find
airtest.core.error.TargetNotFoundError: 'Picture Template(D:\\AirtestProject\\TestSmp.air\\tpl1555933208343.png) not found in screen'

----------------------------------------------------------------------
Ran 1 test in 20.371s

FAILED (errors=1)
[Finished]


![TIM图片20190422195230](https://user-images.githubusercontent.com/26572845/56499629-c5f1a500-6539-11e9-9fef-de21cf7b593c.png)
![TIM图片20190422195356](https://user-images.githubusercontent.com/26572845/56499642-d86bde80-6539-11e9-9e86-b25684cb264c.png)



**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
Cocos-lua打出的windws平台游戏，图像识别的准确率低的令人发指。。。。
**预期效果**
怎么能改善一下，


**python 版本:** `python3`

**airtest IDE版本:** `1.2.1`


**设备:**
 Windows7平台
GTS480独显+英特尔集显
 -

**其他相关环境信息**
(其他运行环境，在安卓正常，只有windows异常。)

**Comment by Macile** [comment]
发现是因为Win32截图的时候只能截取游戏运行的第一张的图，切换场景后识别不出来

**Comment by yimelia** [comment]
尝试下不嵌入游戏，直接用桌面连接来跑脚本看看？
![image](https://user-images.githubusercontent.com/6896468/56563008-4fa67e80-65dd-11e9-9079-4617a0ff5f9c.png)

**Comment by Macile** [comment]
> 尝试下不嵌入游戏，直接用桌面连接来跑脚本看看？
> ![image](https://user-images.githubusercontent.com/6896468/56563008-4fa67e80-65dd-11e9-9079-4617a0ff5f9c.png)

试过了，这样的话是用的，但是Poco功能就无法使用了呀。但是我拿win10的话是正常可以跑的

**Comment by yimelia** [comment]
试一下直接连桌面然后单独跑脚本是否可行。
如果是录制的话，当前版本的ide暂时也不支持打包后的windows窗口的poco框选功能，目前是只支持android和untiy编辑器窗口中的poco元素框选

**Comment by rockywhisper** [comment]
@Macile 
你好，请你这边的游戏有没有外放包链接给一下呀？
我看下截图是什么问题。

另外，你是说win10下的poco脚本可以正常运行，但是在win7下不行吗？

**Comment by Macile** [comment]
直接连桌面然后单独跑脚本是可行的
不是Poco脚本，是单纯的airtest的Touch方法（包括其他的需要图片识别的方法），在windows7上只能识别游戏启动的界面，也就是说在启动界面的时候是完全好用的，但是一旦游戏切换界面后就识别不了了，截取的图片永远是启动的时候初始化的那个界面的图。
[这个是跑的时候报告目录的文件夹，永远都是游戏初始化时候的界面，只要是Cocos-lua打出来的windows平台游戏都这样子。]
![TIM图片20190423160444](https://user-images.githubusercontent.com/26572845/56565827-d78f8700-65e3-11e9-92f1-e08c2d88fe29.png)
![TIM图片20190423160227](https://user-images.githubusercontent.com/26572845/56565840-e118ef00-65e3-11e9-82f3-53141a9a2d14.png)

但是在win10平台跑的时候就是正常的。我不知道是不是我显卡的问题，这是我的显卡配置，独显。
另外一个游戏包很大，还需要找开发要。。所以不太方便提供，不好意思哈。

**Comment by Macile** [comment]
> 试一下直接连桌面然后单独跑脚本是否可行。
> 如果是录制的话，当前版本的ide暂时也不支持打包后的windows窗口的poco框选功能，目前是只支持android和untiy编辑器窗口中的poco元素框选

我可以在windows平台获取到这些Poco的控件树，也就是把android的脚本录制好了拿到windows用，不需要录制，录制我知道是目前ide是不支持的，但是IDE在运行脚本的时候只是截取的游戏初始化时候的图片T_T.全部都是那一张图，Cocos-lua打出来的windows平台的游戏都是这样子的。但是在win10就是完全正常的

**Comment by Macile** [comment]
> @Macile
> 你好，请你这边的游戏有没有外放包链接给一下呀？
> 我看下截图是什么问题。
> 
> 另外，你是说win10下的poco脚本可以正常运行，但是在win7下不行吗？

还有就是我写了一个python脚本
import time
import win32gui, win32ui, win32con, win32api
def window_capture(filename):
  #hwnd =  # 窗口的编号，0号表示当前活跃窗口
  hwnd=264336
  #title 是窗口标题。比如Hwnd = Plugin.Window.Find(0, "魔兽世界")
  # 根据窗口句柄获取窗口的设备上下文DC（Divice Context）
  hwndDC = win32gui.GetWindowDC(hwnd)
  # 根据窗口的DC获取mfcDC
  mfcDC = win32ui.CreateDCFromHandle(hwndDC)
  # mfcDC创建可兼容的DC
  saveDC = mfcDC.CreateCompatibleDC()
  # 创建bigmap准备保存图片
  saveBitMap = win32ui.CreateBitmap()
  # 获取监控器信息
  MoniterDev = win32api.EnumDisplayMonitors(None, None)
  w = MoniterDev[0][2][2]
  h = MoniterDev[0][2][3]
  # print w,h　　　#图片大小
  # 为bitmap开辟空间
  saveBitMap.CreateCompatibleBitmap(mfcDC, w, h)
  # 高度saveDC，将截图保存到saveBitmap中
  saveDC.SelectObject(saveBitMap)
  # 截取从左上角（0，0）长宽为（w，h）的图片
  saveDC.BitBlt((0, 0), (w, h), mfcDC, (0, 0), win32con.SRCCOPY)
  saveBitMap.SaveBitmapFile(saveDC, filename)
beg = time.time()
for i in range(10):
  window_capture("haha.jpg")
  
end = time.time()
print(end - beg)


截图发现也是只能截取游戏初始化的时候的界面，当游戏切换场景后截取的依旧是第一个界面。貌似是W32的api对Cocos-lua打包的windows平台游戏有一些问题，这个是其中一个游戏的demo（来源网络，我的电脑上所有的Cocos-lua的游戏都是一样的情况），我的系统是w7sp1
[win32.zip](https://github.com/AirtestProject/Airtest/files/3106588/win32.zip)

**Comment by Macile** [comment]
[MatchGame.zip](https://github.com/AirtestProject/Airtest/files/3110839/MatchGame.zip)
文件没压缩完全。。。。。补一下

**Comment by Macile** [comment]
找到了一个解决办法
经过多次实验验证，证明之前的结果是错误的，在windows平台识别Coscos-lua项目不准确不是显卡的问题，是Win32APi的问题，
AIrtest截图是调用Win32的APi进行快速截图，但是这样的话当截图时只能截取lua项目初始化时候的图片，而且一直是这张图片。但是WIn10就不会存在这个问题，有可能是更改了底层的WindowsAPI。
其他解决办法就是替换掉airtest的识别图像的代码，本人使用的是pyautogui这个库，截图速度很快，也很方便。
1.首先安装库依赖，把pyautogui，pyscreeze这样个库复制到airtest的根目录；
2.打开airtest\core\win文件夹，打开screen.py
3.注释掉win32的截图语句，采用im = pyautogui.screenshot(region = (rect[0], rect[1], w, h))这个语句。
我这个只是暂时使用，希望airtest团队在下次更新能尽快解决这个问题啦

**Comment by guhan121** [comment]
@Macile 还在用这个么我遇到bitblt failed的错误了，按照你的解法修改了截屏代码，然后有出现 screen grab failed.
