### ISSUE TITLE
使用命令列下指令執行時報錯

### ISSUE THREAD

**Issue by koichipan** [AirtestProject/Airtest#37]
我用命令列下指令執行時報錯了，可以幫我定位一下問題點嗎?

> airtest run "path to your .air dir" --device Android:

======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 88, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath.encode(sys.getfilesystemencoding()), 'exec')) in self.scope
  File "/Users/cm-nb-01007/Desktop/test.air/test.py", line 12, in <module>
    poco(text="test").click()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/pocofw.py", line 97, in __call__
    return UIObjectProxy(self, name, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 63, in __init__
    self.query = build_query(name, **attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/utils/query_util.py", line 57, in build_query
    attr_val = ensure_unicode(attr_val)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/utils/query_util.py", line 46, in ensure_unicode
    return value.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'

**Comment by adolli** [comment]
部分代码python2 3兼容还没做好，请先用python2运行或等下周更新
