### ISSUE TITLE
mac os  + iphone se xcode9 ios 10 执行简单的脚本语句一直不能成功 

### ISSUE THREAD

**Issue by guomochong** [AirtestProject/Airtest#374]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

```
（在这里粘贴traceback或其他报错信息）
```
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 65, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 61, in runTest
  File "/var/folders/ld/w07263cd2bl6dwfr0dkd2jrw0000gn/T/AirtestIDE/Scripts/untitled.air/untitled.py", line 10, in <module>
    touch(Template(r"tpl1556241309588.png", record_pos=(0.367, -0.43), resolution=(640, 1136)))
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/utils/logwraper.py", line 72, in wrapper
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 261, in touch
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 44, in wrapper
    raise err
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 37, in wrapper
    return func(self, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/airtest/core/ios/ios.py", line 223, in touch
    self.session.tap(x, y)
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 381, in tap
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/wda/__init__.py", line 83, in httpdo
**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)
![image](https://user-images.githubusercontent.com/42536731/56777542-bce82880-6804-11e9-9462-02600a437aa0.png)
![image](https://user-images.githubusercontent.com/42536731/56777558-cc677180-6804-11e9-963f-eb739bec9a48.png)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by EraChen233** [comment]
Xcode版本是多少？
另外iproxy 命令窗口输出和 Xcode 日志窗口的输出，可以截图贴出来么
