### ISSUE TITLE
执行脚本时 airtest 报错

### ISSUE THREAD

**Issue by pipBug** [AirtestProject/Airtest#376]
**描述问题 BUG**
执行脚本时 adb.py 抛出 AdbError

Log:
```
adb server version (40) doesn't match this client (39); killing...
[pocoservice.apk] stdout: b'\r\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:'
[pocoservice.apk] stderr: b''
[pocoservice.apk] retrying instrumentation PocoService
[05:00:12][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell am force-stop com.netease.open.pocoservice ; echo ---$?---
2019-04-26 17:00:12 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell am force-stop com.netease.open.pocoservice ; echo ---$?---
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/poco/drivers/android/uiautomation.py", line 211, in loop
    self._start_instrument(port_to_ping)  # 尝试重启
  File "/usr/local/lib/python3.7/site-packages/poco/drivers/android/uiautomation.py", line 235, in _start_instrument
    self.adb_client.shell(['am', 'force-stop', PocoServicePackage])
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/adb.py", line 354, in shell
    out = self.raw_shell(cmd).rstrip()
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/adb.py", line 326, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/adb.py", line 187, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[b''] stderr[b"* daemon not running; starting now at tcp:5037\nADB server didn't ACK\nFull server startup log: /var/folders/nx/8qylv0hs66v2zhbm22505kkr0000gn/T//adb.501.log\nServer had pid: 33767\n--- adb starting (pid 33767) ---\nadb I 04-26 17:00:12 33767 453132 main.cpp:56] Android Debug Bridge version 1.0.40\nadb I 04-26 17:00:12 33767 453132 main.cpp:56] Version 4986621\nadb I 04-26 17:00:12 33767 453132 main.cpp:56] Installed as /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb\nadb I 04-26 17:00:12 33767 453132 main.cpp:56] \nadb E 04-26 17:00:12 33767 453138 usb_osx.cpp:340] Could not open interface: e00002c5\nadb E 04-26 17:00:12 33767 453138 usb_osx.cpp:301] Could not find device interface\nadb I 04-26 17:00:12 33765 453135 usb_osx.cpp:308] reported max packet size for a83a6617d030 is 512\nadb I 04-26 17:00:12 33765 453128 adb_auth_host.cpp:416] adb_auth_init...\nadb I 04-26 17:00:12 33765 453128 adb_auth_host.cpp:174] read_key_file '/Users/anonymous/.android/adbkey'...\nadb I 04-26 17:00:12 33765 453128 adb_auth_host.cpp:467] Calling send_auth_response\nerror: could not install *smartsocket* listener: Address already in use\n\n* failed to start daemon\nerror: cannot connect to daemon\n"]

* daemon started successfully
[05:01:04][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 uninstall com.chainsguard.safebox
2019-04-26 17:01:04 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 uninstall com.chainsguard.safebox
[05:01:08][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 install ./apk/com.chainsguard.safebox.apk
2019-04-26 17:01:08 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 install ./apk/com.chainsguard.safebox.apk
[05:01:10][INFO]<airtest.core.api> Try finding:
Template(./air/_chainsguard.air/tpl1546589231057.png)
2019-04-26 17:01:10 cv.py[line:39] INFO Try finding:
Template(./air/_chainsguard.air/tpl1546589231057.png)
[05:01:10][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
2019-04-26 17:01:10 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
[05:01:11][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-1/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
2019-04-26 17:01:11 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-1/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[05:01:12][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell ls /data/local/tmp/minicap ; echo ---$?---
2019-04-26 17:01:12 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell ls /data/local/tmp/minicap ; echo ---$?---
[05:01:12][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell ls /data/local/tmp/minicap.so ; echo ---$?---
2019-04-26 17:01:12 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell ls /data/local/tmp/minicap.so ; echo ---$?---
[05:01:12][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
2019-04-26 17:01:12 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[05:01:12][DEBUG]<airtest.core.android.minicap> version:5
2019-04-26 17:01:12 minicap.py[line:72] DEBUG version:5
[05:01:12][DEBUG]<airtest.core.android.minicap> skip install minicap
2019-04-26 17:01:12 minicap.py[line:79] DEBUG skip install minicap
[05:01:12][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 forward --no-rebind tcp:15156 localabstract:minicap_15156
2019-04-26 17:01:12 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 forward --no-rebind tcp:15156 localabstract:minicap_15156
[05:01:12][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
2019-04-26 17:01:12 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[05:01:12][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_15156' -P 720x1280@720x1280/0 -l 2>&1
2019-04-26 17:01:12 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_15156' -P 720x1280@720x1280/0 -l 2>&1
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 8428'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'PID: 8428'
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 720x1280@720x1280/0'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: Using projection 720x1280@720x1280/0'
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:240) Creating SurfaceComposerClient'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:240) Creating SurfaceComposerClient'
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:243) Performing SurfaceComposerClient init check'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:243) Performing SurfaceComposerClient init check'
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:250) Creating virtual display'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:250) Creating virtual display'
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:256) Creating buffer queue'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:256) Creating buffer queue'
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:261) Creating CPU consumer'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:261) Creating CPU consumer'
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:265) Creating frame waiter'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:265) Creating frame waiter'
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:269) Publishing virtual display'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:269) Publishing virtual display'
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder'
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:473) Server start'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:473) Server start'
[05:01:12][DEBUG]<airtest.core.android.minicap> (1, 24, 8428, 720, 1280, 720, 1280, 0, 2)
2019-04-26 17:01:12 minicap.py[line:239] DEBUG (1, 24, 8428, 720, 1280, 720, 1280, 0, 2)
[05:01:12][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:475) New client connection'
2019-04-26 17:01:12 nbsp.py[line:37] DEBUG [minicap_server]b'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:475) New client connection'
[05:01:13][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
2019-04-26 17:01:13 adb.py[line:142] DEBUG /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -s a83a6617d030 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[05:01:13][DEBUG]<airtest.core.api> resize: (219, 72)->(146, 48), resolution: (1080, 1920)=>(720, 1280)
2019-04-26 17:01:13 cv.py[line:216] DEBUG resize: (219, 72)->(146, 48), resolution: (1080, 1920)=>(720, 1280)
[05:01:13][DEBUG]<airtest.core.api> try match with _find_template
2019-04-26 17:01:13 cv.py[line:155] DEBUG try match with _find_template
```

**Python 版本:** `3.7.3`

**airtest 版本:** `1.0.25`

**设备**
 - 型号: Redmi 3S
 - MIUI: 10 9.3.28 开发版
 - 系统: Android 6.0.1

**其他相关环境信息**
macOS 10.14.4

**Comment by yimelia** [comment]
请替换所有的adb.exe为同一个版本的adb，参考[文档](http://airtest.netease.com/docs/cn/2_device_connection/2_android_faq.html#airtestadb)

**Comment by pipBug** [comment]
是我不仔细，不好意思！谢了~
