### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'SIFT'

### ISSUE THREAD

**Issue by tester-wells** [AirtestProject/Airtest#377]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
![image](https://user-images.githubusercontent.com/3702343/56858204-138e6780-69a9-11e9-96fd-c78c1fc7dce8.png)

```
（在这里粘贴traceback或其他报错信息）
```
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "d:\develop\python\python3.7\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "d:\develop\python\python3.7\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "d:\develop\python\python3.7\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "D:\Develop\Nokia_Red_Windows\workspace\党建2.0-app自动化\资源\AirTest自动化\scripts\ZHDJ2\000_登陆智慧党建.air\000_登陆智慧党建.py", line 19, in <module>
    ZHDJ2_loginApp("15882298560", "a123456")
  File "D:\Develop\Nokia_Red_Windows\workspace\党建2.0-app自动化/资源/AirTest自动化/scripts/ZHDJ2\../../aw/Common.air\Common.py", line 98, in ZHDJ2_loginApp
    if exists(Template(r"tpl1526609426840.png", record_pos=(0.003, 0.45), resolution=(720, 1280))):
  File "d:\develop\python\python3.7\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "d:\develop\python\python3.7\lib\site-packages\airtest\core\api.py", line 409, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "d:\develop\python\python3.7\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "d:\develop\python\python3.7\lib\site-packages\airtest\core\cv.py", line 49, in loop_find
    match_pos = query.match_in(screen)
  File "d:\develop\python\python3.7\lib\site-packages\airtest\core\cv.py", line 122, in match_in
    match_result = self._cv_match(screen)
  File "d:\develop\python\python3.7\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "d:\develop\python\python3.7\lib\site-packages\airtest\core\cv.py", line 144, in _cv_match
    ret = self._try_match(self._find_sift_in_predict_area, image, screen)
  File "d:\develop\python\python3.7\lib\site-packages\airtest\core\cv.py", line 157, in _try_match
    ret = method(*args, **kwargs)
  File "d:\develop\python\python3.7\lib\site-packages\airtest\core\cv.py", line 187, in _find_sift_in_predict_area
    ret_in_area = aircv.find_sift(predict_area, image, threshold=self.threshold, rgb=self.rgb)
  File "d:\develop\python\python3.7\lib\site-packages\airtest\aircv\sift.py", line 27, in find_sift
    kp_sch, kp_src, good = _get_key_points(im_source, im_search, good_ratio)
  File "d:\develop\python\python3.7\lib\site-packages\airtest\aircv\sift.py", line 99, in _get_key_points
    sift = _init_sift()
  File "d:\develop\python\python3.7\lib\site-packages\airtest\aircv\sift.py", line 91, in _init_sift
    sift = cv2.SIFT(edgeThreshold=10)
AttributeError: module 'cv2.cv2' has no attribute 'SIFT'

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.7`

**airtest 版本:** `1.0.26`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)
windows

**Comment by rockywhisper** [comment]
@tester-wells 
你好，这个是因为[opencv-contrib-python](https://pypi.org/project/opencv-contrib-python/)最新版本里面没有再打contrib包进去：
![image](https://user-images.githubusercontent.com/8188879/56858232-7da70c80-69a9-11e9-93cd-9ef5f1f47f1f.png)

解决方法：（使用包含了对应算法的旧版本）
1、`pip uninstall opencv-contrib-python`
2、`pip install opencv-contrib-python==3.2.0.7`

**Comment by lincoln987** [comment]
airtest                            1.0.26
cv2.__version__         '4.1.0'

sift。py的_init_sift 只检查了 3.X 缺少4.X的判断条件
