### ISSUE TITLE
調用airtest.report.report 後 airtest.cli.info 報錯

### ISSUE THREAD

**Issue by zephyrxvxx7** [AirtestProject/Airtest#381]
在調用 airtest.report.report.LogToHtml(script_root) 後使用report() method會報錯
在經過檢查原始碼之後，發現以下問題

airtest.cli.info
```python
def get_script_info(script_path):
    """extract info from script, like basename, __author__, __title__ and __desc__."""
    script_name = os.path.basename(script_path)
    if script_path.endswith(".py"):
        pyfilepath = script_path
    else:
        pyfilename = script_name.replace(".air", ".py")
        pyfilepath = os.path.join(script_path, pyfilename)

    if not os.path.exists(pyfilepath) and six.PY2:
        pyfilepath = pyfilepath.encode(sys.getfilesystemencoding())
    with open(pyfilepath, encoding="utf-8") as pyfile:
        pyfilecontent = pyfile.read()

    author, title, desc = get_author_title_desc(pyfilecontent)

    result_json = {"name": script_name, "author": author, "title": title, "desc": desc}
    return json.dumps(result_json)
```

由於輸入的路徑會可能會在結尾包含`/`
而使用`os.path.basename()`會導致回傳值是`''`

所以在使用上述提及的原始碼`script_name = os.path.basename(script_path)`之後會使得`script_name`沒有值
之後繼續執行下去可能就會導致錯誤

因此我建議此行可以改為`script_name = os.path.basename(script_path) if(os.path.basename(script_path)) else os.path.basename(script_path[:-1])`

**python 版本:** `python3.7.3`

**airtest 版本:** `1.0.26`

**Comment by yuzhujiutian** [comment]
由於輸入的路徑會可能會在結尾包含/

========

斜线是手工带上的吗，如果是的话，也许按照下面方法，您的问题可以解决。
用可兼容（windows、linux、mac）的 os.sep 来替代手工加的 /

**Comment by zephyrxvxx7** [comment]
@yuzhujiutian 感謝你的回覆

我在呼叫`LogToHtml`時路徑是沒有帶上`/`的
但是我在確認原始碼時，確定在airtest內傳遞參數時會加上`/`

所以我建議要修改`airtest.cli.info`達到兼容的目的

**Comment by yimelia** [comment]
非常感谢 @zephyrxvxx7 
我们会尽快更新这个修改

**Comment by yimelia** [comment]
以及 @zephyrxvxx7 能否幫忙提供一下你的代碼和當時的報錯？

**Comment by zephyrxvxx7** [comment]
@yimelia 感謝你的關注

這是我執行的片段程式碼：

```python
import airtest.report.report as report

rpt = report.LogToHtml(script_root=script_path, log_root=log_path)
rpt.report("log_template.html", output_file=output_file)
```

其中，這是我使用VSCode的偵錯功能擷取到的參數：

```python
script_path = '/Users/zephyr/AirtestRunner/TestCase/registered.air'
log_path = '/Users/zephyr/AirtestRunner/TestCase/log/registered'
output_file = '/Users/zephyr/AirtestRunner/TestCase/log/registered/log.html'
```

<img width="552" alt="螢幕快照 2019-05-06 上午10 21 20" src="https://user-images.githubusercontent.com/12326917/57204198-bb7ae500-6fe8-11e9-8a91-b2fbed9ed1bc.png">

以及這是我當時的報錯：

```log
2019-05-06 10:04:28,590 - root - ERROR - [Errno 21] Is a directory: '/Users/zephyr/AirtestRunner/TestCase/registered.air/'
Traceback (most recent call last):
  File "airtest_runner.py", line 66, in run_air
    rpt.report("log_template.html", output_file=output_file)
  File "/usr/local/lib/python3.7/site-packages/airtest/report/report.py", line 340, in report
    info = json.loads(get_script_info(script_path))
  File "/usr/local/lib/python3.7/site-packages/airtest/cli/info.py", line 25, in get_script_info
    with open(pyfilepath, encoding="utf-8") as pyfile:
IsADirectoryError: [Errno 21] Is a directory: '/Users/zephyr/AirtestRunner/TestCase/registered.air/'
```

可以觀察到，在我呼叫`rpt.report`之前`script_path`是沒有帶`/`的，但是在經過參數傳遞後，我的參數被帶上`/`了。

**Comment by yimelia** [comment]
Duplicate of #461
