### ISSUE TITLE
请问在poco中如何像wda那样通过bundle id打开app

### ISSUE THREAD

**Issue by zacard-orc** [AirtestProject/Airtest#383]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
请问如何像wda那样通过bundleid打开app
c = wda.Client()
s = c.session('com.tencent.xin')

----
如果Poco中实现这样语法，或者隔屏app 
print(poco.get_screen_size())
poco('com.lagou.lagouhr').click()
print(snapshot(msg="aaaa"))
print(poco.get_screen_size())
poco('百度地图').click()
print(snapshot(msg="aaaa"))
就会出现如下报错

```
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 65, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 61, in runTest
  File "/var/folders/zq/fp1y8kc935b6t78wv61gz6g40000gp/T/AirtestIDE/Scripts/untitled.air/untitled.py", line 14, in <module>
    poco('com.lagou.lagouhr').click()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 29, in wrapped
    raise e
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 874, in _do_query
    raise PocoNoSuchNodeException(self)
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "com.lagou.lagouhr"
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
print(poco.get_screen_size())
poco('com.lagou.lagouhr').click()
print(snapshot(msg="aaaa"))

**python 版本:** `python3.7`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: ios
 - 系统: 12.1+
 - (别的信息)

**其他相关环境信息**
osx 10.14+

**Comment by zacard-orc** [comment]
而且，xcode起来后，支持 curl -X POST -d '{"desiredCapabilities": {"shouldWaitForQuiescence": true, "bundleId": "com.lufax.lujinsuo"}}' 'http://localhost:8100/session'，但是api文档里没有艾

**Comment by yimelia** [comment]
试一下 start_app接口？

**Comment by SUDARSHANCHAUDHARI** [comment]
@yimelia 

for me, I tried the same syntax,
but then I lost the connection between WebDriver and Iproxy
connection disabled and can't connect to the device. (I doubt it is optimized and working for iOS?)

have to restart web drive Xcode project and proxy URL.

I think we cant launch the app directly because in background WebdriveAgent application is running and if we launch any app from 'start_app' command then WebdriveAgent stops working.

It is my thinking and can anybody provide the exact cause and solution for this problem

Note: for android, start_app is working as intended and without any issue

**Comment by EraChen233** [comment]
@SUDARSHANCHAUDHARI 

What's the output of your AirtestIDE, iproxy terminal and Xcode log viewer? And what's the version of them.

**Comment by SUDARSHANCHAUDHARI** [comment]
@EraChen233 , AirtestIDE version 1.1.0 for Mac OS
nothing in the log viewer of IDE
but on
--------------------------
iproxy 
Requesting connecion to device handle == 1 (serial: 5f1b2552689774f42e60acc9952be9a7e2eb58e5), port 8100
waiting for connection
run_ctos_loop: fd = 4
run_stoc_loop: fd = 4
accepted connection, fd = 10
waiting for connection
Number of available devices == 1
--------------------------
xcode project terminal >>
t =  3840.87s Find: Children matching type Any    
t =  3840.87s Find: Element at index 6    
t =  3840.88s Snapshot accessibility hierarchy for app with pid 52    
t =  3840.88s Find: Children matching type Any    
t =  3840.88s Snapshot accessibility hierarchy for app with pid 52    
t =  3840.88s Snapshot accessibility hierarchy for app with pid 52    
t =  3840.88s Find: Children matching type Any    
t =  3840.89s Find: Element at index 7    
t =  3840.89s Snapshot accessibility hierarchy for app with pid 52    
t =  3840.89s Find: Children matching type Any    
t =  3840.89s Find: Element at index 7    
t =  3840.89s Snapshot accessibility hierarchy for app with pid 52    
t =  3840.90s Find: Children matching type Any    
t =  3840.90s Snapshot accessibility hierarchy for app with pid 52    
t =  3840.90s Snapshot accessibility hierarchy for app with pid 52    
t =  3843.55s Find the Application 'com.apple.springboard'    
t =  3843.55s     Snapshot accessibility hierarchy for app with pid 52    
t =  3843.65s Get all elements bound by index for: Children matching type Any    
t =  3843.65s     Snapshot accessibility hierarchy for app with pid 52    
t =  3843.75s     Find: Children matching type Any
--------------------------

**Comment by EraChen233** [comment]
@SUDARSHANCHAUDHARI 
I can't see anything wrong in your log. 
It seems that your problem is different with the author.
Can you open a new issue and describe your problem clearly?

**Comment by SUDARSHANCHAUDHARI** [comment]
@EraChen233 , will do

**Comment by SUDARSHANCHAUDHARI** [comment]
@zacard-orc, @EraChen233, @yimelia

now I can use start_app() command to start any application on the iOS device

just in case, if anybody wants to know how to collect bundle id of any  iOS app then follow [here](https://support.microsoft.com/en-us/help/4294074/how-to-find-the-bundle-id-for-an-ios-app) >>
