### ISSUE TITLE
多线程配合多台手机运行脚本，运行中手机之间有冲突，并且报异常ValueError: generator already executing

### ISSUE THREAD

**Issue by rossoneri520** [AirtestProject/Airtest#403]
**描述问题bug**
多线程配合多台手机运行脚本，运行中报异常ValueError: generator already executing

```
Traceback (most recent call last):
  File "D:\Users\tangzt\AppData\Local\Programs\Python\Python35\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "D:\Users\tangzt\AppData\Local\Programs\Python\Python35\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\Users\tangzt\AppData\Local\Programs\Python\Python35\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "D:\git\MobileAutoTest\completePage\debugCase\订单信息_乘客行程_国际多程.air\订单信息_乘客行程_国际多程.py", line 19, in <module>
    assert_exists(Template(r"tpl1557384351372.png", record_pos=(0.158, -0.669), resolution=(1080, 2340)), "一程航班")
  File "D:\Users\tangzt\AppData\Local\Programs\Python\Python35\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "D:\Users\tangzt\AppData\Local\Programs\Python\Python35\lib\site-packages\airtest\core\api.py", line 446, in assert_exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT, threshold=ST.THRESHOLD_STRICT)
  File "D:\Users\tangzt\AppData\Local\Programs\Python\Python35\lib\site-packages\airtest\utils\logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "D:\Users\tangzt\AppData\Local\Programs\Python\Python35\lib\site-packages\airtest\core\cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "D:\Users\tangzt\AppData\Local\Programs\Python\Python35\lib\site-packages\airtest\core\android\android.py", line 216, in snapshot
    screen = self.minicap.get_frame_from_stream()
  File "D:\Users\tangzt\AppData\Local\Programs\Python\Python35\lib\site-packages\airtest\core\android\minicap.py", line 24, in wrapper
    return func(inst, *args, **kwargs)
  File "D:\Users\tangzt\AppData\Local\Programs\Python\Python35\lib\site-packages\airtest\core\android\minicap.py", line 326, in get_frame_from_stream
    return six.next(self.frame_gen)
ValueError: generator already executing
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
总共两台设备，当分别执行t1.start()和t2.start()的时候都是可以成功的。但是当两个线程并发执行队列里面的sctrip的时候，貌似会有冲突。

from airtest.cli.runner import AirtestCase, run_script
from airtest.core.api import *
from argparse import *
import os
import time
import sys
import queue
import re
import threading
sys.path.append("../helper")
import helper

class CustomAirtestCase(AirtestCase):
    def setUp(self):
        ST.rgb = True
        ST.OPDELAY = 0.5
        ST.THRESHOLD_STRICT = 0.7
        ST.THRESHOLD = 0.7
        wake()
        super(CustomAirtestCase, self).setUp()

    def tearDown(self):
        stop_app("ctrip.android.view")
        super(CustomAirtestCase, self).setUp()

    def caseQueue(self,root_dir='.\\dailyTestCase'):
        q = queue.Queue()
        for f in os.listdir(root_dir):
            if f.endswith(".air"):
                script = os.path.join(root_dir, f)
                q.put(script)
        return q

    def run_air(self, caseQueue,device=['android://127.0.0.1:5037/GWY0217406000373']):
        while not caseQueue.empty():
            script = caseQueue.get()
            airName = re.search(r'[^\\]+$', script).group(0)
            caseName = airName.replace('.air', '')
            root_log = 'D:\\testcase\\'
            log = root_log + '\\' + caseName
            args = Namespace(device=device, log=log, recording=None, script=script)
            try:
                run_script(args, CustomAirtestCase)
            except:
                pass

if __name__ == '__main__':
    test = CustomAirtestCase()
    caseTasks = test.caseQueue('.\\debugCase')
    # vivo
    device1 = ['android://127.0.0.1:5037/d5c7f0e8']
    # oppo
    device2 = ['android://127.0.0.1:5037/ee03674a']
    devs = [device1,device2]
    res1 = []
    res2 = []
    t1 = threading.Thread(target=test.run_air, args=(caseTasks,device1,))
    t2 = threading.Thread(target=test.run_air, args=(caseTasks,device2,))

    t1.start()
    time.sleep(5)
    t2.start()
    t1.join()
    t2.join()

**预期效果**

**python 版本:** `python3.5`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2]
 - 系统: [e.g. Android 8.1]
 - (别的信息)

**其他相关环境信息**
windows环境

**Comment by EraChen233** [comment]
代码逻辑问题请自行DEBUG解决。
看你的代码，是想实现多个设备执行相同的 airtest脚本，可以参考我们的多脚本样例[multi-device-runner](https://github.com/AirtestProject/multi-device-runner)
如果希望执行多设备多脚本，烦请等待我们专业版 AirtestIDE Pro 发布， 如需商业合作，可联系 QQ 476271464

**Comment by rossoneri520** [comment]
![image](https://user-images.githubusercontent.com/33311868/57688894-18257200-7671-11e9-8864-603b923603ef.png)
这里是不是笔误？同时这个代码跑通过么

**Comment by EraChen233** [comment]
感谢指出，已修改，可以运行的。
