### ISSUE TITLE
同样的脚本，部署到jenkins怎么跑不起来

### ISSUE THREAD

**Issue by aajustin** [AirtestProject/Airtest#432]
C:\Users\Justin\.jenkins\workspace\test_ui>python run.py 
[03:23:51][DEBUG]<airtest.core.android.adb> C:\Python35\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe devices
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "run.py", line 60, in run_on_multi_device
    'process': subprocess.Popen(cmd, cwd=os.getcwd()),
  File "C:\Python35\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Python35\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] ϵͳ�Ҳ���ָ�����ļ���
Traceback (most recent call last):
  File "run.py", line 117, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python35\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python35\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Justin\.jenkins\workspace\test_ui\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero
C:\Users\Justin\.jenkins\workspace\test_ui
app_001login.air
app_002ValueMeals.air
app_003ItemCard.air
app_005Product.air
app_006QuickPayment.air
app_007Appointment_1.air
app_007Appointment_2.air
app_007Appointment_3.air
app_008_1StaffAddDelete.air
app_008_2StaffAchievement.air
app_009Promotion.air
app_010StoreExtension.air
app_011ReportCenter.air
app_012PresentationProject.air
app_013MemberAdministration_1AddMember.air
app_013MemberAdministration_2Appointment.air
app_013MemberAdministration_2Appointment_2.air
['app_013MemberAdministration_2Appointment_2.air', 'app_013MemberAdministration_2Appointment.air', 'app_013MemberAdministration_1AddMember.air', 'app_012PresentationProject.air', 'app_011ReportCenter.air', 'app_010StoreExtension.air', 'app_009Promotion.air', 'app_008_2StaffAchievement.air', 'app_008_1StaffAddDelete.air', 'app_007Appointment_3.air', 'app_007Appointment_2.air', 'app_007Appointment_1.air', 'app_006QuickPayment.air', 'app_005Product.air', 'app_003ItemCard.air', 'app_002ValueMeals.air', 'app_001login.air']

C:\Users\Justin\.jenkins\workspace\test_ui>exit 0 
Finished: SUCCESS

**Comment by yimelia** [comment]
报错是 FileNotFoundError: [WinError 2]
也就是找不到文件，从log看猜测可能是jenkins找不到report_tpl.html这个模板文件，但是具体原因需要本地调试才知道，jenkins的问题更多会与本地环境、文件路径、配置内容有关，我们很难根据log帮忙排查，这类问题需要你们自行排查环境问题来解决了，请尽量自行阅读traceback的内容解决问题。
