### ISSUE TITLE
android/recorder模块python2/3 兼容性

### ISSUE THREAD

**Issue by adolli** [AirtestProject/Airtest#44]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pocounit/case.py", line 165, in run
    emitter.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pocounit/result/record.py", line 31, in start
    success = self.device.start_recording()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/android.py", line 503, in start_recording
    return self.recorder.start_recording(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/utils/snippet.py", line 101, in ready_func
    return func(inst, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/recorder.py", line 53, in start_recording
    m = re.match("start result: Record start success! File path:(.*\.mp4)", line.strip())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by adolli** [comment]
fixed
