### ISSUE TITLE
使用pycharm执行完用例脚本之后总会提示hrpc.exceptions.TransportDisconnected

### ISSUE THREAD

**Issue by chenyuzhen233** [AirtestProject/Airtest#440]
**描述问题bug**
使用unittest+airtest编写安卓自动化测试脚本。每次执行完用例脚本之后pycharm控制台总会提示HTTPConnectionPool。用例形如：进入微信聊天界面，发送消息，检查消息是否成功。用例执行成功后，pycharm控制台总会显示hrpc.exceptions.TransportDisconnected异常。

```
[11:32:34][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell settings get secure default_input_method
[11:32:34][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell ime list -a
[11:32:34][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell am broadcast -a ADB_INPUT_TEXT --es msg 'test'
[11:32:35][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell input keyevent ENTER
[11:32:40][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell input keyevent BACK
[11:32:41][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 shell input keyevent BACK
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:15663
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:16397
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:19483
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:17705
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:12157
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:17819
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:17439
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:13402
[11:32:42][DEBUG]<airtest.core.android.adb> C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 207943d7 forward --remove tcp:13877
[11:32:42][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
Exception ignored in: <function RpcObjectProxy.__del__ at 0x000001585A005158>
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\object_proxy.py", line 114, in __del__
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\client.py", line 63, in evaluate
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37\lib\site-packages\hrpc\transport\http.py", line 26, in send
hrpc.exceptions.TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=17819): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001585A2AD780>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
```

**相关截图**
![image](https://user-images.githubusercontent.com/18247888/60232980-fa366880-98d0-11e9-8f12-0b6f3f7a49b4.png)

![image](https://user-images.githubusercontent.com/18247888/60233166-d889b100-98d1-11e9-8b70-356cc34b6869.png)

![image](https://user-images.githubusercontent.com/18247888/60233524-3cf94000-98d3-11e9-8439-b180b5c0729c.png)

**复现步骤**
1. 实在不知道怎么复现这个步骤，如果只是单个.air脚本运行就不会出现，但是多个.py脚本相互导包时就会出现这个问题。

**预期效果**
想要去掉这个异常报错信息。

**python 版本:** `python3.7.2`

**airtest 版本:** `1.0.27`

**设备:**
 - 型号 :小米 MIX 2S
 - 系统:  Android9

**其他相关环境信息**

**Comment by yimelia** [comment]
求贴能够复现问题的最简代码，方便我们查找问题

**Comment by chenyuzhen233** [comment]
`import unittest
from airtest.core.api import *
from airtest.core.android import Android
from airtest.cli.parser import cli_setup
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
poco = AndroidUiautomationPoco()
android = Android()


class test_wechat_send_message(unittest.TestCase):
    elements = {
        "文件传输助手": poco(text="文件传输助手"),
        "聊天输入框": poco("com.tencent.mm:id/amh"),
        "聊天发送按钮": poco("com.tencent.mm:id/amp")
    }

    @classmethod
    def setUpClass(cls):
        start_app("com.tencent.mm")

    def test_case_send_message_to_someone(self):
        self.elements['文件传输助手'].click()
        self.elements['聊天输入框'].click()
        text("测试信息")
        self.elements['聊天发送按钮'].click()

        keyevent("BACK")
        keyevent("BACK")

        flag = poco(text="测试信息").exists()
        self.assertEqual(flag, True)


if __name__ == '__main__':
    unittest.main()`

这个脚本可以复现问题，但是只要在头部加上这一行代码就可以避免。
`
if not cli_setup():
    auto_setup(__file__, logdir=True, devices=[
        "Android://127.0.0.1:5037/207943d7?cap_method=javacap&ori_method=adbori",
    ])
`

现在遇到的问题是，我的运行函数是写在另一个文件run.py中的。cli_set_up不管写在用例文件，还是执行文件都会出现hrpc.exceptions.TransportDisconnected

**Comment by yangbaojian4** [comment]
同问，

**Comment by Richard1ybb** [comment]
我遇到类似问题，但是是在运行中抛出的编码异常：

> hrpc.exceptions.TransportDisconnected: 'latin-1' codec can't encode characters in position 188-190: Body ('小程序') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/ybbrichard/Downloads/AirTest/Air/home.air/home.py", line 31, in <module>
    poco(text="小程序").click()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/utils/retry.py", line 20, in wrapped
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/utils/retry.py", line 15, in wrapped
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/utils/hrpc/hierarchy.py", line 33, in select
    return self.selector.select(query, multiple)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/hrpc/object_proxy.py", line 92, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/hrpc/client.py", line 63, in evaluate
    self.transport.send({'id': reqid, 'uri': obj_proxy._uri__, 'method': obj_proxy._invocation_path__})
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/hrpc/transport/http.py", line 26, in send
    raise TransportDisconnected(e)
hrpc.exceptions.TransportDisconnected: 'latin-1' codec can't encode characters in position 188-190: Body ('小程序') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```
