### ISSUE TITLE
使用pip安装的airtest进行swipe报错，使用airtestide正常，右键运行选定代码正常

### ISSUE THREAD

**Issue by sherry0429** [AirtestProject/Airtest#441]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
执行到swipe自动抛出异常（pip安装到airtest）
使用airtest ide则不抛出异常。

```
    touch(Template(r"tpl1561732457072.png", record_pos=(0.172, 0.251), resolution=(2224, 1668)))
    time.sleep(3)
    swipe((1758, 1156), (1758, 800))

报错：
FAIL: runTest (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/background-dev/airtest/venv/lib/python3.7/site-packages/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/Users/background-dev/airtest/venv/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/background-dev/airtest/venv/lib/python3.7/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/background-dev/Documents/airtest-scripts/ipaddaily.air/ipaddaily.py", line 30, in <module>
    swipe((1758, 1156), (1758, 800))
  File "/Users/background-dev/airtest/venv/lib/python3.7/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/Users/background-dev/airtest/venv/lib/python3.7/site-packages/airtest/core/api.py", line 326, in swipe
    G.DEVICE.swipe(pos1, pos2, **kwargs)
  File "/Users/background-dev/airtest/venv/lib/python3.7/site-packages/airtest/core/ios/ios.py", line 238, in swipe
    tx * self._touch_factor, ty * self._touch_factor, duration)
  File "/Users/background-dev/airtest/venv/lib/python3.7/site-packages/wda/__init__.py", line 557, in swipe
    x1, y1 = self._percent2pos(x1, y1, size)
  File "/Users/background-dev/airtest/venv/lib/python3.7/site-packages/wda/__init__.py", line 505, in _percent2pos
    assert w >= x >= 0
AssertionError
```

**复现步骤**
1. pip安装airtest调用swipe

**python 版本:python3.7
**airtest 版本:最新版本

**设备:**
mac，iOS，xcode，应该与运行环境无关。

**Comment by yimelia** [comment]
@sherry0429 
最好列一下ios和xcode的版本号，方便我们定位问题。
以及在运行脚本时，设备画面是否是横屏？

**Comment by sherry0429** [comment]
@yimelia 
iOS：12.1.4
xcode：10.2.1 （换了UItaskFramework为老版本）

**Comment by EraChen233** [comment]
这是我们的一个bug，在iOS>10 的情况下，暂时用这个方法
https://github.com/AirtestProject/Airtest/issues/407#issuecomment-497235934

**Comment by sherry0429** [comment]
@EraChen233 两回事，这个issue我之前看到过，它解决了用自己的python的时候，touch的问题。swipe还是没解决。

**Comment by EraChen233** [comment]
好的，我晚点查看一下

**Comment by sherry0429** [comment]
@EraChen233 好的谢谢！
