### ISSUE TITLE
华为部分设备录屏不可用

### ISSUE THREAD

**Issue by buffaloleo143** [AirtestProject/Airtest#451]
**描述问题bug**

部分设备录屏后只在在手机里生成一个0B的MP4文件，尝试pull至pc端时会报未开始录制（不过这个报错应该是由于录制功能本身有问题）

（在这里粘贴traceback或其他报错信息）
[Start running..]
save log in 'C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\scripts\aed200ddb935ccf7ba2461c3b92df216'
[11:47:18][DEBUG]<airtest.core.android.adb> D:\testline\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s HYJNW18A30001573 wait-for-device
[11:47:18][DEBUG]<airtest.core.android.adb> D:\testline\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s HYJNW18A30001573 shell getprop ro.build.version.sdk
custom setup
[11:47:19][DEBUG]<airtest.core.android.adb> D:\testline\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s HYJNW18A30001573 shell dumpsys package com.netease.nie.yosemite
[11:47:19][INFO]<airtest.core.android.yosemite> local version code is 287, installed version code is 287
[11:47:19][DEBUG]<airtest.core.android.adb> D:\testline\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s HYJNW18A30001573 shell pm path com.netease.nie.yosemite
[11:47:19][DEBUG]<airtest.core.android.adb> D:\testline\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s HYJNW18A30001573 shell CLASSPATH=/data/app/com.netease.nie.yosemite-1KU8Y-eP4HQCfkp_3mjJEg==/base.apk exec app_process -Dduration=1800 -Dvertical=false /system/bin com.netease.nie.yosemite.Recorder --start-record
[11:47:20][DEBUG]<airtest.utils.nbsp> [254753672]'browsing http://10.5.45.151:8686/start<?filename=xxx.mp4> to start recording!'
[11:47:20][DEBUG]<airtest.utils.nbsp> [254753672]'then using http://10.5.45.151:8686/download to stop and download recording.'
[11:47:21][DEBUG]<airtest.utils.nbsp> [254753672]'record started, max duration: 1800 secs.'
[11:47:20][DEBUG]<airtest.utils.nbsp> [254753672]'or using http://10.5.45.151:8686/stop to stop the recording server.'

[11:47:21][DEBUG]<airtest.utils.nbsp> [254753672]'bitrate: 1000000'
[11:47:21][DEBUG]<airtest.utils.nbsp> [254753672]'startLocalRecord:'
[11:47:21][DEBUG]<airtest.utils.nbsp> [254753672]'start result: Record start success! File path:mnt/sdcard/test.mp4'
[11:47:23][DEBUG]<airtest.core.android.adb> D:\testline\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s HYJNW18A30001573 shell pm path com.netease.nie.yosemite
[11:47:24][DEBUG]<airtest.core.android.adb> D:\testline\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s HYJNW18A30001573 shell CLASSPATH=/data/app/com.netease.nie.yosemite-1KU8Y-eP4HQCfkp_3mjJEg==/base.apk exec app_process /system/bin com.netease.nie.yosemite.Recorder --stop-record
custom tearDown
======================================================================
ERROR: runTest (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\testline\venv\lib\site-packages\airtest\cli\runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "D:\testline\venv\lib\site-packages\airtest\cli\runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "D:\testline\static\airscript\zenglihong\test_vedio.air\test_vedio.py", line 58, in <module>
    RecordTest()
  File "D:\testline\static\airscript\zenglihong\test_vedio.air\test_vedio.py", line 36, in RecordTest
    oDevice.stop_recording(is_interrupted=False)
  File "D:\testline\venv\lib\site-packages\airtest\core\android\android.py", line 581, in stop_recording
    return self.recorder.stop_recording(*args, **kwargs)
  File "D:\testline\venv\lib\site-packages\airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "D:\testline\venv\lib\site-packages\airtest\core\android\recorder.py", line 95, in stop_recording
    raise AirtestError("start_recording first")
AirtestError: 'start_recording first'

**复现步骤**
1.命令行里随便带recording参数运行一个脚本
2.或者ide里运行下面的函数
def RecordTest():
    oDevice = device()
    oDevice.start_recording(max_time=1800, bit_rate=None, vertical=False)
    sleep(2)
    oDevice.stop_recording(is_interrupted=False)

**python 版本:** `python2.7`

**airtest 版本:** `1.0.24`

adb版本1.0.40

**设备:**
 - 型号: 华为畅想9plus、华为麦芒7
 - 系统: 8.2

**其他相关环境信息**
win 10 、ubuntu16、任何运行中环境都这样

**Comment by yimelia** [comment]
在命令行运行的时候，是否有带着`--device`参数来运行？
试一下在确保有--device参数指定上述手机运行时，看看能否正确生成录屏文件？

**Comment by buffaloleo143** [comment]
> 在命令行运行的时候，是否有带着`--device`参数来运行？
> 试一下在确保有--device参数指定上述手机运行时，看看能否正确生成录屏文件？

肯定都试过啦，就是不行的

**Comment by yimelia** [comment]
在华为畅想9plus（设备型号JKM-AL00b，Android版本8.1）上已验证确实存在此问题，我们会尽可能想办法修复，感谢提出

**Comment by 1031561252** [comment]
华为nova3i也这样，我们这边很多华为设备都这样，老大大大啥时候修一下

**Comment by yangyang066** [comment]
修了嘛 修了嘛 修了嘛
