### ISSUE TITLE
 If using Airtest adb.exe, import trace outputs ModuleNotfoundError. However, Module can be imported if using Python's default adb.exe.

### ISSUE THREAD

**Issue by phantomsom** [AirtestProject/Airtest#468]
**Python version:** `python3.7.2`
**AirtestIDE version:** `V1.2.0`
**Poco version:** `pocoui==1.0.76`
**Airtest version:** `airtest==1.0.27`

**Describe the bug**
When using Airtest adb.exe to run `import trace`, Airtest shows ModuleNotFoundError.
When using Python adb.exe to run `import trace`. No error.

`\AirtestIDE_2019-01-15\AirtestIDE_2019-01-15_py3_win64\airtest\core\android\static\adb\windows\adb.exe` 

```
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 66, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 62, in runTest
  File "E:\Stuff\AirtestPocoProjects\SecretGameRobot.air\SecretGameRobot.air\SecretGameRobot.py", line 175, in <module>
    import ThreadWithTrace
  File "E:\Stuff\AirtestPocoProjects\SecretGameRobot.air\SecretGameRobot.air\ThreadWithTrace.py", line 7, in <module>
    import trace
ModuleNotFoundError: No module named 'trace'
```

**To Reproduce**
1. Open empty project in Airtest v1.2.0, with default python path set by airtest
2. Type import trace
3. Run code

**Expected behavior**
Airtest adb.exe should be able to import trace , because it is found in Python37 > Lib
![image](https://user-images.githubusercontent.com/19833754/61613287-84d17400-ac93-11e9-82cd-bda94f175c1e.png)

**Screenshots**
My ThreadWithTrace class that outputs error when run using Airtest adb.exe
![image](https://user-images.githubusercontent.com/19833754/61613318-99ae0780-ac93-11e9-9d49-4af75e7756a1.png)

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
- Android Version : Android 9 PKQ1.18076

**Comment by yimelia** [comment]
`ModuleNotFoundError: No module named 'trace'` 
because AirtestIDE.exe use the python in exe, it only has Airtest+Poco+some of the Python Standard Library ( We did not package the `trace.py` module into the AirtestIDE.exe）
if you want to use other packages, you must set the `Custom Python Path` in AirtestIDE settings.
or 
copy the trace.py into the AirtestIDE/ directory

**Comment by phantomsom** [comment]
> `ModuleNotFoundError: No module named 'trace'`
> because AirtestIDE.exe use the python in exe, it only has Airtest+Poco+some of the Python Standard Library ( We did not package the `trace.py` module into the AirtestIDE.exe）
> if you want to use other packages, you must set the `Custom Python Path` in AirtestIDE settings.
> or
> copy the trace.py into the AirtestIDE/ directory

Thank you for your response. If that's the case, I can just use a custom python path. However, there is another problem in doing that.

 I'll link you to it once I'm done writing that Issue ->

**Comment by phantomsom** [comment]
@yimelia, https://github.com/AirtestProject/Airtest/issues/470
