### ISSUE TITLE
Error while running run.py . Also is there any way one can run script in two different devices such that some functions run on one device and some on other one.

### ISSUE THREAD

**Issue by SaketGaur17** [AirtestProject/Airtest#471]
Traceback (most recent call last):
  File "C:\Users\xyz\multi-device-runner-master\multi-device-runner-master\run.py", line 56, in run_on_multi_device
    'process': subprocess.Popen(cmd,cwd=os.getcwd()),
  File "subprocess.py", line 729, in __init__
  File "subprocess.py", line 1017, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\xyz\multi-device-runner-master\multi-device-runner-master\run.py", line 113, in run_summary
    html = env.get_template('report_tpl.html').render(data=summary)
  File "site-packages\jinja2\asyncsupport.py", line 76, in render
  File "site-packages\jinja2\environment.py", line 1008, in render
  File "site-packages\jinja2\environment.py", line 780, in handle_exception
  File "site-packages\jinja2\_compat.py", line 37, in reraise
  File "C:\Users\xyz\multi-device-runner-master\multi-device-runner-master\report_tpl.html", line 219, in top-level template code
    <div class="progress-bar progress-bar-success" role="progressbar"  aria-valuemin="0" aria-valuemax="100" style="width: {{data['success'] *100 / data['count']}}%">
ZeroDivisionError: division by zero

**Comment by EraChen233** [comment]
Check if the path of Airtest script and log dir is correct.
![image](https://user-images.githubusercontent.com/5961185/61676462-9c116f80-ad2e-11e9-9c21-be58a0ff85dc.png)

And for the second question, Try to switch devices with function [set_current](https://airtest.readthedocs.io/en/latest/all_module/airtest.core.api.html#airtest.core.api.set_current). 
Here is an example:
http://airtest.netease.com/docs/en/1_quick_start/2_test_with_Android_device.html#multi-machine-collaboration
