### ISSUE TITLE
努比亚手机stop_app 异常

### ISSUE THREAD

**Issue by dedededede** [AirtestProject/Airtest#475]
在本地开发环境使用stop_app没有异常，但是打包apk后部署到真实手机上，stop_app会有异常。

 File "copy_app/airtest\utils\logwraper.py", line 72, in wrapper
  File "copy_app/airtest\core\api.py", line 158, in stop_app
  File "kivy.py", line 67, in stop_app
  File "copy_app\airtest\core\kivy\controler.py", line 43, in stop_app
AttributeError: 'org.kivy.android.Controler' object has no attribute 'finishApp'
=================script error end================

        at junit.framework.Assert.fail(Assert.java:50)
        at junit.framework.Assert.assertTrue(Assert.java:20)
        at org.kivy.android.ExampleInstrumentedTest.launchAirtestAndPoco(ExampleInstrumentedTest.java:95)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:433)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
        at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:375)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2108)

手机型号：努比亚在7 miniS
系统：root后，安卓7.1.1

**Comment by yimelia** [comment]
stop_app接口暂时是不支持的

**Comment by dedededede** [comment]
有什么替代的办法吗？还是说只能模拟手势去操作了

**Comment by yimelia** [comment]
我暂时还没有找到替代方案

**Comment by Tnxent** [comment]
> 我暂时还没有找到替代方案

这个问题现在解决了吗？
