### ISSUE TITLE
poco元素选择不兼容

### ISSUE THREAD

**Issue by yangbaojian4** [AirtestProject/Airtest#485]
**Describe the bug**
安卓6.0（M2-801w）和安卓8.01（vivo x21A）系统上，poco元素选择方法不兼容。
6.0上需要使用：

poco("发布").click()

poco("课后练习").click()
poco("自由组卷").click()
8.01上需要使用：
poco(text="发布").click()
poco(text="课后练习").click()
poco(text="自由组卷").click()

6.0报错日志
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tool\python\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "D:\tool\python\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\tool\python\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "E:\workspace\airtestnew\0002.air\0002.py", line 26, in <module>
    poco(text="课后练习").click()
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 29, in wrapped
    raise e
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 874, in _do_query
    raise PocoNoSuchNodeException(self)
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "text=课后练习"
```
8.0报错日志：
[03:24:52][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b shell ime list -a
[03:24:53][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b shell dumpsys package com.netease.open.pocoservice
installed version is 41, installer version is 41. force_reinstall=False
[03:24:53][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[03:24:53][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b forward --no-rebind tcp:14018 tcp:10080
[03:24:53][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b forward --no-rebind tcp:13062 tcp:10081
[03:24:53][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b shell ps
[03:24:54][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b shell am force-stop com.netease.open.pocoservice
[03:24:54][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b shell am start -n com.netease.open.pocoservice/.TestActivity
[03:24:54][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
custom tearDown
======================================================================
ERROR: runTest (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 26, in wrapped
    proxy.wait_for_appearance(timeout=proxy.poco._pre_action_wait_for_appearance)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 681, in wait_for_appearance
    raise PocoTargetTimeout('appearance', self)
poco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of "UIObjectProxy of "发布""

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tool\python\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "D:\tool\python\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\tool\python\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "E:\workspace\airtestnew\0002.air\0002.py", line 25, in <module>
    poco("发布").click()
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 29, in wrapped
    raise e
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "D:\tool\python\lib\site-packages\poco\proxy.py", line 874, in _do_query
    raise PocoNoSuchNodeException(self)
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "发布"

----------------------------------------------------------------------
Ran 1 test in 11.877s

FAILED (errors=1)
[03:25:03][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b forward --remove tcp:14018
[03:25:04][DEBUG]<airtest.core.android.adb> D:\tool\python\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 3df4ca7b forward --remove tcp:13062
[Finished]

============================================================
**To Reproduce**

1. run case

**Expected behavior**
不能正常地位；poco框架兼容性存在问题。

**python version:** `python3.7`

**airtest version:** `1.0.27`
> You can get airtest version via `pip freeze` command.

**Smartphone (please complete the following information):**
Device: [vivo x21A]  
Device: [ M2-801w]
 
 - more information if have

**Additional context**

**Comment by yimelia** [comment]
1. 是否是webview实现？
2. 请贴出元素的节点完整信息截图
3. 个人认为是可以统一写法来保证在不同版本手机上的兼容问题的

**Comment by yangbaojian4** [comment]
1.非网页流量实现，是airtest ide 连接真机
2.图片如下：
![image](https://user-images.githubusercontent.com/13099659/62358796-05bc2580-b548-11e9-813a-7eeeaae8125a.png)

**Comment by yangbaojian4** [comment]
@yimelia 3.个人认为是可以统一写法来保证在不同版本手机上的兼容问题的。在这点上尝试了两种写法，但只能在各自的版本上运行。6.0的代码在8.0上报错，8.0的写法在6.0上报错

**Comment by yimelia** [comment]
我确认了一下这个问题，是因为不同系统对控件的渲染不一样导致的，所以可能这种情况需要在代码里增加一句判断来解决了

**Comment by yimelia** [comment]
因为我们拿到的数据是已经渲染完毕之后的，poco里面没有办法知道这是因为系统渲染问题导致的结果，还是这个控件本来就叫这个名字，所以可能无法在poco里面做判断。需要自己在脚本里加了。

**Comment by chinar4** [comment]
@yimelia  能够提供下的渲染的资料吗？还是我需要写个class继承原来的类，然后在其中封装上自己方法。或者写个自己的方法，传相关内容，然后根据系统的版本号来实现。

**Comment by yangbaojian4** [comment]
@yimelia 下一版程序会更新这个问题吗？还是说自己用户自己处理。
