### ISSUE TITLE
类型转换错误；'bytes' and 'tuple'类型

### ISSUE THREAD

**Issue by Kevinchenzero** [AirtestProject/Airtest#50]
```
  File "C:\Python34\lib\site-packages\airtest\core\android\minitouch.py", line 179, in touch
     self.handle(b"d 0 %d %d 50\nc\n" % (x, y))
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple' 
```
我使用的python版本是3.4.3，是否不支持这个功能？

**Comment by Kevinchenzero** [comment]
使用的命令：python -m airtest run "F:\001.专项测试工作\011.游戏自动化\workspace\test.air" --device Android:///
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\airtest\cli\runner.py", line 88, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath.encode(sys.getfilesystemencoding()), 'exec')) in self.scope
  File "F:\001.专项测试工作\011.游戏自动化\workspace\test.air\test.py", line 10, in <module>
    touch(Template(r"tpl1525309728263.png", record_pos=(0.197, 0.544), resolution=(1080, 2116)))
  File "C:\Python34\lib\site-packages\airtest\utils\logwraper.py", line 73, in wrapper
    res = f(*args, **kwargs)
  File "C:\Python34\lib\site-packages\airtest\core\helper.py", line 120, in wrapper
    r = f(*args, **kwargs)
  File "C:\Python34\lib\site-packages\airtest\core\api.py", line 246, in touch
    G.DEVICE.touch(pos, **kwargs)
  File "C:\Python34\lib\site-packages\airtest\core\android\android.py", line 287, in touch
    self.minitouch.touch(pos, duration=duration)
  File "C:\Python34\lib\site-packages\airtest\utils\snippet.py", line 101, in ready_func
    return func(inst, *args, **kwargs)
  File "C:\Python34\lib\site-packages\airtest\core\android\minitouch.py", line 179, in touch
    self.handle(b"d 0 %d %d 50\nc\n" % (x, y))
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

----------------------------------------------------------------------
Ran 1 test in 4.876s

**Comment by adolli** [comment]
如果python版本不能更换的话，我们考虑下怎么兼容这部分写法

**Comment by Kevinchenzero** [comment]
我这个3.4 版本确实不好修改。想请问一下，3.4的兼容版本会着手写么？

**Comment by adolli** [comment]
这样的话我试着修一下吧，等下如果可以跟上版本发布的话，我通知你。

**Comment by Kevinchenzero** [comment]
特别感谢~静候你的消息~

**Comment by adolli** [comment]
麻烦`pip install -U airtest`进行更新。 @Kevinchenzero

**Comment by Kevinchenzero** [comment]
不会报之前的错误了。
能识别截图的ui控件。。但是touch函数貌似没有起作用，只是识别了，没有点击。

**Comment by adolli** [comment]
你touch怎么写的？

**Comment by Kevinchenzero** [comment]
我是直接在命令行执行Airtest IDE写的.air文件。

**Comment by adolli** [comment]
不好意思，下午出了点其他bug，麻烦再`pip install -U airtest`进行更新下就好了

**Comment by Kevinchenzero** [comment]
嗯嗯。没问题了~

但是之前我把minitouch.py从手机中删除了。有时候会报“install_minitouch skipped”或者“minicap server....”,然后卡在那里，动不了了~
这个问题，有没有什么方法解决的呢？

**Comment by adolli** [comment]
minitouch.py并不在手机上，你删的是minitouch吧，你可以直接把 /data/local/tmp目录清空，然后会自动重新初始化。
