### ISSUE TITLE
多设备在循环第二次执行脚本时报错

### ISSUE THREAD

**Issue by daisy0o** [AirtestProject/Airtest#502]
**描述问题bug**
多设备在循环第二次执行脚本时报错。控制台显示已经切换到第一台设备并连接，但实际执行的还是第二台设备，之后脚本因无法找到控件报错

```
报错信息：
[04:07:55][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 4277aff6 forward --no-rebind tcp:13825 tcp:10081
[04:07:55][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 4277aff6 shell ps
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/poco/proxy.py", line 26, in wrapped
    proxy.wait_for_appearance(timeout=proxy.poco._pre_action_wait_for_appearance)
  File "/usr/local/lib/python3.7/site-packages/poco/proxy.py", line 681, in wait_for_appearance
    raise PocoTargetTimeout('appearance', self)
poco.exceptions.PocoTargetTimeout: Waiting timeout for appearance of "UIObjectProxy of "com.hupu.games:id/btn_bbs""

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangpeng1990/Desktop/hupuApp/hupuApp/main.py", line 51, in <module>
    Startbbs( poco=poco1 )
  File "/Users/wangpeng1990/Desktop/hupuApp/hupuApp/bbs/startbbs.py", line 7, in __init__
    poco( "com.hupu.games:id/btn_bbs" ).click()
  File "/usr/local/lib/python3.7/site-packages/poco/proxy.py", line 29, in wrapped
    raise e
  File "/usr/local/lib/python3.7/site-packages/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/poco/proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "/usr/local/lib/python3.7/site-packages/poco/proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/poco/proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "/usr/local/lib/python3.7/site-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/poco/proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "/usr/local/lib/python3.7/site-packages/poco/proxy.py", line 874, in _do_query
    raise PocoNoSuchNodeException(self)
poco.exceptions.PocoNoSuchNodeException: Cannot find any visible node by query UIObjectProxy of "com.hupu.games:id/btn_bbs"
[04:08:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 4277aff6 forward --remove tcp:18959
[04:08:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 4277aff6 forward --remove tcp:15391
[04:08:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 4277aff6 forward --remove tcp:15751
[04:08:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 4277aff6 forward --remove tcp:19606
[04:08:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 8BN4C17B04003397 forward --remove tcp:17743
[04:08:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 8BN4C17B04003397 forward --remove tcp:13768
[04:08:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 8BN4C17B04003397 forward --remove tcp:14508
[04:08:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 8BN4C17B04003397 forward --remove tcp:13437
[04:08:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 4277aff6 forward --remove tcp:11271
[04:08:32][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 4277aff6 forward --remove tcp:13825
[04:08:32][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
[04:08:32][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended

```
**复现步骤**
1. 连接2个设备，执行脚本
2.第一次，2台设备依次运行完脚本
3.再切换到第1台设备准备第二次运行，脚本执行到切换设备后，开始报错

**预期效果**
多设备可以实现循环执行

**python 版本:** Python 3.7.4

**airtest 版本:** 1.0.69

**设备:**
 设备一
型号: oppo
系统: Android 8.1
设备二
型号：honor9
系统：Android 7.0

**Comment by Louis-me** [comment]
怎么解决的？
