### ISSUE TITLE
我想针对Unity或者Unreal的编辑器进行点击测试，发现匹配不到截图

### ISSUE THREAD

**Issue by t1633361** [AirtestProject/Airtest#508]
**描述问题bug**
我想针对Unity或者Unreal的编辑器进行点击测试，发现匹配不到截图

```
"D:\Program\AirtestIDE_2019-05-09_py3_win64\AirtestIDE" runner "C:\Users\HASEE\AppData\Local\Temp\AirtestIDE\Scripts\untitled.air"  --device Windows:///992732 --log "C:\Users\HASEE\AppData\Local\Temp\AirtestIDE\scripts\3f0954b11e33f5b714bfc3ac7ad1925d"
============================================================

[Start running..]
save log in 'C:\Users\HASEE\AppData\Local\Temp\AirtestIDE\scripts\3f0954b11e33f5b714bfc3ac7ad1925d'
D:\Program\AirtestIDE_2019-05-09_py3_win64\pywinauto\application.py:1032: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
[01:09:27][INFO]<airtest.core.api> Try finding:
Template(C:\Users\HASEE\AppData\Local\Temp\AirtestIDE\Scripts\untitled.air\tpl1567050651716.png)
[01:09:28][DEBUG]<airtest.core.api> resize: (50, 57)->(1, 1), resolution: (1936, 1056)=>(0, 0)
[01:09:28][DEBUG]<airtest.core.api> try match with SURFMatching
[01:09:28][DEBUG]<airtest.aircv.keypoint_base> find_best_result() run time is 0.00 s.
[01:09:28][DEBUG]<airtest.core.api> try match with TemplateMatching
[01:09:28][DEBUG]<airtest.core.api> 'error: in template match, found im_search bigger than im_source.'
[01:09:28][DEBUG]<airtest.core.api> try match with BRISKMatching
[01:09:28][DEBUG]<airtest.aircv.keypoint_base> find_best_result() run time is 0.00 s.
[01:09:28][DEBUG]<airtest.core.api> match result: None
[01:09:28][DEBUG]<airtest.core.api> resize: (50, 57)->(1, 1), resolution: (1936, 1056)=>(0, 0)
....
....
....
....

[01:09:47][DEBUG]<airtest.core.api> try match with BRISKMatching
[01:09:47][DEBUG]<airtest.aircv.keypoint_base> find_best_result() run time is 0.00 s.
[01:09:47][DEBUG]<airtest.core.api> match result: None
[01:09:47][DEBUG]<airtest.core.api> resize: (50, 57)->(1, 1), resolution: (1936, 1056)=>(0, 0)
[01:09:47][DEBUG]<airtest.core.api> try match with SURFMatching
[01:09:47][DEBUG]<airtest.aircv.keypoint_base> find_best_result() run time is 0.00 s.
[01:09:47][DEBUG]<airtest.core.api> try match with TemplateMatching
[01:09:47][DEBUG]<airtest.core.api> 'error: in template match, found im_search bigger than im_source.'
[01:09:47][DEBUG]<airtest.core.api> try match with BRISKMatching
[01:09:47][DEBUG]<airtest.aircv.keypoint_base> find_best_result() run time is 0.00 s.
[01:09:47][DEBUG]<airtest.core.api> match result: None
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 65, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 61, in runTest
  File "C:\Users\HASEE\AppData\Local\Temp\AirtestIDE\Scripts\untitled.air\untitled.py", line 6, in <module>
    touch(Template(r"tpl1567050651716.png", record_pos=(-0.013, 0.072), resolution=(1936, 1056)))
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\api.py", line 257, in touch
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\cv.py", line 76, in loop_find
  File "airtest\utils\logwraper.py", line 72, in wrapper
  File "airtest\core\cv.py", line 100, in try_log_screen
  File "airtest\aircv\aircv.py", line 26, in imwrite
cv2.error: OpenCV(3.4.2) C:\projects\opencv-python\opencv\modules\imgcodecs\src\grfmt_base.cpp:145: error: (-10:Unknown error code -10) Raw image encoder error: Empty JPEG image (DNL not supported) in function 'cv::BaseImageEncoder::throwOnEror'


----------------------------------------------------------------------
Ran 1 test in 20.377s

FAILED (errors=1)
[Finished]

============================================================


```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)
![Uploading image.png…]()

**复现步骤**
1.通过touch选中虚幻编辑器里面的运行按钮
2. 点击AirtestIDE里面的运行

**预期效果**
应该能触发虚幻引擎进入到运行状态

**python 版本:** `python3.5`

**airtest IDE版本:** `1.2.1`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. PC i7 9700K Nvidia 1080 双屏幕 ]
 - 系统: [e.g. win10]
 - (别的信息)

**其他相关环境信息**
针对sourcetree或者vscode都可以正常捕获到按钮

**Comment by t1633361** [comment]
再次测试的时候，可以触发了。有可能是之前嵌入编辑器不成功导致的
