### ISSUE TITLE
无法启动脚本

### ISSUE THREAD

**Issue by li9chuan** [AirtestProject/Airtest#512]
**(重要！设备控制相关问题)**

**描述问题bug**
```
[Start running..]
save log in 'C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\scripts\be10ecaa9233c88d9072ace4cb0e7480'
======================================================================
ERROR: setUpClass (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 28, in setUpClass
  File "airtest\cli\runner.py", line 130, in setup_by_args
  File "airtest\core\api.py", line 113, in auto_setup
  File "airtest\core\api.py", line 63, in connect_device
  File "airtest\core\api.py", line 33, in init_device
  File "D:\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\airtest\core\win\win.py", line 44, in __init__
    self._init_connect(handle, kwargs)
  File "D:\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\airtest\core\win\win.py", line 56, in _init_connect
    self.connect(handle=handle)
  File "D:\AirtestIDE_2019-04-16_py3_win64\AirtestIDE_2019-05-09_py3_win64\airtest\core\win\win.py", line 73, in connect
    self.app = self._app.connect(handle=handle)
  File "site-packages\pywinauto\application.py", line 926, in connect
RuntimeError: Invalid handle 0xa80d8e passed to connect()
```

**相关截图**
![image](https://user-images.githubusercontent.com/811164/64152095-74014a00-ce5e-11e9-8bf8-3051a198f68c.png)

**复现步骤**
uinty 2018.4.6f1  

**airtest 版本:** `1.2.1`

**设备:**
windows

**Comment by yimelia** [comment]
1. 需要先连上windows窗口后才能启动脚本
2. windows模式默认是使用连上的那个窗口的句柄，在关闭窗口又重开以后，句柄可能会发生变化
