### ISSUE TITLE
在centos7上运行连接设备时总是报没有权限，即使root执行的

### ISSUE THREAD

**Issue by ASmallListener** [AirtestProject/Airtest#53]
```
[08:25:16][DEBUG]<airtest.core.android.adb> /usr/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb devices
Traceback (most recent call last):
  File "start.py", line 88, in <module>
    run_case(app_name)
  File "start.py", line 38, in run_case
    device_pre(app_name)
  File "start.py", line 13, in device_pre
    connect_device(url)
  File "/usr/lib/python2.7/site-packages/airtest/core/api.py", line 46, in connect_device
    dev = cls(uuid, **params)
  File "/usr/lib/python2.7/site-packages/airtest/core/android/android.py", line 31, in __init__
    self.serialno = serialno or ADB().devices(state="device")[0][0]
  File "/usr/lib/python2.7/site-packages/airtest/core/android/adb.py", line 196, in devices
    output = self.cmd("devices", device=False)
  File "/usr/lib/python2.7/site-packages/airtest/core/android/adb.py", line 167, in cmd
    proc = self.start_cmd(cmds, device)
  File "/usr/lib/python2.7/site-packages/airtest/core/android/adb.py", line 146, in start_cmd
    stderr=subprocess.PIPE
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by adolli** [comment]
pypi的默认把可执行文件的权限都去掉了，麻烦运行一下下面的命令
```bash
chmod +x /usr/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb
```

**Comment by ASmallListener** [comment]
谢谢，解决了！
