### ISSUE TITLE
同样的代码，.air脚本可以运行，但使用.py项目提示'NoneType' object has no attribute 'snapshot'

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/Airtest#531]
*(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
代码如下方截图，两个脚本**代码结构是相同的**。我试图将变量封装起来再给类方法直接调用，在.air脚本中没有任何问题，但是在纯py项目中遇到了如下报错：
```
[Start running..]
[04:24:25][INFO]<airtest.core.api> Try finding:
Template(tpl1568881114580.png)
Traceback (most recent call last):
  File "D:\workspace\test\test.py", line 14, in <module>
    TEST.touchWinButton()
  File "D:\workspace\test\test.py", line 12, in touchWinButton
    touch(TEST.win)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\utils\logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\api.py", line 257, in touch
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\utils\logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\cv.py", line 59, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
AttributeError: 'NoneType' object has no attribute 'snapshot'
[Finished]
```
纯.py脚本中的图片与.py文件在同一目录下（test\test.py和test\picture,png）

看起来问题原因是被我封装起来的图片没有snapshot属性？但具体原因是什么呢？
**有什么方法能够让这个纯.py脚本像.air脚本一样正常运行呢？**

**相关截图**
![air脚本](https://user-images.githubusercontent.com/42226268/65227937-20e4f380-dafc-11e9-9c81-ae093ab226a3.png)
![纯py项目](https://user-images.githubusercontent.com/42226268/65227941-22aeb700-dafc-11e9-9451-048f6eae9115.png)

**python 版本:** `python3.6.8`

**airtest 版本:** `1.1.0`

**设备:**
 - 系统: windows7 x64
 - (别的信息)

**Comment by dinghongyi** [comment]
请参考
http://airtest.netease.com/docs/cn/3_record_script/0_script_faq.html#air-py
进行配置

**Comment by niuniuprice** [comment]
> 请参考
> http://airtest.netease.com/docs/cn/3_record_script/0_script_faq.html#air-py
> 进行配置

配置完成后可以运行脚本。
但是另一个问题出现了，我想在demo.air中引入test.py，但是却发现不能引入，这是为什么呢
![air脚本](https://user-images.githubusercontent.com/42226268/65236614-8ee4e700-db0b-11e9-9ba5-a4ace994954a.png)
![纯py项目](https://user-images.githubusercontent.com/42226268/65236616-90161400-db0b-11e9-9914-524feaf0f6c1.png)

报错信息如下：
[Start running..]
save log in 'C:\Users\user\AppData\Local\Temp\AirtestIDE\scripts\b86215d533d4dedf202e5c95e19c5bf9'
custom setup
[06:29:31][DEBUG]<airtest.core.api> using path: ../../workspace\test
custom tearDown
======================================================================
ERROR: runTest (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "D:\workspace\demo.air\demo.py", line 9, in <module>
    from test import TEST2
ImportError: cannot import name 'TEST2'

----------------------------------------------------------------------
Ran 1 test in 0.256s

FAILED (errors=1)
[Finished]

**Comment by niuniuprice** [comment]
尝试采用AirtestIDE_V1.2.2自有环境运行脚本，情况如下：
1. air脚本引用包含py文件的目录，**不加入**配置代码`from airtest.cli.parser import cli_setup`
`if not cli_setup():
    auto_setup(__file__,logdir='./log',devices=['Windows:///'])`可以成功调用py文件中封装的函数，但是py文件单独运行会报错。若加上此段配置代码，则会报错，报错信息如下：

[Start running..]
save log in 'C:\Users\user\AppData\Local\Temp\AirtestIDE\scripts\7bb817611d2490f76d809a2f64c882b7'
['airtest', 'D:\\workspace\\project\\demo.air', '--device', 'Windows:///', '--log', 'C:\\Users\\user\\AppData\\Local\\Temp\\AirtestIDE\\scripts\\7bb817611d2490f76d809a2f64c882b7']
usage: airtest [-h] [--device [DEVICE]] [--log [LOG]]
               [--recording [RECORDING]]
               script
airtest: error: unrecognized arguments: D:\workspace\project\demo.air
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 61, in runTest
  File "D:\workspace\project\demo.air\demo.py", line 9, in <module>
    from test import ABCD
  File "../../project\test\test.py", line 7, in <module>
    if not cli_setup():
  File "airtest\cli\parser.py", line 51, in cli_setup
  File "argparse.py", line 1737, in parse_args
  File "argparse.py", line 2393, in error
  File "argparse.py", line 2380, in exit
SystemExit: 2

----------------------------------------------------------------------
Ran 1 test in 0.585s

FAILED (errors=1)
[Finished]



2. air脚本引用air脚本（在py文件的目录名最后添加“.air”），可以成功运行。**但运行速度明显变慢了很多**


若采用python3.6.8+airtest1.1.0本地环境运行脚本，无论是引用py文件还是引用air脚本都会报错，如下：

[Start running..]
save log in 'C:\Users\user\AppData\Local\Temp\AirtestIDE\scripts\7bb817611d2490f76d809a2f64c882b7'
custom setup
[09:11:33][DEBUG]<airtest.core.api> using path: ../../project\test.air
custom tearDown
======================================================================
ERROR: runTest (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "D:\workspace\project\demo.air\demo.py", line 9, in <module>
    from test import ABCD
ImportError: cannot import name 'ABCD'

----------------------------------------------------------------------
Ran 1 test in 0.250s

FAILED (errors=1)
[Finished]


air脚本代码如下：
![air脚本](https://user-images.githubusercontent.com/42226268/65291769-63074700-db87-11e9-8fdf-a2989ec2e681.png)
py文件如下：
![纯py项目](https://user-images.githubusercontent.com/42226268/65291773-6a2e5500-db87-11e9-8404-1663de8de327.png)
项目结构如下：
![项目结构](https://user-images.githubusercontent.com/42226268/65291784-70bccc80-db87-11e9-907d-1c1b32ecab44.png)

**Comment by dinghongyi** [comment]
你好，using里要完整的文件名，请参考
http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html?highlight=project_root#air

**Comment by niuniuprice** [comment]
> 你好，using里要完整的文件名，请参考
> http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html?#air

对的，我是按照using('xxx.air')进行引入的，但是截图的test.py只是一个纯py项目。。。我把它改成.air脚本的时候是用using('test.air')的

**Comment by niuniuprice** [comment]
> 你好，using里要完整的文件名，请参考
> http://airtest.netease.com/docs/cn/9_faq/3_api_faq.html?#air

如果是一个air脚本引用另一个air脚本，使用python3.6.8+airtest1.1.0的本地环境是无法运行的
![air脚本](https://user-images.githubusercontent.com/42226268/65293352-90ef8a00-db8d-11e9-9e6c-e812327ea82d.png)
![纯py项目](https://user-images.githubusercontent.com/42226268/65293354-9220b700-db8d-11e9-9ebf-2485ae33f059.png)

但是用AirtestIDE_V1.2.2的自带环境可以运行

**Comment by yimelia** [comment]
ST.PROJECT_ROOT如果改写成绝对路径看看？

**Comment by niuniuprice** [comment]
> ST.PROJECT_ROOT如果改写成绝对路径看看？

之前已经试过了，但是本地环境仍然不行
![image](https://user-images.githubusercontent.com/42226268/65294129-3dcb0680-db90-11e9-81f8-a6a0b428273d.png)

报错信息是这样的：
[Start running..]
save log in 'C:\Users\user\AppData\Local\Temp\AirtestIDE\scripts\7bb817611d2490f76d809a2f64c882b7'
custom setup
[10:19:13][DEBUG]<airtest.core.api> using path: D:/workspace/project\test.air
custom tearDown
======================================================================
ERROR: runTest (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "D:\workspace\project\demo.air\demo.py", line 9, in <module>
    from test import ABCD
ImportError: cannot import name 'ABCD'

----------------------------------------------------------------------
Ran 1 test in 0.245s

FAILED (errors=1)
[Finished]

**Comment by dinghongyi** [comment]
using跟的是路径名，按你的截图应该就是using("test").
尝试把test.py这个文件名改成其他的试试。

**Comment by niuniuprice** [comment]
> using跟的是路径名，按你的截图应该就是using("test").
> 尝试把test.py这个文件名改成其他的试试。

改了文件名之后**没有问题了**：
把test.py改成testABC.py，文件夹名字也相应修改，using('testABC')可以引用。
把文件夹改为testABC,air，test.py改为testABC.py，using('testABC.air')也可以引用。


难道是因为之前用test这个名字太特殊。。。。总感觉升级了就会有奇奇怪怪的问题
