### ISSUE TITLE
夜神模拟器报 ImportError: sys.meta_path is None, Python is likely shutting down

### ISSUE THREAD

**Issue by yang152412** [AirtestProject/Airtest#539]
**描述问题bug**

用同一个测试脚本，IDE 可以正常结束，脚本执行的话，测试都可以正常执行，但是 结束后会报 `ImportError: sys.meta_path is None, Python is likely shutting down` 这个错

执行命令
```
 airtest run example/ddmc-android.air --device Android://127.0.0.1:5037/127.0.0.1:62001?cap_method=JAVACAP --log ./log
```
```
[09:00:56][DEBUG]<airtest.core.android.adb> /Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:62001 forward --remove tcp:18749
[09:00:56][DEBUG]<airtest.core.android.adb> /Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:62001 forward --remove tcp:14005
[09:00:56][DEBUG]<airtest.core.android.adb> /Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 127.0.0.1:62001 forward --remove tcp:14449
Exception ignored in: <function RpcObjectProxy.__del__ at 0x11e5ab050>
Traceback (most recent call last):
  File "/Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/hrpc/object_proxy.py", line 114, in __del__
  File "/Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/hrpc/client.py", line 63, in evaluate
  File "/Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/hrpc/transport/http.py", line 23, in send
  File "/Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/requests/api.py", line 116, in post
  File "/Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/requests/api.py", line 60, in request
  File "/Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
  File "/Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/requests/sessions.py", line 700, in merge_environment_settings
  File "/Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/requests/utils.py", line 761, in get_environ_proxies
  File "/Users/Test/virtualenv_workspaces/airtest/lib/python3.7/site-packages/requests/utils.py", line 745, in should_bypass_proxies
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2610, in proxy_bypass
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2587, in proxy_bypass_macosx_sysconf
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 2534, in _proxy_bypass_macosx_sysconf
ImportError: sys.meta_path is None, Python is likely shutting down
```

**python 版本:** `python3.7`

**airtest 版本:** `1.1.0`

**设备:**
 - 型号: macmini
 - 系统: 10.14.6 
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yang152412** [comment]
发现问题了，在测试脚本中中写的有下面代码：

```
rootView = poco("*****"))
if rootView.exists():
	rootView.swipe([-0.037, -0.7021])
	sleep(0.5)
```
发现定义的 临时变量 `rootView` 必须要自己 del 掉，就不会有问题。否则就报错。
问题是这个 控件不是每次都能获取到，也是为了不报错，才加的判断，这个怎么解决？
