### ISSUE TITLE
PermissionError: [Errno 13] Permission denied when i try to run my script after updating to latest airtest 

### ISSUE THREAD

**Issue by anandplay17** [AirtestProject/Airtest#540]
Getting" PermissionError: [Errno 13] Permission denied" when ever i try to run the script after updating to the latest airtest sdk 

Full Logs:

[Start running..]
save log in '/private/var/folders/3r/j0yh54zj32b_pp_6336p9sx40000gp/T/AirtestIDE/scripts/dff549c0f447c77873cd7c1f4c743fb3'
[02:32:00][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 15a39912 wait-for-device
======================================================================
ERROR: setUpClass (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 130, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/api.py", line 113, in auto_setup
    connect_device(dev)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/api.py", line 63, in connect_device
    dev = init_device(platform, uuid, **params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/api.py", line 33, in init_device
    dev = cls(uuid, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/android.py", line 39, in __init__
    self.adb.wait_for_device()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/adb.py", line 290, in wait_for_device
    proc = self.start_cmd("wait-for-device")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/adb.py", line 151, in start_cmd
    stderr=subprocess.PIPE
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

**Comment by EraChen233** [comment]
try this
http://airtest.netease.com/docs/en/1_online_help/running_scripts.html?highlight=permission#running-scripts-in-the-local-python-environment
