### ISSUE TITLE
Unable to launch the script in android 9 getting the below error RuntimeError: unable to launch AndroidUiautomationPoco

### ISSUE THREAD

**Issue by anandplay17** [AirtestProject/Airtest#548]
save log in '/private/var/folders/3r/j0yh54zj32b_pp_6336p9sx40000gp/T/AirtestIDE/scripts/f643ec8dd315e2d641f7865d1a6b739b'
[02:27:10][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd wait-for-device
[02:27:10][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell getprop ro.build.version.sdk
custom setup
[02:27:11][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell dumpsys activity top
[02:27:11][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell dumpsys package com.netease.nie.yosemite
[02:27:11][INFO]<airtest.core.android.yosemite> local version code is 288, installed version code is 288
[02:27:11][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell settings get secure default_input_method
[02:27:11][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell ime list -a
[02:27:11][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell ime enable com.netease.nie.yosemite/.ime.ImeService
[02:27:11][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell ime set com.netease.nie.yosemite/.ime.ImeService
[02:27:11][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell dumpsys package com.netease.open.pocoservice
installed version is None, installer version is 41. force_reinstall=False
[02:27:11][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd install /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/drivers/android/lib/pocoservice-debug.apk
[02:27:14][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=True
[02:27:14][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd install -r /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/drivers/android/lib/pocoservice-debug-androidTest.apk
[02:27:15][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd forward --no-rebind tcp:16344 tcp:10080
[02:27:15][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd forward --no-rebind tcp:17793 tcp:10081
[02:27:15][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell ps
[02:27:16][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell am force-stop com.netease.open.pocoservice
[02:27:16][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell am start -n com.netease.open.pocoservice/.TestActivity
[02:27:16][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
[02:27:33][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell am force-stop com.netease.open.pocoservice
still waiting for uiautomation ready.
still waiting for uiautomation ready.still waiting for uiautomation ready.
[02:27:33][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner

still waiting for uiau[02:27:32][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell dumpsys package com.netease.open.pocoservice.test
tomation ready.installed version is 0, installer version is 0. force_reinstall=True

[02:27:28][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd uninstall com.netease.open.pocoservice
[02:27:29][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell dumpsys package com.netease.open.pocoservice
installed version is None, installer version is 41. force_reinstall=False
[02:27:29][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd install /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/drivers/android/lib/pocoservice-debug.apk
[02:27:32][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd install -r /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/drivers/android/lib/pocoservice-debug-androidTest.apk
[02:27:33][Dstill waiting for uiautomation ready.
EBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell am start -n com.netease.open.pocoservice/.TestActivity
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
still waiting for uiautomation ready.
[02:27:45][DEBUG]<airtest.core.android.adb> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -P 5037 -s 5ab2fefd shell dumpsys activity top
custom tearDown
======================================================================
ERROR: runTest (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/playsimplegames/qa_automation/wordwars1/ww_adb.air/ww_adb.py", line 11, in <module>
    android_poco = AndroidUiautomationPoco()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/drivers/android/uiautomation.py", line 206, in __init__
    raise RuntimeError("unable to launch AndroidUiautomationPoco")
RuntimeError: unable to launch AndroidUiautomationPoco

**Comment by yimelia** [comment]
try the following:
- Please turn off the network proxy Proxy connected to your PC or mobile phone.
- uninstall `pocoservice-debug.apk` and `pocoservice-debug-androidTest.apk`, and install them manually ( you can find them in path `/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/poco/drivers/android/lib` )
- if your phone is VIVO/OPPO, please set the `Yosemite` input method to the **default keyboard** and **current input method**

**Comment by zyq198764** [comment]
尝试了以上方法，在运行airtest脚本的时候还是报以上的错误，请麻烦尽快解决下
