### ISSUE TITLE
多台设备同时执行时，出现错误

### ISSUE THREAD

**Issue by ly1n** [AirtestProject/Airtest#549]
通过python直接运行时，出现设备未准备好的报错。
执行代码`python custom_launcher.py --y {y} --p {p} test.air --device Android://127.0.0.1:5037/{dev_id}`

```
ERROR: setUpClass (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\airtest\cli\runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "D:\ProgramData\Anaconda3\lib\site-packages\airtest\cli\runner.py", line 130, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root)
  File "D:\ProgramData\Anaconda3\lib\site-packages\airtest\core\api.py", line 113, in auto_setup
    connect_device(dev)
  File "D:\ProgramData\Anaconda3\lib\site-packages\airtest\core\api.py", line 63, in connect_device
    dev = init_device(platform, uuid, **params)
  File "D:\ProgramData\Anaconda3\lib\site-packages\airtest\core\api.py", line 33, in init_device
    dev = cls(uuid, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\airtest\core\android\android.py", line 39, in __init__
    self.adb.wait_for_device()
  File "D:\ProgramData\Anaconda3\lib\site-packages\airtest\core\android\adb.py", line 297, in wait_for_device
    raise DeviceConnectionError("device not ready")
airtest.core.error.DeviceConnectionError: 'device not ready'

----------------------------------------------------------------------
Ran 0 tests in 5.648s
```

出现这种错误之后，再重新执行多次，可能可以执行成功，报错的几率非常高

**Comment by ly1n** [comment]
`adb devices`可以显示设备，也能通过`adb -s {device id} shell`进入设备shell。
通过`custom_launcher.py`传入参数。通过设备号去运行指定设备。有时候可以成功执行，大部分情况下会出现上面的错误。重复执行多次，部分设备可能可以执行成功。

**Comment by ly1n** [comment]
python版本:  `Python 3.6.5 :: Anaconda, Inc.` 一些依赖都已安装

**Comment by yimelia** [comment]
直接在cmd里执行adb devices，看看是否有出现adb server重启的提示，有可能是因为机器上同时存在多个不同版本的adb导致冲突，所以在连手机的时候因为adb冲突所以连接失败

**Comment by ly1n** [comment]
> 直接在cmd里执行adb devices，看看是否有出现adb server重启的提示，有可能是因为机器上同时存在多个不同版本的adb导致冲突，所以在连手机的时候因为adb冲突所以连接失败

是的，发现了不同版本adb，更改之后偶尔还会出现这个问题，但频率和数量降低了很多。代码层面添加进程启动间隔之后，这个问题已经完好解决。
