### ISSUE TITLE
多线程无法执行问题

### ISSUE THREAD

**Issue by zzzbit** [AirtestProject/Airtest#558]
多线程无法执行问题

```
Exception in thread Thread-41:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "C:\Users\Administrator\AppData\Local\Temp\AirtestIDE\Scripts\untitled.air\untitled.py", line 43, in run
    pos = exists(goods_imgs[self.i])
  File "airtest\utils\logwraper.py", line 78, in wrapper
  File "airtest\core\api.py", line 411, in exists
  File "airtest\utils\logwraper.py", line 78, in wrapper
  File "airtest\core\cv.py", line 59, in loop_find
  File "airtest\core\android\android.py", line 222, in snapshot
  File "airtest\core\android\javacap.py", line 101, in get_frame_from_stream
ValueError: generator already executing
```

**Comment by yimelia** [comment]
多线程在截图上可能会有些问题，如果你不介意截图速度缓慢的话，可以考虑选择adb截图的模式（cap_method=ADB)
或者是改用多进程来运行。
