### ISSUE TITLE
[Connection Error] Sumsung GALAXY S4 I959

### ISSUE THREAD

**Issue by rockywhisper** [AirtestProject/Airtest#56]
[bug details](https://github.com/AirtestProject/AirtestIDE/issues/108)

``` python
Traceback (most recent call last):
File "app\plugins\device\android\android_client.py", line 167, in loadConnectedPhones
File "app\plugins\device\android\android_phone.py", line 77, in init
File "app\plugins\device\android\android_phone.py", line 103, in _initDev
File "airtest\core\android\android.py", line 463, in display_info
File "airtest\core\android\android.py", line 475, in get_display_info
File "airtest\utils\snippet.py", line 101, in ready_func
File "airtest\core\android\minicap.py", line 134, in get_display_info
File "airtest\core\android\adb.py", line 345, in shell
AdbShellError: stdout[] stderr[Segmentation fault
]
```

**Comment by Meteorix** [comment]
use adb to get orientation:

``
airtest run ... --device Android:///?ori_method=ADBORI
``
