### ISSUE TITLE
windows下使用自定义python环境无法运行

### ISSUE THREAD

**Issue by sherry0429** [AirtestProject/Airtest#566]
错误：

======================================================================
ERROR: setUpClass (__main__.CustomCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\customairtestpythonenv\venv\lib\site-packages\airtest\cli\runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "D:\customairtestpythonenv\venv\lib\site-packages\airtest\cli\runner.py", line 130, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root)
  File "D:\customairtestpythonenv\venv\lib\site-packages\airtest\core\api.py", line 113, in auto_setup
    connect_device(dev)
  File "D:\customairtestpythonenv\venv\lib\site-packages\airtest\core\api.py", line 63, in connect_device
    dev = init_device(platform, uuid, **params)
  File "D:\customairtestpythonenv\venv\lib\site-packages\airtest\core\api.py", line 32, in init_device
    cls = import_device_cls(platform)
  File "D:\customairtestpythonenv\venv\lib\site-packages\airtest\core\helper.py", line 108, in import_device_cls
    from airtest.core.win.win import Windows as cls
  File "D:\customairtestpythonenv\venv\lib\site-packages\airtest\core\win\__init__.py", line 4, in <module>
    from .win import Windows
  File "D:\customairtestpythonenv\venv\lib\site-packages\airtest\core\win\win.py", line 8, in <module>
    import win32api
ImportError: DLL load failed: 找不到指定的程序。

已经检查virtualenv中安装了airtest和pypiwin32，依然如此。

**Comment by sherry0429** [comment]
我自己通过把airtest下的一系列win32.pyc文件复制到venv/lib下解决了。

这个是不是应该写到文档里面，我在文档里好像没找见

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#python
在这里面有对应描述，可能是DLL文件的缺失导致的，你试一下：
![image](https://user-images.githubusercontent.com/6896468/67171271-e5826100-f3e8-11e9-89e1-2a1d3ef7675e.png)

**Comment by dinghongyi** [comment]
可以安装223版的pywin32
