### ISSUE TITLE
从正常模式切换到访客模式，代码执行过程出现|--   Remote Traceback   --|  java.lang.IllegalStateException: UiAutomation not connected!

### ISSUE THREAD

**Issue by bs111** [AirtestProject/Airtest#58]
```
D:\WebSafe\AndroidTest\venv\Scripts\python.exe D:/WebSafe/my-testflow/testflow/scripts/Setting_changeUserGuest.py
this testcase filename is "D:\WebSafe\my-testflow\testflow\scripts\Setting_changeUserGuest.py".
using "D:\WebSafe\my-testflow\testflow\scripts" as project root. This testcase is "PocoTestSuite"
testcase locates in "D:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\suite.py"
using "D:\WebSafe\my-testflow" as project root. This testcase is "Setting_changeUserGuest"
testcase locates in "D:\WebSafe\my-testflow\testflow\scripts\Setting_changeUserGuest.py"
log filename will be "D:\WebSafe\my-testflow\pocounit-results\testflow\scripts\Setting_changeUserGuest\Setting_changeUserGuest (for P200 8-1)\poco-result.log"
log filename will be "D:\WebSafe\my-testflow\pocounit-results\testflow\scripts\Setting_changeUserGuest\Setting_changeUserGuest (for P200 8-1)\metainfo.txt"
[12:39:53][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe devices
[12:39:53][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB wait-for-device
[12:39:53][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell getprop ro.build.version.sdk
[12:39:53][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell cat /proc/cpuinfo
[12:39:54][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell getprop ro.product.manufacturer
[12:39:54][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell df /data
[12:39:54][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
[12:39:54][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell dumpsys meminfo
[12:40:05][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell dumpsys SurfaceFlinger
[12:40:05][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell getprop ro.product.model
[12:40:05][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell dumpsys display
[12:40:06][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell dumpsys activity top
[12:40:06][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell settings get secure default_input_method
[12:40:06][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell ime list -a
[12:40:07][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell dumpsys package com.netease.open.pocoservice
installed version is None, installer version is 37. force_reinstall=False
[12:40:08][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB install D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\drivers\android\lib\pocoservice-debug.apk
[12:40:11][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=True
[12:40:11][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB install -r D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\drivers\android\lib\pocoservice-debug-androidTest.apk
[12:40:13][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB forward --no-rebind tcp:19202 tcp:10080
[12:40:13][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB forward --no-rebind tcp:11727 tcp:10081
[12:40:13][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell ps
[12:40:14][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell am force-stop com.netease.open.pocoservice
[12:40:14][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell am start -n com.netease.open.pocoservice/.TestActivity
[12:40:14][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell am instrument -w -e debug false -e class com.netease.open.pocoservice.InstrumentedTestAsLauncher com.netease.open.pocoservice.test/android.support.test.runner.AndroidJUnitRunner
still waiting for uiautomation ready.
[12:40:17][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell dumpsys package com.netease.nie.yosemite
[12:40:17][INFO]<airtest.core.android.yosemite> local version code is 281, installed version code is 281
[12:40:17][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell pm path com.netease.nie.yosemite
[12:40:19][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell CLASSPATH=/data/app/com.netease.nie.yosemite-0QA_3mVErBk-yinr6yR8uA==/base.apk exec app_process /system/bin com.netease.nie.yosemite.Recorder --stop-record
[12:40:20][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell pm path com.netease.nie.yosemite
[12:40:22][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell CLASSPATH=/data/app/com.netease.nie.yosemite-0QA_3mVErBk-yinr6yR8uA==/base.apk exec app_process -Dduration=1800 /system/bin com.netease.nie.yosemite.Recorder --start-record
[12:40:23][DEBUG]<airtest.utils.nbsp> [325818824]'Only support local recording.'
[12:40:24][DEBUG]<airtest.utils.nbsp> [325818824]'port:8686'
[12:40:24][DEBUG]<airtest.utils.nbsp> [325818824]'[OkHttp] sendRequest>>'
[12:40:24][DEBUG]<airtest.utils.nbsp> [325818824]'[OkHttp] sendRequest<<'
[12:40:24][DEBUG]<airtest.utils.nbsp> [325818824]'get current display size...'
[12:40:24][DEBUG]<airtest.utils.nbsp> [325818824]'get display size...'
D:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\case.py:187: UserWarning: Fail to start result emitter: "ScreenRecorder". You can report this error to the developers or just ignore it. Error message: 
"Traceback (most recent call last):
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\case.py", line 183, in run
    emitter.start()
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\result\record.py", line 39, in start
    self.started[udid] = self.start_device_recorder(udid, dev)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\result\record.py", line 64, in start_device_recorder
    success = device.start_recording()
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\android.py", line 506, in start_recording
    return self.recorder.start_recording(*args, **kwargs)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\utils\snippet.py", line 101, in ready_func
    return func(inst, *args, **kwargs)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\recorder.py", line 53, in start_recording
    raise RuntimeError("start recording error")
RuntimeError: start recording error
"
  .format(emitter.__class__.__name__, traceback.format_exc()))
[12:40:29][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell monkey -p com.android.settings -c android.intent.category.LAUNCHER 1
[12:40:31][DEBUG]<airtest.utils.logwraper> >start_app Time used: 1.603000s
[12:40:31][DEBUG]<airtest.utils.logwraper> function: {'time_used': 1.6030001640319824, 'args': ('com.android.settings',), 'name': 'start_app', 'ret': None, 'kwargs': {}}
[12:40:34][DEBUG]<airtest.utils.logwraper> >sleep Time used: 3.007000s
[12:40:34][DEBUG]<airtest.utils.logwraper> function: {'time_used': 3.006999969482422, 'args': (3,), 'name': 'sleep', 'ret': None, 'kwargs': {}}
[12:40:43][DEBUG]<airtest.utils.logwraper> >sleep Time used: 1.001000s
[12:40:43][DEBUG]<airtest.utils.logwraper> function: {'time_used': 1.001000165939331, 'args': (1,), 'name': 'sleep', 'ret': None, 'kwargs': {}}
EndOfStream: 325818824
[12:41:02][DEBUG]<airtest.utils.logwraper> >sleep Time used: 10.001000s
[12:41:02][DEBUG]<airtest.utils.logwraper> function: {'time_used': 10.000999927520752, 'args': (10,), 'name': 'sleep', 'ret': None, 'kwargs': {}}
[12:41:02][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell input keyevent HOME
[12:41:07][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell dumpsys package com.netease.nie.yosemite
[12:41:07][INFO]<airtest.core.android.yosemite> local version code is 281, installed version code is 281
[12:41:07][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell am start -a com.netease.nie.yosemite.ACTION_IDENTIFY
[12:41:08][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell input keyevent HOME
[12:41:13][DEBUG]<airtest.utils.logwraper> >wake Time used: 10.539000s
[12:41:13][DEBUG]<airtest.utils.logwraper> function: {'time_used': 10.539000034332275, 'args': (), 'name': 'wake', 'ret': None, 'kwargs': {}}
[12:41:13][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB shell input keyevent POWER
[12:41:17][DEBUG]<airtest.utils.logwraper> >keyevent Time used: 4.224000s
[12:41:17][DEBUG]<airtest.utils.logwraper> function: {'time_used': 4.223999977111816, 'args': ('POWER',), 'name': 'keyevent', 'ret': None, 'kwargs': {}}
ED:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\case.py:204: UserWarning: Fail to stop result emitter: "SiteSnapshot". You can report this error to the developers or just ignore it. Error message: 
"Traceback (most recent call last):
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\case.py", line 200, in run
    emitter.stop()
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\result\site_snapshot.py", line 22, in stop
    self.snapshot('caseEnd')
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\result\site_snapshot.py", line 28, in snapshot
    self.snapshot_screen(site_id)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\pocounit\result\site_snapshot.py", line 47, in snapshot_screen
    b64img, fmt = self.poco.snapshot()
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\pocofw.py", line 418, in snapshot
    return self.agent.screen.getScreen(width)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\drivers\android\uiautomation.py", line 78, in getScreen
    b64img = self.screen.getScreen(width)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\hrpc\object_proxy.py", line 88, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\hrpc\client.py", line 78, in evaluate
    raise RpcRemoteException(resp)
RpcRemoteException: java.lang.IllegalStateException: UiAutomation not connected!

|--   Remote Traceback   --|

java.lang.IllegalStateException: UiAutomation not connected!
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1096)
	at android.app.UiAutomation.takeScreenshot(UiAutomation.java:687)
	at com.netease.open.pocoservice.Screen.getScreen(Screen.java:39)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.netease.open.hrpc.backend.RpcServer.onRequest(RpcServer.java:170)
	at com.netease.open.hrpc.backend.RpcServer.serve(RpcServer.java:57)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:840)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
	at java.lang.Thread.run(Thread.java:764)


|--   Remote Traceback end   --|
"
  .format(emitter.__class__.__name__, traceback.format_exc()))

======================================================================
ERROR: runTest (__main__.Setting_changeUserGuest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/WebSafe/my-testflow/testflow/scripts/Setting_changeUserGuest.py", line 134, in runTest
    self.wakeUpToIdle()
  File "D:/WebSafe/my-testflow/testflow/scripts/Setting_changeUserGuest.py", line 104, in wakeUpToIdle
    scrollUI.scroll('vertical')
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\proxy.py", line 405, in scroll
    return self.focus(focus1).drag_to(self.focus(focus2), duration=duration)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\proxy.py", line 371, in drag_to
    target_pos = target.get_position()
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\proxy.py", line 507, in get_position
    x, y = self.attr('pos')
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\proxy.py", line 620, in attr
    nodes = self._do_query(multiple=False)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\proxy.py", line 755, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\poco\utils\hrpc\hierarchy.py", line 27, in select
    return self.selector.select(query, multiple)
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\hrpc\object_proxy.py", line 88, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "D:\WebSafe\AndroidTest\venv\lib\site-packages\hrpc\client.py", line 78, in evaluate
    raise RpcRemoteException(resp)
RpcRemoteException: java.lang.IllegalStateException: UiAutomation not connected!

|--   Remote Traceback   --|

java.lang.IllegalStateException: UiAutomation not connected!
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1096)
	at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:475)
	at com.netease.open.pocoservice.Dumper.getRoot(Dumper.java:30)
	at com.netease.open.pocoservice.Dumper.getRoot(Dumper.java:17)
	at com.netease.open.libpoco.sdk.Selector.getRoot(Selector.java:135)
	at com.netease.open.libpoco.sdk.Selector.select(Selector.java:37)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.netease.open.hrpc.backend.RpcServer.onRequest(RpcServer.java:170)
	at com.netease.open.hrpc.backend.RpcServer.serve(RpcServer.java:57)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:840)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
	at java.lang.Thread.run(Thread.java:764)


|--   Remote Traceback end   --|

----------------------------------------------------------------------
Ran 1 test in 84.523s

FAILED (errors=1)
[12:41:18][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB forward --remove tcp:19202
exiting.......
[12:41:18][DEBUG]<airtest.core.android.adb> D:\WebSafe\AndroidTest\venv\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s SS79FM99NRFQEMLB forward --remove tcp:11727

Process finished with exit code -1
```

**Comment by adolli** [comment]
airtest可以用，不受影响
