### ISSUE TITLE
魅族M15，调用start_app()接口未成功启动APP；

### ISSUE THREAD

**Issue by RonChu-01** [AirtestProject/Airtest#584]
cmd执行adb指令：adb -s 871QADSJKRL7R shell monkey -p packagename -c android.intent.category.LAUNCHER 1

报错如下：
java.lang.Exception: setActivityController() watcher:com.android.commands.monkey
.Monkey$ActivityController@19aecbc, monkey:true
        at android.app.ActivityManagerProxy.setActivityController(ActivityManage
rNative.java:5299)
        at com.android.commands.monkey.Monkey.getSystemInterfaces(Monkey.java:97
3)
        at com.android.commands.monkey.Monkey.run(Monkey.java:551)
        at com.android.commands.monkey.Monkey.main(Monkey.java:485)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:325)
Events injected: 1
java.lang.Exception: setActivityController() watcher:null, monkey:true
        at android.app.ActivityManagerProxy.setActivityController(ActivityManage
rNative.java:5299)
        at com.android.commands.monkey.Monkey.run(Monkey.java:684)
        at com.android.commands.monkey.Monkey.main(Monkey.java:485)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:325)

**Comment by yimelia** [comment]
请给出运行的airtest代码，以及运行到那行代码时报错的log内容

**Comment by RonChu-01** [comment]
运行过程中没有报错，所以在命令行中使用adb指令运行，报错如上图所示
运行的代码为：start_app(PKG)

**Comment by yimelia** [comment]
试一下传入activity来启动看看，也就是说adb指令是[这样](https://github.com/AirtestProject/Airtest/blob/master/airtest/core/android/adb.py#L1202)：
```
adb shell am start -n  package/package.activity
```
如何查看activity，可以参考[这个](https://www.cnblogs.com/by-dream/p/5157308.html)

**Comment by RonChu-01** [comment]
嗯 尝试过传入activity，仍然无法启动APP

**Comment by yimelia** [comment]
可能是魅族手机做了限制，可以尝试换一台手机试试

**Comment by RonChu-01** [comment]
好的 谢谢回答  这边暂时放弃这台设备了（使用同品牌的其它机型可以正常使用start_app()）
