### ISSUE TITLE
Could not create DC.

### ISSUE THREAD

**Issue by z929151231** [AirtestProject/Airtest#586]
长时间运行脚本，运行12个小时以上，就会报此错误

Could not create DC.

**Comment by z929151231** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\utils\logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\api.py", line 257, in touch
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\utils\logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\cv.py", line 59, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\win\win.py", line 114, in snapshot
    screen = screenshot(filename, self.handle)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\win\screen.py", line 47, in screenshot
    saveDC = mfcDC.CreateCompatibleDC()
win32ui.error: CreateCompatibleDC failed

**Comment by yimelia** [comment]
请根据issue模板，提供更多信息以帮助我们定位问题：
1. 长时间运行的脚本，是连接安卓手机/ios手机/安卓模拟器/windows窗口，还是什么？
2. 环境是windows还是mac，系统版本号是多少？32位还是64位？
3. 在AirtestIDE中长时间运行，还是在命令行中长时间运行？是一个脚本运行了12小时以上，还是多个脚本调度运行了12小时？请贴出实际运行的命令行
4. 是否使用了poco，还是纯airtest截图脚本

**Comment by z929151231** [comment]
1.连接 windows窗口
2.win7 64位
3.使用 python 命令运行
4.纯airtest截图脚本

**Comment by yimelia** [comment]
pip list 看一下你的airtest版本号是多少？
是一个脚本运行了12小时以上，还是多个脚本调度运行了12小时？请贴出实际运行的命令行

**Comment by z929151231** [comment]
单脚本运行  python runtest1.py

**Comment by yihleego** [comment]
这个问题在1.2.0版本也出现了，请问会修复吗？

**Comment by dinghao-8** [comment]
请问这个bug修复了吗？我当前使用的是1.3.5版本。封装airtest之后，长时间运行多个脚本之后会出现这个异常。
