### ISSUE TITLE
录制的数组结构，直接运行报错list index out of rang

### ISSUE THREAD

**Issue by daisy0o** [AirtestProject/Airtest#594]
**描述问题bug**
录制的数组结构，直接运行报错list index out of rang

脚本如下：
poco("Window").offspring("TabBar")[1].child("Button")[2].click()

控制台报错信息：
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 65, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 61, in runTest
  File "/Users/wangjing/Documents/apptest/apptest/iOS.air/iOS.py", line 51, in <module>
    poco("Window").offspring("TabBar")[1].child("Button")[2].click()
  File "/Applications/AirtestIDE.app/Contents/MacOS/poco/proxy.py", line 250, in __getitem__
    return self._sorted_children[item][0]
IndexError: list index out of range

**复现步骤**
1. 录制一个点击底部tab操作
2.点击运行

**预期效果**
可以正确点击到tab按钮

**python 版本:** `python3.5`

**airtest 版本:** `1.2.2`

**设备:**
 - 型号: iphone 7
 - 系统: 12.3.1

**Comment by yimelia** [comment]
直接生成的录制语句有时候在回放时不一定能够正确执行，因为不能完全保证每一次的界面信息都完全一致，建议手动修改代码，采用更不容易出错的语句来获取节点（例如通过唯一的节点id，或是不容易重复的节点属性来获取），请参考文档获取更多帮助：https://poco.readthedocs.io/zh_CN/latest/source/README.html#working-with-poco-objects
