### ISSUE TITLE
airtest连ios设备，一定要先打开xcode，test一下吗？手机里已经安装过wda了

### ISSUE THREAD

**Issue by daisy0o** [AirtestProject/Airtest#602]
**描述问题bug**
airtest连ios设备，一定要先打开xcode，test一下吗？手机里已经安装过wda了。而且一直要开着wda。

**相关截图**
报错信息：
[Errno 61] Connection refused
成功
bbs.air/2019-11-11 12:11:18log/http_//127_0_0_1_8102
airtest run bbs.air --device ios:///http://127.0.0.1:8102 --log bbs.air/2019-11-11 12:11:18log/http_//127_0_0_1_8102
airtest run bbs.air --device ios:///http://127.0.0.1:8102 --log bbs.air/2019-11-11 12:11:18log/http_//127_0_0_1_8102 /Users/wangjing/Documents/iosrun
waiting for connection
save log in 'bbs.air/2019-11-11 12:11:18log/http_//127_0_0_1_8102'
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 434 (serial: 555031b52b97ee0423f984d4d43d4685c4c3056a), port 8100
Error connecting to device!
retry to connect, error: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
accepted connection, fd = 4
waiting for connection
Number of available devices == 1
Requesting connecion to device handle == 434 (serial: 555031b52b97ee0423f984d4d43d4685c4c3056a), port 8100
Error connecting to device!
======================================================================
ERROR: setUpClass (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/airtest/cli/runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/airtest/cli/runner.py", line 130, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/airtest/core/api.py", line 113, in auto_setup
    connect_device(dev)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/airtest/core/api.py", line 63, in connect_device
    dev = init_device(platform, uuid, **params)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/airtest/core/api.py", line 33, in init_device
    dev = cls(uuid, **kwargs)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/airtest/core/ios/ios.py", line 83, in __init__
    self.rotation_watcher = RotationWatcher(self)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/airtest/core/ios/rotation.py", line 22, in __init__
    self.session = iosHandle.session
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/airtest/core/ios/ios.py", line 98, in session
    self.defaultSession = self.driver.session()
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/wda/__init__.py", line 252, in session
    sid = self.status()['sessionId']
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/wda/__init__.py", line 191, in status
    res = self.http.get('status')
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/wda/__init__.py", line 75, in httpdo
    response = requests.request(method, url, data=data, timeout=HTTP_TIMEOUT)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/wangjing/iosrun/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

----------------------------------------------------------------------
Ran 0 tests in 1.117s

FAILED (errors=1)
Report build Failed. File not found in dir bbs.air/2019-11-11 12:11:18log/http_//127_0_0_1_8102/log.txt

**复现步骤**
1. 连接ios，打开iOS-Tagent，test后，ios设备连接成功。http://127.0.0.1:8100/status 有设备信息。
2. 关掉iOS-Tagent，运行脚本，运行报错，设备连接失败

**预期效果**
是否一定依赖iOS-Tagent，必须一直打开iOS-Tagent。

**python 版本:** `python3.5`

**airtest 版本:** `1.2.2`

**设备:**
 - 型号: iphone7
 - 系统: 12.3.1

**Comment by EraChen233** [comment]
![image](https://user-images.githubusercontent.com/5961185/68565134-89fa3f00-048d-11ea-8332-aa6dd1ab5e68.png)

不要关
按照教程说的做
