### ISSUE TITLE
pip安装airtest速度非常慢

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/Airtest#621]
**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
我使用台式机（外接无线网卡）+pip+无翻墙下载airtest库，但下载速度非常慢，经常报超时错误
已经尝试将源更改为阿里云，速度无提高
将pip install命令的timeout系数设置为1000，也会慢到超时。。。
这是一个问题吗？能不能将它下载的速度尽量加快呢？我试过下载selenium、easygui等库也可以正常下载

下面是cmd控制台的错误信息
```
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 397, in _error_catcher
    yield
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 479, in read
    data = self._fp.read(amt)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\commands\install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 305, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\operations\prepare.py", line 195, in prepare_linked_requirement
    unpack_url(
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 1058, in unpack_url
    unpack_http_url(
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 920, in unpack_http_url
    from_path, content_type = _download_http_url(link,
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 1152, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 861, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\utils\hashes.py", line 75, in check_against_chunks
    for chunk in chunks:
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 829, in written_chunks
    for chunk in chunks:
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\utils\ui.py", line 156, in iter
    for x in it:
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 794, in resp_read
    for chunk in resp.raw.stream(
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 496, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 402, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

**python 版本:** `python3.7.2、python3.8.0均出现此问题

**airtest 版本:** `1.1.1

**设备:**
 - 系统: Windows 10 x64 1909

**Comment by Meteorix** [comment]
搜清华pip源




    发自网易邮箱大师


在2019年11月25日 22:17，niuniuprice 写道： (重要！问题分类)

图像识别、设备控制相关问题 -> 按下面的步骤

描述问题bug
我使用台式机（外接无线网卡）+pip+无翻墙下载airtest库，但下载速度非常慢，经常报超时错误
已经尝试将源更改为阿里云，速度无提高
将pip install命令的timeout系数设置为1000，也会慢到超时。。。
这是一个问题吗？能不能将它下载的速度尽量加快呢？我试过下载selenium、easygui等库也可以正常下载

下面是cmd控制台的错误信息
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 397, in _error_catcher
    yield
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 479, in read
    data = self._fp.read(amt)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\http\client.py", line 454, in read
    n = self.readinto(b)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\http\client.py", line 498, in readinto
    n = self.fp.readinto(b)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\commands\install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\legacy_resolve.py", line 305, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\operations\prepare.py", line 195, in prepare_linked_requirement
    unpack_url(
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 1058, in unpack_url
    unpack_http_url(
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 920, in unpack_http_url
    from_path, content_type = _download_http_url(link,
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 1152, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 861, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\utils\hashes.py", line 75, in check_against_chunks
    for chunk in chunks:
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 829, in written_chunks
    for chunk in chunks:
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\utils\ui.py", line 156, in iter
    for x in it:
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_internal\download.py", line 794, in resp_read
    for chunk in resp.raw.stream(
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)

  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 496, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\urllib3\response.py", line 402, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

python 版本: `python3.7.2、python3.8.0均出现此问题
airtest 版本: `1.1.1
设备:

系统: Windows 10 x64 1909


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/AirtestProject/Airtest/issues/621?email_source=notifications\u0026email_token=AA5BAXUCQAYGVMUJORKZML3QVPM6LA5CNFSM4JRJSYY2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H32NIPA",
"url": "https://github.com/AirtestProject/Airtest/issues/621?email_source=notifications\u0026email_token=AA5BAXUCQAYGVMUJORKZML3QVPM6LA5CNFSM4JRJSYY2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H32NIPA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#pip

**Comment by niuniuprice** [comment]
似乎使用清华源后无法下载对应版本的opencv

``ERROR: Could not find a version that satisfies the requirement opencv-contrib-python<=3.4.2.17 (from airtest) (from versions: 3.4.8.29, 4.1.2.30)
ERROR: No matching distribution found for opencv-contrib-python<=3.4.2.17 (from airtest)``

**Comment by yimelia** [comment]
python3.8可能没有对应的支持，建议降低python版本
