### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/xxxx/airtest/core/android/static/stf_libs/minitouch'

### ISSUE THREAD

**Issue by OnTheWay111** [AirtestProject/Airtest#622]
**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 

**描述问题bug**
**该问题偶然出现：**
用例运行到一半（之前有点击、有滑动操作），报错：OSError: [Errno 2] No such file or directory: '/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/static/stf_libs/minitouch'

该用例停止后，下一条用例继续执行没有该报错。

```
Traceback (most recent call last):
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/cmcm/itest/autoTestGame/CleanMaster_cn/testcases/virus_check_and_kill/install_CMB_4_14.air/install_CMB_4_14.py", line 27, in <module>
    import index_no_virus_4_1
  File "/home/cmcm/itest/autoTestGame/CleanMaster_cn/testcases/virus_check_and_kill/../virus_check_and_kill/index_no_virus_4_1.air/index_no_virus_4_1.py", line 21, in <module>
    moudle_begin()
  File "/home/cmcm/itest/autoTestGame/CleanMaster_cn/api/common_action.py", line 123, in moudle_begin
    import start_is_xiaomi_0_1
  File "/home/cmcm/itest/autoTestGame/CleanMaster_cn/testcases/virus_check_and_kill/../../testcases/Start/start_is_xiaomi_0_1.air/start_is_xiaomi_0_1.py", line 44, in <module>
    poco(text = '立即开启').click()
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/proxy.py", line 334, in click
    ret = self.poco.click(pos_in_percentage)
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/pocofw.py", line 252, in click
    ret = self.agent.input.click(pos[0], pos[1])
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/utils/airtest/input.py", line 65, in click
    touch(pos, duration=self.default_touch_down_duration)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/api.py", line 262, in touch
    G.DEVICE.touch(pos, **kwargs)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/android.py", line 340, in touch
    self.minitouch.touch(pos, duration=duration)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/utils/snippet.py", line 104, in ready_func
    method()
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/utils/snippet.py", line 115, in wrapper
    ret = func(inst, *args, **kwargs)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/minitouch.py", line 49, in install_and_setup
    self.install()
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/minitouch.py", line 88, in install
    local_minitouch_size = int(os.path.getsize(path))
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/static/stf_libs/minitouch'
```

**相关截图**
![image](https://user-images.githubusercontent.com/18527679/69699676-80c2d080-1123-11ea-84fa-49ea9e9c5ed0.png)
![image](https://user-images.githubusercontent.com/18527679/69699681-88827500-1123-11ea-80cc-026ece810d50.png)

**复现步骤**

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python2.7`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. 红米note4X]
 - 系统: [e.g. Android 7.0]
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
设备是红米note4X？
在执行到这一句之前，脚本执行了什么样的点击语句，是否成功执行？能否贴一下生成的报告截图？

**Comment by OnTheWay111** [comment]
不好意思，我看错了，执行这一步之前，没有点击操作，只是start_app
![image](https://user-images.githubusercontent.com/18527679/69701035-f1b7b780-1126-11ea-9594-0934d3f2a2da.png)

**Comment by yimelia** [comment]
几个问题麻烦都确认下，方便定位问题：

1. 手机是什么设备型号，什么安卓系统版本号
2. 直接用手机连上IDE后（connect按钮的下拉菜单里，请**不要勾选任何选项**），能否在IDE中使用鼠标进行操作？
3. 请贴一下运行脚本时使用的命令行出来看看

**Comment by ZJSonicMaster** [comment]
> 几个问题麻烦都确认下，方便定位问题：
> 
> 1. 手机是什么设备型号，什么安卓系统版本号
> 2. 直接用手机连上IDE后（connect按钮的下拉菜单里，请**不要勾选任何选项**），能否在IDE中使用鼠标进行操作？
> 3. 请贴一下运行脚本时使用的命令行出来看看

1. redmi note 4X, android7.0
2. 可以
3. `python -m airtest run /home/cmcm/itest/autoTestGame/CleanMaster_en/testcases/me_index/language_9_18.air --device Android://127.0.0.1:5037/stfpro2.stf.zxtest.com:15009 --log /home/cmcm/itest/cmautotest/web/build_game/62/3375/0/language_9_18.air_log`

**Comment by OnTheWay111** [comment]
> 几个问题麻烦都确认下，方便定位问题：
> 
> 1. 手机是什么设备型号，什么安卓系统版本号
> 2. 直接用手机连上IDE后（connect按钮的下拉菜单里，请**不要勾选任何选项**），能否在IDE中使用鼠标进行操作？
> 3. 请贴一下运行脚本时使用的命令行出来看看

**Comment by yimelia** [comment]
直接用IDE连设备+运行脚本时，命令行中输出的设备也是 `--device Android://127.0.0.1:5037/stfpro2.stf.zxtest.com:15009`么？

目前这个问题是因为，airtest在读取手机信息时拿到的内容可能为空（`adb shell getprop ro.product.cpu.abi`），可以在log里找一下这条指令，手工复制下来运行一遍看看

以及你们把单关闭了，意思是现在问题解决了吗？

**Comment by ZJSonicMaster** [comment]
> 直接用IDE连设备+运行脚本时，命令行中输出的设备也是 `--device Android://127.0.0.1:5037/stfpro2.stf.zxtest.com:15009`么？
> 
> 目前这个问题是因为，airtest在读取手机信息时拿到的内容可能为空（`adb shell getprop ro.product.cpu.abi`），可以在log里找一下这条指令，手工复制下来运行一遍看看
> 
> 以及你们把单关闭了，意思是现在问题解决了吗？

1. 使用stf服务
2. 因为是偶然发生事件，不能及时的运行`adb shell getprop ro.product.cpu.abi`。
3. 出现这个问题的原因是因为airtest在读取手机信息时拿到的内容可能为空导致minitouch参数不对而抛出的错误吗

**Comment by yimelia** [comment]
既然能远程连上手机，就可以运行adb shell指令吧。你们可以直接把log里面的那条`getprop ro.product.cpu.abi`指令完整复制出来，手工执行一遍看看效果。

出现这个错误的原因，是因为读取minitouch文件的路径出错了
```
OSError: [Errno 2] No such file or directory: '/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/static/stf_libs/minitouch'
```
它读取的路径拼写方式参考[源码](https://github.com/AirtestProject/Airtest/blob/master/airtest/core/android/minitouch.py#L85)

前面的STF路径是固定的，即`/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/static/stf_libs/`，接下来会根据你的手机是什么平台的，来寻找合适的文件，所以在这个目录下应该是这样的：
![image](https://user-images.githubusercontent.com/6896468/69707079-0189c880-1134-11ea-9fe0-d11bc72bd149.png)

你这里读取路径时少了一个层级，怀疑是获取`ro.product.cpu.abi`的时候没拿对数据，但是具体需要根据实际的环境进行排查，我只是猜测

**Comment by OnTheWay111** [comment]
应该是数据没拿对导致的，目前发现了几次，因为读取路径问题，导致的minitouch找不到的问题

**Comment by yimelia** [comment]
可能需要你们排查一下这个问题出现的原因，以及输出是否真的为空吧

**Comment by 447098173** [comment]
Huawei Mate 30 pro 也发现了这个问题
airtest.core.error.AdbError: stdout[b"adb: error: cannot stat 'c:\\users\\ext.chen.chen\\appdata\\local\\programs\\python\\python36\\lib\\site-packages\\airtest\\core\\android\\static\\stf_libs\\minicap-shared/aosp/libs/android-10/arm64-v8a/minicap.so': No such file or directory\r\n"] stderr[b'']

**Comment by yimelia** [comment]
@447098173 
你的问题和他们不一样，你这个是android10的兼容问题，可以参考 https://github.com/AirtestProject/Airtest/pull/618

**Comment by 447098173** [comment]
那请问Android10大概什么时候可以完全兼容呢？

**Comment by yimelia** [comment]
@447098173 
1. 如果现在需要使用Android10，可以pull一份https://github.com/AirtestProject/Airtest/pull/618 的代码下来试用，但是目前只能在脚本运行时使用，IDE需要等待下一个版本放出才支持。
2. minitouch不支持Android10，我们目前用ADB touch作为替代方案，但是远远不如minitouch好用
3. 目前也在寻求其他的替代方案，“完全兼容”的时间暂时不能确认。
