### ISSUE TITLE
远程连接设备，用例执行过程中设备断开，抛出DeviceConnectionError

### ISSUE THREAD

**Issue by ZJSonicMaster** [AirtestProject/Airtest#624]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
通过ip的方式连接设备，执行多条用例过程中出现尝试重启字样，然后设备就断开连接了（多次出现）
```
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/cli/runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/cli/runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/home/cmcm/itest/autoTestGame/CleanMaster_cn/testcases/virus_check_and_kill/install_CMB_4_14.air/install_CMB_4_14.py", line 27, in <module>
    import index_no_virus_4_1
  File "/home/cmcm/itest/autoTestGame/CleanMaster_cn/testcases/virus_check_and_kill/../virus_check_and_kill/index_no_virus_4_1.air/index_no_virus_4_1.py", line 41, in <module>
    poco(text = '应用在锁屏时偷偷耗电').wait_for_appearance(timeout = 15)
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/proxy.py", line 678, in wait_for_appearance
    while not self.exists():
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/proxy.py", line 774, in exists
    return self.attr('visible')
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/utils/retry.py", line 20, in wrapped
    raise ex
TransportDisconnected: HTTPConnectionPool(host='127.0.0.1', port=16275): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6efbc05350>: Failed to establish a new connection: [Errno 111] Connection refused',))

----------------------------------------------------------------------
Ran 1 test in 75.887s

FAILED (errors=1)
save log in '/home/cmcm/itest/cmautotest/web/build_game/26/3370/0/install_CMB_4_14.air_log'
installed version is 41, installer version is 41. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
installed version is 41, installer version is 41. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
installed version is 41, installer version is 41. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
installed version is 41, installer version is 41. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
installed version is 41, installer version is 41. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:14717
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/drivers/android/uiautomation.py", line 124, in run
    self.poco._start_instrument(self.port_to_ping)  # 尝试重启
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/drivers/android/uiautomation.py", line 247, in _start_instrument
    self.adb_client.shell(['am', 'force-stop', PocoServicePackage])
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 368, in shell
    out = self.raw_shell(cmd)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 326, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 185, in cmd
    raise DeviceConnectionError(stderr)
DeviceConnectionError: "error: device '10.60.132.245:5555' not found\n"

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/drivers/android/uiautomation.py", line 124, in run
    self.poco._start_instrument(self.port_to_ping)  # 尝试重启
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/drivers/android/uiautomation.py", line 247, in _start_instrument
    self.adb_client.shell(['am', 'force-stop', PocoServicePackage])
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 368, in shell
    out = self.raw_shell(cmd)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 326, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 185, in cmd
    raise DeviceConnectionError(stderr)
DeviceConnectionError: "error: device '10.60.132.245:5555' not found\n"

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/drivers/android/uiautomation.py", line 124, in run
    self.poco._start_instrument(self.port_to_ping)  # 尝试重启
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/drivers/android/uiautomation.py", line 247, in _start_instrument
    self.adb_client.shell(['am', 'force-stop', PocoServicePackage])
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 368, in shell
    out = self.raw_shell(cmd)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 326, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 185, in cmd
    raise DeviceConnectionError(stderr)
DeviceConnectionError: "error: device '10.60.132.245:5555' not found\n"

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/drivers/android/uiautomation.py", line 124, in run
    self.poco._start_instrument(self.port_to_ping)  # 尝试重启
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/drivers/android/uiautomation.py", line 247, in _start_instrument
    self.adb_client.shell(['am', 'force-stop', PocoServicePackage])
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 368, in shell
    out = self.raw_shell(cmd)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 326, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 185, in cmd
    raise DeviceConnectionError(stderr)
DeviceConnectionError: "error: device '10.60.132.245:5555' not found\n"

[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:13719
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/drivers/android/uiautomation.py", line 124, in run
    self.poco._start_instrument(self.port_to_ping)  # 尝试重启
  File "/home/cmcm/.local/lib/python2.7/site-packages/poco/drivers/android/uiautomation.py", line 247, in _start_instrument
    self.adb_client.shell(['am', 'force-stop', PocoServicePackage])
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 368, in shell
    out = self.raw_shell(cmd)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 326, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 185, in cmd
    raise DeviceConnectionError(stderr)
DeviceConnectionError: "error: device '10.60.132.245:5555' not found\n"

[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:17068
[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:12717
[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:15095
[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:16275
[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:11400
[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:11713
[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:15013
[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:17212
[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:16245
[12:12:59][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:18923
Exception hrpc.exceptions.TransportDisconnected: TransportDisconnected(ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=18923): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6efbd723d0>: Failed to establish a new connection: [Errno 111] Connection refused',))",),),) in <bound method RpcObjectProxy.__del__ of u'<Rpc remote object proxy of com.netease.open.libpoco.Node@991878>'> ignored
Exception hrpc.exceptions.TransportDisconnected: TransportDisconnected(ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=18923): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6efbd72310>: Failed to establish a new connection: [Errno 111] Connection refused',))",),),) in <bound method RpcObjectProxy.__del__ of u'<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@10c75db>'> ignored
run_result:  65280
/home/cmcm/itest/cmautotest/web/app/static/build_game/26/3370/0/install_CMB_4_14.log/log.html
----------------------------------------stop_current_app------------------------------------------------
dev.stop_current_app(para['device_serial'])
com.cleanmaster.mguard_cn
----------------------------------------stop_current_app------------------------------------------------
[12:13:03][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 shell am force-stop com.cleanmaster.mguard_cn
[12:13:03][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 shell am force-stop com.cleanmaster.mguard_cn
Traceback (most recent call last):
  File "/home/cmcm/itest/cmautotest/uiautotest/run_game_main.py", line 442, in <module>
    main()
  File "/home/cmcm/itest/cmautotest/uiautotest/run_game_main.py", line 438, in main
    operate_device()
  File "/home/cmcm/itest/cmautotest/uiautotest/run_game_main.py", line 398, in operate_device
    dev.stop_current_app(para['device_serial'])
  File "/home/cmcm/itest/cmautotest/uiautotest/run_game_main.py", line 126, in stop_current_app
    stop_app(self.run_name)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/api.py", line 160, in stop_app
    G.DEVICE.stop_app(package)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/android.py", line 147, in stop_app
    return self.adb.stop_app(package)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 1238, in stop_app
    self.shell(['am', 'force-stop', package])
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 368, in shell
    out = self.raw_shell(cmd)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 326, in raw_shell
    out = self.cmd(cmds, ensure_unicode=False)
  File "/home/cmcm/itest/cmautotest/uiautotest/airtest/core/android/adb.py", line 185, in cmd
    raise DeviceConnectionError(stderr)
airtest.core.error.DeviceConnectionError: "error: device '10.60.132.245:5555' not found\n"
[12:13:03][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:17484
[12:13:03][DEBUG]<airtest.core.android.adb> adb -P 5037 -s 10.60.132.245:5555 forward --remove tcp:14559
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**

**预期效果**
1. 设备断开连接的原因有哪些
2. 此次报错的原因可能性有哪些

**python 版本:** `python2.7`

**airtest 版本:** `1.0.69`

**设备:**
 - 型号: redmi note 4X
 - 系统: Android7.0
 - MIUI10.2.2

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
建议使用更稳定的接入方式，用wifi的话因为网络容易波动，很容易出现断连的问题
