### ISSUE TITLE
命令行执行airtest脚本报错

### ISSUE THREAD

**Issue by AdditionMultiplication** [AirtestProject/Airtest#625]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)

在airtestIDE中执行脚本运行正常，使用pycharm通过命令行方式执行脚本报错
（在这里粘贴traceback或其他报错信息）
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "E:\AirtestIDE_2019-09-10_py3_win64\workspaces\test.air\test.py", line 7, in <module>
    flag = exists(Template(r"E:\AirtestIDE_2019-09-10_py3_win64\workspaces\test.air\tpl1574993524470.png", record_pos=(0.003, -0.158), resolution=(1440, 810)))
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\utils\logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\api.py", line 411, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\utils\logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\cv.py", line 59, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\android\android.py", line 218, in snapshot
    screen = self.minicap.get_frame_from_stream()
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\android\minicap.py", line 24, in wrapper
    return func(inst, *args, **kwargs)
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\android\minicap.py", line 339, in get_frame_from_stream
    self.frame_gen = self.get_stream()
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\android\minicap.py", line 233, in get_stream
    stopped = next(gen)
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\android\minicap.py", line 247, in _get_stream
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\android\minicap.py", line 303, in _setup_stream_server
    params, display_info = self._get_params()
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\android\minicap.py", line 199, in _get_params
    display_info = self.ori_function()
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\android\android.py", line 546, in get_display_info
    display_info = self.minicap.get_display_info()
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\utils\snippet.py", line 106, in ready_func
    return func(inst, *args, **kwargs)
  File "E:\pycharm_professional\workspaces\test\venv\lib\site-packages\airtest\core\android\minicap.py", line 149, in get_display_info
    display_info = json.loads(display_info)
  File "E:\python3.7\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "E:\python3.7\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\python3.7\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------

**python 版本:** `python3.7`

**airtest 版本:** `1.1.1`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
在mumu,雷电，夜神模拟器上运行失败

**其他相关环境信息**
windows

**Comment by yimelia** [comment]
https://airtest.doc.io.netease.com/IDEdocs/run_script/1_useCommand_runScript/#_2

提问前，请尽量查阅一下文档，或者先百度一下
