### ISSUE TITLE
Can't launch test on Firebase Test Lab

### ISSUE THREAD

**Issue by Whiteseeker** [AirtestProject/Airtest#63]
Using Airtest version: 0.0.18 if I try to launch a test on FTL it crashes with that error:

```
java.lang.UnsatisfiedLinkError: Native method not found: org.libsdl.app.SDLActivity.nativeSetEnv:(Ljava/lang/String;Ljava/lang/String;)V
FATAL EXCEPTION: main
Process: com.netease.open.airbase, PID: 30796
java.lang.UnsatisfiedLinkError: Native method not found: org.libsdl.app.SDLActivity.nativeSetEnv:(Ljava/lang/String;Ljava/lang/String;)V
	at org.libsdl.app.SDLActivity.nativeSetEnv(Native Method)
	at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:169)
	at org.kivy.android.PythonActivity$UnpackFilesTask.onPostExecute(PythonActivity.java:116)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5633)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
	at dalvik.system.NativeStart.main(Native Method)
```
Which seems to happen in the test apk (not the game).
It seems to fail on all devices:
![screen shot 2018-05-23 at 9 51 12 am](https://user-images.githubusercontent.com/4581097/40413891-e011eb48-5e6e-11e8-8161-1f07258b9cca.png)

**Comment by zzldjkzxf** [comment]
This is caused of not supporting Android API 19. We had modified the minimum android version to 21.
