### ISSUE TITLE
Multi-machine collaboration not working, cannot run automatio script on two android devices using airtest

### ISSUE THREAD

**Issue by sushantoghosh** [AirtestProject/Airtest#663]
Remove any following parts if does not have details about

**Multi-machine collaboration not working**
A clear and concise description of what the bug is. Or paste traceback below.

code used

```
import subprocess
p = subprocess.Popen('adb devices', shell=True, stdout=subprocess.PIPE) 
output = str(p.stdout.read()).split()
output_len = len(output)
serialno1 = output[(output_len-4)]
serialno2 = output[(output_len-2)]


subprocess.call('airtest run /Users/sushanto/Documents/12.air --device Android:///{} --device Android:///{} --log /Users/sushanto/Documents/log_root/'.format(serialno1,serialno2), shell=True)

subprocess.call('airtest report /Users/sushanto/Documents/12.air --log_root /Users/sushanto/Documents/log_root/ --outfile /Users/sushanto/Documents/log_root/log.html --lang en', shell=True) 
```

```
adb server version (40) doesn't match this client (41); killing...
* daemon started successfully
[02:41:10][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5554 wait-for-device
[02:41:14][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5554 shell getprop ro.build.version.sdk
[02:41:14][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 wait-for-device
[02:41:14][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell getprop ro.build.version.sdk
[02:41:14][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb devices
[02:41:14][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb devices
[02:41:14][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5554 wait-for-device
[02:41:14][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5554 shell getprop ro.build.version.sdk
[02:41:14][WARNING]<airtest.core.api> Device:emulator-5554 updated <airtest.core.android.android.Android object at 0x109b76910> -> <airtest.core.android.android.Android object at 0x10a135350>
[02:41:14][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell input keyevent HOME
[02:41:15][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell dumpsys package com.netease.nie.yosemite
[02:41:15][INFO]<airtest.core.android.yosemite> local version code is 288, installed version code is 288
[02:41:15][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell am start -a com.netease.nie.yosemite.ACTION_IDENTIFY
[02:41:16][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell input keyevent HOME
[02:41:17][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell input keyevent HOME
[02:41:18][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell pm list packages
[02:41:19][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 uninstall com.winzo.gold
[02:41:25][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 install /Users/sushanto/winzo-code/WinzoApp/app/build/outputs/apk/goldStag/debug/app-gold-stag-debug.apk
[02:41:31][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell monkey -p com.winzo.gold -c android.intent.category.LAUNCHER 1
[02:41:42][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell dumpsys activity top
[02:41:42][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell dumpsys package com.netease.nie.yosemite
[02:41:42][INFO]<airtest.core.android.yosemite> local version code is 288, installed version code is 288
[02:41:42][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell settings get secure default_input_method
[02:41:43][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell ime list -a
[02:41:44][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell dumpsys package com.netease.open.pocoservice
[02:41:44][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell dumpsys package com.netease.open.pocoservice.test
[02:41:44][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 forward --no-rebind tcp:19394 tcp:10080
[02:41:44][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 forward --no-rebind tcp:13191 tcp:10081
[02:41:44][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell ps
[02:41:44][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 forward --no-rebind tcp:11374 tcp:5001
[02:41:44][INFO]<airtest.core.api> Try finding:
Template(/Users/sushanto/Documents/12.air/tpl1577567384659.png)
[02:41:44][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell pm path jp.co.cyberagent.stf.rotationwatcher
[02:41:45][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-1/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[02:41:45][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell ls /data/local/tmp/minicap
[02:41:45][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell ls /data/local/tmp/minicap.so
[02:41:45][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[02:41:45][DEBUG]<airtest.core.android.minicap> version:5
[02:41:45][DEBUG]<airtest.core.android.minicap> skip install minicap
[02:41:45][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 forward --no-rebind tcp:17776 localabstract:minicap_17776
[02:41:45][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[02:41:45][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell dumpsys window displays
[02:41:45][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_17776' -P 480x800@480x800/0 -l 2>&1
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'PID: 4477'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: Using projection 480x800@480x800/0'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_25.cpp:241) Creating SurfaceComposerClient'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_25.cpp:244) Performing SurfaceComposerClient init check'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_25.cpp:251) Creating virtual display'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_25.cpp:257) Creating buffer queue'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_25.cpp:262) Creating CPU consumer'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_25.cpp:266) Creating frame waiter'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_25.cpp:270) Publishing virtual display'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_25.cpp:287) Found 7.1 Developer Preview SurfaceComposerClient::setDisplaySurface'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 1154052 bytes for JPG encoder'
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:473) Server start'
[02:41:46][DEBUG]<airtest.core.android.minicap> (1, 24, 4477, 480, 800, 480, 800, 0, 2)
[02:41:46][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:475) New client connection'
[02:41:46][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[02:41:46][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell dumpsys window displays
[02:41:46][DEBUG]<airtest.core.api> try match with SURFMatching
[02:41:46][DEBUG]<airtest.aircv.keypoint_base> [SURF] threshold=0.7, result={'confidence': 0.8502045571804047, 'result': (352, 381), 'rectangle': [(238, 333), (238, 429), (466, 429), (466, 333)]}
[02:41:46][DEBUG]<airtest.aircv.keypoint_base> find_best_result() run time is 0.31 s.
[02:41:46][DEBUG]<airtest.core.api> match result: {'confidence': 0.8502045571804047, 'result': (352, 381), 'rectangle': [(238, 333), (238, 429), (466, 429), (466, 333)]}
[02:41:46][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell getprop ro.product.cpu.abi
[02:41:46][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell getprop ro.build.version.sdk
[02:41:47][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell ls /data/local/tmp/minitouch
[02:41:47][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell ls -l /data/local/tmp/minitouch
[02:41:47][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell rm /data/local/tmp/minitouch*
[02:41:47][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 push /Library/Python/2.7/site-packages/airtest/core/android/static/stf_libs/x86_64/minitouch /data/local/tmp/minitouch
[02:41:47][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell chmod 755 /data/local/tmp/minitouch
[02:41:47][INFO]<airtest.core.android.minitouch> install_minitouch finished
[02:41:47][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[02:41:47][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell dumpsys window displays
[02:41:47][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 forward --no-rebind tcp:16605 localabstract:minitouch_16605
[02:41:47][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell /data/local/tmp/minitouch -n 'minitouch_16605' 2>&1
[02:41:47][DEBUG]<airtest.utils.nbsp> [minitouch_server]'Note: device /dev/input/mice is not supported by libevdev'
[02:41:47][DEBUG]<airtest.utils.nbsp> [minitouch_server]'Type B touch device qwerty2 (32767x32767 with 10 contacts) detected on /dev/input/event1 (score 43776)'
[02:41:47][DEBUG]<airtest.utils.nbsp> [minitouch_server]'Connection established'
[02:41:47][DEBUG]<airtest.core.android.minitouch> minitouch header:'v 1\n^ 10 32767 32767 256\n$ 4517\n'
[02:41:49][INFO]<airtest.core.api> Try finding:
Template(/Users/sushanto/Documents/12.air/tpl1577567423840.png)
[02:41:49][DEBUG]<airtest.core.api> try match with SURFMatching
[02:41:49][DEBUG]<airtest.aircv.keypoint_base> [SURF] threshold=0.7, result={'confidence': 0.8869337141513824, 'result': (249, 734), 'rectangle': [(49, 686), (49, 782), (450, 782), (450, 686)]}
[02:41:49][DEBUG]<airtest.aircv.keypoint_base> find_best_result() run time is 0.23 s.
[02:41:49][DEBUG]<airtest.core.api> match result: {'confidence': 0.8869337141513824, 'result': (249, 734), 'rectangle': [(49, 686), (49, 782), (450, 782), (450, 686)]}
[02:41:49][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 shell am force-stop com.winzo.gold
----------------------------------------------------------------------
Ran 1 test in 41.619s
save log in '/Users/sushanto/Documents/log_root/'
installed version is 41, installer version is 41. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
[rpc]connected
test finished

OK
[02:41:52][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 forward --remove tcp:19394
[02:41:52][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 forward --remove tcp:13191
[02:41:52][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 forward --remove tcp:11374
[02:41:52][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 forward --remove tcp:17776
[02:41:52][DEBUG]<airtest.core.android.adb> /Library/Python/2.7/site-packages/airtest/core/android/static/adb/mac/adb -s emulator-5556 forward --remove tcp:16605
[02:41:52][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
Exception hrpc.exceptions.TransportDisconnected: TransportDisconnected(ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=13191): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x109b76910>: Failed to establish a new connection: [Errno 61] Connection refused',))",),),) in <bound method RpcObjectProxy.__del__ of u'<Rpc remote object proxy of [Lcom.netease.open.libpoco.sdk.AbstractNode;@f3a8237>'> ignored
/Users/sushanto/Documents/log_root/log.html
[Finished in 46.6s]
```

**To Reproduce**
1. code used is python
2. running the code only runs the automation script in one device only, check logs

**Expected behavior**
the automation script should run on both devices

**python version:** `python2.7`

**Smartphone (please complete the following information):**
 - Device: emulator

**Additional context**
I might be incorrect, please correct my python code if there is any mistake

Also, please let me know how to write the automation script to access multiple android devices

already tried, 

```
from airtest.core.api import connect_device
import subprocess
p = subprocess.Popen('adb devices', shell=True, stdout=subprocess.PIPE) 
output = str(p.stdout.read()).split()
output_len = len(output)
serialno1 = output[(output_len-4)]
serialno2 = output[(output_len-2)]

dev1 = connect_device("Android://127.0.0.1:5037/[%s]"%serialno1)  # Connect to the first phone
dev1 = connect_device("Android://127.0.0.1:5037/[%s]"%serialno2)  # Connect to the second phone

set_current(0)

set_current("serialno2")

```

**does not work***

logs:

```
============================================================

[Start running..]
Failed to execute ADB commands, please read [Docs](http://airtest.netease.com/docs/en/3_faq/android_connection.html)
save log in '/var/folders/tw/ft1z1z8x4_lddspjtcwdkn280000gn/T/AirtestIDE/scripts/61485f95733df6913ff0b7fcea1d95d2'
[02:58:47][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb devices
[02:58:47][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb devices
[02:58:47][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -s emulator-5554 wait-for-device
[02:58:47][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -s emulator-5554 shell getprop ro.build.version.sdk
[02:58:47][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb devices
[02:58:47][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb devices
[02:58:47][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -s emulator-5554 wait-for-device
[02:58:47][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -s emulator-5554 shell getprop ro.build.version.sdk
[02:58:47][WARNING]<airtest.core.api> Device:emulator-5554 updated <airtest.core.android.android.Android object at 0x10fadeeb8> -> <airtest.core.android.android.Android object at 0x10faf1470>
[02:58:47][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s [b'List] wait-for-device
======================================================================
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 65, in runTest
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/six.py", line 693, in reraise
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/cli/runner.py", line 61, in runTest
  File "/Users/sushanto/Documents/13.air/13.py", line 22, in <module>
    dev1 = connect_device("Android://127.0.0.1:5037/[%s]"%serialno1)  # Connect to the first phone
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 63, in connect_device
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/api.py", line 33, in init_device
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/android.py", line 39, in __init__
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/core/android/adb.py", line 297, in wait_for_device
airtest.core.error.DeviceConnectionError: 'device not ready'

----------------------------------------------------------------------
Ran 1 test in 5.500s

FAILED (errors=1)
[Finished]

```

**Comment by EraChen233** [comment]
Parameter --device is not used to run script on multiple devices.
We have provided a sample that may help you.
https://github.com/AirtestProject/multi-device-runner
