### ISSUE TITLE
mac脚本录制报错

### ISSUE THREAD

**Issue by hujiahong0313** [AirtestProject/Airtest#664]
mac  脚本录制报错，无法录制成功

[11:34:43][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s e0db60c0 forward --no-rebind tcp:18155 localabstract:minitouch_18155
[11:34:43][DEBUG]<airtest.core.android.adb> /Applications/AirtestIDE.app/Contents/MacOS/airtest/core/android/static/adb/mac/adb -P 5037 -s e0db60c0 shell /data/local/tmp/minitouch -n 'minitouch_18155' 2>&1
[11:34:43][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Type B touch device goodix_ts (1079x2339 with 21 contacts) detected on /dev/input/event3 (score 22608)'
[11:34:43][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Note: hard-limiting maximum number of contacts to 10'
[11:34:43][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Connection established'
[11:34:43][DEBUG]<airtest.core.android.minitouch> minitouch header:b'v 1\n^ 10 1079 2339 0\n$ 25229\n'
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/utils.py", line 103, in back_func
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/airtest/airtest_recorder.py", line 134, in record_swipe
  File "/Users/wjjn3033/dev/idestable/airtest-ide/app/plugins/airtest/airtest_recorder.py", line 163, in screen_record
  File "/Users/wjjn3033/dev/idestable/airtest/airtest/aircv/aircv.py", line 29, in imwrite
  File "/Users/wjjn3033/dev/idestable/venv_ide_qt511/lib/python3.6/site-packages/PIL/Image.py", line 1947, in save
NotADirectoryError: [Errno 20] Not a directory: '/Volumes/Transcend/TestMain/111112.py/tpl1577676887367.png'

**Comment by EraChen233** [comment]
麻烦根据题问模板给我们提供更多信息，否则无法复现、定位问题
