### ISSUE TITLE
Cant connect xiaomi devices / cant start multy device runner on xiaomi

### ISSUE THREAD

**Issue by Ufufniy** [AirtestProject/Airtest#679]
**Describe the bug**
Cant connect xiaomi devices / cant start multy device runner on xiaomi

```
If connect 
- D:\Autotests\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ff9f947 wait-for-device
- D:\Autotests\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ff9f947 shell getprop ro.build.version.sdk
- Device:ff9f947 updated <airtest.core.android.android.Android object at 0x0000020A8C20F748> -> <airtest.core.android.android.Android object at 0x0000020A8C209208>
- D:\Autotests\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ff9f947 shell ls /data/local/tmp/minicap
- D:\Autotests\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ff9f947 shell ls /data/local/tmp/minicap.so
- D:\Autotests\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ff9f947 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
- version:5
- skip install minicap
- D:\Autotests\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ff9f947 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
- D:\Autotests\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ff9f947 shell pm path jp.co.cyberagent.stf.rotationwatcher
- D:\Autotests\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ff9f947 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-Nx4XQUZF_ISiqzrZ4VTo-w==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
- D:\Autotests\AirtestIDE_2019-05-09_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s ff9f947 forward --no-rebind tcp:19213 localabstract:minicap_19213
- Failed to execute ADB commands, please read [Docs](http://airtest.netease.com/docs/en/3_faq/android_connection.html)

if start multy device runner (1 device)

- [rpc]connected
- [04:57:44][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 shell ls /data/local/tmp/minicap
- [04:57:44][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 shell ls /data/local/tmp/minicap.so
- [04:57:44][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
- [04:57:44][DEBUG]<airtest.core.android.minicap> version:5
- [04:57:44][DEBUG]<airtest.core.android.minicap> skip install minicap
- [04:57:44][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
- [04:57:45][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 shell dumpsys window displays
- [04:57:45][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 shell pm path jp.co.cyberagent.stf.rotationwatcher
- [04:57:45][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-Nx4XQUZF_ISiqzrZ4VTo-w==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
- [04:57:46][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 forward --no-rebind tcp:11733 localabstract:minicap_11733
- [04:57:46][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
- [04:57:47][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 shell dumpsys window displays
- [04:57:47][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_11733' -P 1080x2340@1080x2340/90 -l 2>&1
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 5863'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1080x2340@1080x2340/1'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'Vector<> have different types (this=0x7fd2f69250, rhs=0x7fd2f69370)'
- [04:57:47][DEBUG]<airtest.utils.nbsp> [minicap_server]b'Aborted'
- ======================================================================
- ERROR: runTest (airtest.cli.runner.AirtestCase)
- ----------------------------------------------------------------------
- Traceback (most recent call last):
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\cli\runner.py", line 65, in runTest
-     six.reraise(*sys.exc_info())
-   File "c:\users\avorobiev\appdata\local\programs\python\python36-32\lib\site-packages\six.py", line 693, in reraise
-     raise value
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\cli\runner.py", line 61, in runTest
-     exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
-   File "D:\Autotests\AirTest_poco\multi-device-runner-master\full_testRun_era.air\full_testRun_era.py", line 24, in <module>
-     poco("SkipButton").click()
-   File "D:\Autotests\AirTest_poco\Poco-master\poco\proxy.py", line 23, in wrapped
-     return func(proxy, *args, **kwargs)
-   File "D:\Autotests\AirTest_poco\Poco-master\poco\proxy.py", line 334, in click
-     ret = self.poco.click(pos_in_percentage)
-   File "D:\Autotests\AirTest_poco\Poco-master\poco\pocofw.py", line 252, in click
-     ret = self.agent.input.click(pos[0], pos[1])
-   File "D:\Autotests\AirTest_poco\Poco-master\poco\utils\airtest\input.py", line 81, in click
-     touch(pos, duration=self.default_touch_down_duration)
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\utils\logwraper.py", line 78, in wrapper
-     res = f(*args, **kwargs)
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\core\api.py", line 259, in touch
-     try_log_screen()
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\utils\logwraper.py", line 78, in wrapper
-     res = f(*args, **kwargs)
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\core\cv.py", line 97, in try_log_screen
-     screen = G.DEVICE.snapshot()
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\android.py", line 220, in snapshot
-     screen = self.minicap.get_frame_from_stream()
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\minicap.py", line 24, in wrapper
-     return func(inst, *args, **kwargs)
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\minicap.py", line 339, in get_frame_from_stream
-     self.frame_gen = self.get_stream()
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\utils\snippet.py", line 106, in ready_func
-     return func(inst, *args, **kwargs)
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\minicap.py", line 233, in get_stream
-     stopped = next(gen)
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\minicap.py", line 247, in _get_stream
-     proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
-   File "D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\minicap.py", line 312, in _setup_stream_server
-     raise RuntimeError("minicap server setup timeout")
- RuntimeError: minicap server setup timeout
- 
- ----------------------------------------------------------------------
- Ran 1 test in 124.776s
- 
- FAILED (errors=1)
- [04:57:52][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 forward --remove tcp:14670
- [04:57:52][DEBUG]<airtest.core.android.adb> D:\Autotests\AirTest_poco\Airtest-master\airtest\core\android\static\adb\windows\adb.exe -s ff9f947 forward --remove tcp:11733
- [04:57:52][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended
- full_testRun_era.air\log\ff9f947\log.html
- 
- Process finished with exit code 0
- 


```

1. run multi devices script / connect airtestIDE to the device
2. ???
3. Profit

**python version:** `python3.6.5`

**airtest version:** `1.1.1`

**Smartphone (please complete the following information):**
 - Xiaomi Redmi Note 7 / Mi Mix 2c
 - Android 9

**Additional context**
airtest stopped working with this devices (checked on the above), it worked fine before and I don’t understand what the problem is. this works if, I run the script for one device (and the application has already been launched earlier), but multi-launch and IDE refuse to work

**Comment by yimelia** [comment]
Now there are some problems with MIUI11, you cannot use `minicap`,  but you can use `javacap` instead. The current version of ·javacap· still has some problems on the horizontal screen, we'll update it as soon as possible

**Comment by yimelia** [comment]
Please download AirtestIDE 1.2.3, and upgrade your airtest to 1.1.3 and re-install the Yosemite.apk, then chose `use javacap` to use MIUI11.
