### ISSUE TITLE
@logwrap raise json exception

### ISSUE THREAD

**Issue by farosep** [AirtestProject/Airtest#704]
Tried to use something like this:

from airtest.core.helper import (G, delay_after_operation, import_device_cls,
                                 logwrap, set_logdir, using, log)
class My_class():
@logwrap
          def myfunction(self,myargements):
                     some actions
Exemple =  My_class()
Exemple.myfunction(argements)

Everytime get this:

Traceback (most recent call last):
  File "D:\python\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "D:\python\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\python\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "D:\AirtestIDE_2019-09-11_py3_win64\projects\DressUp\AirTestScripts\untitled.air\untitled.py", line 42, in <module>
    click("NPC")
  File "D:\python\lib\site-packages\airtest\utils\logwraper.py", line 71, in wrapper
    res = f(*args, **kwargs)
  File "D:\AirtestIDE_2019-09-11_py3_win64\projects\DressUp\AirTestScripts\untitled.air\untitled.py", line 41, in click
    click(name)
  File "D:\AirtestIDE_2019-09-11_py3_win64\projects\DressUp\AirTestScripts\untitled.air\untitled.py", line 40, in click
    Alt.click(name)
  File "D:\python\lib\site-packages\airtest\utils\logwraper.py", line 79, in wrapper
    logger.log('function', fndata)
  File "D:\python\lib\site-packages\airtest\utils\logwraper.py", line 50, in log
    log_data = json.dumps({'tag': tag, 'depth': depth, 'time': time.time(), 'data': data}, default=self._dumper)
  File "D:\python\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\python\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\python\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not type

I expect that my function would at Html report.

**python version:** `python3.6`

**airtest version:** `1.2.3`

**Comment by EraChen233** [comment]
If you want to record some information in the html report, there is a sample function in airtest:

```
from airtest.core.api import *
log("my msg")
```
