### ISSUE TITLE
三星A90录制自动化脚本视频时报错

### ISSUE THREAD

**Issue by Karlykj** [AirtestProject/Airtest#718]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
三星A90运行自动化测试脚本，录制运行视频的时候报错

```
[11:05:22][Step 1/1] Traceback (most recent call last):
[11:05:22][Step 1/1] save log in 'mud_test.air\log\samsung A90'
[11:05:22][Step 1/1]   File "C:\Users\mj\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 47, in tearDown
[11:05:22][Step 1/1]     dev.stop_recording(output)
[11:05:22][Step 1/1]   File "C:\Users\mj\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\android\android.py", line 648, in stop_recording
[11:05:22][Step 1/1]     return self.recorder.stop_recording(*args, **kwargs)
[11:05:22][Step 1/1]   File "C:\Users\mj\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\utils\snippet.py", line 107, in ready_func
[11:05:22][Step 1/1]     return func(inst, *args, **kwargs)
[11:05:22][Step 1/1]   File "C:\Users\mj\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\android\recorder.py", line 61, in stop_recording
[11:05:22][Step 1/1]     self.adb.pull('mnt/sdcard/' + self.adb.get_model() + '_test.mp4', output)
[11:05:22][Step 1/1]   File "C:\Users\mj\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\android\adb.py", line 444, in pull
[11:05:22][Step 1/1]     self.cmd(["pull", remote, local], ensure_unicode=False)
[11:05:22][Step 1/1]   File "C:\Users\mj\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\android\adb.py", line 194, in cmd
[11:05:22][Step 1/1]     raise AdbError(stdout, stderr)
[11:05:22][Step 1/1] airtest.core.error.AdbError: stdout[b"adb: error: failed to stat remote object 'mnt/sdcard/SM-A9080_test.mp4': No such file or directory\r\n"] stderr[b'']
[11:05:22][Step 1/1] ======================================================================
[11:05:22][Step 1/1] ERROR: runTest (airtest.cli.runner.AirtestCase)
[11:05:22][Step 1/1] ---------------------------------------------------------------------
```
![image](https://user-images.githubusercontent.com/63385011/78856265-dce61b80-7a58-11ea-95df-8ab5291ded46.png)

**python 版本:** `python3.6`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: 三星A90 5g
 - 系统: [e.g. Android 9]
 - (别的信息)

**其他相关环境信息**
(在windows上正常。)

**Comment by yimelia** [comment]
用adb shell进入手机的`/mnt/sdcard/`这个目录下面看看有没有mp4文件？

**Comment by Karlykj** [comment]
> 用adb shell进入手机的`/mnt/sdcard/`这个目录下面看看有没有mp4文件？

已经解决了，谢谢大佬
