### ISSUE TITLE
在pycharm运行网页测试脚本时报错

### ISSUE THREAD

**Issue by Karlykj** [AirtestProject/Airtest#725]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
在pycharm下运行网页自动化测试脚本时报错，但是在IDE中可以运行通过，报错如下
![image](https://user-images.githubusercontent.com/63385011/79541813-16540200-80bd-11ea-8587-d94377edf4d4.png)
Traceback (most recent call last):
  File "E:/mud_auto_test/test_cases/micro_functions/cheat.py", line 14, in <module>
    driver.get("http://www.baidu.com")
  File "C:\Users\mj\AppData\Roaming\Python\Python36\site-packages\airtest\utils\logwraper.py", line 71, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\mj\AppData\Roaming\Python\Python36\site-packages\airtest\utils\selenium_proxy.py", line 69, in get
    log({"args": address})
  File "C:\Users\mj\AppData\Roaming\Python\Python36\site-packages\airtest\core\helper.py", line 84, in log
    raise TypeError("arg must be Exception or string")
TypeError: arg must be Exception or string

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**

**预期效果**
预期结果：开网页后，马上关闭网页
实际结果：打开网页后控制台报错

**python 版本:** `python3.6.8`

**airtest 版本:** `1.0.69`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: pc
 - 系统: win10
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
更新你本地python环境的airtest版本到最新
