### ISSUE TITLE
脚本启动时 pywintypes.error: (127, 'SetCursorPos', '找不到指定的程序。')

### ISSUE THREAD

**Issue by ErickJiang** [AirtestProject/Airtest#727]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题
脚本启动时 pywintypes.error: (127, 'SetCursorPos', '找不到指定的程序。')

**描述问题bug**
在windows10 64bit的环境下运行脚本失败，失败的原因LOG如下：
[Start running..]
D:\AirtestIDE_2020-01-21_py3_win64\pywinauto\application.py:1032: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
[888] Failed to execute script AirtestIDE
Traceback (most recent call last):
  File "AirtestIDE.py", line 82, in <module>
  File "AirtestIDE.py", line 58, in main
  File "app\widgets\code_runner\tracer.py", line 72, in run_pyfile
  File "D:\AirtestIDE_2020-01-21_py3_win64\elsword\buyma.py", line 26, in <module>
    touch(_i)
  File "airtest\utils\logwraper.py", line 71, in wrapper
  File "airtest\core\api.py", line 265, in touch
  File "D:\AirtestIDE_2020-01-21_py3_win64\airtest\core\win\win.py", line 250, in touch
    self.mouse.move(coords=(end_x, end_y))
  File "site-packages\pywinauto\mouse.py", line 232, in move
  File "site-packages\pywinauto\mouse.py", line 125, in _perform_click_input
pywintypes.error: (127, 'SetCursorPos', '找不到指定的程序。')
no cmdline args
start...
[Finished]
```

```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
1. 设定好脚本视窗
2. 启动脚本
3. BUG发生

**预期效果**
预期脚本正常运作

**python 版本:** 
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32

**airtest 版本:** 
1.2.3

**设备:**
Window10 64Bit

**其他相关环境信息**
version
pypiwin32==223
pywin32==227
pywinauto==0.6.8

**Comment by yimelia** [comment]
这个是因为没有权限点击，用管理员身份启动AirtestIDE即可
