### ISSUE TITLE
static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE wait-for-device Permission Denied,while adb devices command can list devices correctly

### ISSUE THREAD

**Issue by oakpromise** [AirtestProject/Airtest#73]
xxtest@xxtest-server:~/workspace/airscript$ adb devices
List of devices attached
VS7STS6TUKAU5TBE        device
```
xxtest@xxtest-server:~/workspace/airscript$ airtest run main_ui.air  --device Android://127.0.0.1:5037/VS7STS6TUKAU5TBE 
[08:56:38][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE wait-for-device
======================================================================
ERROR: setUpClass (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/cli/runner.py", line 37, in setUpClass
    connect_device(dev)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/api.py", line 46, in connect_device
    dev = cls(uuid, **params)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/android.py", line 38, in __init__
    self.adb.wait_for_device()
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/adb.py", line 283, in wait_for_device
    proc = self.start_cmd("wait-for-device")
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/adb.py", line 147, in start_cmd
    stderr=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

----------------------------------------------------------------------
Ran 0 tests in 0.019s

FAILED (errors=1)
```

**Comment by adolli** [comment]
on mac please grant excutable permission manually.
```bash
sudo chmod +x /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb
```

**Comment by IcyW** [comment]
> on mac please grant excutable permission manually.
> 
> ```shell
> sudo chmod +x /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb
> ```

# macOS
cd your_python_path/site-packages/airtest/core/android/static/adb/mac
# linux
cd your_python_path/site-packages/airtest/core/android/static/adb/linux
chmod +x adb

ref: http://airtest.netease.com/docs/en/1_online_help/running_scripts.html?highlight=permission#running-scripts-in-the-local-python-environment
