### ISSUE TITLE
1.1.3版本脚本录制视频，找不到对应的视频文件

### ISSUE THREAD

**Issue by weizhengxia** [AirtestProject/Airtest#732]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
脚本运行录制视频，没有生成对应的视频文件

```
[05:35:20][DEBUG]<airtest.core.android.adb> /usr/local/lib/python3.6/dist-packages/airtest/core/android/static/adb/linux/adb -s 008977ad7b89b98a pull mnt/sdcard/Nexus 5X_test.mp4 log/recording_0.mp4
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airtest/cli/runner.py", line 47, in tearDown
    dev.stop_recording(output)
  File "/usr/local/lib/python3.6/dist-packages/airtest/core/android/android.py", line 648, in stop_recording
    return self.recorder.stop_recording(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/airtest/utils/snippet.py", line 107, in ready_func
    return func(inst, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/airtest/core/android/recorder.py", line 61, in stop_recording
    self.adb.pull('mnt/sdcard/' + self.adb.get_model() + '_test.mp4', output)
  File "/usr/local/lib/python3.6/dist-packages/airtest/core/android/adb.py", line 444, in pull
    self.cmd(["pull", remote, local], ensure_unicode=False)
  File "/usr/local/lib/python3.6/dist-packages/airtest/core/android/adb.py", line 194, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[b"adb: error: failed to stat remote object 'mnt/sdcard/Nexus 5X_test.mp4': No such file or directory\n"] stderr[b'']
----------------------------------------------------------------------
Ran 1 test in 185.001s

```

**相关截图**
无

**复现步骤**
无

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.6.9`

**airtest 版本:** `1.1.3`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [ Nexus 5X ]
 - 系统: [ Android 8.1]
 - (别的信息)

**其他相关环境信息**
系统：ubuntu18.04
老版本airtest 1.1.0上脚本执行正常

**Comment by yimelia** [comment]
点开yosemite.apk，看看是不是提示需要给权限，新版本更新之后可能需要重新赋予一个录屏权限
用adb shell进入手机的/mnt/sdcard目录下，看看有没有对应的mp4文件？

**Comment by weizhengxia** [comment]
谢谢，在测试手机上重新赋予录屏权限，能正常录屏了
