### ISSUE TITLE
minicap server setup timeout，when run air script in Ubuntu

### ISSUE THREAD

**Issue by oakpromise** [AirtestProject/Airtest#74]
```
qatest@qatest-server:~/workspace/TestWeb$ airtest run "/home/qatest/workspace/TestWeb/static/airscript/main_ui.air"  --device Android://127.0.0.1:5037/VS7STS6TUKAU5TBE --log "/home/qatest/workspace/TestWeb/static/airscript/main_ui.air/log"
[10:41:20][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE wait-for-device
[10:41:20][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell getprop ro.build.version.sdk
save log in '/home/qatest/workspace/TestWeb/static/airscript/main_ui.air/log'
[10:41:20][DEBUG]<airtest.utils.logwraper> main_script: {'script': u'/home/qatest/workspace/TestWeb/static/airscript/main_ui.air'}
[10:42:20][DEBUG]<airtest.utils.logwraper> >sleep Time used: 60.060048s
[10:42:20][DEBUG]<airtest.utils.logwraper> function: {'time_used': 60.06004810333252, 'args': (60.0,), 'name': 'sleep', 'ret': None, 'kwargs': {}}
[10:42:20][INFO]<airtest.core.api> Try finding:
Template(/home/qatest/workspace/TestWeb/static/airscript/main_ui.air/tpl1524023386611.png)
[10:42:20][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-1.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell ls /data/local/tmp/minicap ; echo ---$?---
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell ls /data/local/tmp/minicap.so ; echo ---$?---
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[10:42:21][DEBUG]<airtest.core.android.minicap> version:5
[10:42:21][DEBUG]<airtest.core.android.minicap> skip install minicap
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE forward --no-rebind tcp:15923 localabstract:minicap_15923
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_15923' -P 1080x1920@1080x1920/90 -l 2>&1
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'PID: 28008'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: Using projection 1080x1920@1080x1920/1'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_19.cpp:246) Creating SurfaceComposerClient'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_19.cpp:249) Performing SurfaceComposerClient init check'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_19.cpp:256) Creating virtual display'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_19.cpp:262) Creating buffer queue'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_19.cpp:269) Creating CPU consumer'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_19.cpp:278) Creating frame waiter'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_19.cpp:282) Publishing virtual display'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 6268932 bytes for JPG encoder'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:473) Server start'
[10:42:21][DEBUG]<airtest.core.android.minicap> (1, 24, 28008, 1080, 1920, 1080, 1920, 1, 2)
[10:42:21][DEBUG]<airtest.core.android.minicap> quirk_flag found, going to resetup
[10:42:21][DEBUG]<airtest.core.android.minicap> minicap stream ends
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (/home/lxn3032/minicap_for_ide/jni/minicap/minicap.cpp:475) New client connection'
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE forward --remove tcp:15923
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE forward --no-rebind tcp:13577 localabstract:minicap_13577
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_13577' -P 1920x1080@1920x1080/0 -l 2>&1
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'PID: 28021'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: Using projection 1920x1080@1920x1080/0'
[10:42:21][DEBUG]<airtest.utils.nbsp> [minicap_server]'INFO: (external/MY_minicap/src/minicap_19.cpp:246) Creating SurfaceComposerClient'
[10:42:21][INFO]<airtest.core.android.rotation> update orientation None->1
[10:42:21][DEBUG]<airtest.core.android.adb> /home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/static/adb/linux/adb -P 5037 -s VS7STS6TUKAU5TBE shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[10:42:26][DEBUG]<airtest.utils.logwraper> error: {'traceback': 'Traceback (most recent call last):\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/utils/logwraper.py", line 78, in wrapper\n    res = f(*args, **kwargs)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/cv.py", line 42, in loop_find\n    screen = G.DEVICE.snapshot(filename=None)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/android.py", line 171, in snapshot\n    screen = self.minicap.get_frame_from_stream()\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 311, in get_frame_from_stream\n    self.frame_gen = self.get_stream()\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/utils/snippet.py", line 100, in ready_func\n    return func(inst, *args, **kwargs)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 217, in get_stream\n    next(gen)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 223, in _get_stream\n    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 288, in _setup_stream_server\n    raise RuntimeError("minicap server setup timeout")\nRuntimeError: minicap server setup timeout\n', 'name': 'loop_find', 'kwargs': {'timeout': 20}, 'time_used': 6.035845994949341, 'args': (Template(/home/qatest/workspace/TestWeb/static/airscript/main_ui.air/tpl1524023386611.png),), 'error_str': "RuntimeError('minicap server setup timeout',)"}
[10:42:26][DEBUG]<airtest.utils.logwraper> error: {'traceback': 'Traceback (most recent call last):\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/utils/logwraper.py", line 78, in wrapper\n    res = f(*args, **kwargs)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/helper.py", line 132, in wrapper\n    r = f(*args, **kwargs)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/api.py", line 239, in touch\n    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/utils/logwraper.py", line 78, in wrapper\n    res = f(*args, **kwargs)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/cv.py", line 42, in loop_find\n    screen = G.DEVICE.snapshot(filename=None)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/android.py", line 171, in snapshot\n    screen = self.minicap.get_frame_from_stream()\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 311, in get_frame_from_stream\n    self.frame_gen = self.get_stream()\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/utils/snippet.py", line 100, in ready_func\n    return func(inst, *args, **kwargs)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 217, in get_stream\n    next(gen)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 223, in _get_stream\n    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)\n  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 288, in _setup_stream_server\n    raise RuntimeError("minicap server setup timeout")\nRuntimeError: minicap server setup timeout\n', 'name': 'touch', 'kwargs': {}, 'time_used': 6.036949157714844, 'args': (Template(/home/qatest/workspace/TestWeb/static/airscript/main_ui.air/tpl1524023386611.png),), 'error_str': "RuntimeError('minicap server setup timeout',)"}
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/cli/runner.py", line 88, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath.encode(sys.getfilesystemencoding()), 'exec'), self.scope)
  File "/home/qatest/workspace/TestWeb/static/airscript/main_ui.air/main_ui.py", line 14, in <module>
    touch(Template(r"tpl1524023386611.png", record_pos=(-0.474, -0.142), resolution=(1920, 1080)))
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/utils/logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/helper.py", line 132, in wrapper
    r = f(*args, **kwargs)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/api.py", line 239, in touch
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/utils/logwraper.py", line 78, in wrapper
    res = f(*args, **kwargs)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/cv.py", line 42, in loop_find
    screen = G.DEVICE.snapshot(filename=None)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/android.py", line 171, in snapshot
    screen = self.minicap.get_frame_from_stream()
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 311, in get_frame_from_stream
    self.frame_gen = self.get_stream()
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/utils/snippet.py", line 100, in ready_func
    return func(inst, *args, **kwargs)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 217, in get_stream
    next(gen)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 223, in _get_stream
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
  File "/home/qatest/.local/lib/python2.7/site-packages/airtest/core/android/minicap.py", line 288, in _setup_stream_server
    raise RuntimeError("minicap server setup timeout")
RuntimeError: minicap server setup timeout

----------------------------------------------------------------------
Ran 1 test in 66.128s
```

**Comment by oakpromise** [comment]
this is fixed，there is a long-time sleep(300.0) in the air script, it becomes ok while remove the sheep action.
