### ISSUE TITLE
使用本地环境airtest-1.1.3，运行脚本，到report.py时提示'Namespace' object has no attribute 'compress'

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/Airtest#744]
**(重要！问题分类)**
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
用本地py环境的airtest-1.1.3运行脚本，自定义启动器运行到用report.py写报告时报错
提示'Namespace' object has no attribute 'compress'
之前在另一台电脑上运行脚本没有问题

```
ERROR: setUpClass (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\guo\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "D:\Users\guo\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 130, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root, args.compress)
AttributeError: 'Namespace' object has no attribute 'compress'



  File "D:/Users/guo/Desktop/myRunner.py", line 100, in run_air
    rpt.report("log_template.html", output_file=output_file)
  File "D:\Users\guo\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\report\report.py", line 475, in report
    data = self.report_data(output_file=output_file, record_list=record_list)
  File "D:\Users\guo\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\report\report.py", line 425, in report_data
    self._load()
  File "D:\Users\guo\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\report\report.py", line 82, in _load
    with io.open(logfile, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Users\\guo\\Desktop\\win7x64\\log\\2020年5月28日17时39分40秒开始的测试\\ApplyCert\\KX-T1722\\log.txt'
```

**python 版本:** `python3.6`

**airtest 版本:** `1.1.3`

**设备:**
 - 系统: windows7x64

**其他相关环境信息**
之前在另一台电脑上运行脚本没有问题

**Comment by yimelia** [comment]
最新版本增加了一个参数`compress`，在启动器里把这个参数加一下默认值就好了

**Comment by niuniuprice** [comment]
> 最新版本增加了一个参数`compress`，在启动器里把这个参数加一下默认值就好了


我按照上述方法在启动器中加了参数，可以运行了，但是运行到创建报告时弹出了以下报错

`Traceback (most recent call last):
  File "D:/Users/guo/Desktop/myRunner.py", line 133, in <module>
    test.run_air('..\\..\\testcase\\'+i, device,i)
  File "D:/Users/guo/Desktop/myRunner.py", line 100, in run_air
    rpt.report("log_template.html", output_file=output_file)
  File "D:\Users\guo\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\report\report.py", line 475, in report
    data = self.report_data(output_file=output_file, record_list=record_list)
  File "D:\Users\guo\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\report\report.py", line 429, in report_data
    info = json.loads(get_script_info(script_path))
  File "D:\Users\guo\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\info.py", line 28, in get_script_info
    with open(pyfilepath, encoding="utf-8") as pyfile:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Users\\guo\\Desktop\\win7x64\\testcase\\ApplyCert\\KX-T1722.air\\KX-T1722.py\\KX-T1722.py'
`


启动器中创建报告的代码如下：
`
import airtest.report.report as report
rpt = report.LogToHtml(script, log,lang='zh')
 rpt.report("log_template.html", output_file=output_file)
`

请问是哪里出了问题？

**Comment by IcyW** [comment]
> 最新版本增加了一个参数`compress`，在启动器里把这个参数加一下默认值就好了

compress参数是压缩报告图片用的吗？

**Comment by niuniuprice** [comment]
> > 最新版本增加了一个参数`compress`，在启动器里把这个参数加一下默认值就好了
> 
> compress参数是压缩报告图片用的吗？

是的，在run_script()中传入的参数里加入就可以了，可以翻看airtest升级到1.1.2的升级内容https://github.com/AirtestProject/Airtest/releases/tag/v1.1.2
