### ISSUE TITLE
命令行/iOS真机/运行脚本时报错 json.decoder.JSONDecodeError 

### ISSUE THREAD

**Issue by IcyW** [AirtestProject/Airtest#766]
**详细描述问题bug：**
```
======================================================================
ERROR: setUpClass (__main__.CustomAirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/airtest/cli/runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/airtest/cli/runner.py", line 130, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root, args.compress)
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/airtest/core/api.py", line 113, in auto_setup
    connect_device(dev)
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/airtest/core/api.py", line 63, in connect_device
    dev = init_device(platform, uuid, **params)
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/airtest/core/api.py", line 33, in init_device
    dev = cls(uuid, **kwargs)
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/airtest/core/ios/ios.py", line 86, in __init__
    self.rotation_watcher = RotationWatcher(self)
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/airtest/core/ios/rotation.py", line 22, in __init__
    self.session = iosHandle.session
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/airtest/core/ios/ios.py", line 101, in session
    self.defaultSession = self.driver.session()
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/wda/__init__.py", line 252, in session
    sid = self.status()['sessionId']
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/wda/__init__.py", line 191, in status
    res = self.http.get('status')
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/wda/__init__.py", line 77, in httpdo
    retjson = response.json()
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/xxx/anaconda3/envs/airtest_py3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 0 tests in 0.340s

FAILED (errors=1)
```
**复现步骤：**
参照了[5.3 Airtest的启动器介绍（试用）](http://airtest.netease.com/docs/cn/5_airtest_framework/3_launcherpy.html?highlight=%E5%90%AF%E5%8A%A8%E5%99%A8)
```
test.run_air(os.path.join(PROJECT_PATH, 'testcases/'), run_device=['ios:///http://127.0.0.1:8100'])
```

**python 版本:** `python3.x`

**操作系统:** `macOS Mojave 10.14.6`

**手机设备信息:**
 - 手机型号: iPhone 6Plus
 - iOS系统版本号:  11.1.1
-- | --

**其他相关信息补充**
(例如在linux ubuntu16.04上运行异常，在windows上正常等信息。)
- AirtestIDE版本号：1.2.0
- 当前操作系统、手机、脚本在AirtestIDE中能正常运行（系统python2.7），但命令行启动就如上报错（python3.7.7）。当前手机、脚本、命令行启动，在另一台macOS（相同系统），python3.6.9，也能正常运行。

**感谢解答**

**Comment by IcyW** [comment]
该问题已解决。。debug发现是请求localhost有问题，将bash_profile中的代理配置删去即可。
