### ISSUE TITLE
使用connect_device(uri)方法无法连接上手机

### ISSUE THREAD

**Issue by AxelHu** [AirtestProject/Airtest#768]
## 问题
在WIFI环境下，使用connect_device("android://adbhost:adbport/serialno?param=value&param2=value2")无法连接上手机

## 环境
- 网络 : 局域网 固定ip
- PC : Win10 ver 2004
- 手机 : Google Pixel4 XL Android 10
- python : 3.7
- adb : 39 40 41都测试过
- airtest : 1.1.3

### 使用的API
希望在局域网环境下对测试机进行操作，参考了airtest的[文档](http://airtest.netease.com/docs/cn/1_quick_start/2_test_with_Android_device.html#adb)
文档中提供了几种连接手机的方式
```
init_device("Android")
```
```
connect_device("android:///")
```
```
connect_device("android://adbhost:adbport/serialno?param=value&param2=value2")
```
前两种会使用当前连接的手机，第三种会连接指定ip的手机。测试的结果是，前两种可以正常连接，第三种无法连接。

#### 可以连接时
```
already connected to 192.168.1.227:5555
do not connect device
save log in 'D:\localSVN\trunk\testScripts\shell\airtest\log'
[10:52:03][DEBUG]<airtest.core.android.adb> c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe devices
[10:52:03][DEBUG]<airtest.core.android.adb> c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe devices
[10:52:03][DEBUG]<airtest.core.android.adb> c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.1.227:5555 get-state
[10:52:03][DEBUG]<airtest.core.android.adb> c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.1.227:5555 wait-for-device
[10:52:03][DEBUG]<airtest.core.android.adb> c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 192.168.1.227:5555 shell getprop ro.build.version.sdk
----------------------------------------------------------------------
Ran 1 test in 6.980s

OK
```
#### 无法连接时
根据具体ip指定手机无法连接时的日志，日志中手机serialno我隐去了，改成了serialno
```
already connected to 192.168.1.227:5555
do not connect device
save log in 'D:\localSVN\trunk\testScripts\shell\airtest\log'
[10:41:36][DEBUG]<airtest.core.android.adb> c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -H 192.168.1.227 -P 5555 
-s serialno wait-for-device
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\adb.py", line 298, in wait_for_device
    self.cmd("wait-for-device", timeout=timeout)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\adb.py", line 178, in cmd
    stdout, stderr = proc_communicate_timeout(proc, timeout)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\utils\compat.py", line 79, in proc_communicate_timeout
    raise_from(exp, None)
  File "<string>", line 3, in raise_from
RuntimeError: Command ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\airtest\\core\\android\\static\\adb\\windows\\adb.exe', '-H', '192.168.1.227', '-P', '5555', '-s', 'serialno', 'wait-for-device'] timed out after 5 seconds: stdout['b'''], stderr['b''']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\cli\runner.py", line 65, in runTest
    six.reraise(*sys.exc_info())
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\cli\runner.py", line 61, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "D:\localSVN\trunk\testScripts\shell\airtest\upr.air\upr.py", line 19, in <module>
    connect_device("android://192.168.1.227:5555/serialno?cap_method=javacap&touch_method=adb")
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\api.py", line 65, in connect_device
    dev = init_device(platform, uuid, **params)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\api.py", line 33, in init_device
    dev = cls(uuid, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\android.py", line 44, in __init__
    self.adb.wait_for_device()
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\adb.py", line 300, in wait_for_device
    raisefrom(DeviceConnectionError, "device not ready", e)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\utils\compat.py", line 55, in raisefrom
    raise_from(exc_type(message), exc)
  File "<string>", line 3, in raise_from
airtest.core.error.DeviceConnectionError: 'device not ready'

----------------------------------------------------------------------
Ran 1 test in 5.185s

FAILED (errors=1)
```
### 后续的测试
因为看到日志中使用了不同的adb指令，所以后续我对adb指令进行了直接的测试，测试的指令是简单的ls
这条指令可以正确运行
```
adb -s 192.168.1.227:5555 shell ls
```
这条指令会卡住
```
adb -H 192.168.1.227 -P 5555 shell ls
```
前面那条指令-s选项后面内容如果乱输会提示找不到设备，如果不使用选项会使用当前连接的设备。
根据adb的help信息来看，下面这条应该也是正确的指令，所以我给google也提了个[issue](https://issuetracker.google.com/issues/160916909)。
我只在公司的环境下进行了测试，不太确定是否能在其他环境下重现。

**Comment by AxelHu** [comment]
之前的讨论是在另外一个issue下面的 #345
@yimelia 这边是新开的issue

**Comment by AxelHu** [comment]
google有在那个issue下面回复，其实是我理解错选项了。
adb有一个server的概念，adb -H -P提供的其实是adb server的ip和port，-s选项是手机的信息。


就是说在这个例子中我其实应该用的是
```
connect_device("android://localhost:5037/192.168.1.227:5555")
```
以ls为例，对应的adb指令是
```
adb -H localhost -P 5037 -s 192.168.1.227:5555 shell ls
```
其中localhost也可以替换成运行adb server的机器的ip，当然运行指令的机器adb版本需要与那台机器相同，否则adb server会被kill。
希望对遇到同样问题的朋友有帮助。

**Comment by vivian12** [comment]
我也遇到了相同的问题，但是还是没解决

**Comment by AxelHu** [comment]
@vivian12 
可以先确认是否是设置成功了无USB线连接手机，并且是否能连上，直接在命令行里测试就行了。airtest其实只是把连接的方法翻译成了命令行的指令，根据我前面发的内容来看，翻译应该是正确的。

**Comment by vivian12** [comment]
> @vivian12
> 可以先确认是否是设置成功了无USB线连接手机，并且是否能连上，直接在命令行里测试就行了。airtest其实只是把连接的方法翻译成了命令行的指令，根据我前面发的内容来看，翻译应该是正确的。

设置成功了的，使用airtestIDE也是可以成功的，但是如果用connect_device()就是会有问题，而且我还想这样连接一下云真机

**Comment by vivian12** [comment]
> @vivian12
> 可以先确认是否是设置成功了无USB线连接手机，并且是否能连上，直接在命令行里测试就行了。airtest其实只是把连接的方法翻译成了命令行的指令，根据我前面发的内容来看，翻译应该是正确的。

设置成功了的，使用airtestIDE也是可以成功的，但是如果用connect_device()就是会有问题，而且我还想这样连接一下云真机

**Comment by AxelHu** [comment]
@vivian12 
那你可以直接测试下命令行使用adb能否连接你的手机，因为我是工作需要，所以我之前都是在局域网环境下测的(手机通过WIFI连接)。
我用移动的网测了一下，确实没办法直接连接。如果是公司/家的情况的话，可以先连至另一边的电脑，然后再连到手机。
至于云手机，服务提供方应该会有说明如何远程使用adb的文档，例如我随手搜了下搜到华为的文档，是通过ssh来使用的。

**Comment by vivian12** [comment]
> @vivian12
> 那你可以直接测试下命令行使用adb能否连接你的手机，因为我是工作需要，所以我之前都是在局域网环境下测的(手机通过WIFI连接)。
> 我用移动的网测了一下，确实没办法直接连接。如果是公司/家的情况的话，可以先连至另一边的电脑，然后再连到手机。
> 至于云手机，服务提供方应该会有说明如何远程使用adb的文档，例如我随手搜了下搜到华为的文档，是通过ssh来使用的。

你好，连接可以成功了，不过只能是conect_device(ios:///127.0.0.1:8100）格式，如果用手机的ip地址，如192.168.1.1就不行

**Comment by wangxue1022** [comment]
我也遇到了这个问题，ios手机conect_device(ios:///127.0.0.1:8100）可以连接，但是conect_device(android:///92.168.1.1:5555）不行

**Comment by AxelHu** [comment]
> 
> 
> 我也遇到了这个问题，ios手机conect_device(ios:///127.0.0.1:8100）可以连接，但是conect_device(android:///92.168.1.1:5555）不行

参考我下面的回复，我后面发现了其实是用的格式不太对

**Comment by rafer16** [comment]
我这边也出现类似的问题，后面尝试将pocoservice的耗电管理中的允许完全后台行为以及允许应用自启动都打开，不报device not ready了 但是出现了新的错误
Traceback (most recent call last):
  File "E:\WahaAutoUI\core\main.py", line 56, in <module>
    if poco(daily_accept).exists():
  File "E:\WahaAutoUI\venv\lib\site-packages\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "E:\WahaAutoUI\venv\lib\site-packages\poco\proxy.py", line 776, in exists
    return self.attr('visible')
  File "E:\WahaAutoUI\venv\lib\site-packages\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "E:\WahaAutoUI\venv\lib\site-packages\poco\proxy.py", line 736, in attr
    nodes = self._do_query(multiple=False)
  File "E:\WahaAutoUI\venv\lib\site-packages\poco\proxy.py", line 886, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "E:\WahaAutoUI\venv\lib\site-packages\poco\utils\retry.py", line 15, in wrapped
    return func(*args, **kwargs)
  File "E:\WahaAutoUI\venv\lib\site-packages\poco\utils\hrpc\hierarchy.py", line 33, in select
    return self.selector.select(query, multiple)
  File "E:\WahaAutoUI\venv\lib\site-packages\hrpc\object_proxy.py", line 92, in __call__
    return self._client__.evaluate(self.__call_no_evaluate__(remote_obj_cache, *args))
  File "E:\WahaAutoUI\venv\lib\site-packages\hrpc\client.py", line 84, in evaluate
    raise RpcRemoteException(resp)
hrpc.exceptions.RpcRemoteException: java.lang.NullPointerException: Attempt to read from field 'int android.accessibilityservice.AccessibilityServiceInfo.flags' on a null object reference in method 'void androidx.test.uiautomator.UiDevice.<init>(android.app.Instrumentation)'

**Comment by rafer16** [comment]
可以尝试将pocosevice中的耗电管理-允许完全后台行为以及允许应用自启动都打开，我这边就不报device not ready 的错误了
