### ISSUE TITLE
使用text()方法时，报错SecurityException: uid 2000 does not have

### ISSUE THREAD

**Issue by ymirshuai** [AirtestProject/Airtest#778]
**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
RT

（在这里粘贴traceback或其他报错信息）
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\widgets\code_runner\run_manager.py", line 206, in my_exec
  File "<string>", line 1, in <module>
  File "airtest\utils\logwraper.py", line 78, in wrapper
  File "airtest\core\api.py", line 367, in text
  File "airtest\core\android\android.py", line 314, in text
  File "airtest\core\android\ime.py", line 123, in text
  File "airtest\core\android\ime.py", line 109, in start
  File "airtest\core\android\ime.py", line 72, in start
  File "airtest\core\android\ime.py", line 48, in _get_ime_list
  File "airtest\core\android\adb.py", line 370, in shell
airtest.core.error.AdbShellError: stdout[b''] stderr[b'Security exception: uid 2000 does not have android.permission.WRITE_SECURE_SETTINGS.\r\n\r\njava.lang.SecurityException: uid 2000 does not have android.permission.WRITE_SECURE_SETTINGS.\r\n\tat android.app.ContextImpl.enforce(ContextImpl.java:1951)\r\n\tat android.app.ContextImpl.enforceCallingPermission(ContextImpl.java:1969)\r\n\tat com.android.server.inputmethod.InputMethodManagerService$ShellCommandImpl.lambda$onCommand$0$InputMethodManagerService$ShellCommandImpl(InputMethodManagerService.java:4834)\r\n\tat com.android.server.inputmethod.-$$Lambda$InputMethodManagerService$ShellCommandImpl$DbZq_GIUJWcuMsIpw_Jz5jVT2-Y.accept(Unknown Source:4)\r\n\tat java.util.Arrays$ArrayList.forEach(Arrays.java:3805)\r\n\tat com.android.server.inputmethod.InputMethodManagerService$ShellCommandImpl.onCommand(InputMethodManagerService.java:4834)\r\n\tat android.os.ShellCommand.exec(ShellCommand.java:104)\r\n\tat com.android.server.inputmethod.InputMethodManagerService.onShellCommand(InputMethodManagerService.java:4808)\r\n\tat android.os.Binder.shellCommand(Binder.java:881)\r\n\tat android.os.Binder.onTransact(Binder.java:765)\r\n\tat com.android.internal.view.IInputMethodManager$Stub.onTransact(IInputMethodManager.java:433)\r\n\tat com.android.server.inputmethod.InputMethodManagerService.onTransact(InputMethodManagerService.java:1619)\r\n\tat com.android.server.inputmethod.ColorInputMethodManagerService.onTransact(ColorInputMethodManagerService.java:85)\r\n\tat android.os.Binder.execTransactInternal(Binder.java:1021)\r\n\tat android.os.Binder.execTransact(Binder.java:994)\r\n']

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)
![image](https://user-images.githubusercontent.com/17920713/88900007-595b6f00-d281-11ea-9d86-80cd45654ea4.png)

**预期效果**
(预期想要得到什么、见到什么)

**python 版本:** `python3.7.0`

**airtest 版本:** `1.1.1`

**设备:
 - 型号: OPPO R17
 - 系统: [e.g. Android 10]

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by ymirshuai** [comment]
更新airtest版本解决。。。问题关闭
