### ISSUE TITLE
my-testflow脚本不能在airtestIDE上执行

### ISSUE THREAD

**Issue by yuzhujiutian** [AirtestProject/Airtest#78]
问题点：my-testflow用例，不能在airtestIDE上执行

步骤：
1、将my-testflow解压至python目录Lib\site-packages，并将文件夹名重命名为testflow

2、修改setup.py
name='testflow_' + project_name,
改后为
name=project_name,

3、安装testflow
pip install -e testflow

4、修改用例脚本example_atide.py中testflow.lib层次结构
from testflow.testflow.lib.case.android_app import AndroidAppCase
from testflow.testflow.lib.utils.installation import install_android_app
from airtest.core.api import start_app, stop_app
from airtest.core.api import device as current_device

5、点击airtestide的执行按钮，执行错误log信息，见附三

附一：example_atide.py代码（atide为airtestIDE缩写）
```python
# -*- encoding=utf8 -*-
__author__ = "xxx"

from airtest.core.api import *

auto_setup(__file__)



import time

# TODO: "from testflow.lib" should be renamed according to your actual package name
from testflow.testflow.lib.case.android_app import AndroidAppCase
from testflow.testflow.lib.utils.installation import install_android_app
from airtest.core.api import start_app, stop_app, Template, exists
from airtest.core.api import device as current_device


class CalculatorPlus(AndroidAppCase):
    @classmethod
    def name(cls):
        return 'CalculatorPlus (customized name)'

    @classmethod
    def getMetaInfo(cls):
        return {
            "author": 'author name',
            "remark": 'any data',
            'any-keys': 'any-values',
        }

    def setUp(self):
        self.package_name = 'com.google.android.calculator'
        apk_path = self.R('res/app/com.google.android.calculator.apk')
        install_android_app(current_device().adb, apk_path)
        start_app(self.package_name)

    def runTest(self):
        keyboard = Template(self.R('res/img/keyboard-digits.png'))
        keyboard_landscape = Template(self.R('res/img/keyboard-digits-landscape.png'))
        self.assertTrue(exists(keyboard) or exists(keyboard_landscape), 'App started.')

        self.poco('com.google.android.calculator:id/digit_1').click()
        self.poco('com.google.android.calculator:id/op_add').click()
        self.poco('com.google.android.calculator:id/digit_1').click()
        self.poco('com.google.android.calculator:id/eq').click()
        time.sleep(1)
        result = self.poco('com.google.android.calculator:id/formula').get_text()
        self.site_capturer.snapshot('check-point-1')
        self.assertEqual(result, '2', '1+1=2 ^^')

    def tearDown(self):
        stop_app(self.package_name)

print "000"
#if __name__ == '__main__':
if 1 == 1:
    print "111"
    import pocounit
    print "222"
    pocounit.main()
```

附二：misc.py文件代码
```python
# coding=utf-8

import os
import re


def detect_package_root(mod_filename):
    """
    从某个模块的文件路径向上搜索，一直找到这个模块所在包的根目录，将包名第一段返回
    
    :param mod_filename:
    :return: 根包名 or None
    """
    print "xxxinfo: mod_filename = %s" %(mod_filename)
    egginfo_pattern = re.compile(r'.*\.egg-info$')
    print "xxxinfo: egginfo_pattern = %s" %(egginfo_pattern)
    p = os.path.abspath(os.path.join(mod_filename, '..'))
    print "xxxinfo: p = %s" %(p)
    while True:
        ls = os.listdir(p)
        print "xxxinfo: ls = %s" %(ls)
        matched = False
        for f in ls:
            if f == 'setup.py' or egginfo_pattern.match(f):
                print "xxxinfo: f = %s" %(f)
                matched = True
                break
        if matched:
            break
        p_prev = os.path.abspath(os.path.join(p, '..'))
        print "xxxinfo: p_prev = %s" %(p_prev)
        if p == p_prev:
            return None
        p = p_prev
    return p


def get_project_root(test_case_filename):
    return os.getenv("PROJECT_ROOT") or detect_package_root(test_case_filename) or os.getcwd()


def has_override(method, subCls, baseCls):
    return getattr(subCls, method) != getattr(baseCls, method)
```

附三：执行输出日志
```
[Start running..]
('add sys.path: ', ['D:\\winusr\\python\\python_2.7.13_x86\\Lib\\site-packages'])
[10:48:31][DEBUG]<airtest.core.android.adb> D:\winusr\netease\airtest\AIRTES~4\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 76UBBL422LVL wait-for-device
[10:48:31][DEBUG]<airtest.core.android.adb> D:\winusr\netease\airtest\AIRTES~4\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 76UBBL422LVL shell getprop ro.build.version.sdk
save log in 'D:/winusr/netease/airtest/airtest_log\9ec8865d0ceefc4919db12d836f87afe'
[10:48:31][DEBUG]<airtest.utils.logwraper> main_script: {'script': u'D:\\winusr\\python\\python_2.7.13_x86\\Lib\\site-packages\\testflow\\testflow\\scripts\\example_atide.air'}
000
111
222
this testcase filename is "D:\winusr\python\python_2.7.13_x86\Lib\site-packages\testflow\testflow\scripts\example_atide.air\example_atide.py".
using "D:\winusr\python\python_2.7.13_x86\Lib\site-packages" as project root. This testcase is "PocoTestSuite"
testcase locates in "D:\winusr\python\python_2.7.13_x86\Lib\site-packages\pocounit\suite.py"

ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)

Traceback (most recent call last):
  File "airtest\cli\runner.py", line 88, in runTest
  File "D:\winusr\python\python_2.7.13_x86\Lib\site-packages\testflow\testflow\scripts\example_atide.air\example_atide.py", line 61, in <module>
    pocounit.main()
  File "D:\winusr\python\python_2.7.13_x86\Lib\site-packages\pocounit\__init__.py", line 41, in main
    case = Case()
  File "D:\winusr\python\python_2.7.13_x86\Lib\site-packages\pocounit\case.py", line 41, in __init__
    FixtureUnit.__init__(self)
  File "D:\winusr\python\python_2.7.13_x86\Lib\site-packages\pocounit\fixture.py", line 16, in __init__
    project_root = get_project_root(test_case_filename)
  File "D:\winusr\python\python_2.7.13_x86\Lib\site-packages\pocounit\utils\misc.py", line 34, in get_project_root
    return os.getenv("PROJECT_ROOT") or detect_package_root(test_case_filename) or os.getcwd()
  File "D:\winusr\python\python_2.7.13_x86\Lib\site-packages\pocounit\utils\misc.py", line 18, in detect_package_root
    ls = os.listdir(p)
WindowsError: [Error 3] : 'D:\\winusr\\netease\\airtest\\AIRTES~4\\airtest\\cli/*.*'


Ran 1 test in 0.558s

FAILED (errors=1)
exiting.......
[Finished]
```

**Comment by adolli** [comment]
@yuzhujiutian 谢谢你的详细的反馈。
IDE里没有打算兼容my-testflow，如果要在IDE里使用的my-testflow，需要配置自己的python解释器，而不是IDE自带的python解释器。

**Comment by adolli** [comment]
以上报错原因在于，通过IDE启动测试脚本时，测试脚本所对应的文件路径是一个虚拟路径，因此检测脚本路径时出现了WindowsError3（无此目录或文件）报错。
