### ISSUE TITLE
Airtest闪退

### ISSUE THREAD

**Issue by adai5210** [AirtestProject/Airtest#790]
测试开发环境AirtestIDE使用问题 

```
AirtestIDE启动后闪退，用CMD启动后，报错


Traceback (most recent call last):
  File "app\plugins\device\device_panel\util.py", line 28, in adbDevices
  File "airtest\core\android\adb.py", line 222, in devices
    output = self.cmd("devices", device=False)
  File "airtest\core\android\adb.py", line 194, in cmd
    raise AdbError(stdout, stderr)
airtest.core.error.AdbError: stdout[List of devices attached
] stderr[* daemon not running; starting now at tcp:5037
could not read ok from ADB Server
* failed to start daemon
error: cannot connect to daemon
]
composeAndFlush: makeCurrent() failed
```

**python 版本:** `python3.85

**airtest 版本:** `1.2.5

**其他相关环境信息**
WIN TO GO WIN10企业版

**Comment by yimelia** [comment]
这个报错只是ADB版本冲突而已，闪退应该还是因为显卡问题，IDE目前不支持云桌面、虚拟机等环境
