### ISSUE TITLE
airtest 1.1.4新出现的问题（windows下）

### ISSUE THREAD

**Issue by niuniuprice** [AirtestProject/Airtest#798]
**(重要！问题分类)**
* 图像识别、设备控制相关问题

**描述问题bug**
我使用1.1.3及之前版本的airtest运行自制的脚本，没有问题，但升级到1.1.4后再运行，出现了如下报错
看起来是setUpClass和pywinauto的问题？我没有对airtest自身的代码有过任何修改，看1.1.4的更新日志，似乎也没有修改过这个地方？

不使用自制的启动器运行脚本，只使用本地python环境+airtest1.1.4运行，也会出现（module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'）这个错误

```
ERROR: setUpClass (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\cli\runner.py", line 136, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root, compress)
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\api.py", line 113, in auto_setup
    connect_device(dev)
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\api.py", line 63, in connect_device
    dev = init_device(platform, uuid, **params)
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\api.py", line 32, in init_device
    cls = import_device_cls(platform)
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\helper.py", line 116, in import_device_cls
    from airtest.core.win.win import Windows as cls
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\win\__init__.py", line 4, in <module>
    from .win import Windows
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\core\win\win.py", line 11, in <module>
    from pywinauto.application import Application
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\__init__.py", line 40, in <module>
    from . import findwindows
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\controls\uiawrapper.py", line 44, in <module>
    from ..uia_defines import IUIA
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\uia_defines.py", line 175, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\uia_defines.py", line 163, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\uia_defines.py", line 63, in __init__
    self.ui_automation_client.CUIAutomation().IPersist_GetClassID(),
AttributeError: module 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'


----------------------------------------------------------------------
Ran 0 tests in 0.762s

FAILED (errors=1)
Traceback (most recent call last):
  File "D:/KeyX/win7x64/myRunner.py", line 134, in <module>
    test.run_air('..\\..\\testcase\\'+i, device,i)
  File "D:/KeyX/win7x64/myRunner.py", line 101, in run_air
    rpt.report("log_template.html", output_file=output_file)
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\report\report.py", line 475, in report
    data = self.report_data(output_file=output_file, record_list=record_list)
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\report\report.py", line 425, in report_data
    self._load()
  File "C:\Users\hao\AppData\Local\Programs\Python\Python36\lib\site-packages\airtest\report\report.py", line 82, in _load
    with io.open(logfile, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\KeyX\\win7x64\\output\\report\\KX-T1722\\log.txt'
[Finished]

```

**python 版本:** `python3.6.8`

**airtest 版本:** `1.1.4`

**设备:**
 - 系统: [Windows 7 x64]

**其他相关环境信息**
使用1.1.3及以下版本的airtest时，运行正常

**Comment by niuniuprice** [comment]
@yimelia 请问能否看得出有什么问题吗？是属于airtest升级的问题还是其他依赖库的问题呢？

**Comment by niuniuprice** [comment]
检查后发现是pywinauto和comtypes安装问题，因未知原因缺少若干函数，导致运行测试时无法启动报错，重装几次之后解决
