### ISSUE TITLE
Android10多指滑动报RuntimeError: minitouch setup timeout

### ISSUE THREAD

**Issue by yelinqz** [AirtestProject/Airtest#808]
def multiswipes(context,terminal):
    points = []
    for point in context.table:
        points.append(MotionTrack().start([float(point["x1"]), float(point["y1"])]).move([float(point["x2"]), float(point["y2"])]).hold(1))
    poco = getPoco(terminal)
    poco.apply_motion_tracks(points)

手机型号：华为P30
Airtest：1.1.4
Poco：0.97.1
使用Pycharm，没有使用IDE

**Comment by yelinqz** [comment]
installed version is 41, installer version is 41. force_reinstall=False
[05:13:59][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 shell dumpsys package com.netease.open.pocoservice.test
installed version is 0, installer version is 0. force_reinstall=False
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 forward --no-rebind tcp:19918 tcp:10080
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 forward --no-rebind tcp:18379 tcp:10081
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 shell ps
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 shell getprop ro.product.cpu.abi
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 shell getprop ro.build.version.sdk
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 shell ls /data/local/tmp/minitouch
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 shell stat -c %s /data/local/tmp/minitouch
[05:14:00][DEBUG]<airtest.core.android.touch_methods.minitouch> install_minitouch skipped
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 shell dumpsys window displays
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 forward --no-rebind tcp:15399 localabstract:minitouch_15399
[05:14:00][DEBUG]<airtest.core.android.adb> C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s Q5S5T19307005717 shell /data/local/tmp/minitouch -n 'minitouch_15399' 2>&1
[05:14:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'open: Permission denied'
[05:14:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event3 for inspectionopen: Permission denied'
[05:14:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event4 for inspectionopen: Permission denied'
[05:14:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/mice for inspectionopen: Permission denied'
[05:14:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event5 for inspectionopen: Permission denied'
[05:14:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/mouse0 for inspectionopen: Permission denied'
[05:14:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event2 for inspectionopen: Permission denied'
[05:14:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event0 for inspectionopen: Permission denied'
[05:14:00][DEBUG]<airtest.utils.nbsp> [minitouch_server]b'Unable to open device /dev/input/event1 for inspectionUnable to find a suitable touch device'

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\behave\model.py", line 1329, in run
    match.run(runner.context)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\behave\matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features\steps\common_steps.py", line 224, in multiswipes
    poco.apply_motion_tracks(points)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\poco\pocofw.py", line 416, in apply_motion_tracks
    return self.agent.input.applyMotionEvents(tb.discretize(accuracy))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\poco\utils\airtest\input.py", line 127, in applyMotionEvents
    current_device().minitouch.perform(mes, interval=0)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\utils\snippet.py", line 105, in ready_func
    method()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\utils\snippet.py", line 115, in wrapper
    ret = func(inst, *args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\touch_methods\base_touch.py", line 42, in install_and_setup
    self.setup_server()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\touch_methods\minitouch.py", line 94, in setup_server
    raise RuntimeError("minitouch setup timeout")
RuntimeError: minitouch setup timeout

**Comment by yimelia** [comment]
airtest的接口发生了改动，poco没有同步更新导致的
这个问题将在几天后版本更新时修复

**Comment by yimelia** [comment]
已修复，请更新至1.1.6以上版本

**Comment by yelinqz** [comment]
已更新到1.1.6，poco也已更新到最新版本，仍存在此问题

**Comment by yelinqz** [comment]
> 已修复，请更新至1.1.6以上版本

已更新到1.1.6，poco也已更新到最新版本，仍存在此问题
