### ISSUE TITLE
逍遥模拟器CMD执行报错

### ISSUE THREAD

**Issue by shudaixiong1013** [AirtestProject/Airtest#811]
**前置条件**
airtest ide版本:1.2.5
逍遥模拟器: 7.2.7 , 安卓 7.1
逍遥模拟器adb版本和airtest 的一样;

**现象**
1:用ide 连接逍遥模拟器,执行脚本正常, CMD 命令执行脚本报错
2:模拟器上的yosemite也已经安装成功

**报错:**
ERROR: runTest (app.widgets.code_runner.ide_launcher.AirtestIDECase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "airtest\core\android\adb.py", line 371, in shell
  File "airtest\core\android\adb.py", line 329, in raw_shell
  File "airtest\core\android\adb.py", line 194, in cmd
airtest.core.error.AdbError: stdout[b''] stderr[b'CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": /data/local/tmp/minicap: has text relocations\r\nAborted \r\n']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "airtest\cli\runner.py", line 65, in runTest
  File "site-packages\six.py", line 693, in reraise
  File "airtest\cli\runner.py", line 61, in runTest
  File "D:\AirtestIDE\t3.air\t3.py", line 10, in <module>
    touch(Template(r"tpl1601396852751.png", record_pos=(0.191, -0.237), resolution=(1080, 1920)))
  File "airtest\utils\logwraper.py", line 71, in wrapper
  File "airtest\core\api.py", line 260, in touch
  File "airtest\utils\logwraper.py", line 71, in wrapper
  File "airtest\core\cv.py", line 59, in loop_find
  File "airtest\core\android\android.py", line 273, in snapshot
  File "airtest\core\android\android.py", line 591, in display_info
  File "airtest\core\android\android.py", line 610, in get_display_info
  File "airtest\utils\snippet.py", line 107, in ready_func
  File "airtest\core\android\minicap.py", line 152, in get_display_info
  File "airtest\core\android\adb.py", line 373, in shell
airtest.core.error.AdbShellError: stdout[b''] stderr[b'CANNOT LINK EXECUTABLE "/data/local/tmp/minicap": /data/local/tmp/minicap: has text relocations\r\nAborted \r\n']

**Comment by spectereye** [comment]
same error met
