### ISSUE TITLE
调用脚本时报错minicap server setup timeout

### ISSUE THREAD

**Issue by yyjy** [AirtestProject/Airtest#819]
使用手机小米8，已开启应用安装权限，选择模拟位置信息应用
1.直接使用airtest软件，connect手机（勾选 use javacap\use ADB orientation），可以正常进行脚本调试，识别图片正常,跑的正常；
出错位置：  if exists(Template(r"tpl1603099217111.png", record_pos=(-0.144, 0.022))):
2.同一个脚本.py文件，通过cmd命令调用执行时，会报错minicap server setup timeout

[07:32:18][INFO]<airtest.core.api> Try finding: Template(E:\AirtestProject\MYZY_android_UI\common.air\tpl1603099217111.png)
[07:32:18][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e shell pm path jp.co.cyberagent.stf.rotationwatcher
[07:32:18][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-01C8uKoFB_pkWrJGgrcQmg==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[07:32:18][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e shell ls /data/local/tmp/minicap
[07:32:19][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e shell ls /data/local/tmp/minicap.so
[07:32:19][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[07:32:19][DEBUG]<airtest.core.android.minicap> version:6
[07:32:19][DEBUG]<airtest.core.android.minicap> skip install minicap
[07:32:19][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e forward --no-rebind tcp:17679 localabstract:minicap_17679
[07:32:19][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
[07:32:19][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e shell dumpsys window displays
[07:32:19][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_17679' -P 1080x2248@1080x2248/90 -l 2>&1
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 28297'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1080x2248@1080x2248/1'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:241) Creating SurfaceComposerClient'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:244) Performing SurfaceComposerClient init check'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:255) Creating virtual display'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:261) Creating buffer queue'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:264) Setting buffer options'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:268) Creating CPU consumer'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:272) Creating frame waiter'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_28.cpp:276) Publishing virtual display'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'Vector<> have different types (this=0x7fc74537d0, rhs=0x7fc74538f0)'
[07:32:19][DEBUG]<airtest.utils.nbsp> [minicap_server]b'Aborted'
installed version is 41, installer version is 41. force_reinstall=False
installed version is 0, installer version is 0. force_reinstall=False
Traceback (most recent call last):
  File "E:\AirtestProject\MYZY_android_UI\common.air\common.py", line 332, in <module>
    if checkloginState():
  File "E:\AirtestProject\MYZY_android_UI\common.air\common.py", line 98, in checkloginState
    if exists(Template(r"tpl1603099217111.png", record_pos=(-0.144, 0.022))):
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\utils\logwraper.py", line 84, in wrapper
    res = f(*args, **kwargs)
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\api.py", line 415, in exists
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT_TMP)
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\utils\logwraper.py", line 84, in wrapper
    res = f(*args, **kwargs)
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\cv.py", line 59, in loop_find
    screen = G.DEVICE.snapshot(filename=None, quality=ST.SNAPSHOT_QUALITY)
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\android.py", line 260, in snapshot
    screen = self.minicap.get_frame_from_stream()
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 24, in wrapper
    return func(inst, *args, **kwargs)
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 357, in get_frame_from_stream
    self.frame_gen = self.get_stream()
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\utils\snippet.py", line 107, in ready_func
    return func(inst, *args, **kwargs)
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 245, in get_stream
    stopped = next(gen)
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 259, in _get_stream
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
  File "D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\minicap.py", line 330, in _setup_stream_server
    raise RuntimeError("minicap server setup timeout")
RuntimeError: minicap server setup timeout
[07:32:24][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e forward --remove tcp:11972
[07:32:24][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e forward --remove tcp:15172
[07:32:24][DEBUG]<airtest.core.android.adb> D:\Users\17173\AppData\Local\Programs\Python\Python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 872f983e forward --remove tcp:17679
[07:32:24][DEBUG]<airtest.core.android.rotation> orientationWatcher has ended

**Comment by RobertWang2** [comment]
同问

**Comment by huluxin** [comment]
解决了吗？

**Comment by yimelia** [comment]
请使用javacap模式，小米手机高版本的MIUI无法使用minicap

**Comment by stamepicmorg** [comment]
> 请使用javacap模式，小米手机高版本的MIUI无法使用minicap

how wolud i use javacap via cli? i usually creating venv, then installing airtest+poco, than i ran `python(3) ./run_test.py` wich is  near test.air folder.

我将如何通过CLI使用Java Cap？ 我通常创建venv，然后安装airtest + poco，而不是运行python（3）/ run_test.py夹在test.air文件夹附近。
