### ISSUE TITLE
1.2.6 不能用javacap连接竖屏模式下的模拟器, 只能连接横屏模式

### ISSUE THREAD

**Issue by Anyrainel** [AirtestProject/Airtest#830]
**描述问题bug**
根据教程连接emulator时选择"use javacap"，然后就会无法连接处于竖屏模式下的模拟器，我尝试了mumu emulator (oversea version) 和 ldplayer 都不行，但是在横屏模式就可以完美连接。如果不勾选"use javacap"，使用minicap也可以在竖屏模式下连接，但图像比较模糊，还是希望可以使用javacap。

***Use javacap connect portrait mode log (mumu emulator)***:
```
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 get-state
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 wait-for-device
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.sdk
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell ls /data/local/tmp/minicap ; echo ---$?---
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell ls /data/local/tmp/minicap.so ; echo ---$?---
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[07:10:58][DEBUG]<airtest.core.android.minicap> WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.
version:5
[07:10:58][DEBUG]<airtest.core.android.minicap> upgrade minicap to lastest version: -1->6
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell rm -r /data/local/tmp/minicap*
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.product.cpu.abi
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.preview_sdk
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.release
[07:10:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 push F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\stf_libs\x86\minicap /data/local/tmp/minicap
[07:10:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell chmod 755 /data/local/tmp/minicap ; echo ---$?---
[07:10:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 push F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-23/x86/minicap.so /data/local/tmp/minicap.so
[07:10:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell chmod 755 /data/local/tmp/minicap.so ; echo ---$?---
[07:10:59][INFO]<airtest.core.android.minicap> minicap installation finished
[07:10:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[07:10:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys window displays ; echo ---$?---
[07:10:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
[07:10:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-1/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[07:11:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys package com.netease.nie.yosemite ; echo ---$?---
[07:11:00][INFO]<airtest.core.android.yosemite> local version code is 302, installed version code is 302
[07:11:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 forward --no-rebind tcp:15578 localabstract:javacap_15578
[07:11:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell pm path com.netease.nie.yosemite ; echo ---$?---
[07:11:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell CLASSPATH=/data/app/com.netease.nie.yosemite-1/base.apk exec app_process /system/bin com.netease.nie.yosemite.Capture --scale 100 --socket javacap_15578 -lazy 2>&1
[07:11:00][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'Capture server listening on @javacap_15578'
[07:11:00][ERROR]<airtest> Traceback (most recent call last):
  File "app\plugins\devicepool\android\device.py", line 342, in run
  File "app\plugins\devicepool\android\device.py", line 351, in main_loop
  File "airtest\core\android\javacap.py", line 101, in get_frame_from_stream
    return self.frame_gen.send(None)
StopIteration

[Warning] The current device is unplugged!
```

***Use minicap connect portrait mode log (mumu emulator)***:
```
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 get-state
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 wait-for-device
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.sdk
F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\helper.py:41: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  cls.LOGGING.warn("Device:%s updated %s -> %s" % (dev.uuid, instance, dev))
[07:20:58][WARNING]<airtest.core.api> Device:127.0.0.1:7555 updated <airtest.core.android.android.Android object at 0x000002244D4A9CF8> -> <airtest.core.android.android.Android object at 0x000002244C134F60>
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell ls /data/local/tmp/minicap ; echo ---$?---
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell ls /data/local/tmp/minicap.so ; echo ---$?---
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[07:20:58][DEBUG]<airtest.core.android.minicap> WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.
version:5
[07:20:58][DEBUG]<airtest.core.android.minicap> upgrade minicap to lastest version: -1->6
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell rm -r /data/local/tmp/minicap*
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.product.cpu.abi
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.preview_sdk
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.release
[07:20:58][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 push F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\stf_libs\x86\minicap /data/local/tmp/minicap
[07:20:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell chmod 755 /data/local/tmp/minicap ; echo ---$?---
[07:20:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 push F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-23/x86/minicap.so /data/local/tmp/minicap.so
[07:20:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell chmod 755 /data/local/tmp/minicap.so ; echo ---$?---
[07:20:59][INFO]<airtest.core.android.minicap> minicap installation finished
[07:20:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[07:20:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys window displays ; echo ---$?---
[07:20:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
[07:20:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-1/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[07:20:59][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 forward --no-rebind tcp:14428 localabstract:minicap_14428
[07:21:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[07:21:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys window displays ; echo ---$?---
[07:21:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_14428' -P 1600x900@450x800/270 -l 2>&1
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 3115'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 1600x900@450x253/3'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:240) Creating SurfaceComposerClient'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:243) Performing SurfaceComposerClient init check'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:250) Creating virtual display'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:256) Creating buffer queue'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:261) Creating CPU consumer'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:265) Creating frame waiter'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:269) Publishing virtual display'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 4379652 bytes for JPG encoder'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:489) Server start'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:492) New client connection'
[07:21:00][DEBUG]<airtest.core.android.minicap> (1, 24, 3115, 1600, 900, 450, 253, 3, 2)
[07:21:00][DEBUG]<airtest.core.android.minicap> quirk_flag found, going to resetup
[07:21:00][DEBUG]<airtest.core.android.minicap> minicap stream ends
[07:21:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 forward --remove tcp:14428
[07:21:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 forward --no-rebind tcp:19850 localabstract:minicap_19850
[07:21:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[07:21:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys window displays ; echo ---$?---
[07:21:00][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -n 'minicap_19850' -P 900x1600@800x450/0 -l 2>&1
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'PID: 3141'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: Using projection 900x1600@253x450/0'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:240) Creating SurfaceComposerClient'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:243) Performing SurfaceComposerClient init check'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:250) Creating virtual display'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:256) Creating buffer queue'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:261) Creating CPU consumer'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:265) Creating frame waiter'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (external/MY_minicap/src/minicap_23.cpp:269) Publishing virtual display'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 4379652 bytes for JPG encoder'
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:489) Server start'
[07:21:00][DEBUG]<airtest.core.android.minicap> (1, 24, 3141, 900, 1600, 253, 450, 0, 2)
[07:21:00][DEBUG]<airtest.utils.nbsp> [minicap_server]b'INFO: (jni/minicap/minicap.cpp:492) New client connection'
```

***Use javacap connect landscape mode log (mumu emulator)***:
```
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 get-state
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 wait-for-device
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.sdk
F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\helper.py:41: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  cls.LOGGING.warn("Device:%s updated %s -> %s" % (dev.uuid, instance, dev))
[07:22:55][WARNING]<airtest.core.api> Device:127.0.0.1:7555 updated <airtest.core.android.android.Android object at 0x000002244C134F60> -> <airtest.core.android.android.Android object at 0x0000022451BC9B70>
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell ls /data/local/tmp/minicap ; echo ---$?---
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell ls /data/local/tmp/minicap.so ; echo ---$?---
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -v 2>&1
[07:22:55][DEBUG]<airtest.core.android.minicap> WARNING: linker: /data/local/tmp/minicap has text relocations. This is wasting memory and prevents security hardening. Please fix.
version:5
[07:22:55][DEBUG]<airtest.core.android.minicap> upgrade minicap to lastest version: -1->6
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell rm -r /data/local/tmp/minicap*
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.product.cpu.abi
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.preview_sdk
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell getprop ro.build.version.release
[07:22:55][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 push F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\stf_libs\x86\minicap /data/local/tmp/minicap
[07:22:56][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell chmod 755 /data/local/tmp/minicap ; echo ---$?---
[07:22:56][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 push F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\stf_libs\minicap-shared/aosp/libs/android-23/x86/minicap.so /data/local/tmp/minicap.so
[07:22:56][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell chmod 755 /data/local/tmp/minicap.so ; echo ---$?---
[07:22:56][INFO]<airtest.core.android.minicap> minicap installation finished
[07:22:56][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i ; echo ---$?---
[07:22:56][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys window displays ; echo ---$?---
[07:22:56][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell pm path jp.co.cyberagent.stf.rotationwatcher ; echo ---$?---
[07:22:56][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell export CLASSPATH=/data/app/jp.co.cyberagent.stf.rotationwatcher-1/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[07:22:56][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell dumpsys package com.netease.nie.yosemite ; echo ---$?---
[07:22:57][INFO]<airtest.core.android.yosemite> local version code is 302, installed version code is 302
[07:22:57][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 forward --no-rebind tcp:18115 localabstract:javacap_18115
[07:22:57][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell pm path com.netease.nie.yosemite ; echo ---$?---
[07:22:57][DEBUG]<airtest.core.android.adb> F:\Program Files\AirtestIDE-win-1.2.6\AirtestIDE\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 127.0.0.1:7555 shell CLASSPATH=/data/app/com.netease.nie.yosemite-1/base.apk exec app_process /system/bin com.netease.nie.yosemite.Capture --scale 100 --socket javacap_18115 -lazy 2>&1
[07:22:57][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'Capture server listening on @javacap_18115'
[07:22:57][DEBUG]<airtest.core.android.javacap> (1, 3, 0, 1600, 900, 0, 0, 0, 1)
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**复现步骤**
1. 打开mumu emulator，启用 ADB connection
2. 添加 remote connection "adb connect 127.0.0.1:7555"
3. 勾选 use javacap
4. 旋转mumu emulator屏幕
5. 点击connect

**预期效果**
横屏和竖屏应该都能正常使用javacap连接

**python 版本:** `Airtest IDE 1.2.6 默认python (3.6.5)`

**airtest 版本:** `1.2.6`

**设备:**
 - 型号: mumu emulator 2.3.18, desktop launcher 2.4.0
 - 系统: Android 6.0.1

**其他相关环境信息**
在横屏模式或minicap下都能正常连接。

**Comment by stamepicmorg** [comment]
> 请使用javacap模式，小米手机高版本的MIUI无法使用minicap

how wolud i use javacap via cli? i usually creating venv, then installing airtest+poco, than i ran `python(3) ./run_test.py` wich is  near test.air folder.

我将如何通过CLI使用Java Cap？ 我通常创建venv，然后安装airtest + poco，而不是运行python（3）/ run_test.py夹在test.air文件夹附近。

**Comment by yimelia** [comment]
更新到1.2.7版本的IDE之后再试试看吧

**Comment by Anyrainel** [comment]
> > 请使用javacap模式，小米手机高版本的MIUI无法使用minicap
> 
> how wolud i use javacap via cli? i usually creating venv, then installing airtest+poco, than i ran `python(3) ./run_test.py` wich is near test.air folder.
> 
> 我将如何通过CLI使用Java Cap？ 我通常创建venv，然后安装airtest + poco，而不是运行python（3）/ run_test.py夹在test.air文件夹附近。

这个跟原本问题无关，但是你想知道的话很简单，只要在IDE里用javacap运行，然后你复制一下log窗口一开始的指令就可以了，直接用python和用IDE那个CLI都是一样的参数。

**Comment by lichangg** [comment]
我把airtest 版本升到: 1.2.9， 也就是目前的最新版也不能使用竖屏， 这能解决么？
