### ISSUE TITLE
OSError: socket connection broken

### ISSUE THREAD

**Issue by wenhuichen** [AirtestProject/Airtest#838]
**描述问题bug**
执行过程中，时常出现：Touch target image Failed，socket connection broken

**traceback**
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 24, in wrapper
    return func(inst, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 358, in get_frame_from_stream
    return six.next(self.frame_gen)
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 291, in _get_stream
    frame_data = s.recv(frame_size)
  File "/usr/local/lib/python3.7/site-packages/airtest/utils/safesocket.py", line 32, in recv
    raise socket.error("socket connection broken")
OSError: socket connection broken

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airtest/utils/logwraper.py", line 84, in wrapper
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airtest/core/api.py", line 261, in touch
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
  File "/usr/local/lib/python3.7/site-packages/airtest/utils/logwraper.py", line 84, in wrapper
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airtest/core/cv.py", line 59, in loop_find
    screen = G.DEVICE.snapshot(filename=None, quality=ST.SNAPSHOT_QUALITY)
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/android.py", line 260, in snapshot
    screen = self.minicap.get_frame_from_stream()
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 27, in wrapper
    return func(inst, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 358, in get_frame_from_stream
    return six.next(self.frame_gen)
  File "/usr/local/lib/python3.7/site-packages/airtest/core/android/minicap.py", line 291, in _get_stream
    frame_data = s.recv(frame_size)
  File "/usr/local/lib/python3.7/site-packages/airtest/utils/safesocket.py", line 32, in recv
    raise socket.error("socket connection broken")
OSError: socket connection broken

**相关截图**
python环境运行：airtest.cli.runner import AirtestCase, run_script
![Uploading image.png…]()

**复现步骤**
/

**预期效果**
/

**python 版本:**
3.7

**airtest 版本:** 
1.1.6

**设备:**
 - 型号: oppo A9
 - 系统:10

**其他相关环境信息**
macOS 10.15.7

**Comment by yimelia** [comment]
这种情况出现有没有规律？是否在运行到密码输入框界面的时候出现的？

**Comment by s866** [comment]
minicap的_get_stream方法的
`proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
s = SafeSocket()
s.connect((self.adb.host, localport))`
替换成下面代码试试
`from time import sleep
count = 0
while count < 3:
    proc, nbsp, localport = self._setup_stream_server(lazy=lazy)
    s = SafeSocket()
    s.connect((self.adb.host, localport))
    try:
        t = s.recv(24)
        break
    except OSError as e:
        s.close()
        nbsp.kill()
        proc.kill()
        self.adb.remove_forward("tcp:%s" % localport)
        count += 1
        sleep(3)
        LOGGING.debug('[retry]*******************************************************')`

**Comment by IcyW** [comment]
> 这种情况出现有没有规律？是否在运行到密码输入框界面的时候出现的？

发现常常在多个用例批量运行的场景下，某次init_device、snapshot时出现。

**Comment by wenhuichen** [comment]
合并入 #924

**Comment by lyowu** [comment]
> 这种情况出现有没有规律？是否在运行到密码输入框界面的时候出现的？

是，何解？
