### ISSUE TITLE
设备控制相关问题，在使用命令行执行一直提示device not ready

### ISSUE THREAD

**Issue by RonnyHU0210** [AirtestProject/Airtest#840]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
*设备控制相关问题

**描述问题bug**
使用命令行无法启动脚本，ADB命令是可以连接手机的

```报错复制
C:\Users\Administrator>airtest run "H:/work/_AirtestIDE/BC2UI_1.air" --device Android:///8BN0217830009097A --log
save log in 'H:/work/_AirtestIDE/BC2UI_1.air\log'
[11:13:03][DEBUG]<airtest.core.android.adb> c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 8BN0217830009097A wait-for-device
======================================================================
ERROR: setUpClass (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\adb.py", line 298, in wait_for_device
    self.cmd("wait-for-device", timeout=timeout)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\adb.py", line 178, in cmd
    stdout, stderr = proc_communicate_timeout(proc, timeout)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\utils\compat.py", line 79, in proc_communicate_timeout
    raise_from(exp, None)
  File "<string>", line 3, in raise_from
RuntimeError: Command ['c:\\users\\administrator\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\airtest\\core\\android\\static\\adb\\windows\\adb.exe', '-s', '8BN0217830009097A', 'wait-for-device'] timed out after 5 seconds: stdout['b'''], stderr['b''']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\cli\runner.py", line 28, in setUpClass
    setup_by_args(args)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\cli\runner.py", line 144, in setup_by_args
    auto_setup(dirpath, devices, args.log, project_root, compress)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\api.py", line 109, in auto_setup
    connect_device(dev)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\api.py", line 58, in connect_device
    dev = init_device(platform, uuid, **params)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\api.py", line 33, in init_device
    dev = cls(uuid, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\android.py", line 46, in __init__
    self.adb.wait_for_device()
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\core\android\adb.py", line 300, in wait_for_device
    raisefrom(DeviceConnectionError, "device not ready", e)
  File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\airtest\utils\compat.py", line 55, in raisefrom
    raise_from(exc_type(message), exc)
  File "<string>", line 3, in raise_from
airtest.core.error.DeviceConnectionError: 'device not ready'
```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)

**预期效果**
希望能用命令行执行脚本

**python 版本:** `python3.7.7`

**airtest 版本:** `1.1.6`
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [Honor 9y]
 - 系统: [Android 8.0]
 - (别的信息)

**其他相关环境信息**
(Win10 64位)

**Comment by yimelia** [comment]
这个报错就是连不上你指定的手机，检查`--device Android:///8BN0217830009097A`有没有问题，是不是本地USB连的手机，IDE里能不能跑，跑的时候的命令行是不是一模一样的？
如果你的代码里有connect_device，自己写了手机的连接字符串的话，那也需要检查一下有没有写错
