### ISSUE TITLE
点击目标图片 异常

### ISSUE THREAD

**Issue by caiquan-github** [AirtestProject/Airtest#858]
在windows环境下 cmd窗口 执行无异常
在Windows环境下 java中执行脚本命令 执行异常
```
`Traceback (most recent call last):
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\aircv\keypoint_matching_contrib.py", line 118, in init_detector
    self.detector = cv2.xfeatures2d.SURF_create(self.HESSIAN_THRESHOLD, upright=self.UPRIGHT)
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-5rb_9df3\opencv_contrib\modules\xfeatures2d\src\surf.cpp:1029: error: (-213:The function/feature is not implemented) This algorithm is patented and is excluded in this configuration; Set OPENCV_ENABLE_NONFREE CMake option and rebuild the library in function 'cv::xfeatures2d::SURF::create'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\utils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\core\api.py", line 351, in touch
    pos = loop_find(v, timeout=ST.FIND_TIMEOUT)
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\utils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\core\cv.py", line 66, in loop_find
    match_pos = query.match_in(screen)
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\core\cv.py", line 145, in match_in
    match_result = self._cv_match(screen)
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\utils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\core\cv.py", line 169, in _cv_match
    ret = self._try_match(func, image, screen, threshold=self.threshold, rgb=self.rgb)
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\core\cv.py", line 178, in _try_match
    ret = func(*args, **kwargs).find_best_result()
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\aircv\keypoint_base.py", line 23, in wrapper
    ret = func(self, *args, **kwargs)
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\aircv\keypoint_base.py", line 65, in find_best_result
    self.kp_sch, self.kp_src, self.good = self._get_key_points()
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\aircv\keypoint_base.py", line 147, in _get_key_points
    self.init_detector()
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\site-packages\airtest\aircv\keypoint_matching_contrib.py", line 121, in init_detector
    traceback.print_exc()
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\aa2\AppData\Local\Programs\Python\Python39\lib\traceback.py", line 105, in print_exception
    print(line, file=file, end="")
OSError: [Errno 22] Invalid argument`
```

**相关截图**
![image](https://user-images.githubusercontent.com/39827081/106593207-7d2ea300-658b-11eb-83ba-f943aac578c5.png)

**复现步骤**
java代码
```
	public static void main(String[] args) throws Exception{
		execShell("airtest run  C:/Users/aa2/Documents/Airtest_file/test2.air --device Android:///DI5DORRO7HEYY9S8 --log C:/Users/aa2/Documents/Airtest_file/log");
	}
	
	

	/** 
	     * 运行shell脚本 
	     * @param shell 需要运行的shell脚本 
	     */  
	    public static void execShell(String shell){  
	        try {  
	            Runtime rt = Runtime.getRuntime();  
	            rt.exec(shell);
	 
	        } catch (Exception e) {  
	            e.printStackTrace();  
	        }  
	    }  
	  
```

**python 版本:** `python3.9.1`
**airtest 版本:** `1.1.7`

**设备:**
 - 型号: 红米 node4x 研发科
 - 系统: 安卓6

**Comment by caiquan-github** [comment]
都是在windows环境下，以java方式来调用shell 执行python命令并没有成功（上述有java源码），cmd控制台执行没有问题

**Comment by yimelia** [comment]
java中执行的那个系统环境是否和直接执行的一致？
