### ISSUE TITLE
Android connect_device(uri)方法无法连接手机，一直提示device not ready，connect_device("Android:///")可以正常连接

### ISSUE THREAD

**Issue by douniwan5788** [AirtestProject/Airtest#870]
**(重要！问题分类)**
* 设备控制相关问题

**描述问题bug**
Android 平台的`connect_device(uri)`方法底层调用`airtest.core.android.android.Android`初始化，由于初始化时调用`adb.wait_for_device`设置了5s的超时，在adb第一次启动时需要先启动adb server，这个时间会大于5s，导致`wait_for_device()`失败，但使用`"Android:///"`连接时，会先调用`get_default_device()`且并未限制超时，所以可以连接成功
#840 应该也是这个原因
#549 当有多个版本adb存在时会不断地互相kill-server，也会间接引起这个问题

```
Traceback (most recent call last):
  File "f:\xxx\xxx\xxx.air\.venv\lib\site-packages\airtest\core\android\adb.py", line 298, in wait_for_device
    self.cmd("wait-for-device", timeout=timeout)
  File "f:\xxx\xxx\xxx.air\.venv\lib\site-packages\airtest\core\android\adb.py", line 178, in cmd
    stdout, stderr = proc_communicate_timeout(proc, timeout)
  File "f:\xxx\xxx\xxx.air\.venv\lib\site-packages\airtest\utils\compat.py", line 79, in proc_communicate_timeout
    raise_from(exp, None)
  File "<string>", line 3, in raise_from
RuntimeError: Command ['f:\\xxx\\xxx\\xxx.air\\.venv\\lib\\site-packages\\airtest\\core\\android\\static\\adb\\windows\\adb.exe', '-s', 'YHEQKJ8HDYRK8DU8', 'wait-for-device'] timed out after 5 seconds: stdout['b'''], stderr['b''']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\process.py", line 232, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "F:\xxx\xxx\xxx.air\main.py", line 56, in task_warrper_job
    main(device, appid)
  File "F:\xxx\xxx\xxx.air\xxx.py", line 17, in main
    dev = connect_device(f"Android:///{uuid}")
  File "f:\xxx\xxx\xxx.air\.venv\lib\site-packages\airtest\core\api.py", line 68, in connect_device
    dev = init_device(platform, uuid, **params)
  File "f:\xxx\xxx\xxx.air\.venv\lib\site-packages\airtest\core\api.py", line 37, in init_device
    dev = cls(uuid, **kwargs)
  File "f:\xxx\xxx\xxx.air\.venv\lib\site-packages\airtest\core\android\android.py", line 47, in __init__
    self.adb.wait_for_device()
  File "f:\xxx\xxx\xxx.air\.venv\lib\site-packages\airtest\core\android\adb.py", line 300, in wait_for_device
    raisefrom(DeviceConnectionError, "device not ready", e)
  File "f:\xxx\xxx\xxx.air\.venv\lib\site-packages\airtest\utils\compat.py", line 55, in raisefrom
    raise_from(exc_type(message), exc)
  File "<string>", line 3, in raise_from
airtest.core.error.DeviceConnectionError: 'device not ready'
```

**复现步骤**
1. adb kill-server
2. connect_device(uri)

**预期效果**
正常连接

**Comment by yimelia** [comment]
最好是不要有多个adb版本同时在使用，否则这个adb不断重启的问题也会影响到别的接口，不止这个

**Comment by douniwan5788** [comment]
> 最好是不要有多个adb版本同时在使用，否则这个adb不断重启的问题也会影响到别的接口，不止这个
```
global options:
 -a         listen on all network interfaces, not just localhost
 -d         use USB device (error if multiple devices connected)
 -e         use TCP/IP device (error if multiple TCP/IP devices available)
 -s SERIAL  use device with given serial (overrides $ANDROID_SERIAL)
 -t ID      use device with given transport id
 -H         name of adb server host [default=localhost]
 -P         port of adb server [default=5037]
 -L SOCKET  listen on given socket for adb server [default=tcp:localhost:5037]
```
adb提供了多个控制client、server端口的参数，一个正确的设计是完全可以规避这些问题的。比如使用一个专有的、自定义端口的adb server

**Comment by yimelia** [comment]
好的，后续我们会考虑尝试对此进行修改

**Comment by douniwan5788** [comment]
https://issuetracker.google.com/issues/182294551
多个adb server同时运行会有问题,我本机测试也有类似的现象.也许应该先尝试使用PATH里的adb?

**Comment by amao12580** [comment]
any update？
