### ISSUE TITLE
进入需要输入、唤起yosmite的页面，报错

### ISSUE THREAD

**Issue by xyl00755** [AirtestProject/Airtest#882]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
进入需要输入、唤起yosmite的页面，就报错
比如进入登录页

```
（在这里粘贴traceback或其他报错信息）
ava.lang.RuntimeException: Unable to stop service com.netease.nie.yosemite.ime.ImeService@ccd141f: java.lang.IllegalStateException: dismissForDestroyIfNecessary can be called only once
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4201)
	at android.app.ActivityThread.access$2000(ActivityThread.java:224)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalStateException: dismissForDestroyIfNecessary can be called only once
	at android.inputmethodservice.SoftInputWindow.dismissForDestroyIfNecessary(SoftInputWindow.java:333)
	at android.inputmethodservice.InputMethodService.onDestroy(InputMethodService.java:1108)
	at com.netease.nie.yosemite.ime.ImeService.onDestroy(ImeService.java:217)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4177)
	... 8 more

```

**相关截图**
(贴出遇到问题时的截图内容，如果有的话)
(在AirtestIDE里产生的图像和设备相关的问题，请贴一些AirtestIDE控制台黑窗口相关报错信息)
![image](https://user-images.githubusercontent.com/22951418/112783616-4bfdbb00-9082-11eb-88b8-80ddda7070af.png)

**复现步骤**
1. 通过执行airtest脚本，进入需要输入文字的登录页

**预期效果**
无报错，可以正常输入

**python 版本:** `python3.5`

**airtest 版本:** `1.2.8`

**设备:**
 - 型号: 小米8
 - 系统: MIUI 12.0.3
 - (别的信息)

**其他相关环境信息**
无

**Comment by yimelia** [comment]
试一下以下几个操作看看有没有效果：

1. 在手机设置-语言和输入法里，修改Yosemite为默认输入法，看能否正常设置，如果可以的话看看脚本能不能跑
2. 检查一下手机里是否有手机助手类型的软件（或者是系统设置-应用里有没有相关设置），限制了yosemite.apk的自启动或者是后台启动
3. 尝试重启手机看看，也有可能是因为这个应用卡死了导致无法拉起，重启后可能会恢复

**Comment by xyl00755** [comment]
感谢回复，我试了下效果如下：
1.可以在输入法中设置默认输入法为 Yosemite，但进登录页还是报错。关闭报错后脚本可以继续跑，也能正常按脚本输入内容。airtest日志本身没有报错。
2.已经改成允许自启动，还是会有报错。
3.这个应用本身没有卡死，重启手机无效。

奇怪的是，在应用某些页面不会导致yosemite报错，登录这种页面才会。目前通过airtest图形把崩溃日志弹窗关掉了，暂时可以使用。

**Comment by yimelia** [comment]
找一下手机有没有安全输入的选项，把安全输入关闭掉？ https://airtest.doc.io.netease.com/IDEdocs/device_connection/2_android_faq/#_4 就是这个链接下面小米这部分的最后一张图，有个安全输入的选项
