### ISSUE TITLE
v1.1.8版本更新的ios相关api是咋使用的，一用就报ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002041A5018D0>: Failed to establish a new connection

### ISSUE THREAD

**Issue by jeniva** [AirtestProject/Airtest#885]
(请尽量按照下面提示内容填写，有助于我们快速定位和解决问题，感谢配合。否则直接关闭。)

**(重要！问题分类)**
* 测试开发环境AirtestIDE使用问题 -> https://github.com/AirtestProject/AirtestIDE/issues
* 控件识别、树状结构、poco库报错  -> https://github.com/AirtestProject/Poco/issues
* 图像识别、设备控制相关问题 -> 按下面的步骤

**描述问题bug**
(简洁清晰得概括一下遇到的问题是什么。或者是报错的traceback信息。)
我根据新版本更新说明的方法使用ios弹窗相关的api，一直报连接的错误，用其他的api是可以的，我不知道是我使用方法有误，还是怎么的求指导。。。
wda使用的是Facebook的那个。在IED里面使用的，Windows连接ios手机执行自动化。

```
Traceback (most recent call last):
  File "airtest\cli\runner.py", line 70, in runTest
  File "E:\Download\child_watcher5\untitled.air\untitled.py", line 26, in <module>
    ios.alert_click(['设置', '允许', '好'])
  File "D:\AirtestIDE-win-1.2.8\AirtestIDE\airtest\core\ios\ios.py", line 33, in wrapper
    return func(self, *args, **kwargs)
  File "D:\AirtestIDE-win-1.2.8\AirtestIDE\airtest\core\ios\ios.py", line 628, in alert_click
    return self.driver.alert.click(buttons)
  File "site-packages\wda\__init__.py", line 1168, in click
  File "site-packages\wda\__init__.py", line 1150, in buttons
  File "site-packages\wda\utils.py", line 47, in _inner
  File "site-packages\wda\__init__.py", line 451, in _fetch
  File "site-packages\wda\__init__.py", line 686, in session_id
  File "<decorator-gen-2>", line 2, in status
  File "site-packages\retry\api.py", line 74, in retry_decorator
  File "site-packages\retry\api.py", line 33, in __retry_internal
  File "site-packages\wda\__init__.py", line 379, in status
  File "site-packages\wda\utils.py", line 47, in _inner
  File "site-packages\wda\__init__.py", line 454, in _fetch
  File "site-packages\wda\__init__.py", line 124, in httpdo
  File "site-packages\wda\__init__.py", line 154, in _unsafe_httpdo
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8100): Max retries exceeded with url: /status (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002041A5018D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

```

**相关截图**
![image](https://user-images.githubusercontent.com/8514029/113390209-dbc5a100-93c3-11eb-90ba-b7786423c279.png)

![image](https://user-images.githubusercontent.com/8514029/113389311-686f5f80-93c2-11eb-9441-e4de65d9753f.png)

**复现步骤**

**预期效果**
跑ios自动化过程中出现非预期弹窗可以自动点掉，比如升级的点，Appid验证等系统弹窗。

**python 版本:** `python3.7.8`

**airtest 版本:** `1.1.6’ ，IDE是最新的1.2.8
> airtest版本通过`pip freeze`可以命令可以查到

**设备:**
 - 型号: [e.g. google pixel 2] iphone7
 - 系统: [e.g. Android 8.1] ios11.4.1
 - (别的信息)

**其他相关环境信息**
(其他运行环境，例如在linux ubuntu16.04上运行异常，在windows上正常。)

**Comment by yimelia** [comment]
可以先试一下普通一点的touch接口能不能用，还有就是IDE里连上手机后能不能操作

**Comment by jeniva** [comment]
可以的，之前是单纯的这个弹窗相关的执行不了，今天重启电脑后又可以了，谢谢。
