### ISSUE TITLE
win7下python2.7离线安装airtest-1.0.17报错无法安装（确认我电脑就一个python版本）

### ISSUE THREAD

**Issue by testyao** [AirtestProject/Airtest#89]
大佬今天新上的包 airtest-1.0.17  ，py2.7离线安装还是报这个错，安装不上啊（1.0.16也是这个问题）
byte-compiling build\bdist.win-amd64\egg\airtest\utils\snippet.py to snippet.pyc
byte-compiling build\bdist.win-amd64\egg\airtest\utils\transform.py to transform.pyc
byte-compiling build\bdist.win-amd64\egg\airtest\utils\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\airtest\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\airtest\__main__.py to __main__.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying airtest.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying airtest.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying airtest.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying airtest.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying airtest.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying airtest.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
airtest.cli.runner: module references __file__
airtest.core.android.constant: module references __file__
airtest.core.ios.constant: module references __file__
airtest.core.ios.minicap: module references __file__
airtest.report.report: module references __file__
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    'Programming Language :: Python :: 3.6',
  File "build\bdist.win-amd64\egg\setuptools\__init__.py", line 129, in setup
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "build\bdist.win-amd64\egg\setuptools\command\install.py", line 67, in run
  File "build\bdist.win-amd64\egg\setuptools\command\install.py", line 109, in do_egg_install
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "build\bdist.win-amd64\egg\setuptools\command\bdist_egg.py", line 220, in run
  File "build\bdist.win-amd64\egg\setuptools\command\bdist_egg.py", line 273, in zip_safe
  File "build\bdist.win-amd64\egg\setuptools\command\bdist_egg.py", line 383, in analyze_egg
  File "build\bdist.win-amd64\egg\setuptools\command\bdist_egg.py", line 422, in scan_module
ValueError: bad marshal data (unknown type code)

**Comment by SUDARSHANCHAUDHARI** [comment]
hope this will help to update pip version - cmd >> python -m pip install --upgrade pip
