### ISSUE TITLE
使用template 做图像匹配时,opencv报错 Out of memory

### ISSUE THREAD

**Issue by ray0728** [AirtestProject/Airtest#899]
【Air test IDE版本】 1.2.8
【opencv 版本】4.5.1
【代码】
`path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'tmp')
page = "1"
freeze = poco.freeze()
screen = G.DEVICE.snapshot(os.path.join(path, page, "snap.jpg"))
for index in range(1,10):
    tagetPath = os.path.join(path, page, '{}.jpg'.format(index))
    template = Template(tagetPath)
    print(template.match_in(screen))`
代码很简单，先冻结界面然后截图，再用之前已准备好的图片（jpg）依次去和截图匹配，获取图片相对截图的位置。

但是多次运行后会报错：
`    print(template.match_in(screen))
  File "D:\Program Files\Python\lib\site-packages\airtest\core\cv.py", line 145, in match_in
    match_result = self._cv_match(screen)
  File "D:\Program Files\Python\lib\site-packages\airtest\utils\logwraper.py", line 90, in wrapper
    res = f(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\airtest\core\cv.py", line 169, in _cv_match
    ret = self._try_match(func, image, screen, threshold=self.threshold, rgb=self.rgb)
  File "D:\Program Files\Python\lib\site-packages\airtest\core\cv.py", line 178, in _try_match
    ret = func(*args, **kwargs).find_best_result()
  File "D:\Program Files\Python\lib\site-packages\airtest\aircv\keypoint_base.py", line 23, in wrapper
    ret = func(self, *args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\airtest\aircv\keypoint_base.py", line 65, in find_best_result
    self.kp_sch, self.kp_src, self.good = self._get_key_points()
  File "D:\Program Files\Python\lib\site-packages\airtest\aircv\keypoint_base.py", line 150, in _get_key_points
    kp_src, des_src = self.get_keypoints_and_descriptors(self.im_source)
  File "D:\Program Files\Python\lib\site-packages\airtest\aircv\keypoint_base.py", line 136, in get_keypoints_and_descriptors
    keypoints, descriptors = self.detector.detectAndCompute(image, None)
cv2.error: OpenCV(4.5.1) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-kh7iq4w7\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 10108800 bytes in function 'cv::OutOfMemoryError'`

**Comment by yimelia** [comment]
首先poco的冻结是冻结界面元素，放进一个变量里，不是真的把画面冻结了，这个代码和图像识别没有任何关系。
其次就是这个问题是如何复现的？使用的windows窗口，还是android设备？

**Comment by ray0728** [comment]
Android设备。
PS：出问题的地方不在冻结，而在最后的Template. match_in

**Comment by yimelia** [comment]
我知道，我只是在说，poco的冻结和你后面写的截图没有关联。
代码是如何执行的？有没有什么其他的额外调度方式，还是只是单纯执行这段代码？我应该如何复现此问题？

**Comment by ray0728** [comment]
随便准备一些图片（可以是提前从界面上截取的部分图片），然后运行代码即可。

代码逻辑和目的很简单。就是用图片在全局进行查找，看看找到的pos就行

**Comment by yimelia** [comment]
我这里用我的截图和脚本无法复现这个问题，最好是你能够直接提供你使用的完整脚本、运行的方式（具体是如何运行的，在IDE中直接运行还是另外写了调度脚本？）、以及提供屏幕的截图screen、连接的是android设备还是windows，等等所有的详细运行环境情况

**Comment by yimelia** [comment]
还有就是你使用的电脑内存是多少？
最好是能把以上所有的信息都提供出来，否则我这里无法复现这个问题，就没办法帮忙查原因了

**Comment by ray0728** [comment]
> 还有就是你使用的电脑内存是多少？
> 最好是能把以上所有的信息都提供出来，否则我这里无法复现这个问题，就没办法帮忙查原因了

内存：16G
系统：Win10
代码：https://github.com/ray0728/Airtest
运行方式：IDE内运行
连接设备：Android

另外：出问题的时候 我使用的不是AirTest自带的Python，是单独安装的Python 3.8.   另外也不是一运行就出错。因为是在调试代码，所以在调试一段时间后，运行就出错了。

**Comment by pastel001** [comment]
我遇到的可能和这个问题一样吧，我觉得没复现出来，可能是环境问题，
这个问题可能是把android模拟器的内存跑挂了，我用的是雷电模拟器4.0.83版本
只是循环执行查找和点击，然后有概率运行一段时间模拟器就崩溃了，模拟器占用内存会达到7G到8G，
但是到底是怎么照成的就不了解了
```
# -*- encoding=utf8 -*-
__author__ = "Administrator"

from airtest.core.api import *
import threading

auto_setup(__file__)
connect_device("Android:///emulator-5554?cap_method=JAVACAP&&ori_method=ADBORI")


def find_click():
    exist =  find_all(Template(r"tpl1654779342092.png", threshold=0.75, record_pos=(0.369, 0.364), resolution=(1080, 1920)))
    if exist:
        try:
            sleep(60)
            return
        except Exception:
            pass
    exist =  find_all(Template(r"tpl1654779245747.png", threshold=0.95, record_pos=(-0.001, 0.819), resolution=(1080, 1920)))
    if exist:
        try:
            touch(exist[0].get("result"))
            sleep(3)
            return
        except Exception:
            pass

while True:
    find_click()
```

调用栈

> Traceback (most recent call last):
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\cli\\runner.py\", line 70, in runTest
    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), self.scope)
  File \"E:\\AirtestIDE_2018-07-20_py3_win64\\online_auto.air\\online4_auto_game.py\", line 86, in <module>
    find_click()
  File \"E:\\AirtestIDE_2018-07-20_py3_win64\\online_auto.air\\online4_auto_game.py\", line 46, in find_click
    exist =  find_all(Template(r\"tpl1654779342092.png\", threshold=0.95, record_pos=(0.369, 0.364), resolution=(1080, 1920)))
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper
    res = f(*args, **kwargs)
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\core\\api.py\", line 642, in find_all
    return v.match_all_in(screen)
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\core\\cv.py\", line 155, in match_all_in
    return self._find_all_template(image, screen)
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\core\\cv.py\", line 192, in _find_all_template
    return TemplateMatching(image, screen, threshold=self.threshold, rgb=self.rgb).find_all_results()
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\aircv\\template_matching.py\", line 25, in wrapper
    ret = func(self, *args, **kwargs)
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\aircv\\template_matching.py\", line 52, in find_all_results
    res = self._get_template_result_matrix()
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\aircv\\template_matching.py\", line 115, in _get_template_result_matrix
    return cv2.matchTemplate(i_gray, s_gray, cv2.TM_CCOEFF_NORMED)
cv2.error: OpenCV(4.5.1) C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-req-build-i1s8y2i1\\opencv\\modules\\core\\src\\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 16612808 bytes in function 'cv::OutOfMemoryError'

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\utils\\logwraper.py\", line 90, in wrapper
    res = f(*args, **kwargs)
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\core\\cv.py\", line 103, in try_log_screen
    screen = G.DEVICE.snapshot(quality=quality)
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\core\\android\\android.py\", line 271, in snapshot
    screen = self.javacap.get_frame_from_stream()
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\core\\android\\javacap.py\", line 103, in get_frame_from_stream
    return self.frame_gen.send(None)
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\utils\\threadsafe.py\", line 27, in send
    return self.it.send(*args)
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\core\\android\\javacap.py\", line 77, in get_frames
    header = s.recv(4)
  File \"C:\\Users\\Administrator\\AppData\\Roaming\\Python\\Python38\\site-packages\\airtest\\utils\\safesocket.py\", line 32, in recv
    raise socket.error(\"socket connection broken\")
OSError: socket connection broken

**Comment by Ezerell** [comment]
我也会有类似的问题，在树莓派上将Airtest从1.1.8升级到1.2.6之后，执行到 wait(Template(dut_name_image_path, threshold=0.90, record_pos=(-0.145, -0.171), resolution=self.__resolution),timeout=20) 这样的语句之后，会出现OutOfMemoryError的问题。
在1.1.8版本上，其他库保持一致，不会出现这个问题。
