### ISSUE TITLE
执行到某一步的时候会导致RpcTimeoutError

### ISSUE THREAD

**Issue by rafer16** [AirtestProject/Airtest#900]
"D:\AirtestIDE\AirtestIDE" pyrunner "D:\xiaohe_autools\login.py" 
============================================================

[Start running..]
[11:00:17][INFO]<airtest.core.android.touch_methods.minitouch> install_minitouch finished
[6872] Failed to execute script AirtestIDE
Traceback (most recent call last):
  File "AirtestIDE.py", line 82, in <module>
  File "AirtestIDE.py", line 58, in main
  File "app\widgets\code_runner\tracer.py", line 72, in run_pyfile
  File "D:\xiaohe_autools\login.py", line 119, in <module>
    poco("Btn_Challenge").click()
  File "D:\AirtestIDE\poco\proxy.py", line 23, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\AirtestIDE\poco\proxy.py", line 332, in click
    pos_in_percentage = self.get_position(focus)
  File "D:\AirtestIDE\poco\proxy.py", line 72, in wrapped
    return func(proxy, *args, **kwargs)
  File "D:\AirtestIDE\poco\proxy.py", line 613, in get_position
    pos = self.attr('pos')
  File "D:\AirtestIDE\poco\proxy.py", line 39, in wrapped
    return func(self, *args, **kwargs)
  File "D:\AirtestIDE\poco\proxy.py", line 734, in attr
    nodes = self._do_query(multiple=False)
  File "D:\AirtestIDE\poco\proxy.py", line 872, in _do_query
    self._nodes = self.poco.agent.hierarchy.select(self.query, multiple)
  File "D:\AirtestIDE\poco\freezeui\hierarchy.py", line 90, in select
    return self.selector.select(query, multiple)
  File "D:\AirtestIDE\poco\sdk\Selector.py", line 77, in select
    return self.selectImpl(cond, multiple, self.getRoot(), 9999, True, True)
  File "D:\AirtestIDE\poco\sdk\Selector.py", line 71, in getRoot
    return self.dumper.getRoot()
  File "D:\AirtestIDE\poco\freezeui\hierarchy.py", line 35, in getRoot
    root = Node(self.dumpHierarchy())
  File "D:\AirtestIDE\poco\utils\simplerpc\utils.py", line 13, in new_func
    ret, err = cb.wait(timeout=30)
  File "D:\AirtestIDE\poco\utils\simplerpc\simplerpc.py", line 78, in wait
    raise RpcTimeoutError(self)
poco.utils.simplerpc.simplerpc.RpcTimeoutError: <poco.utils.simplerpc.simplerpc.Callback object at 0x000000000B4D9438> (rid=42c00337-2b86-4c3f-821e-2447d387fbe5) (connection="tcp://127.0.0.1:16593")
[rpc]connected
start...
[Finished]

============================================================
if poco("bt_maoxian").child("box").exists():  //执行OK
    poco("bt_maoxian").child("box").click()   //执行OK
    poco("click_1").child("ChapterItem(Clone)").click() //执行OK
    time.sleep(10)                                                        //执行OK
    poco("Btn_Challenge").click()                                //执行失败
    time.sleep(3)
    if poco("AutoExchangeBtn").exists():
        poco("AutoExchangeBtn").wait(3).click()
    while not poco("bg").exists():
        pass
    
    if poco(text="点击任意位置继续").exists():
        poco(text="点击任意位置继续").click()
        paseLevel(runcount,flag)
    else:
        poco("bg").click()
        poco("bt_ok").click()
       
设备换了三个真机 都会出现相同的问题 烦请有空帮忙给个解决方案 感谢

**Comment by yimelia** [comment]
poco类型是什么？
如果必现的话，最好是能够提供一个可以复现该场景的apk，以及相关的代码文件，我们尝试复现一下此问题

**Comment by rafer16** [comment]
感谢回信
这个问题很诡异，由于app还在开发阶段还不能分发app。poco是unity类型，另外尝试了使用airtest 图片识别没有问题。并且在poco树中找到报错的节点。我跟另外一个同事相同代码相同app卡在同样位置都是rpctimeout。但是另外一个同事就不会报错，唯一不同的就是他是win10。请问这个跟系统有关系吗？另外还请问rpctimeout是什么导致的，能提供相关信息吗？我这边再尝试。

**Comment by yimelia** [comment]
这个问题不好定位，理论上跟系统关系不大，断开的原因可能有很多种，比如USB线不稳定、端口被别的程序抢占了之类的，但是从你的描述上来看，每次都断在同一个地方确实比较奇怪。

猜想还有一种可能性是断开的那个节点出现的界面上，节点信息很多，导致传输超时了，但是不能确认，需要有apk进行复现才能定位。

或者你们在有问题的机器上面，试一下这种比较简单的apk看看有没有问题 http://top.gdl.netease.com/poco-res/poco-demo-unity-game-android.zip
