### ISSUE TITLE
On android S,can't connect device successfully with python scripts or IDE

### ISSUE THREAD

**Issue by yazhli** [AirtestProject/Airtest#927]
Remove any following parts if does not have details about

**Describe the bug**
On android S,can't connect device successfully with python scripts or IDE

paste traceback here
[07:18:26][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe devices
[07:18:36][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c wait-for-device
[07:18:36][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell getprop ro.build.version.sdk
[07:18:36][WARNING]<airtest.core.api> Device:8853528c updated <airtest.core.android.android.Android object at 0x0000011378508048> -> <airtest.core.android.android.Android object at 0x00000113782B3C18>
[07:18:36][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell dumpsys display
[07:18:36][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell dumpsys window
[07:18:36][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell wm size; wm density
[07:18:37][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell dumpsys SurfaceFlinger
[07:18:37][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell dumpsys input
[07:18:37][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell getevent -p
[07:18:37][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell pm path jp.co.cyberagent.stf.rotationwatcher
[07:18:37][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell export CLASSPATH=/data/app/~~yAWpebFmytZktpS-_kxB5Q==/jp.co.cyberagent.stf.rotationwatcher-OAh7vfhsA9FJHuBUMRnPkQ==/base.apk;exec app_process /system/bin jp.co.cyberagent.stf.rotationwatcher.RotationWatcher
[07:18:38][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell dumpsys window windows
[07:18:38][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell dumpsys package com.netease.nie.yosemite
[07:18:38][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell dumpsys activity top
[07:18:38][INFO]<airtest.core.android.yosemite> local version code is 300, installed version code is 303
[07:18:38][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c forward --no-rebind tcp:17550 localabstract:javacap_17550
[07:18:38][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell pm path com.netease.nie.yosemite
[07:18:38][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell getprop ro.product.manufacturer
[07:18:38][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell CLASSPATH=/data/app/~~bkJLV0n0p-LKDsUbuWPXow==/com.netease.nie.yosemite-73iw8kcAn1z0qqJ27O1Aww==/base.apk exec app_process /system/bin com.netease.nie.yosemite.Capture --scale 100 --socket javacap_17550 -lazy 2>&1
[07:18:38][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe -P 5037 -s 8853528c shell getprop ro.product.model
[07:18:39][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'Capture server listening on @javacap_17550'
[07:18:39][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'java.lang.NoSuchMethodException: android.view.SurfaceControl.screenshot [class android.graphics.Rect, int, int, int]'
[07:18:39][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'at java.lang.Class.getMethod(Class.java:2103)'
[07:18:39][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'at java.lang.Class.getDeclaredMethod(Class.java:2081)'
[07:18:39][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'at com.netease.nie.yosemite.compat.ScreenshotManagerWrapper$NewApiScreenshotInjector.injectorMethod(ScreenshotManagerWrapper.java:123)'
[07:18:39][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'at com.netease.nie.yosemite.compat.ScreenshotManagerWrapper.<init>(ScreenshotManagerWrapper.java:28)'
[07:18:39][DEBUG]<airtest.utils.nbsp> [javacap_sever]b'at com.netease.nie.yosemite.Capture$InputClient.run(Capture.java:168)'
[07:18:39][ERROR]<airtest> Traceback (most recent call last):
  File "app\plugins\device\android\util.py", line 485, in run
  File "app\plugins\device\android\util.py", line 478, in _get_android_frame
  File "airtest\core\android\javacap.py", line 101, in get_frame_from_stream
    return self.frame_gen.send(None)
  File "airtest\core\android\javacap.py", line 64, in get_frames
    t = s.recv(24)
  File "airtest\utils\safesocket.py", line 32, in recv
    raise socket.error("socket connection broken")
OSError: socket connection broken

[07:18:40][DEBUG]<airtest.core.android.adb> C:\AirtestIDE_2020-01-21_py3_win64\AirtestIDE_2020-01-21_py3_win64\airtest\core\android\static\adb\windows\adb.exe devices
[Warning] The current device is unplugged!

**To Reproduce**
1. Android S
2. Connect device with IDE(even check all the three options under connect)

**python version:** `python3.6.3`

**airtest version:** `1.1.11`

**Smartphone (please complete the following information):**
 - Device: [Internal device]
 - OS: [e.g. Android S]

**Comment by yimelia** [comment]
https://airtest.netease.com/changelog.html
try AirtestIDE 1.2.12？
