### ISSUE TITLE
用例执行完毕后，minicap minitouch清理失败

### ISSUE THREAD

**Issue by gyxsnh** [AirtestProject/Airtest#934]
**描述问题bug**
用例执行完毕后，清理minicap以及minitouch失败
```
[18:20:51][DEBUG]<airtest.core.android.adb> /Users/user/.local/lib/python3.6/site-packages/airtest/core/android/static/adb/mac/adb -s 7eb1f72 forward --remove tcp:15080
[18:20:51][DEBUG]<airtest.utils.nbsp> [rotation_server]b''
Exception ignored in: <module 'threading' from '/usr/local/var/pyenv/versions/3.6.8/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/Users/user/.local/lib/python3.6/site-packages/airtest/utils/snippet.py", line 89, in exitfunc
    _cleanup()
  File "/Users/user/.local/lib/python3.6/site-packages/airtest/utils/snippet.py", line 64, in _cleanup
    func(*args, **kwargs)
  File "/Users/user/.local/lib/python3.6/site-packages/airtest/utils/snippet.py", line 78, in kill_proc
    proc.communicate()
  File "/usr/local/var/pyenv/versions/3.6.8/lib/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/var/pyenv/versions/3.6.8/lib/python3.6/subprocess.py", line 1525, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/usr/local/var/pyenv/versions/3.6.8/lib/python3.6/selectors.py", line 351, in register
    key = super().register(fileobj, events, data)
  File "/usr/local/var/pyenv/versions/3.6.8/lib/python3.6/selectors.py", line 237, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/usr/local/var/pyenv/versions/3.6.8/lib/python3.6/selectors.py", line 224, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/var/pyenv/versions/3.6.8/lib/python3.6/selectors.py", line 39, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.BufferedReader name=9>
```

**复现步骤**
任意用例

**预期效果**
minicap mintouch可以正常清理掉

**python 版本:** `python3.6.8`

**airtest 版本:** `1.2.0`

**设备:**
 - 型号: [A57]
 - 系统: [Android 6.0.1]

**Comment by luzihang123** [comment]
遇到了同样的问题

**Comment by yimelia** [comment]
很抱歉，这个是新版本添加了一些功能后，把python低版本的一个BUG暴露出来了
airtest下一个版本会兼容这个问题
或者是临时的解决方案可以是直接升级本地python版本到比较新一点的版本
（例如3.7的python，就升级到 3.7.x，x尽可能选大一些的数字，但我本地使用的是py3.6.8，似乎并没有遇到这个问题……）
