### ISSUE TITLE
poco()操作元素的时候报错；在vivo Y79A上手机会出现该问题，其他小米手机又是正常的

### ISSUE THREAD

**Issue by zhangwk02** [AirtestProject/Airtest#95]
[07:23:18][DEBUG]<airtest.core.android.adb> C:\python\py3.5\lib\site-packages\airtest\core\android\static\adb\windows\adb.exe -s 21e5d44f shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -i
click_report---error: java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission

|--   Remote Traceback   --|

java.lang.SecurityException: Injecting to another application requires INJECT_EVENTS permission
	at android.os.Parcel.readException(Parcel.java:1684)
	at android.os.Parcel.readException(Parcel.java:1637)
	at android.app.IUiAutomationConnection$Stub$Proxy.injectInputEvent(IUiAutomationConnection.java:276)
	at android.app.UiAutomation.injectInputEvent(UiAutomation.java:501)
	at com.netease.open.pocoservice.Input.injectEvent(Input.java:299)
	at com.netease.open.pocoservice.Input.injectEvent(Input.java:303)
	at com.netease.open.pocoservice.Input.down(Input.java:257)
	at com.netease.open.pocoservice.Input.down(Input.java:248)
	at com.netease.open.pocoservice.Input.click(Input.java:45)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.netease.open.hrpc.backend.RpcServer.onRequest(RpcServer.java:170)
	at com.netease.open.hrpc.backend.RpcServer.serve(RpcServer.java:57)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:840)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:189)
	at java.lang.Thread.run(Thread.java:762)

|--   Remote Traceback end   --|

**Comment by Meteorix** [comment]
看看手机设置里面开发者选项，有没有输入权限设置
