### ISSUE TITLE
使用pytest执行用例结束后，exitfunc函数报错了

### ISSUE THREAD

**Issue by kuailel45** [AirtestProject/Airtest#956]
使用pytest执行用例结束后，exitfunc函数报错了。
环境：Python3.9,
用例框架：pytest
日志如下：
testcases/testlogin.py::TestLogin::test_login --- Logging error ---
Traceback (most recent call last):
  File "D:\Python39\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
============================= 1 passed in 45.01s ==============================
  File "D:\Python39\lib\site-packages\airtest\utils\snippet.py", line 92, in exitfunc
    _cleanup()
  File "D:\Python39\lib\site-packages\airtest\utils\snippet.py", line 64, in _cleanup
    func(*args, **kwargs)
  File "D:\Python39\lib\site-packages\airtest\core\android\adb.py", line 1569, in cleanup_adb_forward
    adb._cleanup_forwards()
  File "D:\Python39\lib\site-packages\airtest\core\android\adb.py", line 830, in _cleanup_forwards
    self.remove_forward(local)
  File "D:\Python39\lib\site-packages\airtest\core\android\adb.py", line 549, in remove_forward
    self.cmd(cmds)
  File "D:\Python39\lib\site-packages\airtest\core\android\adb.py", line 179, in cmd
    proc = self.start_cmd(cmds, device)
  File "D:\Python39\lib\site-packages\airtest\core\android\adb.py", line 147, in start_cmd
    LOGGING.debug(" ".join(cmds))
Message: 'D:\\Python39\\Lib\\site-packages\\airtest\\core\\android\\static\\adb\\windows\\adb.exe -s e3b7d428 forward --remove tcp:15324'
Arguments: ()
------------------
执行代码如下：
from common.commonbase import CommonBasePage

class TestLogin(object):
    c= None
    def setup(self):

        self.c =CommonBasePage('Android:///','com.jinxin.namibox')
        self.c.closeapp()
        #install("path/to/your/apk")
    def teardown(self):
        pass
    def test_login(self):
        self.c.startapp()
        self.c.sleepProcess(30)
        e = self.c.findElementById('com.jinxin.namibox:id/tab_item_text3')
        self.c.elementClick(e)

**Comment by yimelia** [comment]
先更新到最新版本，然后逐步用最小代码慢慢尝试，目前的代码看不出问题出在哪里
