### ISSUE TITLE
iOS 启动app总是超时

### ISSUE THREAD

**Issue by hechao1986** [AirtestProject/Airtest#96]
WDA报错:
```
    t = 262212.55s         Wait for com.xx.sdkdemo.cocos2dx to idle
    t = 262213.70s Open com.xx.sdkdemo.cocos2dx
    t = 262213.71s     Launch com.xx.sdkdemo.cocos2dx
2018-07-02 17:33:40.479997+0800 WebDriverAgentRunner-Runner[24368:10178213] Enqueue Failure: Failed to launch com.xx.sdkdemo.cocos2dx: 未能完成该操作。Unable to launch com.xx.sdkdemo.cocos2dx because it has an invalid code signature, inadequate entitlements or its profile has not been explicitly trusted by the user. /Users/pirate/Desktop/github/iOS-Tagent/WebDriverAgentRunner/UITestingUITests.m 37 1
2018-07-02 17:34:40.518652+0800 WebDriverAgentRunner-Runner[24368:10178213] Enqueue Failure: Application 'com.xx.sdkdemo.cocos2dx' does not have a process ID /Users/pirate/Desktop/github/iOS-Tagent/WebDriverAgentRunner/UITestingUITests.m 37 1
    t = 262274.00s         Wait for accessibility to load
2018-07-02 17:35:40.559285+0800 WebDriverAgentRunner-Runner[24368:10178213] Enqueue Failure: App accessibility isn't loaded /Users/pirate/Desktop/github/iOS-Tagent/WebDriverAgentRunner/UITestingUITests.m 37 1
2018-07-02 17:36:40.614794+0800 WebDriverAgentRunner-Runner[24368:10178213] Enqueue Failure: Application '<XCUIApplicationImpl: 0x141d09830 com.xx.sdkdemo.cocos2dx>' failed to activate (current state: Not Running) /Users/pirate/Desktop/github/iOS-Tagent/WebDriverAgentRunner/UITestingUITests.m 37 1
```
airtest报错:
```
+ python -m airtest run cocos2dx_ios.air --device ios:///http://127.0.0.1:8100 --log
======================================================================
ERROR: runTest (airtest.cli.runner.AirtestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/airtest/cli/runner.py", line 66, in runTest
    six.reraise(*sys.exc_info())
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/airtest/cli/runner.py", line 62, in runTest
    exec(compile(code.encode("utf-8"), pyfilepath, 'exec'), self.scope)
  File "/Users/pirate/.jenkins/workspace/SDK_ATUO_TEST/AirtestIOSForCocos2dx/airtest/cocos2dx_ios.air/cocos2dx_ios.py", line 10, in <module>
    start_app("com.babeltime.sdkdemo.cocos2dx")
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/airtest/utils/logwraper.py", line 72, in wrapper
    res = f(*args, **kwargs)
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/airtest/core/api.py", line 146, in start_app
    G.DEVICE.start_app(package, activity)
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/airtest/core/ios/ios.py", line 264, in start_app
    self.driver.session(package)
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/wda/__init__.py", line 278, in session
    res = self.http.post('session', data)
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/wda/__init__.py", line 75, in httpdo
    response = requests.request(method, url, data=data, timeout=HTTP_TIMEOUT)
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Users/pirate/.virtualenv/2.7/airtest/lib/python2.7/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=8100): Read timed out. (read timeout=60.0)

----------------------------------------------------------------------
Ran 1 test in 242.771s
```

**Comment by suyuchen123** [comment]
这个app手动点击可以打开嘛？

**Comment by hechao1986** [comment]
可以打开, 同一个包, 有时候可以启动, 有时候不可以

**Comment by suyuchen123** [comment]
尝试在设置里信任下你这个应用程序的开发者信息？

**Comment by hechao1986** [comment]
已经信任了.
还有一个现象可参考, airtest超时后, 过一会app在设备上启动了
