### ISSUE TITLE
airtest 的 exist() api造成堆栈错误

### ISSUE THREAD

**Issue by didiaodanding** [AirtestProject/Airtest#97]
```
Traceback (most recent call last):
  File "airtest\utils\logwraper.py", line 73, in wrapper
  File "airtest\core\helper.py", line 120, in wrapper
  File "airtest\core\api.py", line 383, in exists
  File "airtest\utils\logwraper.py", line 73, in wrapper
  File "airtest\core\cv.py", line 47, in loop_find
  File "airtest\core\cv.py", line 119, in match_in
  File "airtest\core\cv.py", line 143, in _cv_match
  File "airtest\core\cv.py", line 154, in _try_match
  File "airtest\core\cv.py", line 171, in _find_sift
  File "airtest\aircv\sift.py", line 51, in find_sift
  File "airtest\aircv\sift.py", line 175, in _many_good_pts
  File "airtest\aircv\sift.py", line 251, in _find_homography
error: C:\projects\opencv-python\opencv\modules\calib3d\src\ptsetreg.cpp:180: error: (-215) count >= 0 && count2 == count in function cv::RANSACPointSetRegistrator::run
```

**Comment by rockywhisper** [comment]
@didiaodanding  你好，这个issues之前的外放应该已经修复了，暂时关闭了哈。
如有问题，欢迎及时反馈  :)
