### ISSUE TITLE
airtest/utils/nbsp.py , ValueError: I/O operation on closed file.

### ISSUE THREAD

**Issue by windanchaos** [AirtestProject/Airtest#970]
with pytest ,the airtest logs
```
--- Logging error ---
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/Library/Python/3.8/site-packages/airtest/utils/snippet.py", line 92, in exitfunc
    _cleanup()
  File "/Library/Python/3.8/site-packages/airtest/utils/snippet.py", line 64, in _cleanup
    func(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 1604, in cleanup_adb_forward
    adb._cleanup_forwards()
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 838, in _cleanup_forwards
    self.remove_forward(local)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 549, in remove_forward
    self.cmd(cmds)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 179, in cmd
    proc = self.start_cmd(cmds, device)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 147, in start_cmd
    LOGGING.debug(" ".join(cmds))
Message: '/Library/Python/3.8/site-packages/airtest/core/android/static/adb/mac/adb -s 8SPV8TZ9ORZSLZRG forward --remove tcp:14928'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/Library/Python/3.8/site-packages/airtest/utils/snippet.py", line 92, in exitfunc
    _cleanup()
  File "/Library/Python/3.8/site-packages/airtest/utils/snippet.py", line 64, in _cleanup
    func(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 1604, in cleanup_adb_forward
    adb._cleanup_forwards()
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 838, in _cleanup_forwards
    self.remove_forward(local)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 549, in remove_forward
    self.cmd(cmds)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 179, in cmd
    proc = self.start_cmd(cmds, device)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 147, in start_cmd
    LOGGING.debug(" ".join(cmds))
Message: '/Library/Python/3.8/site-packages/airtest/core/android/static/adb/mac/adb -s 8SPV8TZ9ORZSLZRG forward --remove tcp:18968'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/Library/Python/3.8/site-packages/airtest/utils/snippet.py", line 92, in exitfunc
    _cleanup()
  File "/Library/Python/3.8/site-packages/airtest/utils/snippet.py", line 64, in _cleanup
    func(*args, **kwargs)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 1604, in cleanup_adb_forward
    adb._cleanup_forwards()
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 838, in _cleanup_forwards
    self.remove_forward(local)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 549, in remove_forward
    self.cmd(cmds)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 179, in cmd
    proc = self.start_cmd(cmds, device)
  File "/Library/Python/3.8/site-packages/airtest/core/android/adb.py", line 147, in start_cmd
    LOGGING.debug(" ".join(cmds))
Message: '/Library/Python/3.8/site-packages/airtest/core/android/static/adb/mac/adb -s 8SPV8TZ9ORZSLZRG forward --remove tcp:14371'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
[pocoservice.apk] stdout: b'\ncom.netease.open.pocoservice.InstrumentedTestAsLauncher:'
[pocoservice.apk] stderr: b''
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Python/3.8/site-packages/airtest/utils/nbsp.py", line 37, in _populateQueue
    LOGGING.debug("[%s]%s" % (self.name, repr(line.strip())))
Message: "[rotation_server]b''"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Python/3.8/site-packages/airtest/utils/nbsp.py", line 37, in _populateQueue
    LOGGING.debug("[%s]%s" % (self.name, repr(line.strip())))
Message: "[airtouch_server]b''"
Arguments: ()

```

**Comment by windanchaos** [comment]
#562 
先压制出错的日志类型。
