### ISSUE TITLE
脚本出现ConnectionAbortedError错误，在调用exists时偶尔出现，touch时经常出现

### ISSUE THREAD

**Issue by zongrongjin** [AirtestProject/Airtest#994]
**脚本出现以下错误，在调用exists时偶尔出现，touch时经常出现**
**参考了[issues 149](https://github.com/AirtestProject/Airtest/issues/149)的解决方案，并不能解决此问题。**

**报错信息**

```
Traceback (most recent call last):
  File "airtest\utils\logwraper.py", line 90, in wrapper
  File "airtest\core\api.py", line 357, in touch
  File "airtest\core\android\android.py", line 504, in touch
  File "airtest\core\android\touch_methods\touch_proxy.py", line 128, in touch
  File "airtest\utils\snippet.py", line 125, in ready_func
  File "airtest\core\android\touch_methods\base_touch.py", line 212, in touch
  File "airtest\utils\snippet.py", line 125, in ready_func
  File "airtest\core\android\touch_methods\base_touch.py", line 188, in perform
  File "airtest\core\android\touch_methods\base_touch.py", line 98, in safe_send
  File "airtest\core\android\touch_methods\base_touch.py", line 95, in safe_send
  File "airtest\utils\safesocket.py", line 35, in send
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。
```

**相关截图**
![1638520872(1)](https://user-images.githubusercontent.com/49151134/144572237-56a0f823-817a-4dcd-a2ee-cdf3c0f8273a.jpg)

**python 版本: python3.6**
**airtest 版本: 1.2.3**
**运行环境：windows10**
**adb版本：**
```
Android Debug Bridge version 1.0.41
Version 29.0.6-6198805
```

**设备:**
 - 型号: <b>vivo Y55L</b>
- 系统: <b>Android 6.0.1</b>

**Comment by zongrongjin** [comment]
解决了

1. 任务管理器中关闭其他应用程序的adb.exe
2. 不要使用多线程，有需要请使用多进程
3. 参考[issues 149](https://github.com/AirtestProject/Airtest/issues/149)
